### ISSUE TITLE
Should be able to select comboBox with placeHolders

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#100]
**Expected behavior**
Should be able to select comboBox with placeHolders
<img width="398" alt="screen shot 2018-08-08 at 6 05 00 pm" src="https://user-images.githubusercontent.com/6310197/43837492-4cb73d44-9b36-11e8-968e-e3de919f3640.png">

**Actual behavior**
Unable to find the element

**Version**
```
commit - 51de58ab2c042b63be0e5d19a79450de0cd03acd
```

**Comment by Apoorva-GA** [comment]
@sguptatw Where are you trying this? 
Could you give steps to reproduce the issue?

**Comment by Apoorva-GA** [comment]
In the above case `Select a card type` is not a placeholder. Its an option which is selected and disabled.

So selecting the combobox by id should work.
