### ISSUE TITLE
Documentation for exists() function

### ISSUE THREAD

**Issue by moogleberry** [getgauge/taiko#1000]
### Expected behavior
Documentation for exists() function should describe that the `(number, number)` arguments are for overriding the global `retryInterval` and `retryTimeout`.

### Actual behavior
Reads as:
> exists function (number, number) Checks existence for element.

with no reference to what the arguments are for

### Versions
```
1.0.3
Documentation on https://taiko.gauge.org/#elementwrapper as of 2010/1/6.  
```

**Comment by moogleberry** [comment]
Is my reading of the source right in that the arguments are for `retryInterval` and `retryTimeout`?

**Comment by zabil** [comment]
Yes, you are right.
