### ISSUE TITLE
scrollTo() behavior

### ISSUE THREAD

**Issue by moogleberry** [getgauge/taiko#1005]
### Expected behavior
`scrollTo()` should provide the ability to center the view on the element provided by leveraging underlying features.  

Specifically, using `element.scrollIntoView()` instead of the Chrome-only `element.scrollIntoViewIfNeeded()` internally should provide better future support since `scrollIntoView` is in a Working Draft and `scrollIntoViewIfNeeded` is not on any standards track.  

Further, `scrollIntoView` provides more positioning options such as `{ block: "center" }`, which can be made available by passing a configuration Object through the `scrollTo()` call into the internal call.  These options are important for sites with sticky or floating elements.  Scrolling barely into "view" as the browser sees it may not scroll an element into an uncovered position.  

`scrollIntoViewIfNeeded()` only provides a center on element Boolean, but I have observed this flag to not work on the listed Chromium version below.

### Actual behavior
`scrollTo()` only allows for scrolling barely into view because of the behavior of the internally used `scrollIntoViewIfNeeded()`, and both its lack of positioning options, and Taiko's provision of a pass-through to them. 

### Steps to reproduce
1. openBrowser()
2. goto("https://taiko.gauge.org/#/")
3. scrollTo("This launches the Taiko prompt")

### Versions
```
Taiko 1.0.3
Chromium Version 79.0.3945.88 (Developer Build) Fedora Project (64-bit)
Chromium Version 81.0.3994.0 (Developer Build) (64-bit)
```
[scrollIntoView](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView)
[scrollIntoViewIfNeeded](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoViewIfNeeded)

**Comment by negiDharmendra** [comment]
@moogleberry Can you please elaborate your use case about using `scrollIntoView` instead of `scrollIntoViewIfNeeded`. Just want to understand where and how [scrollIntoViewOptions](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) are adding values as far as automation testing is concern.

**Comment by NivedhaSenthil** [comment]
Thanks for bring this up, scrollTo is modified to `scrollIntoView` in favour of supporting firefox currently.
