### ISSUE TITLE
open a page with  an error “NET:ERROR_CERT_AUTHORITY_INVALID”，I hope I can continue my test

### ISSUE THREAD

**Issue by xiaojia1203** [getgauge/taiko#1012]
### Expected behavior
When I open a page with keyword goto，I get an error““NET:ERROR_CERT_AUTHORITY_INVALID””，and I hope I can continue my test by click advance button or link。

### Actual behavior
When I saw the error “NET:ERROR_CERT_AUTHORITY_INVALID”，the testcase is stoped.

### Steps to reproduce
1.openBrowser()
2.goto(somekind of url which need certification) 
3.hope go on the test,but can not

### Versions
```
 `taiko` versions 1.0.3.
```

**Comment by zabil** [comment]
Please set the option to ignore certificate errors when opening the browser.
More information at https://taiko.gauge.org/#openbrowser
