### ISSUE TITLE
Locators chaining not working in taiko

### ISSUE THREAD

**Issue by advait012** [getgauge/taiko#1015]
this.fetchTheCourse=async function(){
let rows=await $('table#product > tbody > tr').elements();
for (row of rows){
let cells = row.$('td').elements();
if(cells[2]=='35'){
console.log(await cells[1].text());

}

### Expected behavior
row.$('td').elements() should fetch 'td' locators under the particular row

### Actual behavior
Getting the error as -- 'row.$ is not a function'

### Steps to reproduce
1.
2.
3.

### Gauge version
```
Run gauge -v on your system and paste the results here.
```
taiko -- 1.0.3

**Comment by sriv** [comment]
`taiko` does not support this syntax. The idea is that the selectors should abstract the DOM as much as it can.

If you can explain the objective, possibly with the help of an example, we can either suggest a way with taiko or take it up as a feature, if it's not possible. Thanks.

**Comment by advait012** [comment]
The objective is  to manipulate the webtables. The Idea was to first determine the table 'css' then within the table css find the number of rows . Then start the for loop in rows and then in each row  , find the cells with in that row.

Hope I am making sense?

In Selenium we achieve through this :-

WebElement table = driver.findElement('....');

List rows = table.findElement(by.tagName('tr'));
for (WebElement row : rows){
List cells =  row.findElement(by.tagname('td'));
System.out.println(cells.get(0).getText());
} 

How we will achieve this objective in taiko ?

**Comment by Debashis9012** [comment]
You can use the [Evaluate](https://taiko.gauge.org/#evaluate) api which lets you to execute your code on the browser.
