### ISSUE TITLE
Taiko generated code often omits a crucial 'await' command, leading to errors when running script 

### ISSUE THREAD

**Issue by ndbhamvani** [getgauge/taiko#1016]
### Expected behavior
Successful steps in REPL mode should translate to successful run of associated code generated by Taiko. 

### Actual behavior
What seems to be happening is that the resultant code doesn't always have an 'await' before `goto("url");` and when this happens, running that script from Taiko causes errors (see attached image and file).

Workaround: if user manually edits the generated code to:- `await goto("url");` this resolves the issue.

### Steps to reproduce
1. Steps shown in attached Powershell screenshot image.
2. Notice that often, the Taiko generated Javascript code doesn't run unless user manually edits it to include any missing 'await' command.

![taiko-running-script-error-a1](https://user-images.githubusercontent.com/37751257/72224627-5d899e80-3574-11ea-9137-5d5d39dc85f2.png)

![taikoGeneratedCode](https://user-images.githubusercontent.com/37751257/72224660-bc4f1800-3574-11ea-989f-0134c19703ea.png)

### Versions
```
Taiko Version: 1.0.3 (Chromium: 81.0.3994.0) 
Node Version: 12.14.1
```

**Comment by moogleberry** [comment]
This happens when you put a space between a command and its opening parenthesis `goto (foo)` vs `goto(foo)`.  Then the subsequent`.split()` in `isTaikoFunc()` results in looking for `goto ` instead of `goto`.  

Workaround is to not use a space.

**Comment by negiDharmendra** [comment]
@ndbhamvani  This issue has been fixed and the same is available on the master branch.

**Comment by ndbhamvani** [comment]
Excellent, thanks!
