### ISSUE TITLE
Should take z index into consideration when selecting an element

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#102]
_From @sguptatw on August 8, 2018 12:32_

**Expected behavior**
Should work with elements of the pop-up currently shown

**Actual behavior**
The element considered is not for the window with the highest z-index

**Version**
```
commit 51de58ab2c042b63be0e5d19a79450de0cd03acd
```

_Copied from original issue: getgauge/gauge#1142_

**Comment by Apoorva-GA** [comment]
As per the discussion with the team,
Taiko will check for a fixed number of elements defaulted to 10, for the match and if there is no match in those number of elements, user will have to provide more appropriate selector in order to fetch the element.

**Comment by sguptatw** [comment]
Another example 
```
const { openBrowser, goto, link, click, highlight } = require('taiko');

(async () => {
    try {
        await openBrowser();
        await goto("google.com");
        await click(link({"title":"Google apps"}));
        await highlight("Gmail");
    } catch (e) {
        console.error(e);
    } finally {
        closeBrowser();
    }
})();
```
> The Gmail highlighted is not of the pop-up

**Comment by Apoorva-GA** [comment]
Fix should be available in commit 888638d275cfebad0747695ebbd1404c60295846

**Comment by sguptatw** [comment]
**Question**

While finding the element, if multiple elements are present. If element(s) is not covered, then should next element should be considered.

**Steps to replicate**
```
const { openBrowser, goto, scrollTo, click, button, link } = require('taiko');

(async () => {
    try {
        await openBrowser({headless:false});
        await goto("http://demos.jquerymobile.com/1.4.5/popup/");
        await scrollTo("sign in");
        await click(link("Sign in"));
        await click(link("Sign in"));
    } catch (e) {
        console.error(e);
    } finally {
        closeBrowser();
    }
})();
```
> Here there are 2 sign in options. One which is covered, the other is not. Which one should be clicked?

**Comment by sguptatw** [comment]
Thanks @Apoorva-GA It works for the above script. However there is another problem

As per the discussion. When there are multiple options for selecting an element, we can narrow down with proximity selectors. I am using the proximity selector `above`. But this is considering an element that is farther away than the one close by -
```
const { openBrowser, goto, link, click, highlight, above } = require('taiko');

(async () => {
    try {
        await openBrowser();
        await goto("google.com");
        await click(link({"title":"Google apps"}));
        await highlight(contains("Gmail"),above("More"))
        await screenshot()
    } catch (e) {
        console.error(e);
    } finally {
        closeBrowser();
    }
})();
```
![narrowsearch](https://user-images.githubusercontent.com/6310197/45202730-8bcbdf80-b297-11e8-916d-a5a0eb4efd0a.png)

**Comment by Apoorva-GA** [comment]
@sguptatw looks like this is an issue with proximity selector. How is it related to the original issue?
 Let me know if I am missing something?

**Comment by sguptatw** [comment]
@Apoorva-GA Thanks. Yes, the original issue is resolved. Closing this issue. 
Tracking the highlight issue as a part of https://github.com/getgauge/taiko/issues/145
