### ISSUE TITLE
try/catch failing when used in a step

### ISSUE THREAD

**Issue by djfbryant** [getgauge/taiko#1022]
### Expected behavior
I am attempting to click an element that is hidden behind a spinner, having spoken to our development team they are suggesting I implement a try/catch mechanism. The below does not appear to work when added to a step.

By the time this step is reached, the specification file has already opened Chrome and got to the page with the element on it. So this step and code is in its own file.

`step("Create a New Case", async () => {
    
    try {
        await click('Start New Case');
        await write('CaseReferenceAutomation' + DateNow, into(textBox({id:'new-case-reference'})));
        await click(button({id:'btn-modal-create-a-case-create'}));
    } catch(e) { 
        console.error(e);
    } finally {
        closeBrowser();
    }

    
})(); `

### Actual behavior
"Cannot read property 'error' of undefined" is shown. The behavior works fine using a simple google search async try/catch ;

(async () => {
    try {
        await openBrowser();
        await goto("google.com");
        await write("taiko test automation");
        await click("Google Search");
    } catch (error) {
            console.error(error);
    } finally {
            closeBrowser();
    }
})();

taiko 
### Versions
```
taiko: Version: 1.0.3 (Chromium: 81.0.3994.0) RELEASE
Node : v10.16.3

```

**Comment by sriv** [comment]
Also discussed here - https://spectrum.chat/taiko/engineering/try-catch-where-am-i-going-wrong~40877a49-0f39-48fc-b1c6-1dff15f248db

@djfbryant - I can access `console.error` (steps in [my comment](https://spectrum.chat/taiko/engineering/try-catch-where-am-i-going-wrong~40877a49-0f39-48fc-b1c6-1dff15f248db?m=MTU3ODg5NTEyODk2NA==)). 

Can you please try this:

- `git clone clone https://github.com/sriv/taiko-1022`
- `npm install`
- `npm test`

**Comment by sriv** [comment]
Closing this assuming things are well :)

Feel free to reopen if this is still an issue.
