### ISSUE TITLE
Is there a way to get the defaultConfig?

### ISSUE THREAD

**Issue by moogleberry** [getgauge/taiko#1023]
### Expected behavior
Looking for a way to get the `defaultConfig` object that `taiko.js` and `config.js` use, and make it its values available to plugins and other custom addons.  

For example, if I build my own functionality that I want to use often in multiple tests, I want it to be able to know what the global `retryTimeout` and `retryInterval` values are.  

### Actual behavior
The only way I've found is to modify `taiko.js` to provide a getter function for it.  

### Versions
```
Taiko 1.0.3
```

**Comment by negiDharmendra** [comment]
@moogleberry Right now there is no way to access the default config inside the `taiko-plugins`.
However if you want to set any of the default config you can do that by `setConfig` API.
**Example:**
```
setConfig( { observeTime: 3000});
      or
setConfig( { waitForNavigation: false, navigationTimeout: 3000});
```

**Comment by moogleberry** [comment]
@negiDharmendra Would adding a `getConfig` in MR be welcome, or is that discouraged?

**Comment by sriv** [comment]
IMO introducing `getConfig` makes sense.

**Comment by Debashis9012** [comment]
Verified [PR 1036](https://github.com/getgauge/taiko/pull/1036)
