### ISSUE TITLE
Ignore certificate errors by default

### ISSUE THREAD

**Issue by zabil** [getgauge/taiko#1028]
## Actual

Test environments don't set up certificates. Using Taiko against these environments produces certificate errors. For example

```
goto("https://172.0.1.111:1234") 
[FAIL] Error: Navigation to url https://172.0.1.111:1234 
failed.
REASON: net::ERR_CERT_AUTHORITY_INVALID, run .trace for more info.
```

## Change

Ignore certificates by default. The tester can choose to not ignore certificates as follows

```
openBrowser({ignoreCertificateErrors:false})
```

**Comment by jfgreffier** [comment]
`setConfig({ ignoreSSLErrors: false });` does the trick

Oddly enough ignoreSSLErrors appears in getConfig doc, but not setConfig's

**Comment by zabil** [comment]
Thanks for pointing that out. Please feel free to send a PR for this!

The change can be made at https://github.com/getgauge/taiko/blob/75d0c38181157007492acc095f084101728e43ea/lib/taiko.js#L2994-L3006

**Comment by jfgreffier** [comment]
Working on harmonizing setConfig/getConfig doc
