### ISSUE TITLE
How to integrate gauge-taiko test with Bamboo deployment server

### ISSUE THREAD

**Issue by srajkavithaa** [getgauge/taiko#1035]
I want to run my tests as part of deployment from the Bamboo server, but I am not able to get any help from the document, any help will be highly appreciated. thanks

**Comment by negiDharmendra** [comment]
We don't have access to Bamboo server. As a reference you can look [here](https://docs.gauge.org/examples.html?os=windows&language=csharp&ide=vscode#integration-with-ci-cd)  for integration with CI/CD

If you are facing any issue related to gauge please tell us about the issue.

**Comment by srajkavithaa** [comment]
Hi, thanks for the update, but I too gone thru that and felt no information for Bamboo integration and hence asked

**Comment by negiDharmendra** [comment]
@srajkavithaa We understand your pain but it is really hard to maintain doccumentation for Gauge's integration with every CI/CD tool available. 
If you are facing issues with Gauge or any of it's plugins installations or Gauge specs executions we can try to help you.

**Comment by srajkavithaa** [comment]
Thanks, will try and come back for help.
