### ISSUE TITLE
How do you clear highlights when debugging with REPL?

### ISSUE THREAD

**Issue by TotalLag** [getgauge/taiko#1039]
### Expected behavior
I should be able to clear highlights after using highlight() without starting over.

### Actual behavior
All elements highlighted with highlight() sticks until I refresh the page.

### Steps to reproduce
1. taiko
2. goto()
3. highlight()

### Versions
```
node 13.6.0
taiko 1.0.3
```
Some webapps when refreshing brings you to a completely different screen.  It would be nice if clear() or something similar could remove the highlights.

**Comment by zabil** [comment]
Are you highlighting elements in the REPL? 
If that's the case maybe an argument to the `.clear` command like

```
.clear highlight
```

**Comment by TotalLag** [comment]
Correct. Using REPL for debugging.  If that worked it would fill this request.

**Comment by zabil** [comment]
Proposing the following command

```
.highlight
```

With any one of the following options

For disabling highlight feature on current REPL session
```
.highlight disable
```

Enabling the highlighting on current REPL session
```
.highlight disable
```

Clearing highlights on the current page
```
.highlight clear
```
