### ISSUE TITLE
Stack trace in Concept file not shown in Gauge report

### ISSUE THREAD

**Issue by TotalLag** [getgauge/taiko#1043]
### Expected behavior
Errors in Concept steps should be reported in HTML similarly to running into an error with a Spec step.

### Actual behavior
The HTML report shows that Spec step failed, but it does not contain information about the error or stack trace that was incurred by the Concept step

### Steps to reproduce
1. Create a Concept file with failure step
2. Use concept in Spec file as a step
3. Gauge run specs will report the error in the console.  The error does not show in the report.

### Versions
```
Node 13.6.0
Taiko 1.0.3
```

**Comment by negiDharmendra** [comment]
@TotalLag In HTML-Report you should see a plus(+) icon in front of the failing concept name.
Just click on that and you should be able to see the stacktrace.

<img width="1059" alt="Screenshot 2020-01-20 at 11 57 16 AM" src="https://user-images.githubusercontent.com/15261737/72703617-0e4afb80-3b7c-11ea-99d5-3bec14aea341.png">

**Comment by TotalLag** [comment]
Thank you.  I think something was preventing my browser from being able to expand the box.  Tried to view report on another machine and I am seeing more info.

Is there a way to halt tests and throw custom error messages?  If I throw an error outside of an async function, taiko would fail (expected) but it doesn't get picked up by Gauge.

**Comment by zabil** [comment]
Looks like you might be using
```
throw "Error";
```

Instead of

```
throw new Error("Error");
```

The former does not appear as a stack strace in the Gauge report.
