### ISSUE TITLE
Testing that a given selector does not exist

### ISSUE THREAD

**Issue by vitor-gyant** [getgauge/taiko#1047]
What is the available method to validate that a given selector does not exist ? 

My use case is confirming that a given element is not displayed after mocking a given API call. I'm using the intercept to mock the response but it seems that .exists() raises a timeout which I do understand why but I'd need to assert that the return is false and still pass the test.

Any idea how to achieve this ?

Thanks,

**Comment by zabil** [comment]
If you don't have to wait for the element you can set options on `exists` to not wait for it.

```
assert(!text("must not exist").exists(0,0))
```

**Comment by vitor-gyant** [comment]
@zabil Thanks. It worked.
