### ISSUE TITLE
Change browser locale

### ISSUE THREAD

**Issue by vitor-gyant** [getgauge/taiko#1050]
Is there support to mock or change the browser locale ? Thanks

**Comment by zabil** [comment]
Try passing the `--lang` option to [`openBrowser`](https://taiko.gauge.org/#openbrowser)

**Comment by vitor-gyant** [comment]
@zabil is it possible to change it after calling openBrowser ?

**Comment by zabil** [comment]
If the web application uses [`Accept-Language`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language) to identify the locale try setting that as a header in [`goto`](https://taiko.gauge.org/#goto)
