### ISSUE TITLE
switchTo with empty string should throw error

### ISSUE THREAD

**Issue by Debashis9012** [getgauge/taiko#1057]
### Expected behavior
`switchTo("")` should throw the below error.
```
 ✘ Error: The "targetUrl" argument must be of type string or regex. 
```

### Actual behavior
> switchTo("")
 ✔ Switched to tab matching

### Versions
```
commit: 8bf5be40abd96c2f391d94665e3005929d838de8
```

**Comment by luciferankon** [comment]
targetUrl is of type string why should it throw 
`✘ Error: The "targetUrl" argument must be of type string or regex.`
this error? Does not it makes sense to provide a error which makes more sense to user about what happened?
something like `targetUrl should not be empty`

**Comment by zabil** [comment]
> something like targetUrl should not be empty

Agree, but it should be a mix. The type of the argument also indicates that what's possible and the user can discover the support for regex. the message can be

In this case however, I think it should not switch to "" as there is not tab or window with that name so more importantly it should raise an error saying

```
Error: Cannot switch to tab or window. Hint: The targetUrl is empty. Please use a valid string or regex.
```
