### ISSUE TITLE
Automate the Taiko release for every PR merge

### ISSUE THREAD

**Issue by zabil** [getgauge/taiko#1074]
### Current behavior

PR's are merged after a static analysis and then tested. Issues are fixed via other PR's. This creates the need for a testing phase before a release making it a decision driven process at the end of the testing phase. A few problems with this approach

* Releases are delayed
* Merges are blocked during a release phase
* PR authors get testing feedback very late
* It is hard to keep track of discussions around a specific change.

### Expected behavior

* Review and test every PR
* Publish an new version of Taiko to npm whenever a PR is merged

#### Note
* All feedback and testing must be done on the PR before it is merged.
* There must also be a way to not trigger a release for certain PR's (Maybe minor changes)

**Comment by BugDiver** [comment]
This has been done.
