### ISSUE TITLE
Support for verifying http requests are made

### ISSUE THREAD

**Issue by ed0906** [getgauge/taiko#1079]
We can currently intercept http calls and return stubbed responses e.g.

`intercept("http://host.com/some-api-endpoint", ["some response"])`

To properly component test our UI we'd like to be able to verify that certain requests are made. For example "click save" then verify that a `POST` request was sent to the API with a certain payload.

This could potentially look like something along the lines of 
`var requestSent = intercepted("http://host.com/some-api-endpoint", {method: "POST"})`
Which could return `null`/`undefined` if the request wasn't made, or some representation of the request + body if it was.
A user could then use their assertion library of choice to assert on what request was or wasn't sent.

**Comment by sriv** [comment]
You can attach a callback to `intercept`, so if you were to do something like this:

```
intercept("http://host.com/some-api-endpoint",r => console.log(r))
```

You should see the payload that was sent to `http://host.com/some-endpoint`. The `r` here would look like this (note: I use a different URL):

```
request: {
    url: 'http://example.com/register',
    method: 'POST',
    headers: {
      'User-Agent': '<snipped>',
      'Content-Type': 'multipart/form-data; boundary=----WebKitFormBoundaryRI93xiyCXdfRxPa7',
      Accept: '*/*'
    },
    postData: '------WebKitFormBoundaryRI93xiyCXdfRxPa7\r\n' +
      'Content-Disposition: form-data; name="email"\r\n' +
      '\r\n' +
      'foo@example.com\r\n' +
      '------WebKitFormBoundaryRI93xiyCXdfRxPa7\r\n' +
      'Content-Disposition: form-data; name="password"\r\n' +
      '\r\n' +
      'garbage\r\n' +
      '------WebKitFormBoundaryRI93xiyCXdfRxPa7--\r\n',
    initialPriority: 'High',
    referrerPolicy: 'no-referrer-when-downgrade'
  },
```

**Comment by ed0906** [comment]
> You can attach a callback to `intercept`, so if you were to do something like this:
> 
> ```
> intercept("http://host.com/some-api-endpoint",r => console.log(r))
> ```
> 
> You should see the payload that was sent to `http://host.com/some-endpoint`. The `r` here would look like this (note: I use a different URL):
> 
> ```
> request: {
>     url: 'http://example.com/register',
>     method: 'POST',
>     headers: {
>       'User-Agent': '<snipped>',
>       'Content-Type': 'multipart/form-data; boundary=----WebKitFormBoundaryRI93xiyCXdfRxPa7',
>       Accept: '*/*'
>     },
>     postData: '------WebKitFormBoundaryRI93xiyCXdfRxPa7\r\n' +
>       'Content-Disposition: form-data; name="email"\r\n' +
>       '\r\n' +
>       'foo@example.com\r\n' +
>       '------WebKitFormBoundaryRI93xiyCXdfRxPa7\r\n' +
>       'Content-Disposition: form-data; name="password"\r\n' +
>       '\r\n' +
>       'garbage\r\n' +
>       '------WebKitFormBoundaryRI93xiyCXdfRxPa7--\r\n',
>     initialPriority: 'High',
>     referrerPolicy: 'no-referrer-when-downgrade'
>   },
> ```

I guess we could stick an assertion into the callback. It still wouldn't verify the request was actually made, but it would help with us verifying that *if the request was made* that it was made correctly.

I still think it'd be nice to have an `intercepted` method of some form. It could potentially hijack the existing interceptor framework thats in place under the hood e.g. create an interceptor that sticks the request in some store which is exposed via an `intercepted` (or better named) method

**Comment by zabil** [comment]
> I still think it'd be nice to have an intercepted method of some form. It could potentially hijack the existing interceptor framework thats in place under the hood e.g. create an interceptor that sticks the request in some store which is exposed via an intercepted (or better named) method

Something, that could be a plugin? 
It's better to keep mocking semantics out of Taiko in favour of stubbing for now. 

Closing this issue in the core, but hoping someone can use the info here and implement a plugin to support this.
