### ISSUE TITLE
Allow REPL communication via socket

### ISSUE THREAD

**Issue by adamalton** [getgauge/taiko#1084]
This is a feature request for allowing communication with the Taiko REPL via a Unix socket, as described in the [Node REPL docs](https://nodejs.org/api/repl.html#repl_starting_multiple_repl_instances_against_a_single_running_instance).

The reason for this is to allow a Taiko process to be started which can then be communicated with _programmatically_ from an entirely separate application.  I've looked around in the docs and the code, and I can't currently see a way of doing this.

If it helps, here's my particular use case:

I've got a web application which I want to run automated tests against. But I don't want the tests to be _only_ browser tests - I want to be able to do checks against the database and other aspects of the application.  My application happens to be written in Python, so my tests would look something like this:

```python
# test.py
start_application_server("http://localhost:8000")
run_process("taiko --socket 5555")  # My imagined new feature 🙂
check_database_contains_zero_users()
talk_to_socket(5555, ".load scripts/registration-flow.js")
check_database_contains_one_user()
talk_to_socket(555, ".load scripts/other-flow.js")
```

Currently I'm doing something similar to this but just by communicating with the process via `stdin` and `stdout`, but it seems really dirty and unreliable, because there's no reliable way to know when a command that you've sent has finished.  As I understand it (which is admittedly not very far!), putting the REPL on a socket would allow you to listen to the signals which indicate when a command has finished.

**Comment by sriv** [comment]
>  I've looked around in the docs and the code, and I can't currently see a way of doing this.

Yes, we didn't consider this so far. Thanks for bring this up.

 > I don't want the tests to be only browser tests - I want to be able to do checks against the database and other aspects of the application.

Normally, I'd recommend using Gauge+Taiko and let Gauge help do the orchestration both around and within your application. But since you mention python, this isn't currently possible.

The idea sounds sane to me. Would you be interested in taking a shot at raising a PR? I see that you've done most of the research already :)

**Comment by adamalton** [comment]
> The idea sounds sane to me.
Great, thanks for the feedback.

> Would you be interested in taking a shot at raising a PR? I see that you've done most of the research already :)
I can try! My Javascript is admittedly a bit rusty these days, but I'll try to allocate a few hours to this sometime over the next week and dig into it and create a PR.

Thanks!

**Comment by sriv** [comment]
Sounds good, feel free to call out if you need any input or just a sounding board.

**Comment by zabil** [comment]
Closing this as Taiko will not be implementing this feature.
