### ISSUE TITLE
will taiko support emoji?

### ISSUE THREAD

**Issue by SanjuSona-19** [getgauge/taiko#1091]
in taiko, it is only supporting the keyboard keys it is not supporting the emoji. is there any way to make the taiko supporting the emoji.
thankyou in advance.
![Screenshot from 2020-02-18 09-12-17](https://user-images.githubusercontent.com/60461581/74702066-d4c6e800-522e-11ea-88ce-88d1000f4d8d.png)

**Comment by sriv** [comment]
related #1061 

See [notes](https://github.com/getgauge/taiko/issues/1061#issuecomment-587290989).

**Comment by SanjuSona-19** [comment]
is there any alternative way to overcome it?
