### ISSUE TITLE
force closeBrowser or reload

### ISSUE THREAD

**Issue by dsolisp** [getgauge/taiko#1093]
### Expected behavior
There should be a flag or new option to force a close or reload page

### Actual behavior
Browser will not close as changes are not saved

<img width="456" alt="Screen Shot 2020-02-19 at 9 51 16 AM" src="https://user-images.githubusercontent.com/5098526/74848577-6b61da80-52fd-11ea-8f2c-5a8ac000d63b.png">

Console:
Failed to capture screenshot on failure.
Error: WebSocket is not open: readyState 3 (CLOSED)
    Error Message: Error: Timed out
    Stacktrace: 
    Error: Timed out
        at Timeout.<anonymous> (/Users/dsolis/.gauge/plugins/js/2.3.7/src/test.js:43:23)
        at ontimeout (timers.js:436:11)
        at tryOnTimeout (timers.js:300:5)
        at listOnTimeout (timers.js:263:5)
        at Timer.processTimers (timers.js:223:10)

### Steps to reproduce
1. Open a page with Edit (do not save changes)
2. Try to close the browser
3.  Chrome displays a popup with Leave site question...

### Versions
```
Daniel-Solis-MacBook-Pro:gauge-tests daniel.solis$ node --version
v10.16.0
Daniel-Solis-MacBook-Pro:gauge-tests daniel.solis$ taiko --version
Version: 1.0.3 (Chromium: 81.0.3994.0) RELEASE
```

Is there a working work around?

Thanks in advance

**Comment by negiDharmendra** [comment]
@dsolisp We do have an API [beforeunload](https://docs.taiko.dev/#beforeunload) to handle these [kinde of poup](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload) which seems to be broken as of now. We will try to fix this API and keep you updated.

**Workaround:** Right now the best workaround would be to ensure that either the content is saved or reset to the original state. 


**Observations**

For more informations about [beforeunload ](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload). Taiko adds an [listner](https://github.com/getgauge/taiko/blob/dd43357cbcbd8f15e6de74562b949d23cab28f85/lib/handlers/pageHandler.js#L46) to handle these events. But during `closeBrowser`  API call. Taiko [removes all the listeners](https://github.com/getgauge/taiko/blob/dd43357cbcbd8f15e6de74562b949d23cab28f85/lib/taiko.js#L313) added to the client just before calling `page.close()` which prevents **Taiko** from getting notified whenever `beforeunload` event is fired.

If users have registered any `beforeunload` popup handling, we need a way to wait for them to finish handling.
