### ISSUE TITLE
[Feature Request] to get an element by indexNumber on elements();

### ISSUE THREAD

**Issue by msx752** [getgauge/taiko#1095]
hi, could you add a specific function to get element in an array by number of Index

### Case
- there may more than one matches while using

 `$('input[maxlength="11"]');` **or** `$('button[type="button"].btn.btn-outline-dark');`

### Current State
- this is the ugly solution which i found.

```
let matches = $('button[type="button"].btn.btn-outline-dark');
let selectedElement = (await matches.elements())[indexNumber];
```

### Request
- this is not big deal but reducing the line of codes matter while working on project.
```
 let selectedElement =   await `$('input[maxlength="11"]').ElementAt(indexNumber);`
// or
 let selectedElement =   await `$('input[maxlength="11"]').At(indexNumber);`
```
``
### Versions
```
Version: 1.0.3 (Chromium:81.0.3994.0)
```

**Comment by zabil** [comment]
Perhaps

```
let selectedElement =   await $('input[maxlength="11"]').element(indexNumber);
```
