### ISSUE TITLE
Allow user to configure the port

### ISSUE THREAD

**Issue by BugDiver** [getgauge/taiko#110]
### Expected behavior
The port should be configurable.

### Actual behavior
A user can not configure the port. Currently, it's hardcoded to `9222`

This might cause an issue if some other process is using the same port.

**Comment by NivedhaSenthil** [comment]
Fix should be available in a9ea9fa

**Comment by NivedhaSenthil** [comment]
eg: `openBrowser({port:9222})`

**Comment by sguptatw** [comment]
Taiko documentation needs to be updated for this.

**Comment by NivedhaSenthil** [comment]
Have updated the docs.
