### ISSUE TITLE
ElementWrapper's .exists() no longer waiting for element to appear from 1.0.3 --> 1.0.4

### ISSUE THREAD

**Issue by nickanna42** [getgauge/taiko#1102]
### Expected behavior
`selector('criteria').exists(1000, j)` should wait up to j milliseconds for the element to appear before returning false

### Actual behavior
`selector('criteria').exists(1000, j)` immediately returns false if no element matching the criteria is present.

### Steps to reproduce
1. Point taiko at a page which will have an element appear within `x` milliseconds, but is not present at page load
2. upon page load, have taiko check to see if that element is present, providing `.exists()` a timeout value greater than `x`

### Versions
`node: v12.16.1`
`taiko: v1.0.4`

**Comment by NivedhaSenthil** [comment]
@nickanna42  Thanks for reporting, I could replicate the issue. Looks like `.exists` is not honouring the custom wait time given, we will look at fixing this soon.

**Comment by zabil** [comment]
@nickanna42 You can test this by installing the latest version of taiko from master using.

```
npm install https://github.com/getgauge/taiko
```
