### ISSUE TITLE
How to intercept and manipulate a real response of a network request

### ISSUE THREAD

**Issue by krsk9999** [getgauge/taiko#1103]
### Description
I need to intercept a network request and get the response retrieved from the server to save and validate its content.
Is there a way to get that?

This is an example we currently have in Cypress.io

cy.server();
cy.route(
	"POST",
	"https://domain/Prod/api/v1/test"
).as("request");

cy.wait("@request");

//Assert on XHR
cy.get("@request").then(function(xhr) {
	let responseBody = JSON.parse(xhr.response.body);
	expect(xhr.status).to.eq(201);
	expect(responseBody.CreativeId).to.eq(creativeId);
});

Thanks in advance!

**Comment by zabil** [comment]
There is core API for doing this but you could use the chrome remote interface via

https://docs.taiko.dev/#client

and use something like 

https://chromedevtools.github.io/devtools-protocol/tot/Network#method-getResponseBodyForInterception

**Comment by xyb** [comment]
> There is no core API for doing this but you could use the chrome remote interface via
> 
> https://docs.taiko.dev/#client

The document has been moved to https://docs.taiko.dev/api/client/
