### ISSUE TITLE
Writing to the input field not working

### ISSUE THREAD

**Issue by Apoorva-GA** [getgauge/taiko#111]
### Expected behavior
Shouldn't hang and should write the given text to the input field

### Actual behavior
Doesn't write the given text to input field and script hangs.

### Steps to reproduce
```
const { browser, openBrowser, goto, click,link,image } = require('taiko');

(async () => {
    try {
        await openBrowser({headless:false});
        await goto("https://in.bookmyshow.com/bengaluru");

        await click("Bengaluru");
        await write('NCR', into(await inputField({"placeholder":"Search for your city"})));
    } catch (e) {
        console.error(e);
    } finally {
        await closeBrowser();
    }
})();
```

### Versions
```
taiko version : 0.1.0
```

**Comment by Apoorva-GA** [comment]
Fix should be available in commit 0721871

**Comment by sguptatw** [comment]
Sorry closed it by mistake

**Comment by sguptatw** [comment]
This issue is still replicable with the same steps in commit `ec0cb85571aa2130abd5fe7a183de1ad709f1b5b`

**Comment by sguptatw** [comment]
This issue is replicable on Windows with the same steps. Works as expected in Mac
commit - a5da76d97ef5a1e6ca17534424747b96003c8b13

**Comment by Apoorva-GA** [comment]
Unable to replicate the issue on windows. Works as expected with the below mentioned steps : 
```
const { browser, openBrowser, goto, click,link,image } = require('taiko');

(async () => {
    try {
        await openBrowser({headless:false});
        await goto("https://in.bookmyshow.com/bengaluru");

        await click("Bengaluru");
        await write('NCR', into(await inputField({"placeholder":"Search for your city"})));
    } catch (e) {
        console.error(e);
    } finally {
        await closeBrowser();
    }
})();
```

Commit : 1af8a9dcc2595b2ec8635869aa66743bb3f97baf

**Comment by sguptatw** [comment]
Working as expected `acaa752bbcc298d48152d8fc893529efa283f0a8`
