### ISSUE TITLE
[issue] write function doesn't support unicode characters

### ISSUE THREAD

**Issue by msx752** [getgauge/taiko#1112]
### Expected behavior
`write('Testüöşığ123')` function's output is `Testüöşığ123`

### Actual behavior
`write('text')` function's output is `Test` and stopping when reach to char`ü` and gives error `Error Message: Error: Unknown key: "ü"`

### Versions
```
Version: 1.0.3 (Chromium:81.0.3994.0)
```

**Comment by NivedhaSenthil** [comment]
Try updating taiko to 1.0.4 which has a fix for this

**Comment by msx752** [comment]
you right, i am closing the issue. thank you @NivedhaSenthil
