### ISSUE TITLE
Unable to switch to windows popup

### ISSUE THREAD

**Issue by tariquesalat386** [getgauge/taiko#1113]
### Expected behavior
Should be able to switch to a windows popup and respective actions should be performed accordingly in the popup.

### Actual behavior
Unable to switch to windows popup no needful actions are being performed.

### Steps to reproduce
After clicking a particular link on a webpage, a popup is displayed to select value from dropdowns to proceed further.
I tried a couple of ways to tackle that but of no luck.
Can anyone please guide me with a script on how to select the values from dropdowns from attached snapshot.

### Taiko code used to read dropdowns:
1. await dropDown(below('Select the following to proceed')).select(`SABRE`);
2. await dropDown(toRightOf('GDS')).select(`SABRE`);
3. I have also tried to implement alert/prompt listeners in the code but no luck.

### Versions
Gauge version: 1.0.7
html-report (4.0.9)
js (2.3.8)
json-report (0.3.2)
screenshot (0.0.1)
xml-report (0.2.3)
Node - 12.7.0
Taiko - 1.0.4
![Capture 1](https://user-images.githubusercontent.com/58719426/75964058-9434c300-5eec-11ea-8434-bb0ffeddc28e.JPG)
![Capture](https://user-images.githubusercontent.com/58719426/75964078-9a2aa400-5eec-11ea-96a5-4f64e50bfe2f.JPG)

**Comment by NivedhaSenthil** [comment]
`dropdown` api looks for <select> tag and from the snippet it doesn't look like one. Seems like a div painted to look like a dropdown. Can you try using multiple `click` to select instead ?

**Comment by tariquesalat386** [comment]
Hi Nivedha, as suggested I tried using multiple clicks to select the value and it is working fine. You are right it is painted as to look like a dropdown.
Closing this issue. Thanks for the help.
