### ISSUE TITLE
Spike: Support for Microsoft edge

### ISSUE THREAD

**Issue by zabil** [getgauge/taiko#112]
[Microsoft Edge Diagnostics Adapter](https://github.com/Microsoft/edge-diagnostics-adapter) is a protocol adapter that enables tools to debug Microsoft Edge using the Chrome DevTools Protocol. 

Check of Taiko can connect this adapter for running tests on Microsoft Edge.

**Comment by NivedhaSenthil** [comment]
Microsoft edge is being written based on chromium and the nightly builds are out. Currently it is available only for windows10 https://www.microsoftedgeinsider.com/en-us/ . Taiko works fine with the dev build available in it, all functional tests passed. 

Just set `TAKIO_BROWSER_PATH` to Edge's path and thinks works seamlessly. We can expect it to work the same way once it is released for other platforms too.

**Comment by sriv** [comment]
This is good news. We can add this to the docs, and potentially include examples of cross browser (at least with Chrome/Edge) testing.
