### ISSUE TITLE
Documentation for textBox is missing

### ISSUE THREAD

**Issue by moogleberry** [getgauge/taiko#1123]
### Expected behavior
Should have documentation for textBox on website

### Actual behavior
Documentation for textBox  does not show on website

### Versions
```
Taiko 1.0.4 website: https://docs.taiko.dev/#textbox
```

**Comment by sriv** [comment]
thanks for reporting, I can see that the `textBox` section is missing even when I generate the site from source.

Looking into this.

**Comment by sriv** [comment]
fixed via 4196c68d5adb36d3264b90a1b1f9735efe0610a7
