### ISSUE TITLE
dropdown selection doesn't respond

### ISSUE THREAD

**Issue by jaredkotoff** [getgauge/taiko#1127]
Seems similar to #936 but this isn't a react app

### Expected behavior
When using `dropDown().select()` the app should reflect the new state.

### Actual behavior
The dropdown is changed but the app's state remains the same.  
![image](https://user-images.githubusercontent.com/3268576/76770400-22b20b80-675b-11ea-8007-4ba065422a3f.png)

### Steps to reproduce
```javascript
const { openBrowser, goto, dropDown, closeBrowser } = require('taiko');
(async () => {
  try {
    await openBrowser();
    await goto('https://www.twitch.tv/jobs#jobs');
    await dropDown({ id: 'job-offices' }).select('tokyo-japan');
    await new Promise(resolve => setTimeout(resolve, 30000));
  } catch (error) {
    console.error(error);
  } finally {
    await closeBrowser();
  }
})();
```
Note the difference when a human uses the dropdown than when taiko selects the option.

### Versions
```
node 13.10.1
taiko 1.0.5
```

**Comment by sriv** [comment]
`select` takes the `option`'s display text, not `value`. Please try this:

```
const { openBrowser, goto, dropDown, closeBrowser } = require('taiko');
(async () => {
    try {
        await openBrowser();
        await goto('https://www.twitch.tv/jobs#jobs');
        await dropDown({ id: 'job-offices' }).select("Tokyo, Japan");
    } catch (error) {
        console.error(error);
    } finally {
        await closeBrowser();
    }
})();
```

**Comment by jaredkotoff** [comment]
@sriv same result.  
The issue isn't that the selection didn't change, its that the page does update. In this case, the filtering isn't applied.

**Comment by sriv** [comment]
Thanks, that helped. Taiko was not firing `input` event on dropdown change, it only fires `change` event. In this case the method to filter was registered to `input` event.

Fix following...
