### ISSUE TITLE
Case insensitive selectors

### ISSUE THREAD

**Issue by gabrielpeixinho** [getgauge/taiko#1134]
### Expected behavior
Selectors should be case insensitive
 
Example: radioButton(...) should work for &lt;input type="Radio" > (case insensitive)

[Spectrum Thread](https://spectrum.chat/taiko/general/making-taiko-works-with-input-that-has-type-value-with-upper-letters~c60854a2-2abc-40ea-8b36-8708d930cba7)

**Comment by gabrielpeixinho** [comment]
I would love to work on this issue, can I? =)

**Comment by sriv** [comment]
We would love it. Please carry on and raise a PR when you are done!!

**Comment by sriv** [comment]
fixed via #1137
