### ISSUE TITLE
Should show screenshot when async custom screenshot is defined

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#114]
**Expected behavior**
Should show screenshot when async custom screenshot is defined

**Actual behavior**
The screenshot does not appear

**Steps to replicate**
* Create a js-taiko project
* Ensure the project dependency has the latest taiko
```
  "dependencies": {
    "taiko": "git+https://github.com/getgauge/taiko.git#ddd7db3a57be5b6e9a1922d85928050077f583ed"
  }
```
* In the implementation add the custom screenshot and use it in as step
```
const { openBrowser, closeBrowser, goto, click, text,screenshot } = require('taiko');

gauge.screenshotFn = async function () {
    return await screenshot();
};

step("Go to Gauge homepage at <query>", async (query) => {
    goto(query)
    gauge.screenshot();
});
```
* Run the test
> The screenshot image is getting captured. The file is available in the project
* Open the html-report report. 
> The image is not displayed

**Version**
```
Gauge version: 1.0.1.nightly-2018-08-16
Commit Hash: fbaccd3

Plugins
-------
js (2.3.2.nightly-2018-08-17)
screenshot (0.0.1)
```
Taiko - ddd7db3a57be5b6e9a1922d85928050077f583ed

Blocks https://github.com/getgauge/gauge-js/issues/165

**Comment by zabil** [comment]
Please modify the code to

```
gauge.screenshotFn = async function () {
    return await screenshot({encoding: "base64"});
};

```

**Comment by sguptatw** [comment]
Thanks, but after modifying the code as suggested getting an empty screenshot in the report.

<img width="838" alt="screen shot 2018-08-21 at 8 26 20 am" src="https://user-images.githubusercontent.com/6310197/44377824-0c5eb200-a51c-11e8-81d7-c89a15df8c18.png">

**Comment by Apoorva-GA** [comment]
I am getting a valid screenshot. Please have a look.
<img width="1428" alt="screen shot 2018-08-24 at 10 28 23" src="https://user-images.githubusercontent.com/8462534/44565989-a1fe7980-a788-11e8-9e95-3094b3605141.png">

**Comment by sguptatw** [comment]
Here is a project with which I am not getting the screenshot https://github.com/sguptatw/js-taiko-screenshot.

```
Gauge version: 1.0.1.nightly-2018-08-22
Commit Hash: 3750b26

Plugins
-------
js (2.3.2.nightly-2018-08-17)
screenshot (0.0.1)
```

Taiko commit - ddd7db3a57be5b6e9a1922d85928050077f583ed

**Comment by sguptatw** [comment]
The empty screenshot is when the script is run in the headless mode. In the headless mode false the screenshot is captured as expected.

**Comment by Apoorva-GA** [comment]
Even with the above mentioned [project](https://github.com/sguptatw/js-taiko-screenshot) I am able to get screenshot.
<img width="1436" alt="screen shot 2018-08-28 at 14 57 44" src="https://user-images.githubusercontent.com/8462534/44714432-eebcba00-aad2-11e8-8c06-db5317c45e62.png">

**Comment by sguptatw** [comment]
Can you try running it in the headless mode. Like I mentioned in the above comment, the problem seems to be when run in the headless mode.

**Comment by Apoorva-GA** [comment]
I am running the project you have mentioned above. Which runs taiko in headless mode.

**Comment by NivedhaSenthil** [comment]
In the [project](https://github.com/sguptatw/js-taiko-screenshot) there is no await on goto and screenshot 
https://github.com/sguptatw/js-taiko-screenshot/blob/master/tests/step_implementation.js#L16

which will not ensure that the goto is done to take screenshot and also screenshot is taken properly before sending it to reports. It has to be like below
```
await goto(query);
await gauge.screenshot();
```

I am able to get proper screenshot always with the above fix.
