### ISSUE TITLE
closeWindow should connect to existing window after closing current

### ISSUE THREAD

**Issue by NivedhaSenthil** [getgauge/taiko#1142]
### Expected behavior
`closeWindow` should close the current active window and connect to existing window.

### Actual behavior
closes the current window and does not make a new connection to existing window.

### Steps to reproduce

```
> openBrowser()
 ✔ Browser opened
> openWindow("google.com")
Incognito windows in non-headless mode is unstable and may have issues
 ✔ Incognito window opened with name undefined
> closeWindow()
 ✔ Window with name undefined closed
> openWindow("google.com",{incognito:false})
' ✘ Error: WebSocket is not open: ' +
  'readyState 3 (CLOSED), run `.trace` for ' +
  'more info.'
> closeWindow()
" ✘ Error: Cannot read property 'targetId' " +
  'of undefined, run `.trace` for more info.'
```

Dev note:
enable the test after fix https://github.com/getgauge/taiko/blob/c147a4bf06a4efe1ab19b394e1a7010bdd9faf0b/test/unit-tests/browserContext.test.js#L113

### Versions
```
Version: 1.0.6 (Chromium: 81.0.3994.0) RELEASE
```

**Comment by saikrishna321** [comment]
Right usage of `openWindow` and `closeWindow` API

```
Version: 1.0.6 (Chromium:81.0.3994.0)
Type .api for help and .exit to quit

> openBrowser()
 ✔ Browser opened
> openWindow("google.com", {name:'admin'})
Incognito windows in non-headless mode is unstable and may have issues
 ✔ Incognito window opened with name admin
> closeWindow('admin')
 ✔ Window with name admin closed
> openWindow("google.com",{incognito:false})
" ✘ Error: Cannot read property 'message' of undefined, run `.trace` for more info."
> 
```

**Comment by saikrishna321** [comment]
I had a chat with @zabil and we thought of deprecating the existing `openWindow` and  `closeWindow` API and create a new API called as `openIncognitoWindow` and `closeIncognitoWindow`

Reason: Once we switch the connection to default window in `closeWindow` API the default browser becomes the active target and opening a window with `incognito:false` gives us no benefit.

With the new API we get the flexibility to open window in Incognito and perform the journey and close the window and start journey on a non-incognito window.
