### ISSUE TITLE
switchTo() doesn't support RegEx's anymore

### ISSUE THREAD

**Issue by bjarkehs** [getgauge/taiko#1147]
There seems to be a bug in `lib/taiko.js` on line 418-422. This function isn't present on a RegEx. The call could be moved. The tests should probably also be updated to test for this use case.

Alternatively this should be removed from the docs.

### Expected behavior
Calling `switchTo(/http(s):\/\/www.google.com/)` is a valid use case.

### Actual behavior
A TypeError is thrown:
```
Error Message: TypeError: arg.trim is not a function
        Stacktrace: 
        TypeError: arg.trim is not a function
            at module.exports.switchTo (node_modules/taiko/lib/taiko.js:419:13)
            at module.exports.<computed> (node_modules/taiko/lib/taiko.js:3225:36)
            at Object.<anonymous> (tests/login.js:70:9)
```

### Steps to reproduce
1. Create a taiko step
2. Call switchTo(/http/)

### Versions
```
$ node --version
v13.11.0

$ taiko --version
Version: 1.0.5 (Chromium: 81.0.3994.0) RELEASE
```

**Comment by zabil** [comment]
Looks like this was caused by this change https://github.com/getgauge/taiko/pull/1118
