### ISSUE TITLE
Taiko install failure

### ISSUE THREAD

**Issue by crogger62** [getgauge/taiko#115]
### Expected behavior
Tried to install Taiko per github instructions: 
npm install -g taiko

### Actual behavior

ERROR: Failed to download Chromium r571040! Set "SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/taiko/.local-chromium'
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/local/lib/node_modules/taiko/.local-chromium' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! taiko@0.1.0 install: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the taiko@0.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/crog/.npm/_logs/2018-08-24T14_39_57_874Z-debug.log

### Steps to reproduce
npm install -g taiko

### Versions
```
installed on ubuntu 16.04 LTS
npm version 6.4.0
node version 8.11.4
taiko v0.1.0 (?) 


```

**Comment by sriv** [comment]
I could see the same issue. I could successfully install using `sudo` i.e. `sudo npm install -g taiko`

It seems that in linux there could be a permission issue to write to `/usr/local/lib/node_modules` which is the default node prefix location.

`sudo chown -R $(whoami) /usr/local/lib/node_modules` could also be an option that is suggested by various folks on various forums.

**Comment by zabil** [comment]
There are other issues install `npm` modules with `sudo` for e.g launching the chrome browser fails on taiko REPL
For linux systems the best option is to set a [custom npm install](https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-two-change-npms-default-directory) location

We've mentioned it in [Getting Started](https://github.com/getgauge/taiko#getting-started) but Taiko must have a better way to handle this as the steps are elaborate and not easy for noobs.

**Comment by crogger62** [comment]
Yes, it turned out to be a permissions issue and more of an npm install issue. Once fixed Taiko worked as expected! sriv's suggestion worked best. Thanks!

**Comment by KaiserItachi** [comment]
I faced the same issue and even with sudo, i was getting the below error
EACCES: permission denied, mkdir '/usr/lib/node_modules/taiko/.local-chromium.

So i just went ahead and manually created the .local-chromium folder and then did npm install -g taiko. It worked.

**Comment by sriv** [comment]
also `npm i -g --unsafe-perm taiko` should work.

**Comment by Shivkant-Chauhan** [comment]
hi @sriv, I am also facing many problems in installing Taiko! your suggestion works for Windows as well as Linux users.. But I am still stuck in taiko's installation in my mac. Can anyone please help?

**Comment by edison-0828** [comment]
Encountered this problem: Error getting Taiko node directory: Failed to get home directory Can anyone help?
