### ISSUE TITLE
Cannot click although log shows click pass

### ISSUE THREAD

**Issue by levietquynh** [getgauge/taiko#1163]
### Expected behavior
Can click successfully after log shows pass "click button..."

### Actual behavior
Button isn't clicked although log show pass "click button..."

### Steps to reproduce
1. I write a step to scroll then click a Save button
    await scrollUp($('#btnSaveConfig'))
    await click(button({ id: 'btnSaveConfig' }))
2. When Save Config button is click, Run button will be enable. But when I click Run button, it's failed because Run button is disable.
3. I see screenshot for failing issue then see Run button is still disable. I guess Save Config isn't clicked before. But it shows log as pass

### Versions
taiko 1.0.5 and node v12.16.1

**Comment by zabil** [comment]
Maybe related to https://github.com/getgauge/taiko/pull/1138
Please upgrade to vesion 1.0.6

**Comment by levietquynh** [comment]
Hi zabil,

I upgrade to 1.0.6 but I still meet that problem. I don't want to add waitFor(2000), it makes me waste time to wait next step. 

My steps is:
Click on 'Edit Config Save' button
Click on 'Save Config' button
Click on 'Run' button

There is Edit Config pop-up, when I click 'Edit Config Save', the pop-up will close.
I write method to wait for pop-up close, then click 'Save Config' button.
After click 'Save Config' button, Run button will be enable to click.
But it's alway failed after Click on 'Save Config' button, on log, Click on 'Save Config' button is pass, but when I check screenshot, I don't see Run button is enable. So I guess Save Config is never clicked.

This is my code:
await click(button({ id: 'btnEditConfigSave' }))
await utils.waitForPopupClose("Edit Config")
await scrollUp($('#btnSaveConfig'))
await click(button({ id: 'btnSaveConfig' }))
await utils.waitForPageLoad()
await utils.waitForControlNotDisabled('btnRun')
await click(button({ id: 'btnRun' }))


This is failed log
Click on 'Run' button	 ...[FAIL]
         
         Failed Step: Click on 'Run' button
         Error Message: Error: Button[@id = concat('btnRun', "")]is disabled
         Stacktrace: 
         Error: Button[@id = concat('btnRun', "")]is disabled
             at _click (node_modules/taiko/lib/taiko.js:1093:13)
             at async click (node_modules/taiko/lib/taiko.js:1155:5)

**Comment by sriv** [comment]
Is this still an issue?

in order to investigate, we'll need an example that we can run. So if you have a sample script illustrating the problem and access to the html, please do share.

**Comment by sriv** [comment]
Closing this. Feel free to comment with more information to help troubleshoot, if this is still an issue.
