### ISSUE TITLE
Remove translation map for browser permissions

### ISSUE THREAD

**Issue by sriv** [getgauge/taiko#1165]
### Expected behavior
Taiko's `overridePermissions` api should use the permissions defined in CDP - https://chromedevtools.github.io/devtools-protocol/tot/Browser#type-PermissionType

### Actual behavior
Taiko has a translation layer that is out of sync with the upstream permissions defined. Example `clipboard-read` and `clipboard-write` do not work because 
upstream merged these into `clipboardReadWrite`.

### Versions
```
$ node -v
13.12.0

$ taiko -v
Version: 1.0.6 (Chromium: 81.0.3994.0) RELEASE

```

**Comment by NivedhaSenthil** [comment]
Fixed by 4bcbd1a
