### ISSUE TITLE
closeBrowser fails

### ISSUE THREAD

**Issue by nathanBrenner** [getgauge/taiko#1166]
### Expected behavior
There shouldn't be a type error and the browser should close when `closeBrowser` is invoked in the callback of the afterSuite

### Actual behavior
Chromium stays open. Error printed in console:
```
Error Message: TypeError: Cannot read property 'removeAllListeners' of null
  Stacktrace: 
  TypeError: Cannot read property 'removeAllListeners' of null
      at _closeBrowser (node_modules/taiko/lib/taiko.js:347:19)
```
### Steps to reproduce
1. click "Run Scenario
2. Chromium opens, and the error is logged to the console, and chromium stays open

test:
```
## Search

* Starting from a new session
* I visit the console homepage
* I search for vulnerabilities in the ecosystem, version and the results include the vulnerability
  | ecosystem | version | foo  |
  | --------- | ------- |----------------|
  | value1      | version1   | foo1  |
```

### Versions
```
node: 10.16.0, taiko: 1.0.6
```

**Comment by nathanBrenner** [comment]
Works as expected with taiko installed at version 1.0.2. on 1.0.0 and 1.0.3, this error is returned:
```
  Error Message: Error: Timed out
  Stacktrace: 
  Error: Timed out
      at Timeout.<anonymous> (/Users/myworkspace/.gauge/plugins/js/2.3.8/src/test.js:43:23)
      at ontimeout (timers.js:436:11)
      at tryOnTimeout (timers.js:300:5)
      at listOnTimeout (timers.js:263:5)
      at Timer.processTimers (timers.js:223:10)
```
and the original error comes back in 1.0.4, then the timeout bug comes back in 1.0.5

**Comment by nathanBrenner** [comment]
The spec in the description wasn't helpful. I had two files in the tests directory with these lines in both files:

```
beforeSuite(async () => {
  await openBrowser({ headless: headless })
})

afterSuite(async () => {
  await closeBrowser()
})
```

The outcome was openBrowser was called twice, so opening two instances of Chromium, and closeBrowser was called twice, so maybe _client on the second call didn't have the `removeAllListeners`

It also looks like the order of specs that are invoked are sorted alphabetically by the specification headings, and whichever is the first heading, that one and only that one should openBrowser and closeBrowser in the beforeSuite and afterSuite.

is a suite a test specification? or does it comprises of all of the specs in the specs directory?

**Comment by zabil** [comment]
Depends on https://github.com/getgauge/taiko/issues/818#issuecomment-608319716

**Comment by sriv** [comment]
@nathanBrenner - please upgrade and try. #1181 fixes an issue with `closeBrowser`
