### ISSUE TITLE
Should wait for the page to load before performing the action

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#118]
**Expected behavior**
Should wait for the page to load before performing the action

**Actual behavior**
It tries to perform the action before the page is loaded completely

**Steps to replicate**
* Pull the image - this is a one time task
`docker pull mddubey/bahmni-openmrs`

**Steps given below should be performed before running the script everytime**

* Stop all containers
docker stop $(docker ps -aq)
* Remove all containers
docker rm $(docker ps -aq)

> This is required as the application takes longer time to initialize. Taiko is expected to wait for page load until the initializations succeed.

* Start a container and map the 443 port for httpd
`docker run -itd --name=sample -p 8000:443 mddubey/bahmni-openmrs /bin/bash`

> The following step has to be done once
* Open the REPL. Access the link https://localhost:8000/bahmni/home/index.html#/login. This will give you a security warning. Resolve this manually. 

* Run the script
```
const { openBrowser, goto, inputField, into, write, toRightOf, comboBox, click } = require('taiko');

(async () => {
    try {
        await openBrowser();
        await goto("https://localhost:8000/bahmni/home/index.html#/login");
        await write("user",into(inputField({"placeHolder":"Enter your username"})));
    } catch (e) {
        console.error(e);
    } finally {
        closeBrowser();
    }
})();
```
> The script fails to find the first input Field as it does not wait sufficiently for the calls to complete

Blocks #28

**Comment by Apoorva-GA** [comment]
@sguptatw this seems to work fine after the waitForNavigation fix. Please verify with commit 1af8a9dcc2595b2ec8635869aa66743bb3f97baf.
