### ISSUE TITLE
Support for discovering --emulate-network

### ISSUE THREAD

**Issue by scottdavis99** [getgauge/taiko#1197]
### Expected behavior
When a user types `taiko --help`, the options for --emulate-network are hardcoded. The values for this flag are stored in https://github.com/getgauge/taiko/blob/master/lib/data/networkConditions.js

It would be preferable to have a `.list-emulated-networks` command in the REPL, and a `taiko --list-emulated-networks` command line flag to shield the user from the implementation details.

### Steps to reproduce
1. Type `taiko --help`

### Versions
```
taiko --version
Version: 1.0.7 (Chromium: 81.0.3994.0) RELEASE

node --version
v12.14.1
```

**Comment by zabil** [comment]
This is now a part of the API documentation.

```
.api emulateNetwork
Activates emulation of network conditions.

Parameter:

* networkType - string - 'GPRS','Regular2G','Good2G','Good3G','Regular3G','Regular4G','DSL','WiFi, Offline'


Returns: Promise

Examples:
	await emulateNetwork("Offline")
	await emulateNetwork("Good2G")
```
