### ISSUE TITLE
Create 'Deprecated' section in .api call from Taiko REPL

### ISSUE THREAD

**Issue by scottdavis99** [getgauge/taiko#1199]
### Expected behavior
I'd like to see a 'Deprecated' section in the list of actions when the user types `.api` in the Taiko REPL. 

Currently, these actions are deprecated, but still listed among the active actions. The only way to discover that they are deprecated is by typing `.api openWindow`.

Partial (?) list of deprecated actions:

- openWindow
- closeWindow

**Comment by zabil** [comment]
Closing this as Taiko will not be deprecating any more API's.
