### ISSUE TITLE
Adding Taiko to Firebase project prevents deployment

### ISSUE THREAD

**Issue by ultraGentle** [getgauge/taiko#1201]
EDIT: Taiko 1.07, Node 12.16.2, npm 6.9.0

I recently (attempted) to add Taiko to my Firebase web app.  Now deployment fails with the error message below.  

I believe this is a Taiko issue, because adding other packages has not created a problem.   

**Steps to reproduce**

- created a Taiko test function in `index.js`, `require`ing Taiko.  

- added Taiko to `package.json` 

- ran `npm install` in functions folder 

- received message (maybe unrelated) `
npm WARN ws@7.2.3 requires a peer of bufferutil@^4.0.1 but none is installed. 
npm WARN ws@7.2.3 requires a peer of utf-8-validate@^5.0.2 but none is installed. 
You must install peer dependencies yourself.
`  

- following which, `npm install`ed both of the above packages in `/functions` 

**Error Message:** (bold mine, highlighting stuff that might be relevant)

- **Build failed:** {"error": {"canonicalCode": "INVALID_ARGUMENT", "errorMessage": "\`npm_install\` had stderr output:\n/workspace/node_modules/fs-extra/lib/mkdirs/make-dir.js:86\n      } catch {\n              ^\n\nSyntaxError: **Unexpected token {\n**    at createScript (vm.js:80:10)\n    at Object.runInThisContext (vm.js:139:10)\n    at Module._compile (module.js:617:28)\n    at Object.Module._extensions..js (module.js:664:10)\n    at Module.load (module.js:566:32)\n    at tryModuleLoad (module.js:506:12)\n    at Function.Module._load (module.js:498:3)\n    at Module.require (module.js:597:17)\n    at require (internal/module.js:11:18)\n    at Object.<anonymous> (/workspace/node_modules/fs-extra/lib/mkdirs/index.js:3:44)\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 1\nnpm ERR! taiko@1.0.7 install: \`node lib/install.js\`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! **Failed at the taiko@1.0.7 install script.\nnpm** ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /builder/home/.npm/_logs/2020-04-19T14_36_20_217Z-debug.log\n\nerror: \`npm_install\` returned code: 1", "errorType": "InternalError", "errorId": "02C3A7B5"}}

**package.json**

```
{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "lint": "eslint .",
    "serve": "firebase serve --only functions",
    "shell": "firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "8"
  },
  "dependencies": {
    "firebase-admin": "^8.10.0",
    "firebase-functions": "^3.3.0",
    "node-fetch": "^2.6.0",
    "stripe": "^7.14.0",
    "taiko": "^1.0.6",
    "bufferutil": "^4.0.1",
    "utf-8-validate": "^5.0.2"
  },
  "devDependencies": {
    "eslint": "^5.12.0",
    "eslint-plugin-promise": "^4.0.1",
    "firebase-functions-test": "^0.1.6"
  },
  "private": true
}

```

**index.js** (I don't think this is relevant, but including for completeness:  

```
exports.taikoTest = functions.region('us-east1').https.onCall(async (data, context) => {
  const {openBrowser, goto, write, press, text, closeBrowser} = require('taiko');
    console.log('taiko started');
    try {
      await openBrowser();
      await goto('www.google.com');
      await write('wikipedia');
      await press('Enter');
      const result = await text('wikipedia').text();
      console.log(result);
    } catch (error) {
      console.error(error);
    } finally {
      await closeBrowser();
    }
});

```

Thanks for any insights!

**Comment by NivedhaSenthil** [comment]
can you please update details about the versions of taiko, node and npm being used ?

**Comment by ultraGentle** [comment]
@NivedhaSenthil Apologies: Taiko 1.07, Node 12.16.2, npm 6.9.0

**Comment by zabil** [comment]
This error generally happens on version < node 10 indirectly because of the fs-extra package.
Firebase cloud functions uses node 8 by default. Please try setting the expermental node 10 as mentioned in the documentation at
https://firebase.google.com/docs/functions/manage-functions#set_nodejs_version

**Comment by ultraGentle** [comment]
Thank you, this solved my issue!

Perhaps it is worth putting a note about this in the "install" section of taiko.dev for anyone using taiko in a remote environment.  

When I tested locally, there was no problem, so it didn't occur to me to check my remote runtime.  Of course, that's my fault, but a little more direction in the install section might save time in the future.  

Thanks again!

**Comment by zabil** [comment]
Now that this issue is here, someone can search find hopefully solve it.
