### ISSUE TITLE
Initializing taiko in an existing project overrides the project's package.json

### ISSUE THREAD

**Issue by cnagadya** [getgauge/taiko#1208]
### Expected behavior
Modify the existing package.json like it does for the .gitignore file when initialised using _gauge init js_ if there is already an existing package.json file

### Actual behavior
package.json should be updated as is the case with other files eg .gitignore

### Versions
```
node v12.11.1
taiko v1.0.8/ current latest
```

**Comment by zabil** [comment]
Thanks for reporting this.

But unfortunately `gauge init js` is very different from `npm` as it downloads a zip file and extracts it's content. 

The only workaround is running 'gauge init js' first and then modifying `.gitignore` and `package.json`

**Comment by cnagadya** [comment]
Interesting since the .gitignore is not overridden, just added to but the package.json is completely replaced. Thanks for the response though

**Comment by zabil** [comment]
You are right.
There was a change done for this https://github.com/getgauge/gauge/issues/785

Doing this for package.json is going to be trickier as it's a JSON file so appending won't help.

I looked at what `npx create-react-app` does

```
npx create-react-app .
npx: installed 99 in 6.387s
The directory . contains files that could conflict:

  .vscode/
  env/
  manifest.json
  package-lock.json
  package.json
  specs/
  tests/

Either try using a new directory name, or remove the files listed above.
```

It does not allow creation of the project. 
Gauge does this check for existing Gauge projects. But I am not sure this can be done reliably 
for other files as Gauge can be initialized for different languages.
