### ISSUE TITLE
Get error Error: Cannot read property 'message' of undefined at runtimeEvaluate

### ISSUE THREAD

**Issue by windyliu1118** [getgauge/taiko#1216]
### Expected behavior
The browser communication should not be closed when this type of error occurs.

### Actual behavior
Once the error Cannot read property 'message' of undefined occurs, then the browser will fail to be closed. Seems some kind of communication with browser is closed.

### Steps to reproduce
When running test, I got the error below:
Error: Cannot read property 'message' of undefined
at runtimeEvaluate (/var/lib/jenkins/workspace/testing_branch/node_modules/taiko/lib/handlers/runtimeHandler.js:59:20)
[0;31m
  Error Message: rpc error: code = Unavailable desc = transport is closing
  Stacktrace:
My env variable is as below:
```
node: 10.16.3
Taiko: Version: 1.0.5 (Chromium: 81.0.3994.0) RELEASE
Gauge version: 1.0.7
Commit Hash: ed7b4fd6
Plugins
-------
html-report (4.0.9)
js (2.3.7)
screenshot (0.0.1)
xml-report (0.2.3)
```

**Comment by NivedhaSenthil** [comment]
@windyliu1118 can you please provide an example as in when this happens ?

**Comment by zabil** [comment]
It's still worth handling the error reporting for this at.

https://github.com/getgauge/taiko/blob/88b4b73875dfbf12f6f752138bb11bab72167f04/lib/handlers/runtimeHandler.js#L55-L59

It should should do a check if the error does not have a message and report correctly

**Comment by zabil** [comment]
It looks like the error check on issue is already done.
@windyliu1118 can you please see if this error is happening with Taiko 1.0.11?

**Comment by NivedhaSenthil** [comment]
Closing as the error handling is done properly and Taiko should throw the right error now.
