### ISSUE TITLE
Taiko doesn't work when installed using Yarn (works with npm)

### ISSUE THREAD

**Issue by Calinou** [getgauge/taiko#1218]
### Expected behavior

Taiko should work when installed using Yarn, or the README should make it prominent that only npm is supported. Maybe an error can be thrown while installing Taiko?

### Actual behavior

Running `taiko` prints nothing and exits. Command-line switches like `--help` don't work either.

### Steps to reproduce

1. Run `yarn global add taiko`.
2. Run `taiko`.
3. -> Nothing is printed, Taiko exits.

### Versions

```text
Node.js v12.6.0
Yarn 1.22
Taiko 1.0.8 (Chromium: 83.0.4103.0)
```

For the record, I'm using [fnm](https://github.com/Schniz/fnm) to manage my Node.js verion. It seems to work fine with npm, so I'm not sure if that's related.

**Comment by NivedhaSenthil** [comment]
This looks like a bug in the way taiko launches REPL and runner.. thanks for reporting will try fixing it soon.

**Comment by zabil** [comment]
Also note that Taiko uses `npx` during a post install process to generated documentation.

https://github.com/getgauge/taiko/blob/9b6def065386fbc3b536b9f14d7474f82d650aee/package.json#L21
https://github.com/getgauge/taiko/blob/9b6def065386fbc3b536b9f14d7474f82d650aee/lib/documentation.js#L5

I don't think that can't be fixed via yarn. 
Perhaps fix the REPL load issue but only support `npm` and modify the documentation.

**Comment by zabil** [comment]
Closing this as Taiko will not be supporting yarn as it used `npm` and `npx` for a few crucial steps in the installation process. However, any PR's to fix this will be merged.
