### ISSUE TITLE
Wait for navigation is causing tests to be flaky

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#122]
**Expected behavior**
Script should be executed consistently

**Actual behavior**
There is flakiness while waiting for navigation. Getting error while finding the next element in script

**Steps to replicate**
> Note the following script has to be executed a few times, the navigation is not consistent.

Sometimes it fails to find the input element to write text
```
(async () => {
    try {
        await openBrowser({headless:false});
        await goto("thetrainline.com");
 
        await write("London",into(inputField(toRightOf("From"))));
        await press("Enter");
        await write("Manchester");
        await press("Enter");
        await click("Tomorrow")
        await click(button({"type":"submit"}));
        await click(radioButton(toRightOf("Cheapest First Class Single")))
        // // await click(radioButton(toRightOf("First Class Single")))
        await click("Continue");
    } catch (e) {
        console.error(e);
    } finally {
        closeBrowser();
    }
 })();
```
**Version**
```
commit - ec0cb85571aa2130abd5fe7a183de1ad709f1b5b
```
Blocks https://github.com/getgauge/taiko/issues/113

**Comment by NivedhaSenthil** [comment]
Fix should be available in fd86932

**Comment by sguptatw** [comment]
This works as expected on Mac. But on Windows the script hangs.
Not sure if it is OS specific, but observed the behavior on Windows

**Comment by Apoorva-GA** [comment]
Works as expected on windows. Please verify.
commit : 1af8a9dcc2595b2ec8635869aa66743bb3f97baf

**Comment by sguptatw** [comment]
Works as expected `acaa752bbcc298d48152d8fc893529efa283f0a8`
