### ISSUE TITLE
Use REPL .step to generate typescript

### ISSUE THREAD

**Issue by chicken-suop** [getgauge/taiko#1225]
### Expected behavior
`.step` should let me generate code like:
```
  @Step('The word <word> has <expectedCount> vowels.')
  public async verifyVowelsCountInWord(word: string, expectedCount: number) {
    equal(await this.countVowels(word), expectedCount);
  }
```

### Actual behavior
It only lets me generate regular JS code

### Steps to reproduce
1. Record a flow
2. Run `.step`

### Versions
```
Paste `node` and `taiko` versions here.
```
node: 12.16.1
Taiko: 1.0.8

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
