### ISSUE TITLE
Unable to Automate Popup Notification 

### ISSUE THREAD

**Issue by rakeshkmr516** [getgauge/taiko#124]
<img width="372" alt="screen shot 2018-09-01 at 2 13 48 am" src="https://user-images.githubusercontent.com/5263739/44935287-abda3b00-ad8d-11e8-9bba-c698863ac7d7.png">

### Expected behavior
Tell us what should happen
The script should Click button Allow/ Block /X icon of Notification

### Actual behavior
Tell us what happens instead
Unable to perform operations on that Notification 
### Steps to reproduce
1. Navigate to http://google.com
2. Write Text
3. Press Enter

Paste `node` and `taiko` versions here.
Node - v10.8.0
taiko - 0.1.0

Could you please let me know any solution or workaround

**Comment by rakeshkmr516** [comment]
if am using Selenium I have used the below code to disable/block Notifications and Location 
`ChromeOptions opt = new ChromeOptions();
Map<String, Object> prefs = new HashMap<String, Object>();
prefs.put("profile.default_content_setting_values.notifications", 2);
prefs.put("profile.default_content_setting_values.geolocation", 2);
opt.setExperimentalOption("prefs", prefs);
WebDriver driver = new ChromeDriver(opt);`

Can we set something in taiko to customize browser behaviour

**Comment by NivedhaSenthil** [comment]
@rakeshkmr516  For now there is no way we could do this with taiko. Thanks for bringing this up, we will try to handle this scenario in taiko.

**Comment by NivedhaSenthil** [comment]
Fix available in 27c68da

**Comment by Debashis9012** [comment]
The requirement can be handled by using ```overridePermissions() ``` api.
Tested with below version:
``` 27c68da```
For more information: https://taiko-preview.gauge.org/#overridepermissions
