### ISSUE TITLE
repl does not work as expected loading repl commands from file

### ISSUE THREAD

**Issue by mkausl** [getgauge/taiko#1248]
### Expected behavior
when loading a prerecorded repl session, it should execute as before

### Actual behavior
taiko does not seem to wait until the steps have completed in repl session.

it prevents to have simple prerecorded repl scripts from running form the command line.

It would be very nice to be able to do something like this

```
#! /usr/bin/env taiko -l

openBrowser()
goto("www.google.com")
```

### Steps to reproduce
1. taiko on command line (repl mode)
2. type commands and save to js file then quit command line
```openBrowser()
goto("anyurl.com")
 .save test.js
^C^C
```
3. open new taiko repl
4. load recorded script 
```
.load test.js
openBrowser()
goto("www.google.com")
...  ✘ Error: Browser or page not initialized. Call `openBrowser()` before using this API, run `.trace` for more info.
>  ✔ Browser opened
```
 also `taiko -l test.js` does not work as expected

### Versions
```
taiko -v
Version: 1.0.9 (Chromium: 83.0.4103.0) RELEASE
node -v
v12.13.1
```

**Comment by NivedhaSenthil** [comment]
Please use `.code` to save the taiko generated code. `.save` is a built in repl command that simply saves the executed  commands into file without any await for the async functions which is taken care by `.code` . 

With properly generated code `.load` seems to work fine. Do try again and let us know it that helped.

**Comment by mkausl** [comment]
.code works, but generates a normal js file . i guess its more of a feature request then having taiko execute a file with only repl commands

**Comment by zabil** [comment]
This could be useful and loosely related to https://github.com/getgauge/taiko/issues/1084

**Comment by zabil** [comment]
Taiko won't be implementing this feature as the REPL commands are syntactic sugar for Javascript and very limited. Although this maybe good for writing simple scripts there will be several issues like variable declarations, handling return values, assertions etc which can be done much better with a first class programming language support.
