### ISSUE TITLE
Taiko install fail in mac 10.14.6  with Node v12.16.3 and NPM v6.14.4

### ISSUE THREAD

**Issue by vramasv** [getgauge/taiko#1251]
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/usr/local/lib/node_modules'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pradeepa/.npm/_logs/2020-05-12T23_30_57_442Z-debug.log
Pradeepas-MacBook-Pro:~ pradeepa$ sudo 
usage: sudo -h | -K | -k | -V
usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]
usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user]
            [command]
usage: sudo [-AbEHknPS] [-C num] [-g group] [-h host] [-p prompt] [-T timeout]
            [-u user] [VAR=value] [-i|-s] [<command>]
usage: sudo -e [-AknS] [-C num] [-g group] [-h host] [-p prompt] [-T timeout]
            [-u user] file ...
Pradeepas-MacBook-Pro:~ pradeepa$ sudo npm install -g taiko
Password:
/usr/local/bin/taiko -> /usr/local/lib/node_modules/taiko/bin/taiko.js

> taiko@1.0.10 install /usr/local/lib/node_modules/taiko
> node lib/install.js

ERROR: Failed to download Chromium r762701! Set "TAIKO_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
[Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/taiko/.local-chromium'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/local/lib/node_modules/taiko/.local-chromium'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! taiko@1.0.10 install: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the taiko@1.0.10 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by zabil** [comment]
This issue is related to permissions. As mentioned in the documentation please use `npm install -g taiko` instead of `sudo npm install -g taiko`.

You will have to fix your node installation to avoid using `sudo npm` recommend using home-brew to install node.

Alternatively you can try using 

```
npx taiko
```

to run the REPL or install taiko locally in using

```
npm install --save-dev taiko
npx taiko
```
