### ISSUE TITLE
closeTab(URL) doesn't exact match the URL

### ISSUE THREAD

**Issue by scottdavis99** [getgauge/taiko#1259]
### Expected behavior
closeTab(URL) matches the URL exactly, or is able to differentiate between different tabs whose URL starts the same but the full path is unique. 

### Actual behavior
closeTab(URL) doesn't exactly match the URL. If I have two tabs open, one with 'https://thirstyhead.com/conferenceworks' and the other with 'https://thirstyhead.com/groceryworks', the action closeTab('https://thirstyhead.com/groceryworks') closes both tabs. 

### Steps to reproduce
openBrowser()
goto('https://thirstyhead.com/conferenceworks/')
openTab('https://thirstyhead.com/groceryworks/')
switchTo('ConferenceWorks')
closeTab('https://thirstyhead.com/groceryworks/')

[RESULT: closes both tabs and browser]

### Versions
```
Version: 1.0.9 (Chromium:83.0.4103.0)
```

**Comment by Manikkumar1988** [comment]
Issue is tied up with #626 

Need a better way to compare URLS without host & protocol and taking host redirection into the account.

**Comment by NivedhaSenthil** [comment]
Fixed by #1311
