### ISSUE TITLE
Feature Request: LoadProfile / SaveProfile 

### ISSUE THREAD

**Issue by scottdavis99** [getgauge/taiko#1262]
I would like to describe a "profile" for a device/network/location/etc. in a JSON file and a command-line flag to load it.

taiko --load-profile=profile.json 

ALSO: loadProfile('path/to/profile.json')

ALSO (in REPL): saveProfile('profile.json') to capture/save current profile.

The profile should include:

* emulateDevice
* emulateNetwork
* emulateTimezone
* setLocation
* setViewPort
* setConfig
* setCookie
* overridePermissions

Also (not currently supported in Taiko, but available in https://chromedevtools.github.io/devtools-protocol/tot/Emulation/, so technically available via taiko.client)

* setTouchEmulationEnabled
* setUserAgentOverride
* resetPageScaleFactor
* setCPUThrottlingRate
* setEmitTouchEventsForMouse
* setPageScaleFactor
* setNavigatorOverrides
* setVisibleSize

This will allow me to run the same Taiko script for different devices. For example:

taiko --load-profile=iphone.json myscript.js

taiko --load-profile=android.json myscript.js

taiko --load-profile=laptop.json myscript.js

taiko --load-profile=smarttv.json myscript.js

**Comment by zabil** [comment]
As taiko is most like to be used with a test runner like Gauge, jest or mocha it's more portable to expose all of these as environment variables.

**Comment by zabil** [comment]
Using [dotenv](https://github.com/motdotla/dotenv#readme) will solve this issue. It's a very popular library for managing environment variables.

The environment variables can be in a `.env` file in a root folder and it can be run as follows for a default set of parameters.

```
node -r dotenv/config sample.js
```

or using a specific file

```
node -r dotenv/config sample.js dotenv_config_path=/custom/path/to/.env
```
