### ISSUE TITLE
Sporadic: Error matching text is covered by another item.

### ISSUE THREAD

**Issue by pablougaz** [getgauge/taiko#1267]
### Expected behavior
Page rendered has a pop-up overlaying it.  I clear off pop-up, then click an element in the page behind it.  I should be able to always find the element to click after I clear off pop-up. 

### Actual behavior
I get the error:
Error: Element matching text "Show Items" is covered by other element, run `.trace` for more info. 

In the REPL I can reproduce error consistently.  When running my tests it happens sporadically - I believe is a timing issue with a slow existing pop-up.

### Steps to reproduce
On the Taiko REPL, type the following commands:

1. await openBrowser({ignoreCertificateErrors:true})
2. await goto('https://test03.yubbler.com/Yub/Details/32412#grade?id=32413')
3. await click($('#yub-modal > div > div > div.modal-header > button'));await click('Show Items')

### Versions
```
node --version
v10.16.3
taiko --version
Version: 1.0.9 (Chromium: 83.0.4103.0) RELEASE
```

**Comment by NivedhaSenthil** [comment]
Related https://spectrum.chat/taiko/general/getting-sporadic-error-element-is-covered-by-other-element~2db19078-feba-4ba5-ae30-38eed33eb336
