### ISSUE TITLE
How to use screencast to record a video at any failed step on gauge spec

### ISSUE THREAD

**Issue by levietquynh** [getgauge/taiko#1269]
### Actual behavior
How to use screencast if we write spec using gauge

### Steps to reproduce
1. I have a spec on gauge with sample as below
* Login to website
* Type in "testuser@gmail.com" into 'Email' textBox
* Type in "abc123" into 'Password' textBox
* Click on 'Login' button

## Select Team 
* Select "Admin" in Team dropdown
* Click on 'Change Team Save ' button

2. Every step is defined in a file .js
step("Login to website", async () => {
    await goto(web_url)
})

step("Type in <email> into 'Email' textBox", async (Email) => {
    await write(Email, into(textBox({id:fieldID})))
})

3. In case I run in headless mode to step "* Select "Admin" in Team dropdown" and it's failed, how to add a screencast recording at this failed step?
I see in example, we use try catch finally, but it's only used when we write all step in a file .js
I tried to add screencast start at the beginning of spec, before step "Login to website", and screencast stop at the end of spec, after step "Click on 'Change Team Save ' button". However, when we meet fail at "Select "Admin" in Team dropdown", we cannot run to the last step to stop screencast.

4. In real case, I have a long spec, it takes a long time to finish, and it's only failed when running headless, screenshot is not enough information to find out the issue. So I would like to add a video to observe whole running test script.

**Comment by NivedhaSenthil** [comment]
have you tried using [hooks](https://docs.gauge.org/writing-specifications.html?os=linux&language=java&ide=vscode) to start and stop screencast ? 
This can done at various levels as needed, like to capture a screencast of a scenario try starting and stoping at @beforeScenario and @afterScenario hooks respectively.

**Comment by levietquynh** [comment]
Thanks @NivedhaSenthil , I tried with your suggestion and it works well. However, when I finish the first spec, I met error like "Error Message: Error: Unsupported action removeListener on client". Could you please help me to resolve this?

**Comment by NivedhaSenthil** [comment]
can you please provide complete stackTrace to understand from where this error is happening ?

**Comment by NivedhaSenthil** [comment]
closing this issue as the actual query was answered ... feel free to open new issue if you face any
