### ISSUE TITLE
Taiko is unable to handle an alert which asks a user to enter a username and password

### ISSUE THREAD

**Issue by amitsarkar007** [getgauge/taiko#1279]
### Expected behavior
Taiko should be able to handle an alert which asks a user to enter a username and password

### Actual behavior
I tried setting up the listener like this
```
await prompt("Username", async () => await accept("admin")); 
await prompt("Password", async () => await accept("admin")); 
await goto("the-internet.herokuapp.com/basic_auth")
```
But the page simply never loads.

### Steps to reproduce
1. Start Taiko
2. Set up a listener to handle an alert
3. Go to the page https://the-internet.herokuapp.com/basic_auth
4. Wait for prompt to display
5. Enter Username as **admin**
6. Enter Password as **admin**

### Versions
```
PS C:\Users\Neo> taiko --version
Version: 1.0.8 (Chromium: 83.0.4103.0) RELEASE

PS C:\Users\Neo> node --version
v12.16.3
```

**Comment by NivedhaSenthil** [comment]
Basic authentication has to be handled by setting auth headers in goto. Refer https://docs.taiko.dev/#goto.

Example:
```
goto("https://the-internet.herokuapp.com/basic_auth",{headers:{'Authorization':'Basic YWRtaW46YWRtaW4='}})
```

**Comment by amitsarkar007** [comment]
Thanks a lot @NivedhaSenthil . Its working now. I didn't realize we had to use the headers for authorization.
