### ISSUE TITLE
Unable to select slider and move it

### ISSUE THREAD

**Issue by amitsarkar007** [getgauge/taiko#1280]
### Expected behavior
Should be able to select a slider on a page and interact with it using XPath selectors or CSS selectors in the absence of an ID or a CLASS

### Actual behavior
Unable to interact with slider on the page [Horizontal Slider](https://the-internet.herokuapp.com/horizontal_slider) using the **range** selector. Tried all the following options but still not able to move the slider.

```
range({'class':'sliderContainer'}).select('3.5')
range($(`[type=range]`)).select(3.5)
range($(`[type=range]`)).exists()
range({class:'sliderContainer'}).select(3.5)
range({'class':'sliderContainer'}).select('3.5')
range({id:'range'}).select('3.5')
range({id:'range'}).select(3.5)
range($(`.sliderContainer`)).select(3.5)
```

### Steps to reproduce
1. Go to the page
2. Identify the slider element
3. Interact with it and try to move the slider

### Versions
```
Taiko 
1.0.11 (84.0.4143.0)

Node
v12.16.3
```

**Comment by NivedhaSenthil** [comment]
Thanks for reporting, I could see the value is getting updated in the element but not reflected in DOM as the change events are not triggered properly. We will work on fixing this

**Comment by NivedhaSenthil** [comment]
Fixed by #1299

**Comment by amitsarkar007** [comment]
The [commit](https://github.com/getgauge/taiko/commit/c75497243c46c77612f4b067ba9b16b70b549731) has a test that indicates the issue has been tested and fixed.

But using the code below indicates it is not working
```
taiko

Version: 1.0.12 (Chromium:81.0.3994.0)
Type .api for help and .exit to quit

> openBrowser()
[PASS] Browser opened
> goto("https://the-internet.herokuapp.com/horizontal_slider")
[PASS] Navigated to URL https://the-internet.herokuapp.com/horizontal_slider
> range({id:'range'}).select(3.5)
> Uncaught Range Type[@id = concat('range', "")] not found
> highlight($(`//input`))
[PASS] Highlighted the custom selector $(//input)
> clearHighlights()
[PASS] Cleared all highlights for this page.
> range($(`//input`))
RangeWrapper {
  _get: [AsyncFunction: get],
  _description: 'Range Type with label [object Object] '
}
> highlight($(`[id=range]`))
[PASS] Highlighted the custom selector $([id=range])
> range($(`[id=range]`)).exists
[AsyncFunction: exists]
> range($(`[id=range]`)).select(3.5)
Uncaught s.match is not a function
> clearHighlights()
[PASS] Cleared all highlights for this page.
> range($(`[type=range]`)).exists
[AsyncFunction: exists]
> range($(`[type=range]`)).select('3.5')
Uncaught s.match is not a function
> range({id:'range'}).select('3.5')
Uncaught Range Type[@id = concat('range', "")] not found
> range({id:'range'}).exists()
false
[PASS] Does not exists
```
I would like to re-open this issue.

**Comment by NivedhaSenthil** [comment]
`range` api does not take another selector `$` as an argument, there is no range with id `range` in the page hence all the above sample fails for a valid reason. Below snippet works fine,
```
(async () => {
    try {
        await openBrowser();
        await goto("https://the-internet.herokuapp.com/horizontal_slider");
        await range().select("3.5");//since there is only one range field that will be selected by default
        await range(below("Horizontal Slider")).select("2");//range selection using proximity selector 
    } catch (error) {
        console.error(error);
    } finally {
        await closeBrowser();
    }
})();
```

**Comment by amitsarkar007** [comment]
Thanks a lot @NivedhaSenthil . That really helps. I can move the slider now.

I can see there is an input field **range** and assumed that would work. Reference - [How TO - Range Sliders](https://www.w3schools.com/howto/howto_js_rangeslider.asp). 

Is there a reason the **.range** API only takes ID as range and not anything else such as input type or class?

**Comment by NivedhaSenthil** [comment]
range api can actually take any attribute and value pair that identifies the range inputfield.
