### ISSUE TITLE
openTab should open a tab on active window

### ISSUE THREAD

**Issue by NivedhaSenthil** [getgauge/taiko#1282]
### Expected behavior
openTab should open a tab on currently active window

### Actual behavior
opens a tab on default window

### Steps to reproduce
1. openBrowser()
2. openIncognitoBrowser()
3. openTab()

### Versions
```
taiko 1.0.11
```

**Comment by saikrishna321** [comment]
Will be fixed once https://github.com/getgauge/taiko/pull/1432 is Merged.

**Comment by BugDiver** [comment]
#1432 has been merged. Closing this issue.

**Comment by zabil** [comment]
I don't think it's fixed. I think @saikrishna321 meant this should be fixed after merging #1432

**Comment by dersar00** [comment]
Hi therem, still facing the same problem using the latest version of taiko
I have an active incognito browser open, and when I try to open a new tab, a new incognito window opens instead.

### Versions
`taiko 1.2.5`
