### ISSUE TITLE
observe option is not honoured by taiko runner

### ISSUE THREAD

**Issue by NivedhaSenthil** [getgauge/taiko#1283]
# Expected behavior
running taiko script with `taiko code.js -o` should open browser in headful mode 

### Actual behavior
opens a browser in headless mode not honouring the option given

### Steps to reproduce
1. code.js
```
(async () => {
    try {
        await openBrowser();
        await goto("http://google.com");
        await click(contains('Gmai'))
        await screenshot()

        assert.ok(await highlight(contains('Meet your new inbox')));
    } catch (e) {
        console.error(e);
    } finally {
        closeBrowser();
    }
})();
```
run `taiko code.js -o`

### Versions
```
taiko 1.0.11
node v14.1.0
```

**Comment by zabil** [comment]
This is now working on version 1.0.16
