### ISSUE TITLE
Drag and drop file (Feature Request)

### ISSUE THREAD

**Issue by brandonrock919** [getgauge/taiko#1291]
I think I will be very useful if you will add drag and drop to drop zone 
for example in selenium 

// locate the drop area
WebElement droparea = driver.findElement(By.cssSelector("#holder"));

// drop the file
DropFile(new File("C:\\Downloads\\image.png"), droparea, 0, 0);

**Comment by amitsarkar007** [comment]
Similar to my request in [Issue 279](https://github.com/getgauge/taiko/issues/279)

**Comment by zabil** [comment]
This should work with the attach API to a specific element text https://docs.taiko.dev/api/attach
It can use selectors

```
attach("C:\Downloads\image.png", to(fileField(near('some text inside #holder'))))
```
