### ISSUE TITLE
User should have option to open browser in normal or headless mode

### ISSUE THREAD

**Issue by sguptatw** [getgauge/Taiko#13]
**Expected behavior**
User should have option to open browser in normal or headless mode

**Actual behavior**
On Windows, openBrowser(true), openBrowser(false) both are in headless mode.

**Steps to replicate**
* Check out [project](https://github.com/getgauge-examples/js_puppeteer)
* Use openBrowser(true) or openBrowser(false) both work in the headless mode.

**Version**
```
Gauge version: 0.9.5

Plugins
-------
html-report (4.0.2)
js (2.0.3.nightly-2017-11-08)
```

**Comment by zabil** [comment]
Check documentation
https://getgauge.github.io/Taiko/#openbrowser
