### ISSUE TITLE
Failed to launch chrome! spawn

### ISSUE THREAD

**Issue by rajkumars82** [getgauge/taiko#1312]
### Actual behavior
Chrome browser not launched on exeuctin openBrowser(). Error '[FAIL] Error: Failed to launch chrome! spawn C:\\Program Files (x86)\\Google\\Chrome\\Application ENOENT'
I set the env var setx TAIKO_BROWSER_PATH "C:\Program Files (x86)\Google\Chrome\Application"

### Versions
```
Version: 1.0.11 (Chromium:84.0.4143.0)
Node Version: 12.18.0
OS: Windows 10
```

**Comment by zabil** [comment]
Please point to the full executable path. 
refer https://github.com/getgauge/taiko/issues/875#issuecomment-540389202

**Comment by rajkumars82** [comment]
It worked thank you.
