### ISSUE TITLE
closeBrowser() hangs when used at the command prompt on windows server

### ISSUE THREAD

**Issue by harimadusumilli** [getgauge/taiko#1319]
Hello Taiko Support Team,

Thank you for the great tool. I may be missing something here as  I am encountering an error when I use closeBeowser(). The issue occurs on a Windows Server 2012 R2 version and not on Windows 10 machines.

### Expected behavior
The opened Browser using the REPL window should close when closeBrowser() command is issued

### Actual behavior
The closeBrowser() displays the following error message  as given below and hangs.It does not close the browser.

[FAIL] Error: page.close is not a function, 'run '.trace' for more info

### Steps to reproduce
1. at the command prompt type taiko and hit enter
2. type openBrowser() command in the REPL window and hit enter
3. after the browser is opened, type closeBrowser() and hit enter. 

### Versions
Operating system : Windows server R12.

**Comment by NivedhaSenthil** [comment]
This is something weird, Taikos tests are running fine in windows server 2019. Couldn't get access to windows 2012 R2 currently, can you please provide the full stacktrace, also confirm the version of Taiko and if you are using the chromium bundled with Taiko ?

**Comment by harimadusumilli** [comment]
Hello Taiko developers,

We installed a newer version of the chrome browser which is 88

Gauge version : 1.0.7
Javascript plugin : 2.3.7

Now, when we do the openBrowser() and then closeBrowser(), the error is no longer occurring on the windows server 2012 R2, It appears that we have had an outdated version of the chrome browser and it was creating the above issue.
