### ISSUE TITLE
Hi there,  Is there any way to select Html5 tooltip using Taiko selector. I just need to assert on tooltip text in gauge test implementation. 

### ISSUE THREAD

**Issue by NanditaReshamwala** [getgauge/taiko#1320]
hi there,  Is there any way to select Html5 tooltip using Taiko selector. I just need to assert on tooltip text in gauge test implementation.

**Comment by sriv** [comment]
hi, can you share an example for this please? that would help us understand your case better.

**Comment by NivedhaSenthil** [comment]
There is no direct api to get tooltips, but you could try using evaluate api to assert on it. 
Example: `await evaluate($("button"),(elem) => {return elem.getAttribute('title') === "Expected tooltip"})`
Above snippet returns a boolean which can be asserted on.

**Comment by klhex** [comment]
I think the following "black box" approach using the mighty proximity selectors should also work (at least for me it does):

1. Hover over the desired tooltip button by locating it via the proximity selectors. This should bring up the tooltip.
2. Assert on the existence of the tooltip's text content.

Example: Assume there's a tooltip button to the right of a text field whose heading is "Full Name". Assume the tooltip's text content is "Please enter here your full name.". Then the corresponding code could look like this (uses "expect" from Chai):

```javascript
await hover(button(toRightOf('Full Name')));
expect(await text('Please enter here your full name.').exists()).to.be.true;
```
In case a tooltip's asserted text content is also used elsewhere on the page, you can again use the proximity selectors to zero in on the desired element.
