### ISSUE TITLE
Win10 Taiko opens Chromium browser error: STATUS_INVALID_IMAGE_HASH has been a few days in the works, and setting up the registry according to the web solution doesn't work either, but it's fine to download chromium separately

### ISSUE THREAD

**Issue by jennyjane** [getgauge/taiko#1324]
#736 # Expected behavior
Win10 Taiko opens Chromium browser error: STATUS_INVALID_IMAGE_HASH has been a few days in the works, and setting up the registry according to the web solution doesn't work either, but it's fine to download chromium separately

### Actual behavior
Win10 system Taiko opened Chromium browser error：STATUS_INVALID_IMAGE_HASH

### Steps to reproduce
1.Enter the command at the terminal to open browser:  1. taiko   2.openBrowser()   
2.The browser reported an error：STATUS_INVALID_IMAGE_HASH 
3.Follow the online solution to set up the registry：Save the following command to this file: google.reg，and Double-click
Windows Registry Editor Version 5.00
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google]
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome]
"RendererCodeIntegrityEnabled"=dword:00000000
4.reopen browser: openBrowser() 
5.Problem not solved：STATUS_INVALID_IMAGE_HASH 

### Versions
taiko version ：Version: 1.0.12 (Chromium:81.0.3994.0)
node version：v12.18.1
npm version：6.14.5

**Comment by sriv** [comment]
Please, could you translate this in English?

**Comment by jennyjane** [comment]
> Please, could you translate this in English?

Okay, thank you for reminding me

**Comment by jennyjane** [comment]
The issue of using the environment variable TAIKO BROWSER PATH has been resolved
