### ISSUE TITLE
When a browser session has been manually closed, an attempt to restart a new browser session from Taiko doesn't enable Taiko to handle it

### ISSUE THREAD

**Issue by amitsarkar007** [getgauge/taiko#1330]
### Summary
For some reason Taiko doesn't know if a browser session has been manually closed and an attempt to restart a new browser session from Taiko doesn't enable Taiko to handle it.

### Steps to reproduce
1. openBrowser()
2. goto("google.com")
3. Close the browser manually
4. openBrowser()
5. goto("google.com")

### Expected behavior
The browser should navigate to "google.com"

### Actual behavior
The browser doesn't navigate to "google.com" but simply keeps loading without giving any timeout error.

### Sample code
```
taiko

Version: 1.0.12 (Chromium:81.0.3994.0)
Type .api for help and .exit to quit

> openBrowser()
[PASS] Browser opened
> goto("google.com")
[PASS] Navigated to URL http://google.com
> openBrowser()
[PASS] Browser opened
> goto("google.com")
```

### Versions
```
Taiko
Version: 1.0.12 (Chromium:81.0.3994.0)

Node
Node.js v12.17.0
```

**Comment by zabil** [comment]
This now works on release 1.0.18 @amitsarkar007 please try it out. 
Closing this for now. Will re-open if there are issues.
