### ISSUE TITLE
Element cannot be located using click($("//input[name= 'button_name']") Need extra click add @ to locate elements ($("// input [@ name =' button_name']")) I hope to modify the example on Github and the official website to avoid others taking detours like me

### ISSUE THREAD

**Issue by jennyjane** [getgauge/taiko#1339]
### Expected behavior
Element cannot be located using click($("//input[name= 'button_name']")
Need extra click add @ to locate elements ($("// input [@ name =' button_name']"))
I hope to modify the example on Github and the official website to avoid others taking detours like me

### Steps to reproduce
https://github.com/getgauge/taiko
![image](https://user-images.githubusercontent.com/19267219/85966167-8225e580-b9f1-11ea-9b9e-b28589f582c8.png)

https://docs.taiko.dev/#get-started
![image](https://user-images.githubusercontent.com/19267219/85966171-8baf4d80-b9f1-11ea-847e-032d5d9ab94f.png)

### Versions
```
node Versions:  v10.16.2
taiko Versions:  Version: 1.0.12 (Chromium:81.0.3994.0)
```

**Comment by sriv** [comment]
thanks for reporting @jennyjane - this is a mistake indeed. XPath attribute selectors should have `@` prefixed to the keys.

Thanks for offering to fix this. A pull request would be most welcome!
