### ISSUE TITLE
elements(), element(index) and ElementWrapperList is missing from Typescript type definitions

### ISSUE THREAD

**Issue by sceee** [getgauge/taiko#1341]
# Expected behavior
`elements()` and `element(index)` from https://docs.taiko.dev/#elementwrapperlist is available in type definitions

### Actual behavior
`elements()`, `element(index)` and `ElementWrapperList` is not available in type definitions

### Steps to reproduce
Try to use `elements()` or `element(index)` in a typescript project.

### Versions
```
`taiko 1.0.12`
```

**Comment by jfgreffier** [comment]
Looking at the code, I'm not even sure `ElementWrapperList` exists elsewhere than in the docs. It seems to me that every wrapper extend `ElementWrapper`, which holds `elements()` and `elements(index)` methods.

@NivedhaSenthil can you confirm ? Is it a documentation issue ? `ElementWrapperList` probably disappeared during a refacto.

**Comment by NivedhaSenthil** [comment]
Yes, it has to be Element and ElementWrapper instead. There is no ElementWrapperList, ElementWrapper consists of Element list and first Element's properties as direct properties.

**Comment by jfgreffier** [comment]
I'll work on it
