### ISSUE TITLE
screenshot doesn work

### ISSUE THREAD

**Issue by zhangty0101** [getgauge/taiko#1350]
screenshot({fullPage: true}) get white page out of screen view

**Comment by BugDiver** [comment]
@zhangty0101 Thanks for reporting. I could replicate this. We will work on it soon.

**Comment by saikrishna321** [comment]
This is a upstream issue - https://github.com/getgauge/taiko/issues/346

**Comment by zabil** [comment]
Closing as duplicate of #346 and the fix needs be done in Chromium.
