### ISSUE TITLE
unable to launch microsoft edge browser using taiko on Windows 10

### ISSUE THREAD

**Issue by harimadusumilli** [getgauge/taiko#1362]
Hello Taiko Team,

I am unable to launch the Edge Browser (based of chromium) using Taiko. I am able to launch the Google Chrome Browser

### Expected behavior
Taiko should be able to launch Microsoft Edge Browser (Chromium based) on Windows 10 

### Actual behavior
It hangs and error message is displayed.

### Steps to reproduce
1. Created a Test script in Gauge
2. used the openBrowser() command as follows 
await openBrowser({headless:false});
    //await openBrowser();
    await goto(url);
3 gauge -v
Gauge version: 1.0.7
Commit Hash: ed7b4fd6

Plugins
-------
dotnet (0.1.3)
html-report (4.0.9)
js (2.3.7)
json-report (0.3.3)
screenshot (0.0.1)
xml-report (0.2.3)

### Versions
 node -v
v12.16.1

taiko -v
Version: 1.0.2 (Chromium: 76.0.3803.0) RELEASE

![Edge_version](https://user-images.githubusercontent.com/25215979/87689265-013b4d80-c756-11ea-854d-8d99edb240f1.PNG)

![rnv_variable](https://user-images.githubusercontent.com/25215979/87689475-3e9fdb00-c756-11ea-9c83-712d3115b807.PNG)

Error message :
     * Launch Travelers Inside App with the following url: "https://inside.here.travp.net/"     ...[FAIL]
        
        Failed Step: Launch Travelers Inside App with the following url: "https://inside.here.travp.net/"
        Specification: specs\search_travelers.spec:9
        Error Message: Error: Timed out
        Stacktrace: 
        Error: Timed out
            at Timeout.<anonymous> (C:\Users\hadusumi\AppData\Roaming\gauge\plugins\js\2.3.7\src\test.js:43:23)
            at listOnTimeout (internal/timers.js:549:17)
            at processTimers (internal/timers.js:492:7)
```

**Comment by NivedhaSenthil** [comment]
Does it work without Gauge ? If so do try increasing the step timeout in `env/default/js.properties`

**Comment by harimadusumilli** [comment]
It does not launch the Microsoft Edge Browser without Gauge too. I have done the following at the terminal or CLI on windows as follows : 
1. taiko
at the prompt typed openBrowser()

It hangs and does not launch Microsoft Edge Browser( Chromium based).

When I point the TAIKO_BROWSER_PATH to Chrome it launches from Taiko without any issue.

Any help to progress forward is appreciated.

Thanks,
Hari

**Comment by harimadusumilli** [comment]
Hello Taiko support,

Following up to see, if you have had a chance to look at this issue and provide any advise.

Thanks,
Hari

**Comment by sriv** [comment]
In command prompt (where you ran `taiko` command) - what happens when you run `start C:\Program Files(x86\Microsoft\Edge Dev\Application\msedge.exe`?

If the above command does not run properly, try running `echo %PATH%` and ensure that `C:\Program Files(x86\Microsoft\Edge Dev\Application` is present in it.

**Comment by harimadusumilli** [comment]
I have updated taiko and here is the information below. When I try to launch using taiko.

C:\>taiko -v
Version: 1.0.14 (Chromium: 85.0.4168.0) RELEASE

C:\>taiko

Version: 1.0.14 (C:\Program Files (x86)\Microsoft\Edge Dev\Application\msedge.exe)
Type .api for help and .exit to quit

> openBrowser()
[FAIL] Error: connect ECONNREFUSED 127.0.0.1:57483, run `.trace` for more info.
> .trace
'Error: connect ECONNREFUSED 127.0.0.1:57483
' +
  '    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)'
>

I will try with the path you have suggested and update the same.

**Comment by harimadusumilli** [comment]
When I remove the msedge and just have the path in the environment variable section till Application and run taiko I get the following:

C:\>taiko

Version: 1.0.14 (C:\Program Files (x86)\Microsoft\Edge Dev\Application)
Type .api for help and .exit to quit

Warning: Please check if TAIKO_BROWSER_PATH (C:\Program Files (x86)\Microsoft\Edge Dev\Application)
points to a valid browser executable file.

> openBrowser()
'[FAIL] Error: Failed to launch browser! spawn C:\\Program Files (x86)\\Microsoft\\Edge Dev\\Application ENOENT
' +
  ', run `.trace` for more info.'
>

**Comment by sriv** [comment]
Sorry, I wasn't clear before. TAIKO_BROWSER_PATH has to point to the executable.

What happens if you run `start C:\Program Files(x86\Microsoft\Edge Dev\Application\msedge.exe` ?

**Comment by harimadusumilli** [comment]
Hello Sriv,

I have updated the TAIKO BROWSER PATH to point to the msedge.exe and updated the path variable section to point till the application.


C:\>taiko

Version: 1.0.14 (C:\Program Files (x86)\Microsoft\Edge Dev\Application\msedge.exe)
Type .api for help and .exit to quit

> openBrowser()
[FAIL] Error: connect ECONNREFUSED 127.0.0.1:58165, run `.trace` for more info.
>
and it hangs. I have to explicitly kill it.

Thanks,
Hari

**Comment by sriv** [comment]
What happens if you launch `msedge.exe --remote-debug-port=9222` and then from within Taiko, you try `openBrowser({host:'localhost', port:'9222'})`?

**Comment by harimadusumilli** [comment]
At the command line when I use msedge.exe --remote-debug-port=9222 it launches the Browser

C:\>taiko

Version: 1.0.14 (C:\Program Files (x86)\Microsoft\Edge Dev\Application\msedge.exe)
Type .api for help and .exit to quit

> openBrowser({host:'localhost', port:'9222'})
[FAIL] Error: connect ECONNREFUSED 127.0.0.1:9222, run `.trace` for more info.

Thanks,
Hari

**Comment by sriv** [comment]
So that is strange. I notice that you are using EdgeDev. I tried with the recently launched stable MS Edge.

I could replicate the issue with browser launch, Edge crashed when launched from within Taiko. I think perhaps it does not lime all the flags that we pass to chromium.

But launching it separately, and connecting it to Taiko by setting host and port works for me on a fresh Win10 VM.

**Comment by harimadusumilli** [comment]
I have un-installed the dev version of EDge and installed the stable version and tried the following:

![edge_stable_version](https://user-images.githubusercontent.com/25215979/88284920-3dbdfa80-ccbc-11ea-9089-7dad74267e97.PNG)

![taiko_error_msedge](https://user-images.githubusercontent.com/25215979/88284948-4a425300-ccbc-11ea-8555-6ca457cb8b3f.PNG)

![taiko_error_msedge_stable](https://user-images.githubusercontent.com/25215979/88284954-4e6e7080-ccbc-11ea-84f5-dcf5d4807d1e.PNG)

**Comment by harimadusumilli** [comment]
using the localhost arguments it hangs and  I had to explicitly kill it.

**Comment by harimadusumilli** [comment]
C:\WINDOWS\system32>taiko

Version: 1.0.14 (C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe)
Type .api for help and .exit to quit

> openBrowser({host:'localhost', port:'9222'})
[FAIL] Error: connect ECONNREFUSED 127.0.0.1:9222, run `.trace` for more info.
>

**Comment by sriv** [comment]
just to confirm, did you launch `msedge.exe` outside of taiko with remote port 9222 before using `openBrowser({host:'localhost', port:'9222'})` ?

**Comment by harimadusumilli** [comment]
Yes I did launch the following command  **msedge.exe --remote-debug-port=9222** at the command prompt at the c: drive prompt :

The Browser got launched.

and I tried the following too. keeping the browser open from the above command, I then went to the taiko prompt and did use the openBrowser({host:'localhost', port:'9222'}) and it did not launch. 

I also tried again with a new prompt of taiko, After closing the launched browser  outside of taiko   **msedge.exe --remote-debug-port=9222** and tried it. I was still not able to launch the browser. Please let me know if you need any more information that I need to provide or help me look at any logs that you think are generated on my machine will be helpful for you to further trouble shoot the issue.

**Comment by sriv** [comment]
> I then went to the taiko prompt and did use the openBrowser({host:'localhost', port:'9222'}) and it did not launch.

It woudn't launch another browser, passing `host` and `port` would lead to taiko connecting to the already launched browser instance.

Once you've launched a browser (outside of taiko), and connected to it using `openBrowser({host:'localhost', port:'9222'})`, you should be able to do regular taiko actions, such as `goto`. This works for me on Win10.

**Comment by harimadusumilli** [comment]
Hello Sriv,

Thank you for writing back.
I have tried the steps based on your explanation above. I am still unable to get access to the browser and perform any actions against it using Taiko. Screen shots below.

![taiko-remote-ie-fail](https://user-images.githubusercontent.com/25215979/88400256-13407000-cd96-11ea-8114-0ca549bdeea8.PNG)

**Comment by zabil** [comment]
This looks like some issue you have specific to your instance of edge. A quick google search says that this might happen if there are other edge browser instances running in the background and you try to launch it. 

On the other hand the chromium bundled with Taiko always launches its separate instance. It looks like you might be having a background process or some other instance of edge running. Make sure you terminate all edge process before trying what you did.

There are a few steps mentioned at https://github.com/microsoft/vscode-chrome-debug#chrome-user-profile-note-cannot-connect-to-the-target-connect-econnrefused and flags you can try to get around this.

**Comment by harimadusumilli** [comment]
Hello Zabil,

I have tried this on another machine which is a personal windows 10 home and I am unable to get access to the Edge Browser with taiko. I have looked at the link you have provided above, I did understand some of the explanation and not the others about which flags to use. I used --user-data-dir: true and although the browser launches from the command line, When I launch Taiko from the prompt and try to connect to the opened browser it hangs. 

Can you please suggest a few examples on how to use the flags, I will try and see the combination of various flags and see if I am successful in launching the EDGE Browser.

Thanks,
Hari

**Comment by amitsarkar007** [comment]
@harimadusumilli I did try this scenario and it successfully worked for me

**Step 1** - Change environment variable in Windows 10

![image](https://user-images.githubusercontent.com/8624518/88927131-e34e0c80-d26e-11ea-9f31-01b2e1d84487.png)

**Step 2** - Install the latest version of Taiko

```
npm install -g taiko
```

**Step 3** - Close all terminals and browser instances of Edge

![image](https://user-images.githubusercontent.com/8624518/88927389-3b850e80-d26f-11ea-8347-60571ab1a230.png)

I noticed that even when I close Edge there is an instance running in the taskbar. So close that well please.

**Step 4** - Run the commands in REPL mode

```
❯ taiko

Version: 1.0.16 (C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe)
Type .api for help and .exit to quit

> openBrowser()
[PASS] Browser opened
> goto("google.com")
[PASS] Navigated to URL http://google.com
> write("amit sarkar")
[PASS] Wrote amit sarkar into the focused element.
> press("Enter")
[PASS] Pressed the Enter key
```

Hope this helps and solves your problem.

**Comment by harimadusumilli** [comment]
Hello Amit,

Thank you for your suggestion of closing the Browser in the Task bar too. I had it pinned to the task bar for easy launching manually. So, based on your explanation, even the short cut or a link to it should not be present is that a correct statement ? 

After i removed the Edge browser from the task bar and then launched it using taiko, I was able to do launch it without any issue. 

Thank you, 
Hari
