### ISSUE TITLE
Taiko fails to finish navigation in headless mode

### ISSUE THREAD

**Issue by jniebuhr** [getgauge/taiko#1367]
### Expected behavior
The page should load and the test should be executed, same behavior as in normal mode.

### Actual behavior
The page never finishes loading from taikos point of view (the page is actually loaded in the browser as seen from screenshots).

The behavior with events is a bit flaky, sometimes it will reach networkIdle / meaningfulPaint. But even if it does it won't continue.

### Steps to reproduce
1. Use test setup from https://github.com/jniebuhr/taiko-headless-bug-example
2. Execute tests with headless mode and without
3. See failed headless test

### Versions
```
Node: v14.5.0
Taiko: v1.0.13
```

**Comment by NivedhaSenthil** [comment]
@jniebuhr try updating the user-data-dir like below
```
 `--user-data-dir=${path.resolve(__dirname, './.gauge/.user-data-dir')}`,
```
seems like the browser was not getting the right path in some cases and not sure why it does not complain about it too.. with this change navigation worked fine for me

**Comment by jniebuhr** [comment]
Thank you @NivedhaSenthil , that indeed resolves the problem in my example project. I'll verify that it resolves the bug in our code as well and close this afterwards.

**Comment by zabil** [comment]
Closing this for now assuming that it's been resolved.
