### ISSUE TITLE
Assert if action is perfomed successfully before displaying sucess message

### ISSUE THREAD

**Issue by nehashri** [getgauge/taiko#137]
**Actual Behaviour**
An API can perform an action on the web page and Taiko displays a success message as soon as it triggers the action. It doesn't wait to check if the action actually succeeded or not.

**Expected Behaviour**
Taiko should assert if the action actually succeeded or not. If the action was really performed then, we should display the success message.

**Comment by zabil** [comment]
Closing this as an old issue.
