### ISSUE TITLE
Documentation Website

### ISSUE THREAD

**Issue by cassiomc** [getgauge/taiko#1379]
Hello, good morning

First I wanna congratulate for the very good tool. I've used it along Gauge at work. The reason that I'm opening this issue is not because some technical problem, but I would like to have access to the old documentation website. There is a new website for the documentation but the old one was very good. I would like to know if it's still available.

Regards,
Cássio Castro

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Versions
```
Paste `node` and `taiko` versions here.
```

**Comment by zabil** [comment]
The old site backup is not available. Can you be a bit more specific about what is missing in the new website? It will help improve the current website. 

The new website actually has more documentation than the old one and is search friendly. So it will be good if you can elaborate.

**Comment by cassiomc** [comment]
Hello, thanks for the reply. I was trying to search a command (`link()`) and wasn't find it. Now I see that when I type on search box there is a popup appears with the results. But I couldn't access this popup today. Now it's ok.
