### ISSUE TITLE
tableCell missing from types

### ISSUE THREAD

**Issue by fmpanelli** [getgauge/taiko#1383]
### Expected behavior
index.d.ts should export `tableCell` function

### Actual behavior
`tableCell` function is missing

### Steps to reproduce
1. open types/taiko/index.d.ts
2. search for tableCell

### Versions
```
node v12.16.1
taiko v1.0.16
```

**Comment by NivedhaSenthil** [comment]
Thanks for reporting, will add them soon

**Comment by fpanelli** [comment]
Thank you Nivedha for your prompt response!

**Comment by fmpanelli** [comment]
Dear taiko team,

I had the opportunity to take a closer look at the topic.
I compared the functions declared in `index.d.ts` with the ones in `taiko.metadata` and I discovered that:

1. the following functions are exported by taiko.js, but they are missing from index.d.ts:
  - clearHighlights
  - color
  - getConfig
  - range
  - tableCell
  - timeField
2. A couple of functions are declared in index.d.ts, but are not exported from taiko.js:
  - intervalSecs
  - timeoutSecs

Additionally I tried to lint index.d.ts and got some warnings.

Now what... if you wish I can try to fix this, but it is somewhat invasive so I would like your ok before proceeding.

I am also trying to understand if it would be possible to introduce some testing or linting to avoid similar issues in the future (I am looking at dtslint and see if it can help).

What do you think?

Thanks
Filippo

**Comment by NivedhaSenthil** [comment]
This is so great to see the effort you have put to gather these details, we would be very much happy to review a PR.

**Comment by fmpanelli** [comment]
Ok 😀

I will start with a small PR to try the process and proceed incrementally.

Thank you,

**Comment by fmpanelli** [comment]
This issue was resolved with PR #1454
