### ISSUE TITLE
ERROR: Failed to download Chromium r724157! Set "TAIKO_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.

### ISSUE THREAD

**Issue by kharemohit85** [getgauge/taiko#1387]
<!--
Thanks a lot for reporting issues to Taiko! This is the issue tracker for reporting bugs or for requesting new feature and enhancements.

### Expected behavior
all dependencies should get downloaded after executing command "npm test".

### Actual behavior
when running command "npm install", getting error "ERROR: Failed to download Chromium r724157! Set "TAIKO_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download."

### Steps to reproduce
1. Run command "npm install" on the project.

Taiko Version used 1.0.3 & 1.0.9

Dependencies used:
{
  "name": "gauge-taiko-template",
  "version": "0.0.1",
  "description": "Starter template for writing JavaScript tests for Gauge",
  "scripts": {
    "test": "gauge run specs",
    "gauge": "gauge",
    "lint": "eslint . --ext .js",
    "prettier": "prettier --list-different \"**/*.js\""
  },
  "dependencies": {
    "@getgauge/cli": "latest",
    "console-stamp": "^3.0.0-rc3.0",
    "https-proxy-agent": "latest",
    "taiko": "^1.0.9"
  },
  "devDependencies": {
    "chai": "^4.2.0",
    "eslint": "^5.16.0",
    "eslint-config-airbnb-base": "^13.2.0",
    "eslint-config-prettier": "^4.3.0",
    "eslint-plugin-import": "^2.18.2",
    "prettier": "^1.18.2"
  }
}

**Comment by sriv** [comment]
Can you provide some details?

**Comment by zabil** [comment]
Closing this as it does not use the issue template to explain the issue. Will re-open it after there are more details.
