### ISSUE TITLE
Some API not working well in taiko v1.0.16

### ISSUE THREAD

**Issue by windyliu1118** [getgauge/taiko#1388]
I tried the new taiko version 1.0.16, but found there are some taiko API not working so well, 

e.g, for clear api, when use code like this:
`await write(process_name, into(textBox({class: "ant-input ant-input-lg"}, below("Enter process name"))));`
 this line of code is not working using the latest version.
So i need to change it like 
`await write(process_name, into($(".ant-input.ant-input-lg", below("Enter process name"))));, `
seems the textBox api cannot identify element when using class name.

Also for the radioButton API, it's able to identify the label with Yes, but cannot identify the label with No.
These 2 issues I see in latest taiko version.

### Versions
```
node: 10.16.3
Taiko: 1.0.16
```

**Comment by NivedhaSenthil** [comment]
class selector is fixed by #1406.. please do create separate issues for others with example.
