### ISSUE TITLE
Won't click using Xpath

### ISSUE THREAD

**Issue by kaldown** [getgauge/taiko#1398]
### Expected behavior
Click on a given **div** by XPath
![2020-07-31_957x76_scrot](https://user-images.githubusercontent.com/3754017/89069325-9dcb3580-d37b-11ea-803e-52fb247df01a.png)

### Actual behavior
` ✘ Error: CustomSelector with query not found`

### Steps to reproduce
Have a site with 
```
<div class="js-lk-modal-product-rating-rate Rating__iconsFront Rating__iconsFront--2 Rating__iconsFront--active" data-rate="2">...</div>
```
2. ```await click($("//*[@id=`js-lk-modal-product-rating`]/div/div/div/div/form/div[3]/div/div/div[3]"))``` // copied form browser XPath
3. ```await click($("//div[data-rate=`2`]"))``` // and changed all types of quotes

### Versions
```
Version: 1.0.16 (Chromium: 85.0.4168.0)
```

**Comment by kaldown** [comment]
Would be very nice if there would be a chance to click on a browser and see what happens in Taiko.

like `element //div[class="ClassName"] being clicked`.
In order for me to reverse behavior from the UI into the code.

I didn't find anything by searching.

**Comment by BugDiver** [comment]
> 3. await click($("//div[data-rate=`2`]")) // and changed all types of quotes

@kaldown Your Xpath seems wrong. Try `click($("//div[@data-rate='2']"))`

**Comment by zabil** [comment]
> Would be very nice if there would be a chance to click on a browser and see what happens in Taiko.
like element //div[class="ClassName"] being clicked.

Unfortunately there's no easy way to do this.

Closing this issue for now as @BugDiver pointed it looks like an XPath issue. Taiko just uses the browser's XPATH implementation. 

If you see an Xpath not working it is best to check the XPATH on the browser console before using it in Taiko.
