### ISSUE TITLE
Cannot drag and drop to target position on HEADLESS mode

### ISSUE THREAD

**Issue by levietquynh** [getgauge/taiko#1413]
### Expected behavior
I try to drag and drop HTML5 element on headless mode when running with gauge

### Actual behavior
Cannot drop to target element although I setViewPort

### Steps to reproduce
1. Implement drag and drop function
2. Test to see it works well on No Headless mode when I move pointer to target area
3. But when I switch to Headless mode, it's always failed
4. I try to setViewPort to 10000,10000 but no thing is changed

### Versions
node v12.16.1 and taiko 1.0.16

**Comment by zabil** [comment]
Please share a sample where this is failing as tests for drag and drop run in headless mode https://github.com/getgauge/taiko/blob/master/test/unit-tests/dropDown.test.js and are passing.

**Comment by levietquynh** [comment]
@zabil Is this a test for dropdown? But I have problem with dragAndDrop

**Comment by zabil** [comment]
Sorry the test is here https://github.com/getgauge/taiko/blob/57ce5a064debf622b6f9359f6360aec8a8d55b16/test/functional-tests/tests/pageActions.ts#L48-L51

It will be much easier to fix look into the issue of you have a code sample.

**Comment by levietquynh** [comment]
I used 
await dragAndDrop((source), $(destination));
with source is text and destination is xpath. Because it has problem with headless mode, so I wonder if I miss any config here, I’m running it with gauge

**Comment by zabil** [comment]
I don't think so, if it is working in headful mode it should work on headless mode. 

However, most sites render different on headless mode. A quick way to check this is taking a [screenshot](https://docs.taiko.dev/taking_screenshots/#default-screenshot) before the drag and drop call to see if the
screen is the same.

**Comment by levietquynh** [comment]
I take screencast and see on HEADLESS mode, the element isn't even highlighted.
[https://share.getcloudapp.com/DOuxjBYK](url)

This is screenshot for NO_HEADLESS
[https://share.getcloudapp.com/d5uEzRkJ](url)

@zabil Do you have suggesstion is this case?

**Comment by zabil** [comment]
Unfortunately, Taiko does not highlight elements in headless mode.

It will be much easier to see if this is an issue if you have a sample to replicate this

**Comment by levietquynh** [comment]
How can I give you a sample to this issue? Do you need a link web or html structure?

**Comment by zabil** [comment]
The easiest way is be to share a GitHub repository with a script replicating the issue so that someone can checkout and run it.

**Comment by levietquynh** [comment]
@zabil This is my repo https://github.com/levietquynh/tk_support
Could you please help me to check this issue?

**Comment by BugDiver** [comment]
@levietquynh I tried to look into the issue and was able to replicate it. On further debugging, it looks like the issue is in the way you are trying to use the source element.

`await dragAndDrop('Header', into($("//*[@class='dynamic-digest']")));` in this API since you are using `Header` taiko will find the text node for `Header` which is actually not draggable, even the parent node of the `Header` is not draggable. Actually, there is a multiple levels of nesting in the element. So you might want to change the selector for the source element. Make sure the element which is getting selected should be draggable.

**Comment by levietquynh** [comment]
@BugDiver I got what you mentioned but I concern about why I can drag it successfully with NO HEADLESS mode

**Comment by BugDiver** [comment]
@levietquynh When taiko finds that the element is not an HTML5 draggable element (in this case), it tries to perform drag and drop by dispatching mouse event. But the chromium has an issue with dispatching mouse events, to the drop happens the current cursor location, which could be out of the browser window. Refer https://github.com/getgauge/taiko/issues/279 and https://github.com/ChromeDevTools/devtools-protocol/issues/130

Now case of Non-Headless, the cursor might be inside the browser window (most probably), so it's able to drop the element. In your script when I moved the cursor out the browser I could see that the element was not getting dropped.
In headless mode, the cursor would not be in browser window at all, hence you seeing the issue.

The best way to solve this is to use some other selector (to select `Header`) which selects the draggable HTML5 element.

**Comment by levietquynh** [comment]
@BugDiver I change to a xpath and see it works well. Thanks so much for your support.

**Comment by esvet** [comment]
Hi all,

I face same issues as described here before in headful mode with taiko dragAndDrop() in gauge tests on a vue.js ui.

It seems to be a similar above described issue, os takes over mouse control and interrupts mouse move simulation by taiko. Even when the mouse cursor is within the browser window it jumps there while test execution and looses its target. It only works when I help the taiko api with moving mouse cursor manually while execution to target location :/ 
only then taiko manages to drop the element to the specified target. 
I have tried all source/target parameter combinations (label, xpath element selector, distance object) but target is always the flaky thing in my case; not dragging the source;

label -> element
element -> element
element -> distance
label -> distance

`step("And user drags&drops Library vehicle with <id> into Panel", async(id) => {

    //await dragAndDrop("Object Name", "//*[text()='Vehicles']/parent::div/following-sibling::div//*[contains(@class,'dragArea')]" )
    //await dragAndDrop($("//*[@class='vId'][text()='"+ id +"']"), "//*[text()='Vehicles']/parent::div/following-sibling::div//*[contains(@class,'dragArea')]" )
    //await dragAndDrop($("//*[@class='vId'][text()='"+ id +"']"), {left:340, down:70} )
    await dragAndDrop("Object Name", {left:340, down:70} )
});`

In headless mode it doesn't work either. 

I'll appreciate any support on this folks.

Thank you

tools setup:

% taiko --version                      
Version: 1.2.2 (Chromium: 88.0.4314.0) RELEASE
 % gauge --version
Gauge version: 1.1.7
% node --version
v14.7.0
