### ISSUE TITLE
Could not generate API documentation

### ISSUE THREAD

**Issue by pslmsngr** [getgauge/taiko#1426]
### What I think happened
I think that because the user name for the work computer that I installed node, then taiko on, had spaces "IPX REGRESSION 2".  You can see from the log that I attached, on line 17, the following text: Error: EPERM: operation not permitted, mkdir 'C:\Users\IPX'.  There is no user IPX, just "IPX REGRESSION 2"

### Expected behavior
Tell us what should happen
It should install the API documentation.

### Actual behavior
Tell us what happens instead
It does not install/generate the API documentation.

### Steps to reproduce
I can reproduce this consistently on my work computer with a user name of "IPX REGRESSION 2"; Windows 10.
1.  Install node using node-v12.18.3-x64.msi installer
2.  When step 1 is completed, open a command prompt and run <npm install -g taiko> 
3.  At the end of the installation you will see the following text:   Could not generate API documentation. ...
4.  Open a command prompt at location specified on that text line and run <node lib/documentation.js>
5.  The same error will occur.

### Versions
```
Used node-v12.18.3-x64.msi for install.
Command prompt <node> displays Welcome to Node.js v12.18.3.
Command prompt <taiko> displays Version: 1.0.18 (Chromium: 86.0.4214.0)

```
[taiko-install.log](https://github.com/getgauge/taiko/files/5068844/taiko-install.log)

**Comment by NivedhaSenthil** [comment]
Thanks for reporting I could replicate the issue

**Comment by zabil** [comment]
@pslmsngr there were changes to this part of the functionality. Can you please try to see if this issue is fixed by running the following command?

```
npm install -g https://github.com/getgauge/taiko
```

This will install a version of Taiko which is from the main branch.

**Comment by pslmsngr** [comment]
Hello,
When I ran the command that you gave me on the computer that first showed
the issue I reported, I got the following error message when I ran
































*C:\Users\IPX REGRESSION 2>npm install -g https://github.com/getgauge/taiko
<https://github.com/getgauge/taiko>npm ERR! code ENOENTnpm ERR! syscall
spawn gitnpm ERR! path gitnpm ERR! errno ENOENTnpm ERR! enoent Error while
executing:npm ERR! enoent undefined ls-remote -h -t
https://github.com/getgauge/taiko.git
<https://github.com/getgauge/taiko.git>npm ERR! enoentnpm ERR! enoentnpm
ERR! enoent spawn git ENOENTnpm ERR! enoent This is related to npm not
being able to find a file.npm ERR! enoentnpm ERR! A complete log of this
run can be found in:npm ERR!     C:\Users\IPX REGRESSION
2\AppData\Roaming\npm-cache\_logs\2020-10-19T12_59_25_306Z-debug.logC:\Users\IPX
REGRESSION 2>npm --version6.14.6C:\Users\IPX REGRESSION 2>ping
www.github.com <http://www.github.com>Pinging github.com
<http://github.com> [140.82.112.3] with 32 bytes of data:Reply from
140.82.112.3 <http://140.82.112.3>: bytes=32 time=36ms TTL=52Reply from
140.82.112.3 <http://140.82.112.3>: bytes=32 time=37ms TTL=52Reply from
140.82.112.3 <http://140.82.112.3>: bytes=32 time=36ms TTL=52Reply from
140.82.112.3 <http://140.82.112.3>: bytes=32 time=36ms TTL=52Ping
statistics for 140.82.112.3 <http://140.82.112.3>:    Packets: Sent = 4,
Received = 4, Lost = 0 (0% loss),Approximate round trip times in
milli-seconds:    Minimum = 36ms, Maximum = 37ms, Average =
36msC:\Users\IPX REGRESSION 2>*

I have attached the log.


Now, when I ran that command that you gave me on my desktop it ran without
issue.




















*C:\Users\rgreen\AppData\Local\_git\_in-progress\mandark-regressiontester-mr-268>npm
install -g https://github.com/getgauge/taiko
<https://github.com/getgauge/taiko>npm WARN deprecated resolve-url@0.2.1:
https://github.com/lydell/resolve-url#deprecated
<https://github.com/lydell/resolve-url#deprecated>npm WARN deprecated
urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
<https://github.com/lydell/urix#deprecated>C:\Users\rgreen\AppData\Roaming\npm\taiko
-> C:\Users\rgreen\AppData\Roaming\npm\node_modules\taiko\bin\taiko.js>
taiko@1.0.25 install
C:\Users\rgreen\AppData\Roaming\npm\node_modules\taiko> node
lib/install.jsDownloading Chromium r811961 - 153.7 Mb
[====================] 100% 0.0s> taiko@1.0.25 postinstall
C:\Users\rgreen\AppData\Roaming\npm\node_modules\taiko> node
lib/documentation.jsnpm WARN optional SKIPPING OPTIONAL DEPENDENCY:
fsevents@~2.1.2
(node_modules\taiko\node_modules\chokidar\node_modules\fsevents):npm WARN
notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for
fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current:
{"os":"win32","arch":"x64"})+ taiko@1.0.25added 572 packages from 620
contributors, removed 10 packages and updated 27 packages in
123.313sC:\Users\rgreen\AppData\Local\_git\_in-progress\mandark-regressiontester-mr-268>*



Can I install that locally?  Clone the repository; copy it onto the
computer in question; install from there?

Or, if you have any further suggestions?

Thanks,
Richard Green

**Comment by pslmsngr** [comment]
Whoops.

I did not have Git installed on that computer.  I have that is not the
reason for the issue.

Anyways, here is the result of running that command you gave me.

*C:\Users\IPX REGRESSION 2>git version*
*git version 2.28.0.windows.1*

*C:\Users\IPX REGRESSION 2>npm install -g https://github.com/getgauge/taiko
<https://github.com/getgauge/taiko>*
*npm WARN deprecated resolve-url@0.2.1:
https://github.com/lydell/resolve-url#deprecated
<https://github.com/lydell/resolve-url#deprecated>*
*npm WARN deprecated urix@0.1.0: Please see
https://github.com/lydell/urix#deprecated
<https://github.com/lydell/urix#deprecated>*
*C:\Users\IPX REGRESSION 2\AppData\Roaming\npm\taiko -> C:\Users\IPX
REGRESSION 2\AppData\Roaming\npm\node_modules\taiko\bin\taiko.js*

*> taiko@1.0.25 install C:\Users\IPX REGRESSION
2\AppData\Roaming\npm\node_modules\taiko*
*> node lib/install.js*

*Downloading Chromium r811961 - 153.7 Mb [====================] 100% 0.0s*

*> taiko@1.0.25 postinstall C:\Users\IPX REGRESSION
2\AppData\Roaming\npm\node_modules\taiko*
*> node lib/documentation.js*

*npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2
(node_modules\taiko\node_modules\chokidar\node_modules\fsevents):*
*npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for
fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current:
{"os":"win32","arch":"x64"})*

*+ taiko@1.0.25*
*added 635 packages from 689 contributors in 139.991s*

*C:\Users\IPX REGRESSION 2>*

Hope that helps.
Richard Green

**Comment by zabil** [comment]
```
*> taiko@1.0.25 postinstall C:\Users\IPX REGRESSION
2\AppData\Roaming\npm\node_modules\taiko*
*> node lib/documentation.js*

*npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2
(node_modules\taiko\node_modules\chokidar\node_modules\fsevents):*
*npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for
fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current:
{"os":"win32","arch":"x64"})*

*+ taiko@1.0.25*
*added 635 packages from 689 contributors in 139.991s*
```

This output usually means that Taiko was installed successfully. Thanks for verifying that. I'll close this issue for now. An official release with the fix will be out soon.

**Comment by pslmsngr** [comment]
Well,
After installing Git, I uninstalled taiko and started from scratch.  Here
is the log for installing taiko as described at "
https://github.com/getgauge/taiko", and I saw the same issue (see the
log).  I then installed it as per your instructions (that worked):

*C:\Users\IPX REGRESSION 2>taiko --version*
*'taiko' is not recognized as an internal or external command,*
*operable program or batch file.*

*C:\Users\IPX REGRESSION 2>npm install -g taiko*
*C:\Users\IPX REGRESSION 2\AppData\Roaming\npm\taiko -> C:\Users\IPX
REGRESSION 2\AppData\Roaming\npm\node_modules\taiko\bin\taiko.js*

*> taiko@1.0.25 install C:\Users\IPX REGRESSION
2\AppData\Roaming\npm\node_modules\taiko*
*> node lib/install.js*

*Downloading Chromium r808757 - 152.8 Mb [====================] 100% 0.0s*

*> taiko@1.0.25 postinstall C:\Users\IPX REGRESSION
2\AppData\Roaming\npm\node_modules\taiko*
*> node lib/documentation.js*

*executing: npx documentation build --shallow lib/taiko.js
lib/elementWrapper/*.js -o lib/api.json*
*Generating documentation to lib/api.json*
*Error: Command failed: npx documentation build --shallow lib/taiko.js
lib/elementWrapper/*.js -o lib/api.json*
*Error: EPERM: operation not permitted, mkdir 'C:\Users\IPX'*
*command not found: documentation*

*    at ChildProcess.exithandler (child_process.js:303:12)*
*    at ChildProcess.emit (events.js:315:20)*
*    at maybeClose (internal/child_process.js:1021:16)*
*    at Process.ChildProcess._handle.onexit
(internal/child_process.js:286:5) {*
*  killed: false,*
*  code: 1,*
*  signal: null,*
*  cmd: 'npx documentation build --shallow lib/taiko.js
lib/elementWrapper/*.js -o lib/api.json ',*
*  stdout: '',*
*  stderr: "Error: EPERM: operation not permitted, mkdir
'C:\\Users\\IPX'\n" +*
*    'command not found: documentation\n'*
*}*
*Could not generate API documentation. Run <node lib/documentation.js> in
the directory C:\Users\IPX REGRESSION
2\AppData\Roaming\npm\node_modules\taiko.*
*executed successfully: npx documentation build --shallow lib/taiko.js
lib/elementWrapper/*.js -o lib/api.json*
*+ taiko@1.0.25*
*added 73 packages from 117 contributors in 39.539s*

*C:\Users\IPX REGRESSION 2>taiko version*
*Invalid file extension. Only javascript files are accepted.*

*C:\Users\IPX REGRESSION 2>taiko --version*
*Version: 1.0.25 (Chromium: 87.0.4270.0) RELEASE*

*C:\Users\IPX REGRESSION 2>npm uninstall -g taiko*
*removed 73 packages in 3.263s*

*C:\Users\IPX REGRESSION 2>taiko --version*
*'taiko' is not recognized as an internal or external command,*
*operable program or batch file.*

*C:\Users\IPX REGRESSION 2>npm install -g https://github.com/getgauge/taiko
<https://github.com/getgauge/taiko>*
*npm WARN deprecated resolve-url@0.2.1:
https://github.com/lydell/resolve-url#deprecated
<https://github.com/lydell/resolve-url#deprecated>*
*npm WARN deprecated urix@0.1.0: Please see
https://github.com/lydell/urix#deprecated
<https://github.com/lydell/urix#deprecated>*
*C:\Users\IPX REGRESSION 2\AppData\Roaming\npm\taiko -> C:\Users\IPX
REGRESSION 2\AppData\Roaming\npm\node_modules\taiko\bin\taiko.js*

*> taiko@1.0.25 install C:\Users\IPX REGRESSION
2\AppData\Roaming\npm\node_modules\taiko*
*> node lib/install.js*

*Downloading Chromium r811961 - 153.7 Mb [====================] 100% 0.0s*

*> taiko@1.0.25 postinstall C:\Users\IPX REGRESSION
2\AppData\Roaming\npm\node_modules\taiko*
*> node lib/documentation.js*

*npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2
(node_modules\taiko\node_modules\chokidar\node_modules\fsevents):*
*npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for
fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current:
{"os":"win32","arch":"x64"})*

*+ taiko@1.0.25*
*added 635 packages from 689 contributors in 124.608s*

*C:\Users\IPX REGRESSION 2>taiko --version*
*Version: 1.0.25 (Chromium: 87.0.4279.0)
0be7642ba4bbe9a97d5a93af6b34722097e9138d*

*C:\Users\IPX REGRESSION 2>*

Regards,
Richard Green

**Comment by pslmsngr** [comment]
Ok,
Thanks.
