### ISSUE TITLE
Get x-csrftoken of opened page

### ISSUE THREAD

**Issue by renatovieiradesouza** [getgauge/taiko#1428]
When try get hearders of request, cannot get x-csrftoken.

`const response = await goto('URL;gf=all'); if(response.status.code === 200) {console.log("Success!!")}`

Only possible get status code and url.

### Steps to reproduce
1. const response = await goto('URL;gf=all'); if(response.status.code === 200) {console.log("Success!!")}
2. response.status
3. { code: 200, text: '' }

### Versions
Version: 1.0.12 (Chromium: 81.0.3994.0) RELEASE

**Comment by NivedhaSenthil** [comment]
Request header can be fetched by intercepting the request. 
Example, 
```
intercept('google.com',(request) => {
            console.log(request);
            request.continue(request);
        });
```

Do let us know if looking for something different.

**Comment by renatovieiradesouza** [comment]
> Request header can be fetched by intercepting the request.
> Example,
> 
> ```
> intercept('google.com',(request) => {
>             console.log(request);
>             request.continue(request);
>         });
> ```
> 
> Do let us know if looking for something different.

Thank you for answer, all ok now.
