### ISSUE TITLE
Running a suite of tests using taiko and gauge fails after execution of first scenario.

### ISSUE THREAD

**Issue by rajeshvaran** [getgauge/taiko#143]
### Expected behavior
As a user I should be able to run test suite using taiko without any browser open close issues using taiko and gauge
### Actual behavior
Tell us what happens instead
If the test closes the browser for each and every scenario then the scenario hangs with google chrome popup attached
### Steps to reproduce
1. In the beforeScenario execution hook  add openBrowser() statement
2. In the afterScenario execution hook add closeBrowser() statement
3. Add a bunch of scenarios to the suite and every suite
4. url should be using https protocol with self signed certificate

### Versions
```
Paste `v8.11.2` and `Version: 0.2.0 (Chromium:69.0.3476.0)` versions here.
```

**Comment by rajeshvaran** [comment]
<img width="1203" alt="screen shot 2018-09-11 at 11 35 38 am" src="https://user-images.githubusercontent.com/16767/45342460-ae256c00-b5bb-11e8-9d7d-7f7792cb6447.png">

**Comment by rajeshvaran** [comment]
<img width="1129" alt="screen shot 2018-09-11 at 12 12 21 pm" src="https://user-images.githubusercontent.com/16767/45342576-02c8e700-b5bc-11e8-98a6-5db85f9afe26.png">

**Comment by sriv** [comment]
@rajeshvaran - can you please share a sample project to replicate this issue?

If you can see this with just taiko, then even a sample js script would be of good help. thanks.

**Comment by NivedhaSenthil** [comment]
Seems like google chrome pop up does not makes the script to hangs, as the below script works fine

```
(async () => {
    try {
        await openBrowser();
        await goto("google.com");
        await click("Google Search");
        await click("I'm Feeling Lucky");
    } catch (e) {
        console.error(e);
    } finally {
        closeBrowser();
    }
})();
```
Will be helpful if you could provide any sample to replicate and if there is any other error.

**Comment by rajeshvaran** [comment]
Finally got it fixed. It was due to missing promise. This issue could be closed.
