### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by dcRUSTy** [getgauge/taiko#1437]
https://github.com/getgauge/taiko/blob/6f4fc5b5b2b48c5e33036a7bda8bb739e8a2d66b/lib/taiko.js#L1113

https://github.com/getgauge/taiko/blob/6f4fc5b5b2b48c5e33036a7bda8bb739e8a2d66b/lib/taiko.js#L2023

### Expected behavior
Parameter Match

### Actual behavior
Parameter Mismatch?

**Comment by NivedhaSenthil** [comment]
Fixed in e1b066e
