### ISSUE TITLE
recording and repl taiko test script

### ISSUE THREAD

**Issue by roughsoft** [getgauge/taiko#1443]
1)npx taiko create url [name][...options]
the browser will be launched ,the script will be recoded as you use the application in the browser.
the ref site is:
https://docs.qawolf.com/docs/create_a_test
2)npx taiko  edit myTest
we can insert these statement "taiko.create();" or "taiko.repl()" in the test script.
the ref site is:
https://docs.qawolf.com/docs/edit_a_test

**Comment by jfgreffier** [comment]
It's an amazing feature ! I love Taiko REPL, but some kind of recorder would be nice.

**Comment by zabil** [comment]
A recorder is very handy. 
Looking at QA wolf playwright recorder the generated script uses css selectors which may make the tests flaky. It's a bit tough to generate a clean script with proximity selectors from a recorder. Worth a try though.

**Comment by roughsoft** [comment]
yeah!thank you response @zabil 
proximity selectors+recorder will be great!
Look forward that feature !
thank you your great work:taiko

**Comment by zabil** [comment]
@roughsoft thanks a lot for suggesting this feature. However, after trying https://docs.qawolf.com/docs/create_a_test there seems no way ideal way to record tests without relying on hardcoded selectors. Unfortunately, this is undesirable as it will lead to flaky tests. Taiko's objective is to reduce flakiness and for now the best possible way is to manually create the tests using proximity selectors. 

Please do feel free to experiment or share a repo if you feel that a recorder feature like the link you shared can be implemented with smart selectors.
