### ISSUE TITLE
Unable to run REPL after install via `yarn global add taiko`

### ISSUE THREAD

**Issue by adrianhopebailie** [getgauge/taiko#1449]
I installed taiko by running

```
yarn global add taiko
```

### Expected behavior

When I run `taiko` it launches the REPL

### Actual behavior

The script is executed and exits immediately.

On inspection it looks like the `isTaikoRunner` utility function is returning `false`.

It is looking for `taiko.js` in the path however my path is `/usr/local/bin/taiko` which is a symlink to `../../../Users/adrian/.config/yarn/global/node_modules/.bin/taiko` so neither path contains `taiko.js`

### Steps to reproduce
1. Run `yarn global add taiko`
2. Run `taiko`

### Versions
```
taiko@1.0.18
node@v12.18.1
```

**Comment by sriv** [comment]
Thanks for reporting @adrianhopebailie  - I could replicate this. The issue, as you suspected, is in the `isTaikoRunner` function. The problem was that it was only resolving first symlink, but in case of yarn install, there was another symlink created.

Added a fix via #1456
