### ISSUE TITLE
screenshot_on_success = true

### ISSUE THREAD

**Issue by roughsoft** [getgauge/taiko#1457]
if we could support these feature ,we could make step by step reporter more good.
screenshot_on_success = true

**Comment by zabil** [comment]
Thanks for the feedback. 

This feature makes more sense as a Taiko plugin. For example https://github.com/getgauge-contrib/taiko-screencast plugin. 

Closing this at this won't be implemented in the core.

**Comment by saikrishna321** [comment]
@roughsoft Here is the solution - https://github.com/saikrishna321/taiko-screeny

**Comment by roughsoft** [comment]
@saikrishna321 thank you!
