### ISSUE TITLE
share the token of auth between Scenarios

### ISSUE THREAD

**Issue by roughsoft** [getgauge/taiko#1460]
my spec include:one auth scenario(login),two feature scenarios,
I want to share the token of auth between feature scenarios, but we know the scenarios not share the memory state.
how can i get it?

**Comment by NivedhaSenthil** [comment]
@roughsoft You could try using [dataStore](https://docs.gauge.org/writing-specifications.html?os=macos&language=python&ide=vscode#data-store).

**Comment by roughsoft** [comment]
thank you!
