### ISSUE TITLE
taiko 1.0.20 doesn't start, leaves no error message

### ISSUE THREAD

**Issue by mhp-borisbojic** [getgauge/taiko#1467]
# Expected behavior
taiko should start

### Actual behavior
taiko doesn't start, leaving no error message.

### Steps to reproduce
1. update taiko 1.0.19 to 1.0.20
2. type `yarn run taiko`

### Versions
```
macOS 10.15.6
node v12.18.3
taiko 1.0.20
```

While using taiko 1.0.19, we don't have any issues - we can just start it with a basic `yarn run taiko`.

Updating it to 1.0.20 results in no output or message at all:

```
yarn run taiko
yarn run v1.22.5
$ *********/src/porsche/taiko-common/node_modules/.bin/taiko
✨  Done in 0.32s.
```

**Comment by zabil** [comment]
Thanks for reporting. There is an issue launching the REPL via yarn/npm/npx in release 1.0.20 will be fixing it soon.

**Comment by mhp-borisbojic** [comment]
Thank you! 👍
