### ISSUE TITLE
Should be able to goto link with file API

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#147]
**Expected behavior**
` goto("file:///<localPath>/something.html",{timeout:30000})` should navigate to the given html in the browser

**Actual behavior**
The `file:///` is getting changed to `file///` and the navigation fails

**Steps to replicate**
* Create a html file
```
<!DOCTYPE html>
<html>
<body>

<p>
To break lines<br>in a text,<br>use the br element.
</p>

</body>
</html>
```

* Open REPL
* openBrowser()
* goto("file:///<html_file_path>")
> The url is changed to file///. The colon ':' is getting removed

**Version**
```
commit - 24451f49f67f9376f3fb6b1734c4f6c0e6332a09
```

**Comment by NivedhaSenthil** [comment]
Fix should be available in f00fe76
