### ISSUE TITLE
Gauge and Taiko in 2021

### ISSUE THREAD

**Issue by zabil** [getgauge/taiko#1470]
From January 2021, Gauge and Taiko will move to being fully community managed open source projects. 

After 6 years of fully sponsored development, ThoughtWorks will no longer sponsor a team to work full time on Gauge and Taiko.

Gauge saw its first release in 2014 when ThoughtWorks sponsored a small team to build a radically different framework around our solid experience in testing and software quality. In 2018, we released Taiko after feedback from Gauge users for the need for a different kind of browser automation tool. 

As community managed open source projects, Gauge and Taiko joins other testing projects started at ThoughtWorks like Selenium/Webdriver, Mockito, Mountebank (and many more). ThoughtWorks is proud [of these projects](https://www.thoughtworks.com/open-source) and they are thriving among their own communities.

Here’s a set of Q&A about what this decision means for the community and the future of the projects. 

#### What happens to Gauge and Taiko after 2020?
From 2021, ThoughtWorks will no longer formally staff Gauge and Taiko teams. Gauge and Taiko will rely solely on community contributions.

#### Who will do Gauge and Taiko releases?
Gauge and Taiko releases along with its build infrastructure scripts are completely open source and automated using GitHub and GitHub Actions. Any modifications to the release process will be managed by core contributors.

#### Have you considered making Gauge and Taiko part of a foundation?
Yes. We are looking to do this over the next few months. We are still in early stages. Please do reach out to us if you can help us find one or have any recommendations.

#### What about Gauge and Taiko licenses and copyright?
Gauge and Taiko source use Apache and MIT licenses, respectively. Its content logo and assets are under Creative Commons. All contributions use Developer Certificate of Origin (https://developercertificate.org/)  for signing commits instead of a CLA. 

#### Should I stop using Gauge/Taiko and migrate my tests?
ThoughtWorks will staff the Gauge and Taiko team till the end of 2020. The projects will remain open source and open to contributions during this period and beyond. The projects will have a release cycle based on contributions. 

Please feel free to comment on this issue if you have any more questions.

**Comment by klctrl** [comment]
Many thanks for the great work you guys (+ the community of course) have done and the great products that have come out of it. I've been using Taiko since recently and I have to say that especially its "black box testing" features are absolutely outstanding and make writing and maintaining e2e tests a pure joy. You can be very proud of what you have achieved in the past years and I hope Taiko will continue to thrive in 2021 and beyond. 👏 🙇‍♂️

**Comment by roughsoft** [comment]
Thank you!
Great jobs!

**Comment by roughsoft** [comment]
can you provide the roadmap before 2021?
we look forward some feature: #1356 #1443 
1356,can make the distribute running infrastructure (spec and test can run in grid cluster)
1443,can make the script authoring 10X

**Comment by roughsoft** [comment]
@zabil

**Comment by roughsoft** [comment]
Gauge+Taiko+Selenoid

**Comment by zabil** [comment]
Please refer https://github.com/orgs/getgauge/projects/6 for items in the backlog and which are worked upon.

**Comment by roughsoft** [comment]
@zabil ，thank you！
We can write some docs about our “gauge grid” or “taiko grid”，that make we can run spec in large browser cluster！

**Comment by fmancardi** [comment]
It's really a pity. Taiko is a great tool

**Comment by zabil** [comment]
@fmancardi to be be clear Taiko is pretty much stable and feature packed. It will still be round.
