### ISSUE TITLE
Please implement a way to "paste" large data into an input field instead of using the write() API 

### ISSUE THREAD

**Issue by jakobheine** [getgauge/taiko#1475]
I asked a [question](https://spectrum.chat/taiko/general/is-there-a-way-to-paste-data-instead-of-the-write-api~d8c8ffe7-250c-4f5e-b171-a03db13531cd) regarding this feature on monday, and @sriv wanted me to open an issue.

### Expected behavior
For e2e-testing I want to have the possibility to paste large data into input fields.

### Actual behavior
I have to use the `write()` API, leading to (unnecessary) long execution times.

**Comment by NivedhaSenthil** [comment]
Interested in knowing why write api is having a significant overhead, can you please mention which version of Taiko you are on ?
