### ISSUE TITLE
button click is clicking on an incorrect element for version 21,20,19 works for v18

### ISSUE THREAD

**Issue by manasi-rk** [getgauge/taiko#1476]
### Expected behavior
Button Click with Text displayed should click on the right element. 
UI Element - 
![image](https://user-images.githubusercontent.com/46588493/91993202-b5b72000-ed52-11ea-9ee6-506323454dc5.png)

DOM -
![image](https://user-images.githubusercontent.com/46588493/91993300-d41d1b80-ed52-11ea-96b3-e9b4d0f5f5c5.png)

### Actual behavior
1. Using 
await highlight(button("Submit"));
await click(button("Submit"));

clicks on the following element
UI -
![image](https://user-images.githubusercontent.com/46588493/91995247-337c2b00-ed55-11ea-8413-205d725fa1be.png)

DOM-
![image](https://user-images.githubusercontent.com/46588493/91995328-4db60900-ed55-11ea-9754-fb120c698fef.png)

I have tried with some of the taiko versions
1. v1.0.21 - Fails
2. v1.0.20 - Fails
3. v1.0.19 - Fails
4. v1.0.18 - Works

But this works in REPL for all versions, but when using it with Gauge scripts in a step definitions, it fails and clicks on the incorrect element. 

### Versions
node - v12.16.1
Gauge version: v1.1.1

**Comment by saikrishna321** [comment]
What happens when u try click('Submit')

**Comment by manasi-rk** [comment]
click('Submit') also doesnt work - tried with v1.0.21
only thing that works currently -  await click($(`#assignPhysicalCardSubmitBtn`));

**Comment by mhp-borisbojic** [comment]
We have this issue, too. We could only solve it ATM like this:
```
  const scheduleButtonElement = $('.mileage-form-schedule-btn');
  await evaluate(scheduleButtonElement, (el) => el.click());
```
This worked in v1.0.18, but not in later versions of taiko anymore.

**Comment by NivedhaSenthil** [comment]
Will try reproducing this from our end, meanwhile if anyone of you can share a repro will help us fixing the issue sooner.

**Comment by NivedhaSenthil** [comment]
@mhp-borisbojic can you please confirm if your buttons label is also 'Submit' ? I could see it broken for type submit

**Comment by mhp-borisbojic** [comment]
@NivedhaSenthil No, the button name is irrelevant.

This worked with 1.0.18:
```
  await click('Further details');
```

With 1.0.19 and above, it's broken and it could't find and click the button anymore. I had to change it having a class and evaluate it like this:

```
  const scheduleButtonElement = $('.schedule-btn');
  await evaluate(scheduleButtonElement, (el) => el.click());
```

**Comment by NivedhaSenthil** [comment]
@mhp-borisbojic That shouldn't be happening.. atleast the click api should have worked with css/xpath selectors.
Can you please provide a sample html where this is happening ?

**Comment by mhp-borisbojic** [comment]
I forgot to mention that the button itself is a Web Component that makes use of the shadow DOM, too.

Here is the generated markup:
![Bildschirmfoto 2020-09-07 um 12 18 31](https://user-images.githubusercontent.com/47522149/92377352-4c456180-f104-11ea-9df1-01b26b462be8.JPG)

**Comment by NivedhaSenthil** [comment]
test.html
```
<html>
  <script>
    class ShadowButton extends HTMLElement {
      constructor() {
        super();

        var button = document.createElement('button');
        // button.setAttribute('type', 'button');
        // button.setAttribute('value', 'Shadow Click');
        button.addEventListener("click", event => {
          alert("Hello from the shadows");
        });
        button.textContent = "Hello";

        var shadow = this.attachShadow({mode: 'open'});
        shadow.appendChild(button);
      }
    }

    customElements.define('shadow-button', ShadowButton);
  </script>
  <body>
     <shadow-button/>
  </body>
</html>
```

code.js
```
(async () => {
    try {
        await openBrowser();
        await goto("file:///.../test.html");
        await alert(()=>accept());
        await click("Hello");
    } catch (error) {
        console.error(error);
    } finally {
        await closeBrowser();
    }
})();
```

I am able to successfully click the text of button within shadow DOM like in the above. These kind of screenshots does not really help catch the issue, please provide a repro like above. The issue with button having label as submit is fixed as part of  #1485.

**Comment by mhp-borisbojic** [comment]
Please try out this form: https://login.porsche.com/login/gb/en_GB#

We're only able to click the buttons with this piece of code - this works without issues:

```
const protractor = (protractorId) => {
  return $(`//*[@data-protractor-id="${protractorId}"]`)
}

const clickLoginBtn = async() => {
  warn('Clicking on login button');
  const loginBtn = protractor('login-btn');
  await evaluate(loginBtn, (el) => el.click());
  success('Clicked on login button');
}
```

Whereas this doesn't work at all - it just doesn't go an further and waits endlessly for the click to happen:

```
const clickLoginBtn = async() => {
  warn('Clicking on login button');
  const loginBtn = protractor('login-btn');
  await click(loginBtn');
  success('Clicked on login button');
}
```

Can I provide you with anything more?

**Comment by NivedhaSenthil** [comment]
Thanks, that was very helpful for understanding the issue. Fix done via https://github.com/getgauge/taiko/pull/1500, should be available i next release once reviewed and merged. 

Meanwhile you could try installing from the branch.
