### ISSUE TITLE
[Question] support profiling use devtools tracing 

### ISSUE THREAD

**Issue by gayanper** [getgauge/taiko#1482]
Do you plan to add support for dev tools profiler, to do performance tracing and dump trace files as json which can be imported into devtools profile to analyze them ?

**Comment by zabil** [comment]
There are no plans to support this. Taiko core will only be focused on testing and automation. However you can extend Taiko using plugins or use the [client](https://docs.taiko.dev/api/client/) API to do something like this.

**Comment by sriv** [comment]
@saikrishna321 wrote [a plugin](https://github.com/saikrishna321/taiko-diagnostics) that can perhaps help here.
