### ISSUE TITLE
below(below("1"))

### ISSUE THREAD

**Issue by roughsoft** [getgauge/taiko#1494]
### Expected behavior
Tell us what should happen

write("8888",textBox(below(below("1"))))
### Actual behavior
Tell us what happens instead

✘ Error: undefined not found, run `.trace` for more info.

### Steps to reproduce
1.
2.
3.
<img width="198" alt="Screen Shot 2020-09-09 at 4 37 29 PM" src="https://user-images.githubusercontent.com/459565/92575976-8a38b600-f2bb-11ea-96bc-5d10a2c66970.png">

### Versions
```
Paste `node` and `taiko` versions here.
```

**Comment by zabil** [comment]
@roughsoft can you please provide a sample project or at-least the html structure of the page you are trying to test so that someone can replicate this issue? Also please specify the node and Taiko versions. 

I am closing this temporarily until more information to replicate this is available. 
Will re-open this as soon as there is more info.

**Comment by roughsoft** [comment]
taiko :1.0.19
node:12.18.3
html structure:
<table>
<tbody>
<tr>
<td>1</td><td>2</td><td>3</td>
</tr>
<tr>
<td>0</td><td>0</td><td>0</td>
</tr>
<tr>
<td><input type=text name=f1></td><td><input type=text name=f2></td><td><input type=text name=f3></td>
</tr>
</tbody>
</table>

**Comment by roughsoft** [comment]
`<table>
<tbody>
<tr>
<td>1</td><td>2</td><td>3</td>
</tr>
<tr>
<td>0</td><td>0</td><td>0</td>
</tr>
<tr>
<td><input type=text name=f1></td><td><input type=text name=f2></td><td><input type=text name=f3></td>
</tr>
</tbody>
</table>`

**Comment by roughsoft** [comment]
> <table>
<tbody>
<tr>
<td>1</td><td>2</td><td>3</td>
</tr>
<tr>
<td>0</td><td>0</td><td>0</td>
</tr>
<tr>
<td><input type=text name=f1></td><td><input type=text name=f2></td><td><input type=text name=f3></td>
</tr>
</tbody>
</table>

**Comment by roughsoft** [comment]
I want to select the input below "0" in first col.
So I try these: 

write("8888",textBox(below(below("1"))))

I get these in console:

✘ Error: undefined not found, run .trace for more info.

**Comment by roughsoft** [comment]
@zabil

**Comment by saikrishna321** [comment]
write("8888",into(textBox(below(text("1")))))

Try 👆🏻
