### ISSUE TITLE
Taiko + Gauge Error in Doker 

### ISSUE THREAD

**Issue by bholya** [getgauge/taiko#1498]
#736 # Expected behavior
We are using gauge and taiko with jenkin. On jenkin we use docker image to run frontend test.
Test should run stable and provide reports. 

### Actual behavior
The JS-runner quits unexpectedly and test doesn't run on CI. No reports has been also generated.
The JS-runner _quits at different different step and different scenarios_.
The same tests are running multiple times on developer PC (uses same taiko and gauge version) stable. 

**Example:**
1.
[0;32m          * Anmeldung mit Testbenutzer	 ...[PASS]
[0m[0m[0;31m[0m[0;32m          * Benutzer klickt "Registrierung"	 ...[PASS]
[0m[0m[0;31m[0m[0;32m      * Der Träger gibt die Daten "Caritatis Düsseldorf e.V." "Internationale Organisationen" "Unterweg 34" "Hinterhaus" "99999" "Düsseldorf" "Bayern" "Lisa Simpson" "Frau" "Dr." "Marge" "Simpson" "marge.simpson@gehtschon.de" "010101099" "1" "" "" für die Selbstregistrierung ein	 ...[PASS]
[0m[0m[0;31m[0m[0;32m      * Handynummer "010101099" und PLZ "1234A" wurden eingegeben	 ...[PASS]
[0m[0m[0;31m[0m[0;32m      * Nach Prüfung durch den Träger wird der Registrierungsprozess abgeschlossen	 ...[PASS]
[0m[0m[0;31m[0m[0;32m      * Selbstregistrierung war nicht erfolgreich	 ...[PASS]
[0m[0m[0;31m[0m
[0mError: Navigation took more than 30000ms. Please increase the navigationTimeout.
at doActionAwaitingNavigation (/usr/lib/node_modules/taiko/lib/doActionAwaitingNavigation.js:65:13)
Error ----------------------------------

[Gauge]
js runner quit unexpectedly. Check logs for more details.
ErrorMessage: transport is closing

Get Support ----------------------------
	Docs:          https://docs.gauge.org
	Bugs:          https://github.com/getgauge/gauge/issues
	Chat:          https://spectrum.chat/gauge

Your Environment Information -----------
	linux, 1.1.1, 6e0d83f
	html-report (4.0.12), java (0.7.9), js (2.3.12), screenshot (0.0.1), spectacle (0.1.4)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gauge-taiko-template@0.0.1 test-entw: `dummy data/PDF1_groeßer10MB.pdf 11mb && gauge run --verbose --fail-safe --env itsi-entw specs/implemented`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gauge-taiko-template@0.0.1 test-entw script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-09-10T04_17_24_500Z-debug.log
[Pipeline] }
[Pipeline] // script

**2.**
[0;32m          * Anmeldung mit Testbenutzer	 ...[PASS]
[0m[0m[0;31m[0m[0;32m          * Benutzer klickt "Registrierung"	 ...[PASS]
[0m[0m[0;31m[0m[0;32m      * Der Träger gibt die Daten "Caritatis Düsseldorf e.V." "Internationale Organisationen" "Unterweg 34" "Hinterhaus" "99999" "Düsseldorf" "Bayern" "Lisa Simpson" "Frau" "Dr." "Marge" "Simpson" "marge.simpson@gehtschon.de" "010101099" "1" "" "" für die Selbstregistrierung ein	 ...[PASS]
[0m[0m[0;31m[0m[0;32m      * Handynummer "010101099" und PLZ "1234A" wurden eingegeben	 ...[PASS]
[0m[0m[0;31m[0mError: Element cannot be cleared
at module.exports.clear (/usr/lib/node_modules/taiko/lib/taiko.js:1548:11)
at async module.exports.<computed> (/usr/lib/node_modules/taiko/lib/taiko.js:3223:14)
Error ----------------------------------

[Gauge]
js runner quit unexpectedly. Check logs for more details.
ErrorMessage: transport is closing

Get Support ----------------------------
	Docs:          https://docs.gauge.org
	Bugs:          https://github.com/getgauge/gauge/issues
	Chat:          https://spectrum.chat/gauge

Your Environment Information -----------
	linux, 1.1.1, 6e0d83f
	html-report (4.0.12), java (0.7.9), js (2.3.12), screenshot (0.0.1), spectacle (0.1.4)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gauge-taiko-template@0.0.1 test-entw: `dummy data/PDF1_groeßer10MB.pdf 11mb && gauge run --verbose --fail-safe --env itsi-entw specs/implemented`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gauge-taiko-template@0.0.1 test-entw script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

### Steps to reproduce
1. Run Tests
2. Jenkins jobs are unsuccessful.

### Versions
Taiko-Version: 1.0.21
Gauge-Version: 1.1.1

Paste `node` and `taiko` versions here.
```

**Comment by NivedhaSenthil** [comment]
Can you please try launching browser with args suggested here https://docs.taiko.dev/frequently_asked_questions/#how-can-i-optimize-chrome-instances-for-parallel-runs%3F
