### ISSUE TITLE
The Taiko selectors checkBox and radioButton do not bubble the click event.

### ISSUE THREAD

**Issue by falcon030** [getgauge/taiko#1499]
### Expected behavior
When I use radioButton().select() or checkBox.check() I expect the JavaScript `click` event to be triggered.

### Actual behavior
The JavaScript click event is not triggered, when  using radioButton().select() or checkBox.check().

This is probably caused by the fact that the setChecked function of the `radioButton` and `checkBox` API does not bubble the `click` event:
```
function setChecked(value) {
  this.checked = value;
  let event = new Event('click');
  this.dispatchEvent(event);
}

Taiko version 1.0.19
```

**Comment by saikrishna321** [comment]
Fix in master.
