### ISSUE TITLE
Unable to click with text of input with type file

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#15]
**Expected behavior**
Should be able to click on html element input by specifying the text

**Actual behavior**
Getting the error
```
(node:3052) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Element not found
(node:3052) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Steps to replicate**
* In the html use element
```
        <input type="file" onchange='readText(this)'/>
```
* This displays element with text 'Choose File'
* In code call API 
```
    click('Choose File')
```

**Version**
```
Gauge version: 0.9.6.nightly-2017-12-04
Commit Hash: 584485d

Plugins
-------
js (2.0.3.nightly-2017-11-30)
```

**Comment by kashishm** [comment]
Use upload on file input element.
```
upload('file.txt', to(fileField('Label')));
```
The example is present in [getgauge-examples/js_puppeteer](https://github.com/getgauge-examples/js_puppeteer/blob/master/tests/step_implementation.js#L87).

**Comment by kashishm** [comment]
Now, `click` throws an exception if the selector passed resolves to a file input field and suggests to use `attachFile`.
```
> click($('#file'))
 ✘ Error: Unsupported operation, use `attachFile` on file input field, run `.trace` for more info.
```
