### ISSUE TITLE
Api to Simulate different devices

### ISSUE THREAD

**Issue by NivedhaSenthil** [getgauge/taiko#150]
Provide an api to simulate different devices. To take advantage of devtool feature(https://developers.google.com/web/tools/chrome-devtools/device-mode/).

**Comment by NivedhaSenthil** [comment]
Fix done in f0a6c49

Three ways to emulate

- Pass it as command line arg to taiko runner
`taiko code.js --emulateDevice=iphone6`

- Set it as env variable to emulate using other runners
`TAIKO_EMULATE_DEVICE=iphone6 gauge run specs`

- call it as api `emulateDevice('iphone6')`

Refer https://github.com/getgauge/taiko/blob/master/lib/device.js for available devices to emulate

**Comment by Debashis9012** [comment]
We are able to emulate the supported device by using emulateDevice() api. Tested with the below version
``` f0a6c49```
