### ISSUE TITLE
closeBrowser throws error as browserProcess is undefined

### ISSUE THREAD

**Issue by saikrishna321** [getgauge/taiko#1503]
`openBrowser` API takes options to connect to the open instance of browser, which skips the launch of the browser in taiko.

When `closeBrowser` API is called the browerProcess is undefined and it fails.

Code to Reproduce:

1. Open chrome in debugging mode `/Users/git/taiko/.local-chromium/mac-796283/chrome-mac/Chromium.app/Contents/MacOS/Chromium --remote-debugging-port=9222`
2. Enter REPL.
3. openBrowser({host:'127.0.0.1', port: 9222})
4. closeBrowser() // Fails

**Comment by NivedhaSenthil** [comment]
fixed via #1510
