### ISSUE TITLE
getMatchingInterceptor() @ fetchHandler.js crashes when calling decodeURI()

### ISSUE THREAD

**Issue by rmallof** [getgauge/taiko#1509]
Hi, first of all a big thank you for maintaining such a great project

### Expected behavior
getMatchingInterceptor() should handle different types of URL encodings

### Actual behavior
Exception is raised: "Exception has occurred: URIError: URI malformed"

### Steps to reproduce
TL;DR: URL 'https://bh.contextweb.com/bh/rtset?pid=557219&ev=1&rurl=https://simage2.pubmatic.com/AdServer/Pug?vcode=bz0yJnR5cGU9MSZqcz0xJmNvZGU9MzMxOSZ0bD0xMjk2MDA=&ev=1&piggybackCookie=%%VGUID%%' should raise an exception at getMatchingInterceptor() line 233: "return decodeURI(url).match(re);"

1. Open taiko
2. Go to "https://tryphp.w3schools.com/showphp.php?filename=demo_form_post" page
3. intercept requests to "https://tryphp.w3schools.com/demo/welcome.php"
2. Use taiko to fill in the "name" input and the "e-mail" inputs at the right
3. Eventually, intercept should crash

### Versions
```
> gauge --version
Gauge version: 1.1.1
Commit Hash: 6e0d83f

Plugins
-------
flash (0.0.2)
html-report (4.0.12)
js (2.3.12)
screenshot (0.0.1)

> taiko --version
Version: 1.0.22 (Chromium: 86.0.4240.0) RELEASE

Your Environment Information -----------
        windows, 1.1.1, 6e0d83f
        flash (0.0.2), html-report (4.0.12), js (2.3.12), screenshot (0.0.1)
```

Thanks in advance

**Comment by rmallof** [comment]
Adding one more URL example triggering the exception: 

`'https://bh.contextweb.com/bh/rtset?pid=558511&ev=1&rurl=https%3A%2F%2Fce.lijit.com/merge?pid=49&3pid=%%VGUID%%&gdpr=1&gdpr_consent=CO5wEyeO5wEyeDlBzAENA3CsAP_AAH_AACiQGktf_X_fb2vj-_599_t0eY1f9_63v-wzjheNs-8Nyd_X_L4Xv2MyvB36pq4KuR4ku3bBAQdtHOncTQmRwIlVqTLsbk2Mr7NKJ7LEmlsbe2dYGH9vn9XT_ZKZ70_v___7_3______77_-b_4GkkEmGpfAQJCWMBJNmlUKIEIVxIVAOACihGFo0sNCVwU7K4CPUECABAagIwIgQYgoxZBAAAAAElEQAkBwIBEARAIAAQArQEIACJAEFgBIGAQACgGhYARRBKBIQZHBUcogQFSLRQTzRgSQfIAA'`

**Comment by zabil** [comment]
Just a note, both of these fail when using Node's `decodeURI`

```
Welcome to Node.js v14.10.1.
Type ".help" for more information.
> decodeURI('https://bh.contextweb.com/bh/rtset?pid=558511&ev=1&rurl=https%3A%2F%2Fce.lijit.com/merge?pid=49&3pid=%%VGUID%%&gdpr=1&gdpr_consent=CO5wEyeO5wEyeDlBzAENA3CsAP_AAH_AACiQGktf_X_fb2vj-_599_t0eY1f9_63v-wzjheNs-8Nyd_X_L4Xv2MyvB36pq4KuR4ku3bBAQdtHOncTQmRwIlVqTLsbk2Mr7NKJ7LEmlsbe2dYGH9vn9XT_ZKZ70_v___7_3______77_-b_4GkkEmGpfAQJCWMBJNmlUKIEIVxIVAOACihGFo0sNCVwU7K4CPUECABAagIwIgQYgoxZBAAAAAElEQAkBwIBEARAIAAQArQEIACJAEFgBIGAQACgGhYARRBKBIQZHBUcogQFSLRQTzRgSQfIAA')
Uncaught URIError: URI malformed
    at decodeURI (<anonymous>)
> decodeURI('https://bh.contextweb.com/bh/rtset?pid=557219&ev=1&rurl=https://simage2.pubmatic.com/AdServer/Pug?vcode=bz0yJnR5cGU9MSZqcz0xJmNvZGU9MzMxOSZ0bD0xMjk2MDA=&ev=1&piggybackCookie=%%VGUID%%')
Uncaught URIError: URI malformed
    at decodeURI (<anonymous>)
```
