### ISSUE TITLE
Provide option to emulate network conditions

### ISSUE THREAD

**Issue by NivedhaSenthil** [getgauge/taiko#151]
Add an api to emulate network conditions like downloadThroughput, offline, uploadThroughput etc.
https://chromedevtools.github.io/devtools-protocol/tot/Network#method-emulateNetworkConditions

**Comment by NivedhaSenthil** [comment]
Fix available in  b669a07

**Comment by Debashis9012** [comment]
This has been tested with the below version
```b669a07 ```
