### ISSUE TITLE
Proximity Selectors - Inside an element is missing

### ISSUE THREAD

**Issue by patidar-jaishree** [getgauge/taiko#1511]
### Expected behavior
As we have feature of Proximity Selectors - I should be able to use inside an element
For example: If I would like to see a text is appearing inside a form (when there are 2 forms on a webpage)

### Actual behavior
Currently available options for Proximity selectors are- 
    toLeftOf, toRightOf, above, below, near

### Versions
Taiko - Version: 1.0.3 (Chromium: 79.0.3945.16) RELEASE

![image](https://user-images.githubusercontent.com/41952531/93188665-e0e03d00-f75e-11ea-999a-f8607726c75c.png)

**Comment by sriv** [comment]
Can you share a html snippet illustrating where the proximity selector does not work? Thanks.

**Comment by patidar-jaishree** [comment]
Example - I want to asset a Company is available in both the tables 
I was hoping to have an proximity Selector to say something like inside instead of above/below

```
<table id="CompanyTableCompleted">
  <tr>
    <th>Company</th>
    <th>Contact</th>
    <th>Country</th>
  </tr>
  <tr>
    <td>Alfreds Futterkiste</td>
    <td>Maria Anders</td>
    <td>Germany</td>
  </tr>
  <tr>
    <td>Centro comercial Moctezuma</td>
    <td>Francisco Chang</td>
    <td>Mexico</td>
  </tr>
  <tr>
    <td>Ernst Handel</td>
    <td>Roland Mendel</td>
    <td>Austria</td>
  </tr>
</table>
<br><br>
<table id="CompanyTablePending">
  <tr>
    <th>Company</th>
    <th>Contact</th>
    <th>Country</th>
  </tr>
  <tr>
    <td>Alfreds Futterkiste</td>
    <td>Maria Anders</td>
    <td>Germany</td>
  </tr>
  <tr>
    <td>Centro comercial Moctezuma</td>
    <td>Francisco Chang</td>
    <td>Mexico</td>
  </tr>
  <tr>
    <td>Ernst Handel</td>
    <td>Roland Mendel</td>
    <td>Austria</td>
  </tr>
</table>
```
Please let me know, in case more details are required.

**Comment by sriv** [comment]
You can add a scope to the selector, ex: `text("Company", $("#CompanyTablePending"))` would select a text element inside table with id `CompanyTablePending`

**Comment by patidar-jaishree** [comment]
I tried below code, it is not working for me. Please let me know if I am missing anything.
The element is existing and "smart selectors" text also.
```
> openBrowser()
> goto('https://taiko.dev/')
> text('Smart selectors').exists()
> $('a[href*=smart]  div.box').exists()
> text('Smart selectors', $('a[href*=smart]  div.box')).exists()
```
<img width="1440" alt="Screen Shot 2020-09-17 at 3 39 34 PM" src="https://user-images.githubusercontent.com/41952531/93457110-40278400-f8fc-11ea-9d14-64708d677a44.png">

**Comment by NivedhaSenthil** [comment]
@patidar-jaishree yes selectors cannot be scoped like that, there is currently no way to do this except for using css selector or `near` proximity selector

**Comment by saikrishna321** [comment]
@NivedhaSenthil I think this is very useful API to have in taiko. I use Taiko to automate legacy application which does not have enough unique locators. In lot of cases proximity selectors are saving us. We have a use case where we want to interact with a specific element which is within another element. For Ex: First Row and some element(The page has 30 other similar elements)

**Comment by saikrishna321** [comment]
@patidar-jaishree `within` API is implemented and Merged to master. 

Try `text('Smart selectors', within($('a[href*=smart]  div.box'))).exists()`
