### ISSUE TITLE
 Failed to launch browser!

### ISSUE THREAD

**Issue by sofo506-maker** [getgauge/taiko#1514]
Hi All,
I ran into this issue and not quite know how to resolve it. Any help would be appreciated.
### Expected behavior
Scripts are deployed and run headless on the bitbucket-pipline code commit.

### Actual behavior
+ /opt/atlassian/pipelines/agent/build/packages/server/app/tests/E2E/node_modules/taiko/.local-chromium/linux-800071/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory

### Steps to reproduce
1. Scripts are using: await openBrowser({
    headless: true,
    args: [
      "--disable-gpu",
      "--disable-dev-shm-usage",
      "--disable-setuid-sandbox",
      "--no-first-run",
      "--no-sandbox",
      "--no-zygote"],
  });
2. E2E package.json : {
  "name": "gauge-taiko-template",
  "version": "0.0.1",
  "description": "Starter template for writing JavaScript tests for Gauge",
  "scripts": {
    "e2e": "gauge run specs/"
  },
  "dependencies": {
    "taiko": "latest",
    "taiko-storage": "0.0.3"
  }
}
3. The root level package.json has 
"scripts": {
    "e2etest": "cd packages/server/app/tests/e2e && npm install taiko && npm run e2e",
}
### Versions
 "node": "12.16.2" and taiko@1.0.23.

**Comment by zabil** [comment]
There a section in the FAQ for this https://docs.taiko.dev/frequently_asked_questions/#i-have-a-few-issues-launching-the-browser-instance-in-linux

Please try installing all the dependencies to see if it fixes the issue.
