### ISSUE TITLE
checkbox($(locator)) does not work.

### ISSUE THREAD

**Issue by flexin777** [getgauge/taiko#1519]
### Expected behavior
checkbox($(locator)).check() - method checkbox( ) should accept as input $(locator)

### Actual behavior
throws exception when use checkbox($(locator)).check()

### Steps to reproduce
1. Open Website with checkbox element
2. execute method checkbox($(locator)).check()
3.

### Versions
```
latest versions.
```

**Comment by NivedhaSenthil** [comment]
checkBox does not accept another selector `$`, if you want to select using any attribute value pair you can pass them like below,

`await checkBox({'id':'something'}).exists()`

**Comment by flexin777** [comment]
So, I cannot use xpath, or css locator, am I right, @NivedhaSenthil ?

**Comment by NivedhaSenthil** [comment]
yes, only attribute value pair or label or proximity selector can be used.
