### ISSUE TITLE
Control+a is not working..

### ISSUE THREAD

**Issue by hrishabhkumar** [getgauge/taiko#1524]
### Expected behavior
Tell us what should happen
 When I send taiko.press(["ControlLeft", "a"]) it should select all the text in input
### Actual behavior
Tell us what happens instead
When I send taiko.press(["ControlLeft", "a"]) it is not doing anything

### Versions
node: 12.13.0,
taiko: 1.0.22
```

**Comment by zabil** [comment]
This is not supported please refer https://github.com/getgauge/taiko/issues/192#issuecomment-428518608 for more info If you want to clear the text use https://docs.taiko.dev/api/clear/
