### ISSUE TITLE
The element should be scrolled into view only if needed

### ISSUE THREAD

**Issue by hrishabhkumar** [getgauge/taiko#1526]
### Expected behavior
The element should be scrolled into view only if needed

### Actual behavior
It is trying to scroll the element to the center which is causing flicker on the website.

### Steps to reproduce
1. try to click when the element is in the view but not at the center.

### Versions
node: 12.13.0
taiko: 1.0.23

can we use element.scrollIntoView()?

**Comment by NivedhaSenthil** [comment]
can you please give an example for us to understand this scenario better? Taiko does use element.scrollIntoView() for scrolling before action

**Comment by hrishabhkumar** [comment]
Sorry I mean, can we use element.scrollIntoViewIfNeeded()?
I am unable to provide the URL as it is limited to our internal network.

**Comment by NivedhaSenthil** [comment]
We moved away from using `scrollIntoViewIfNeeded()` in order to support firefox, as it is not standardized and available only in chromium based browsers

**Comment by hrishabhkumar** [comment]
can we have it based on browser type?

**Comment by zabil** [comment]
> Can we have it based on browser type?

This will cause issues when the tests are run across browsers. Ideally the tests should work on both without any modifications. You could try using the `evaluate` api to scroll using javascript on the browser. This is likely to work across both browsers.

**Comment by NivedhaSenthil** [comment]
Can we know exactly what is the problem you are facing when taiko tries to scroll element into center before action ?

**Comment by NivedhaSenthil** [comment]
current behavior of scroll is modified to use `nearest` as an option to `scrollIntoView`.... try out 1.0.25

**Comment by hrishabhkumar** [comment]
Thank you it's working now
