### ISSUE TITLE
Should scroll before click

### ISSUE THREAD

**Issue by yz56** [getgauge/taiko#1541]
### Expected behavior
It should scroll down before click

### Actual behavior
It didn't scroll down in some special case, like when the button is at the bottom of the page.  So it can't click the element matching particular text, and throw error "element matching text "buttonText" is covered by other elements"

### Steps to reproduce
1. Fill some form (with several rows) which is not too short and not too long
2. Click the button to submit

### Versions
```
node: v10.15.3
takio: ^1.0.6
```
### Other informations

Taiko API document describes the Click as below 
```
"Fetches an element with the given selector, scrolls it into view if needed,"
```
It does scroll down in most time, but if the form is a little long but not too long, it will not scroll down. So it is a little hard to reproduce this bug.

In my case, it passes all functional-test on my computer, but it fails in the pipeline. 
![WeChat Screenshot_20200925122032](https://user-images.githubusercontent.com/68947376/94232063-ce70bb00-ff37-11ea-92a5-5f9ad54dec7d.png)

this is the user_journey before I manually add scroll down, it passes the test on my computer but fails on the pipeline.
```
* Fill some form with "text1", "text2", "text3", "text4"
* Click "Check out"
```
This is the user_journey after I add scroll down, it passes on my computer and pipeline.
```
* Fill some form with "text1", "text2", "text3", "text4"
* Scroll down
* Click "Check out"
```
I use the codes below to complete the ‘Scroll down’
```
step("Scroll down", async function () {
    await scrollDown(1000)
});
```

**Comment by mhp-borisbojic** [comment]
Maybe related to https://github.com/getgauge/taiko/issues/1526#issuecomment-698712751 ?

**Comment by yz56** [comment]
> Maybe related to [#1526 (comment)](https://github.com/getgauge/taiko/issues/1526#issuecomment-698712751) ?

maybe it's different, in my case, the browser didn't scroll the element into view automatically as the document describes 
https://docs.taiko.dev/api/click/

**Comment by NivedhaSenthil** [comment]
This seems more specific to the page being tested, will be great if you can help us with some repro to understand the behind-hood of this scenario.

**Comment by msharma-tw** [comment]
Tried to reproduce with the above steps. Didn't faced this issue. @yz56 - can you share the URL which you are testing.

**Comment by yz56** [comment]
> Tried to reproduce with the above steps. Didn't faced this issue. @yz56 - can you share the URL which you are testing.

Sorry, my company does allow me to share the project, I will try to make a demo when I have time.
