### ISSUE TITLE
parent table

### ISSUE THREAD

**Issue by roughsoft** [getgauge/taiko#1547]
https://sahipro.com/docs/sahi-apis/relation-apis.html#_parentTable
if we can support this API，we can better select table element from browser as blackbox

**Comment by zabil** [comment]
> we can better select table element from browser as blackbox

Can you please provide an example to understand a scenario where this API can be used? Right now Taiko's API only returns the element (or multiple elements for more than one match)

The [tableCell](https://docs.taiko.dev/api/tablecell/) API allows the user to select cells in the table directly. An example of how you intend use the table element will help to cover use cases missing in `tableCell`

**Comment by roughsoft** [comment]
“locating table using proximity selectors, or table labels.”
we often meet table just these：“<table><tr><td>ddd</td><td>ttt</td></tr><tr><td>ddd</td><td>ttt</td></tr><tr><td>ddd</td><td>ttt</td></tr></table>”
If we want to use tableCell api we must select table at first.
within proximity api maybe is a good idea.

**Comment by zabil** [comment]
You can select the table using a caption 
```
highlight(tableCell({row:2, col:3}, "Table Caption"))
```
In case a table caption is not there there is a new proximity selector called [within](https://docs.taiko.dev/api/within/) which is coming out in the next release that can narrow down the search to a region.

You can try this API by installing taiko from the main branch i.e. `npm i https://github.com/getgauge/taiko`
