### ISSUE TITLE
taiko selector engineer and playwright 

### ISSUE THREAD

**Issue by roughsoft** [getgauge/taiko#1548]
If we can refactor the code make the taiko selector engineer and playwright side by side，It will be awesome.

**Comment by roughsoft** [comment]
https://github.com/microsoft/playwright/blob/master/docs/extensibility.md#custom-selector-engines

**Comment by zabil** [comment]
We did look at this. I also see a comment at https://github.com/microsoft/playwright/issues/2877#issuecomment-695803698
However I am closing this as there is probably no refactoring to be done in Taiko to enable this. Its best tracked at the linked issue.
