### ISSUE TITLE
[Question] Select a random value from a dropDown

### ISSUE THREAD

**Issue by nosdoska** [getgauge/taiko#1551]
Hi,

First of all thanks for the amazing work! Taiko is an awesome tool, pretty easy to use, and has changed the way we work beautifully.

The title is pretty descriptive about my question: is it possible to select a random value from a dropDown? Is there any plans to implement something like this? I would be more than happy to help in implementing it.

Thanks!

**Comment by zabil** [comment]
@nosdoska glad to see you are finding Taiko useful!

There's no support out of the box yet. But have you tried using the [index](https://docs.taiko.dev/api/dropdown/) parameter and a [random number generator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random)?

```
await dropDown('Vehicle:').select({index:Math.floor(Math.random() * Math.floor(max))})
```

**Comment by nosdoska** [comment]
Thanks for the response @zabil !

Yes, in fact I tried to do something similar, and it fixes the problem for dropDowns that are not dynamic. However, there is a set of dropDowns _that are dynamic_, and I can't get one to be randomly selected. Is something that could be provided out of the box by taiko? Would it be something that gets out of taiko's hands?

**Comment by saikrishna321** [comment]
@nosdoska Are you expecting the `dropDown` API to return you all the values present in the dropdown and then select one of them?

**Comment by zabil** [comment]
> However, there is a set of dropDowns that are dynamic

Forgive me for going meta on this. 

This API will get tricky, more so from consistency with other API's. Right now, Taiko uses implicit assertions, that means it fails when a drop down is not available. This is good for testing as it gives early feedback and works deterministically on each run for the same test data. Selecting a random value is good from an automation perspective but can make the test unpredictable or be difficult to debug. 

Is there a way you can provided an example of the values you are trying to randomise? The `dropdown` does have a regex match feature for partial matches. Perhaps that could be extended?

**Comment by nosdoska** [comment]
@saikrishna321 That would be helpful too!

@zabil I understand. And what about the suggestion that @saikrishna321 said? Would be that more consistency with the API?

The values that I'm pointing are cities/states/countries. I don't want to specifically test them, just want to set a random value for them. Does that make sense? Is there any other way I can make this?

**Comment by zabil** [comment]
> Would be that more consistency with the API?

Probably not, as it will not fail the test. 

> Is there any other way I can make this?

You could use [`evaluate` ](https://docs.taiko.dev/api/evaluate/) for e.g. (you may have to modify the script)

```
var randomSelector = function(element) {
     var max = element.options.length;
     var randomIndex = Math.floor(Math.random() * Math.floor(max));
     element.selectedIndex = randomIndex;
}

await evaluate(dropDown('Country:'), randomSelector)
```

You refer the tutorial for more info https://docs.taiko.dev/running_scripts_inside_the_browser/

**Comment by nosdoska** [comment]
@zabil I think that would work like a charm! Thanks a lot!

I'll close it considering that this is a perfect solution.
