### ISSUE TITLE
Return elementWrapper by running a function in browser

### ISSUE THREAD

**Issue by NivedhaSenthil** [getgauge/taiko#1557]
### Expected behavior
Should be able to get an element wrapper by executing function in browser, so that it can be used in other actions like `click`

Example: `click($(() => return document.getElementById('id') ))` or  
`click(evaluate(() => return document.getElementById('id'),{elementWrapper:true}))`

**Comment by zabil** [comment]
I like reusing 

```
click(evaluate(() => return document.getElementById('id')))
```

Without `{elementWrapper:true}` this makes `evaluate` return a JSON or the `elementWrapper` by checking the return value.
This will make it easier to use the API

**Comment by NivedhaSenthil** [comment]
That has to defined before executing the function  in the browser so that CDP can return object accordingly.. currently we set `returnByValue` option to true when executing the function in browser context to get the return value as string.. if we have to get the object reference it should not be set.. else it will error out with `Error: Object reference chain is too long`

**Comment by NivedhaSenthil** [comment]
As there are elimitations with `evaluate` api $ selector will be updated to take a callback like below,

```
$(() => {return document.querySelector('#foo');})
$((selector) => document.querySelector(selector), { args: '#foo' })
```
