### ISSUE TITLE
Click on navigation bar item does not trigger navigation (scroll down)

### ISSUE THREAD

**Issue by klhex** [getgauge/taiko#1565]
**Describe the bug**
When a navigation item on a page with a navigation bar is clicked then the scrolling down to the page's section referenced by the navigation item does only start for a short moment but then stops. It only succeeds fully when the same navigation item is clicked again. 

The next issue concerns clicking on 'MEHR ERFAHREN' once the downwards navigation has succeeded (currently, by clicking again on 'Auto Abo abschließen'): If one tries to click on the leftest 'MEHR ERFAHREN' button like as follows

```javascript
await click('MEHR ERFAHREN', {}, below('Premium-Paket'));
```
then the button is scrolled into view and you get this error: "Error: Element matching text "MEHR ERFAHREN" is covered by other element".

If one adds `await hover('MEHR ERFAHREN');` before the above mentioned click, then the click succeeds, no error message.

**To Reproduce**
```javascript
const { openBrowser, goto, click, closeBrowser } = require('taiko');
(async () => {
    try {
        await openBrowser({headless: false});
        await goto('vwfs.de/autoabo.html');
        await click('Ja, ich willige ein');
        await click('Auto Abo abschließen');
    } catch (error) {
        console.error(error);
    } finally {
        await closeBrowser();
    }
})();
```

**Expected behavior**
1st issue expected behavior: After the click on 'Auto Abo abschließen' the page should be scrolled down to where the navigation item is referencing to.

2nd issue expected behavior: The above mentioned click on 'MEHR ERFAHREN' should lead for the right element to be found, scrolled into view and be clicked instead of throwing the above mentioned error message.

**Versions:**
 - Taiko: 1.0.23
 - MacOS Catalina: 10.15.6 (19G2021)
 - Node.js: v14.7.0

**Additional context**
It appears that the scrolling issue is related to the size of the browser window. Running the same test with a lower browser window height, for example, seems to make the scrolling (after the click on 'Auto Abo abschließen') work. But it still seems to be relatively brittle.

**Comment by NivedhaSenthil** [comment]
I could that when we try to click `Auto Abo abschließen` for the first time the page is scrolled once the coordinates to click is calculated and hence Taiko is clicking on wrong coordinates. Seems like highlighting element on action is causing the scroll, trying to find why that is happening.
