### ISSUE TITLE
Adding Github action for dtslint

### ISSUE THREAD

**Issue by fmpanelli** [getgauge/taiko#1571]
**Is your feature request related to a problem? Please describe.**
Taiko's project contains an npm script to verify the type declarations which can be executed by `npm run dtslint`

That script is not run automatically anywhere in the pipeline. Therefore type issues can get merged into master and get published without noticing.

E.g. the `within` function was introduced recently, but the related tyoe declaration was not added. This led to issue #1569. Which could have been prevented if `dtslint` had been run.

**Describe the solution you'd like**
In the github actions that are run for new PRs add a job to run `dtslint`.
This can be done by adding a job to `.github/workflows/taiko.yml`

**Describe alternatives you've considered**
Alternatively we could add `dtslint `to the `pre-commit` actions run by `husky `before committing together with the standard linting.

**Additional context**

**Comment by zabil** [comment]
> Alternatively we could add dtslint to the pre-commit actions run by husky before committing together with the standard linting.

This looks like the better alternative to catch these things early. Also other lint tasks run as a pre commit hook.

**Comment by fmpanelli** [comment]
I am back on the topic (sorry it's been so long).

Fine with using git hooks, anyway I propose to execute `npm run dtslint` within `pre-push`.
I think it is too slow to have it executed in `pre-commit`.

I submitted PR #1651 with the proposed changes.
