### ISSUE TITLE
Wild cards in URL to close or switch Tabs

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#158]
**Expected behavior**
Should be able to specify wild cards in URL to close or switch Tabs.

**Current behavior**
The exact URL with parameters have to be specified to switch or close Tabs.

**Version**
```
b15afd9db54135e2c0a78485df0869913cd9a9a4
```

**Comment by zabil** [comment]
Support for this was added via regex https://github.com/getgauge/taiko/pull/968
