### ISSUE TITLE
Getting uncaught unexpected error while running the saved script

### ISSUE THREAD

**Issue by nseshadr** [getgauge/taiko#1580]
**Describe the bug**
I am trying to run the saved JS file using command npx taiko xx.js and getting below error
> Uncaught Unexpected token, expected ";" (1:21)
> Uncaught Unexpected identifier

I used the recorder and saved the file using .code command. Now i am trying to run the js file with the saved steps.

**Comment by zabil** [comment]
@nseshadr closing this temporarily as there not enough information to replicate and debug this. Please take a look at https://docs.taiko.dev/contributing/#reporting-an-issue to make sure you are filling the whole issue template. Will open it as soon as there is enough information.
