### ISSUE TITLE
Clear intercept warning in closeIncognitoWindow

### ISSUE THREAD

**Issue by saikrishna321** [getgauge/taiko#1589]
**Describe the bug**

**WARNING: More than one intercept** is bloating the terminal as I'm using `intercept` API with beforeEach hook which has incognito session. 

**Expected behavior**
Clear the intercept listener in closeIncognitoWindow

**Versions:**
 - Taiko: 1.0.24
 - OS - MAC
 - Node.js - v14.8.0

**Comment by NivedhaSenthil** [comment]
Is there any particular reason why intercept is called in `beforeEach` instead of `before` ? 
Also [clearIntercept](https://docs.taiko.dev/api/clearintercept/) api can called anytime an intercept wants to be cleared...

Currently Taiko resets intercept on `closeBrowser`

**Comment by saikrishna321** [comment]
Question: Would intercept API called on openBrowser have effect on incognito window?

**Comment by saikrishna321** [comment]
>> Also clearIntercept api can called anytime an intercept wants to be cleared

This helps

**Comment by NivedhaSenthil** [comment]
>Would intercept API called on openBrowser have effect on incognito window?

yes.. currently it would
