### ISSUE TITLE
Should be able to navigate to the URL using goto on the instance of browser launched in the current run, not on the previously started browser instance. 

### ISSUE THREAD

**Issue by ShilpaGopal** [getgauge/taiko#159]
### Steps to reproduce
1. Make sure you have chromium instance running already
2. openBrowser()
 - this open new browser chromium instance
3. goto("some URL")
 - creates a new tab in the previously running chromium instance instead of the later one.

### Expected behavior
Should be able to create a new tab in the newly launched browser instance unless the user wants to connect to the existing browser instance. 

### Versions
taiko - 0.2.0

**Comment by NivedhaSenthil** [comment]
Fix should be available in a9ea9fa
