### ISSUE TITLE
Provide own browser and page

### ISSUE THREAD

**Issue by iofjuupasli** [getgauge/taiko#16]
Please, add methods to provide my own `browser` and `page` instances to taiko.
In my case browser created using `connect`, and page is created by using `Page.create` from puppeteer.
Such methods can be named `setBrowser`, `setPage`, or `setup({browser, page})`

**Comment by sguptatw** [comment]
**Expected behavior**
The default code generated with openBrowser() should work.

**Actual behavior**
Getting the following error
```
(node:40864) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Browser or page not initialized. Call `openBrowser()` before using this API
(node:40864) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Steps to replicate**
* start taiko
* openBrowser()
* .code something
* taiko something.js
Getting the above error

**Comment by sguptatw** [comment]
OS - Windows 10
npm version
```
{ 'gauge-js-template': '0.0.1',
  npm: '5.6.0',
  ares: '1.10.1-DEV',
  cldr: '31.0.1',
  http_parser: '2.7.0',
  icu: '59.1',
  modules: '57',
  nghttp2: '1.25.0',
  node: '8.9.4',
  openssl: '1.0.2n',
  tz: '2017b',
  unicode: '9.0',
  uv: '1.15.0',
  v8: '6.1.534.50',
  zlib: '1.2.11' }
```

**Comment by sguptatw** [comment]
Is this issue related to https://github.com/getgauge/taiko/issues/22

**Comment by NivedhaSenthil** [comment]
not relevant any more, as taiko is rewritten on top of chrome remote interface
