### ISSUE TITLE
Smart selectors fail to find search bar using text placeholder

### ISSUE THREAD

**Issue by rmallof** [getgauge/taiko#1624]
**Is your feature request related to a problem? Please describe.**
Smart selectors do not work when deal with search bar placeholders using text inside the bar as target
Related to https://github.com/getgauge/taiko/issues/1625

So, if you go to https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_search_placeholder and then run: _write("AAAA", textBox("Filter items"))_ - Taiko won't write into the search bar

Running: _write("AAAA", textBox({**placeholder**: "Filter items"}))_ - it'll work

_In the best case, the functionality already exists but I'm missing something - if so, I'd appreciate some pointers :)
**Describe the solution you'd like**
To be able to interact with elements with placeholders visually available

**Describe alternatives you've considered**
_write("AAAA", textBox("Filter items"))_ should work just like _write("AAAA", textBox({placeholder: "Filter items"}))_

**Additional context**
This is an example of the kind of input with placeholders:
![image](https://user-images.githubusercontent.com/3352772/97082256-acd32400-1608-11eb-9584-2418783068b9.png)

**Comment by roughsoft** [comment]
Lookforward this feature!

**Comment by saikrishna321** [comment]
@NivedhaSenthil  Currently, Taiko works only on _label_ in textBox

https://github.com/getgauge/taiko/blob/480cb4726d8afa05d235695eed34db7d6b33cdc6/lib/elementWrapper/textBoxWrapper.js#L21

`placeholder` attribute would be present only on _input_ tag. I'm thinking the current function https://github.com/getgauge/taiko/blob/480cb4726d8afa05d235695eed34db7d6b33cdc6/lib/elementWrapper/textBoxWrapper.js#L6

Will check with _label_ and _input_ tag for the given value. Thougts?

**Comment by zabil** [comment]
> Will check with label and input tag for the given value. Thougts?

This makes sense, because the placeholder is mostly used like a label for text fields. In most cases the label is ommitted when there is a placeholder. In case there is a label with the same text Taiko should pick the placeholder.

**Comment by rmallof** [comment]
Thank you @zabil @saikrishna321 - you rock!
