### ISSUE TITLE
Smart selectors fail to find search bar using placeholder

### ISSUE THREAD

**Issue by rmallof** [getgauge/taiko#1625]
**Describe the bug**
Smart selectors do not work when deal with search bar placeholders

**To Reproduce**
Steps (or script) to reproduce the behavior:
1. Go to https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_search_placeholder
2. Open Taiko
3. Run: write("AAAA", textBox("Filter items"))" - it won't work
4. Run: write("AAAA", textBox({placeholder: "Filter items"})) - it'll work

**Expected behavior**
write("AAAA", textBox("Filter items")) should work just like write("AAAA", textBox({placeholder: "Filter items"}))

**Screenshots**
![image](https://user-images.githubusercontent.com/3352772/97082349-3d116900-1609-11eb-9ce8-1872f803cd54.png)

**Versions:**
 - taiko: Version: 1.0.25 (Chromium: 87.0.4270.0) RELEASE
 - Node.js v12.19.0
 - Gauge version: 1.1.1

```
Gauge version: 1.1.1
Commit Hash: 6e0d83f

Plugins
-------
flash (0.0.2)
html-report (4.0.12)
js (2.3.12)
screenshot (0.0.1)
```

**Additional context**
I created a feature request for this just in case. If this is working as expected, please, I'd appreciate some pointers to the right way to do the above

Appreciated

**Comment by rmallof** [comment]
Related to: https://github.com/getgauge/taiko/issues/1624

**Comment by rmallof** [comment]
P.S.: I noticed that _textBox({placeholder:"Filter items"})));_ is case sensitive, while other smart selector methods are case insensitive

**Comment by zabil** [comment]
Closing this in favour of https://github.com/getgauge/taiko/issues/1624 (which is a feature request)

The textBox does not have placeholder based locators at the moment. `textBox({placeholder:"Filter items"})));` is an attribute selector and will be case sensitive. However, it should work for `write("AAAA", textBox("Filter items"))"` as this is how the user would see and record it.
