### ISSUE TITLE
Smart selectors(tableCell)  do not work when deal with table using text inside "td" tag in "thead" tab

### ISSUE THREAD

**Issue by roughsoft** [getgauge/taiko#1630]
Is your feature request related to a problem? Please describe.
Smart selectors(tableCell) do not work when deal with table using text inside "td" tag in "thead" tag

Smart selectors(tableCell) do work when deal with table using text inside "th" tag in "thead" tag

Describe alternatives you've considered
(text inside "td" tag in "thead" tag) should work just like (text inside "th" tag in "thead" tag)

**Comment by zabil** [comment]
To understand this better can you please provide a sample HTML and how you are using the `tableCell` API

**Comment by roughsoft** [comment]
sample html：
https://www.w3schools.com/code/tryit.asp?filename=GK6XI2TZCM21
tableCell({row:1, col:1}, "Month") 
do not work
sample html:
https://www.w3schools.com/code/tryit.asp?filename=GK6XLN2O9GHQ
tableCell({row:1, col:1}, "Month") 
do work

**Comment by roughsoft** [comment]
(text inside "td" tag in "thead" tag) should work just like (text inside "th" tag in "thead" tag)

**Comment by zabil** [comment]
Thanks for sharing the samples and patiently explaining this. 

`thead/tr/td` looks like a non-standard way of defining table header cells. 

On further reading https://www.w3.org/WAI/tutorials/tables/tips/ (under list Styling header cells) recommends to clearly differentiate between `th` and `td` in header and body. 

Taiko must fail in this case to show the accessibility issue. The application can fix this instead. I hope this makes sense.

**Comment by roughsoft** [comment]
thank you for your reply！
I see it，but as we know the application not under my control ,this thead/tr/td ,can render well in chrome browser.

**Comment by zabil** [comment]
Have you tried using `$()` selector for this specific case?

> can render well in chrome browser

That's true! Browsers are very tolerant of HTML issues. 
I recommend not fixing this for now and using the workaround.

**Comment by roughsoft** [comment]
@zabil ，@saikrishna321 
I suggest fixing this.
Because if we not fixing this ,it will hurt our taiko's vision-"Taiko's API is designed for testers. Unlike other testing frameworks, Taiko treats the browser like a black box. With Taiko you can write scripts by looking at a web page and without inspecting its source code."
You know I meet this table( https://www.w3schools.com/code/tryit.asp?filename=GK6XI2TZCM21),this table look the same as that table(https://www.w3schools.com/code/tryit.asp?filename=GK6XLN2O9GHQ),so if I can not select the table by `tableCell({row:1,` col:1}, "Month")
I will confused.

**Comment by zabil** [comment]
@roughsoft tables are tricky. A table can also be rendered using divs, multiple headers columns etc. 
For now the `tablecell` api is limited to cover only standard cases.
