### ISSUE TITLE
document about Selenoid+taiko

### ISSUE THREAD

**Issue by roughsoft** [getgauge/taiko#1649]
If we can documenting the detail about Selenoid+taiko ,it would be great.
We know it is not so easy.

**Comment by saikrishna321** [comment]
Do you think a plugin for selenoid would help or just the documentation?

**Comment by roughsoft** [comment]
plugin is great！
code is more than documentation.
@saikrishna321

**Comment by saikrishna321** [comment]
I started with the plugin and stopped half-way! Will finish the plugin and publish to npm

**Comment by saikrishna321** [comment]
@roughsoft Plugin for Selenoid is published https://github.com/saikrishna321/taiko-selenoid

**Comment by roughsoft** [comment]
Great job！
@saikrishna321
