### ISSUE TITLE
waitFor passes retryInterval in as retryTimeout

### ISSUE THREAD

**Issue by carpeliam** [getgauge/taiko#1661]
`waitFor` calls `ElementWrapper.elements` with three parameters: `undefined`, `retryInterval`, and `retryTimeout`. However, `ElementWrapper.elements` only takes two, which means that `elements` is getting called with an undefined value for `retryInterval` and a `retryTimeout` equal to whatever the retry interval was.

This results in `waitFor` not waiting long enough if I have a small `retryInterval` but a relatively large `retryTimeout`.

**To Reproduce**
Steps (or script) to reproduce the behavior:
1. Run `waitFor.test.js` mocha test with a breakpoint within the elements method 
2. Observe that `retryInterval` is undefined, and `retryTimeout` is equal to what `retryInterval` should be

**Expected behavior**
`retryInterval` will be passed as first argument to `ElementWrapper.elements`, and `retryTimeout` will be passed as the second argument.

**Screenshots**

**Versions:**
 - Taiko: latest commit on master

**Comment by carpeliam** [comment]
Current workaround:
```js
const retryInterval = getConfig('retryInterval');
setConfig({ retryInterval: getConfig('retryTimeout') });
await waitFor('whatever it might be that needs waiting');
setConfig({ retryInterval });
```

**Comment by NivedhaSenthil** [comment]
`waitFor` calls elements from [match](https://github.com/getgauge/taiko/blob/44e90ed63357fbb16f4d8660ec4717117418a4bc/lib/elementSearch.js#L170) which takes three args (tag, retryInterval and retryTimeout), since tag is not needed from waitFor it is passed as undefined. I could see retryTimeout is applied properly in below example. Can you please verify again and let us know if you seeing something differently ?

```
(async () => {
    try {
        await openBrowser();
        let startTime = Date.now();
        await waitFor("something").catch(()=>{});
        console.log(Date.now()-startTime);
        await setConfig({retryTimeout:30000});
        startTime = Date.now();
        await waitFor("something").catch(()=>{});
        console.log(Date.now() - startTime);
    } catch (error) {
        console.error(error);
    } finally {
        await closeBrowser();
    }
})();
```

Output:
```
 ✔ Browser opened
10018
30007
 ✔ Browser closed
```

Note after updating retryTimeout second console log shows the updated value.

**Comment by carpeliam** [comment]
@nandhae you're right, if the argument is a string :) but if it's a selector, e.g. `waitFor(button('Click me'))`, then it calls [ElementWrapper.elements](https://github.com/getgauge/taiko/blob/master/lib/elementWrapper/elementWrapper.js#L165), which doesn't have a `tag`. I'm sorry that my example code wasn't accurate, I didn't realize that `match` doesn't return an `ElementWrapper`.

Here's your example but with a selector instead of a string:
```js
(async () => {
    try {
        await openBrowser();
        let startTime = Date.now();
        await waitFor(text("something")).catch(()=>{});
        console.log(Date.now()-startTime);
        await setConfig({retryTimeout:30000});
        startTime = Date.now();
        await waitFor(text("something")).catch(()=>{});
        console.log(Date.now() - startTime);
        await setConfig({retryInterval:10000}); // as retryInterval is passed as retryTimeout
        startTime = Date.now();
        await waitFor(text("something")).catch(()=>{});
        console.log(Date.now() - startTime);
    } catch (error) {
        console.error(error);
    } finally {
        await closeBrowser();
    }
})();
```
Output:
```
✔ Browser opened
3120
3111
13867
 ✔ Browser closed
```

So, the path through the code that works with a string works fine, but the path through the code that accepts a selector doesn't wait as long.

**Comment by NivedhaSenthil** [comment]
Yes, thanks for pointing that out :) will be happy to review you a PR
