### ISSUE TITLE
Running taiko (with chrome) from WSL2

### ISSUE THREAD

**Issue by valentijnscholten** [getgauge/taiko#1666]
Hi,

I'm doing most of my development on WSL2, so would like to do the same for writing tests in taiko. Running Ubuntu20.04 on WSL2.

`sudo npm install -g taiko`

succeeds

`taiko`

succeeds

`openBrowser()`

fails:

```
> openBrowser()
 ✘ Error: Chromium revision is not downloaded. Provide TAIKO_BROWSER_PATH or Install taiko again to download bundled chromium., run `.trace` for more info.
```

So it doesn't seem to install chromium. Anyway, I'd like to use chrome which is installed in the windows host system.

```
export TAIKO_BROWSER_PATH=/mnt/c/Program\ Files\ \(x86\)/Google/Chrome/Application/chrome.exe
taiko
openBrowser()
```

This opens chrome on windows. Shows some warnings about userprofile (which might be OK).
But taiko cannot connect after starting:

```
 ✘ Error: connect ECONNREFUSED 127.0.0.1:37908, run `.trace` for more info.
````

I tried making host and port explicit. host.docker.internal is the hostname for the windows host, which resolves OK inside WSL and on Windows itself. I opened port 12345 in the windows firewall.

```
> openBrowser({headless: false, host:'host.docker.internal', port: 12345, args: ['--remote-debugging-address=host.docker.internal', '--remote-debugging-port=12345']})
```

Nothing happens. Taiko just seems to hang (which may indicate a network issue conntecting to the host). Same for `headless: true`.

Anybody able to get it work with WSL2?

**Comment by zabil** [comment]
Hey @valentijnscholten can we first discuss this at https://spectrum.chat/gauge ? There are more chances of finding help there as this seems to be an issue with environment. If it is indeed an issue this can be re-opened with all sections of the issue template filled up.

**Comment by valentijnscholten** [comment]
Created https://github.com/getgauge/taiko/discussions/1761 now that Taiko moved from Spectrum to Github Discussions.

**Comment by GaTechThomas** [comment]
Taiko/Gauge seem awesome on paper, but items like the one described in this thread have plagued me every step along the way. It absolutely is not ready for prime time, not until it has clear instructions with clear steps that really work. There's a Saturday I'll never get back.
