### ISSUE TITLE
Readable mechanism to deal with "buttons" based on css, divs and spans

### ISSUE THREAD

**Issue by rmallof** [getgauge/taiko#1676]
**Is your feature request related to a problem? Please describe.**
I find hard to create readable selectors when dealing with pages using CSS or other drawings resembling buttons - see the screenshot below

I tend to copy-paste Xpath selectors from Chrome in this case, resulting in something like: 

`click($('//*@id="69540"]/label/div[2]/span'))
`

**Describe the solution you'd like**
I'd like to use other selectors than $ or even proximity selectors for clicking these "buttons"

**Describe alternatives you've considered**
Looking for elements with a class containing some text, but not sure what's the most readable approach here.
I've seen solutions for links, like: 

`click(link({"class":"options-button"}))
`

**Additional context**
![image](https://user-images.githubusercontent.com/3352772/98862071-93cecd80-2466-11eb-801c-a2145c500067.png)
![image](https://user-images.githubusercontent.com/3352772/98862483-443cd180-2467-11eb-8fe6-1fcf40de040f.png)

I'd appreciate any pointers or workarounds that I could apply now
Thank you! ❤

**Comment by rmallof** [comment]
Maybe related to https://github.com/getgauge/taiko/issues/89

**Comment by zabil** [comment]
```
click(link({"class":"options-button"}))
```

Searches for an attribute string. 

To match based on css please use [css selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors) in your case this will be

```
click(link($(".options-button")))
```

More info at [$](https://docs.taiko.dev/api/$/)

**Comment by rmallof** [comment]
Thanks for the quick response. For the record, the correct syntax is: click($(".options-button")):

```
> click(link($(".options-button")))
Uncaught You are passing a `ElementWrapper` to a `link` selector. Refer https://docs.taiko.dev/api/link/ for the correct parameters
```

@zabil It is possible to use proximity selectors instead of $?

**Comment by zabil** [comment]
From the screenshots you shared you could try something like

```
click(listItem(toRightOf("Web Canvas")))
```

I am note sure as I do not have the full structure of the application.

Also, you might want to pop this question at https://spectrum.cat/gauge there are a few users who might be able to help.

**Comment by rmallof** [comment]
Thank you Zabil, I'll investigate 👍
