### ISSUE TITLE
friendly upload and download API

### ISSUE THREAD

**Issue by roughsoft** [getgauge/taiko#1690]
**Is your feature request related to a problem? Please describe.**
https://docs.taiko.dev/file_upload_and_download/
It is so ugly code

**Describe the solution you'd like**
why not design API like these：
upload(fileField(selector),fileName,selector for upload button )
download(selector ,fileName)
fileName can include path

**Describe alternatives you've considered**
https://tagui.readthedocs.io/en/latest/index.html
download https://admin.typeform.com/xxx to report.csv

**Additional context**

**Comment by zabil** [comment]
The uploading a file has two parts in a web application

* Attaching a file location with a specific local path
* Clicking on a button to post the attached file and confirm the upload

in code as follows

```
await attach(path.join(__dirname, 'data', 'foo.txt'), 
        fileField(above(button('Upload'))));
click(button('Upload')):
```
Also file field is sometimes hidden under another front end hence the use of proximity selectors covers those cases. 

You api suggestion, clubs both these actions together 

```
upload(fileField(selector),fileName,selector for upload button )
``` 
which does not cover all use cases efficeintly. If you see it repeating in your tests, you can probably extract is as a method and reuse it. 

A download action is actually dependent on how the application treats a specific link. The server sets the mime type for a resource to indicate that it should be downloaded. The user has to just click a link. 

The following part 

```
await client().send('Page.setDownloadBehavior', {
    behavior: 'allow',
    downloadPath: downloadPath,
    });
```

Is to set a global download location, and allow downloads. It's been disabled by default to avoid security issues. The actually download code is what you see further down which is simply

```
await click('foo.txt');
```

The rest of the code is just assertion code for reference on how to access the downloaded file. 
This IMHO is actually simpler than

```
download(selector ,fileName)
```

as `download(selector ,fileName)` is ambiguous as the selector can be any element regardless of whether it can be downloaded or not.
