### ISSUE TITLE
using index selector element

### ISSUE THREAD

**Issue by roughsoft** [getgauge/taiko#1703]
**Is your feature request related to a problem? Please describe.**

There are 13 links on the page.The name is the same.
How can I select the 13th link?

**Describe the solution you'd like**

link(12) | Using index in the page; assuming it is the 13th link on the page.
link(0, near("User Two"))

**Describe alternatives you've considered**

**Additional context**

**Comment by NivedhaSenthil** [comment]
`await link().elements()` will return all the links in the page, for more examples refer https://docs.taiko.dev/working_with_element_lists/

**Comment by roughsoft** [comment]
thank you !
I know it.
If we could support these selector policy ,it can make life better.
link(index)
link(index,proximity selectors)

**Comment by roughsoft** [comment]
> link().element(1)
Element {
  objectId: '-5335921367651143915.2.712',
  description: '',
  runtimeHandler: {
    findElements: [AsyncFunction: findElements],
    activeElement: [AsyncFunction: activeElement],
    runtimeEvaluate: [AsyncFunction: runtimeEvaluate],
    runtimeCallFunctionOn: [AsyncFunction: runtimeCallFunctionOn]
  }
}
> link().element(1).exists()
Uncaught link(...).element(...).exists is not a function

**Comment by roughsoft** [comment]
@NivedhaSenthil 
In repl console I try these statement:
link().element(1)
It is ok!
When I try these:
link().element(1).exists()
I get error:
Uncaught link(...).element(...).exists is not a function

**Comment by NivedhaSenthil** [comment]
link().element(1) this is an asyncs func which has to be awaited `await (await link().element(1)).exists()`

**Comment by roughsoft** [comment]
ok
If we can support these statement:
textBox(index)
textBox(index,proximity selectors)
It would be awesome!
You know we often need fill a lot of input fields in table ,in these situation we can not selector .
sometimes we can not select table, then we would be in trouble

**Comment by zabil** [comment]
Unfortunately Taiko's API cannot be changed to add another parameter like `index` as this will break backward compatibility. 

Using 

```
async textBox(selector).element(1);
```

Should be the best option.

**Comment by zfrk** [comment]
> link().element(1) this is an asyncs func which has to be awaited `await (await link().element(1)).exists()`

@NivedhaSenthil I tried this but also I am getting an error.
Uncaught (intermediate value).exists is not a function
![image](https://user-images.githubusercontent.com/9010753/111435592-0a7c2000-8712-11eb-9fb2-a49a491797ca.png)
![image](https://user-images.githubusercontent.com/9010753/111435641-14058800-8712-11eb-8b30-df9c7ca5511f.png)

**Comment by NivedhaSenthil** [comment]
What is the result you are getting for `await button('Check Out').element(0)` is the element present while processing ?

**Comment by zfrk** [comment]
element result is ok but the existence part does not work.

![image](https://user-images.githubusercontent.com/9010753/111834159-3e1e9c00-8904-11eb-8d0d-ddc7ab79c943.png)

> await button('Check Out').element(0)
Element {
  objectId: '-5915700874441622357.4.52',
  description: 'Button with label Check Out ',
  runtimeHandler: {
    findElements: [AsyncFunction: findElements],
    runtimeEvaluate: [AsyncFunction: runtimeEvaluate],
    runtimeCallFunctionOn: [AsyncFunction: runtimeCallFunctionOn]
  }
}

**Comment by zfrk** [comment]
The existence method takes place under elementwrapper. That's the reason, isn't it?

![image](https://user-images.githubusercontent.com/9010753/111834655-f77d7180-8904-11eb-9f81-6f3a5ab97c82.png)





![image](https://user-images.githubusercontent.com/9010753/111834538-cb61f080-8904-11eb-8741-74acbb4aabfd.png)
