### ISSUE TITLE
Highlighting is off [Windows]

### ISSUE THREAD

**Issue by srp-at-ema** [getgauge/taiko#1704]
### Describe the bug
Highlighting is off as you can see on the attached .GIF
### What command(s) did you run when you found the bug?
`mkdir ptg`
`cd ptg`
`gauge init js`
open the `ptg` folder in vscode
`npm init`.
I click on `Run Spec` above *# Getting Started with Gauge*
### Output, stack trace or logs related to the bug
![highlight4](https://user-images.githubusercontent.com/68943060/100258848-d0f78d00-2f47-11eb-98b0-8d5e4d9e4515.gif)

Maybe related is the following output from `gauge init js`:
```
-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

  Verion 9 of Highlight.js has reached EOL.  It will no longer
  be supported or receive security updates in the future.
  Please upgrade to version 10 or encourage your indirect
  dependencies to do so.

  For more info:
  https://github.com/highlightjs/highlight.js/issues/2877
  https://github.com/highlightjs/highlight.js/blob/master/VERSION_10_UPGRADE.md

-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*                                              
```
#### Gauge (Output of `gauge -v`)
```
gauge -v
Gauge version: 1.1.5
Commit Hash: f455126

Plugins
-------
html-report (4.0.12)
js (2.3.14)
screenshot (0.0.1)
```
#### Node.js/Java/Python/.Net/Ruby version
```
node -v
v14.15.1
```
#### Operating System information
```
Get-ComputerInfo -Property os* | select OSName, OsArchitecture | fl

OsName         : Microsoft Windows 10 Pro
OsArchitecture : 64-bit
```
#### IDE information
```
code-insiders.cmd --version
1.52.0-insider
6026ab576dc6a4fbb8e255241a364816f42464c5
x64
```

**Comment by zabil** [comment]
![Kapture 2020-11-25 at 14 34 41](https://user-images.githubusercontent.com/54427/100241442-97b12400-2f2b-11eb-86b7-6dae74158283.gif)

I am unable to replicate this on windows. Was this one off or do you see it happening again? As the page does not seem to render correctly, it could've been a network issue. Can you please confirm that you see this consistently?

**Comment by srp-at-ema** [comment]
I see that everytime.

**Comment by srp-at-ema** [comment]
Do you have any idea in which direction to investigate? Both computers run Windows.

**Comment by zabil** [comment]
If you have chrome or chromium installed on the machine can you try opening https://todo.taiko.dev and inspecting the browser console or network tabs (in developer tools) to see if there are any errors? Also to see if the page is rendered correctly with reference to the screen grab I posted.

**Comment by srp-at-ema** [comment]
I see what you mean with not rendering. I had lowered the quality of the GIF before uploading it. Opening https://todo.taiko.dev/ in Chrome and it's looking good.

**Comment by srp-at-ema** [comment]
I see the same two errors in the Chrome console whether I open the https://todo.taiko.dev/ in Chrome or I quickly do a F12 when the test is executing. Nothing more, nothing less.

**Comment by zabil** [comment]
> I see the same two errors

What's the exact error you see on the console?

**Comment by srp-at-ema** [comment]
![image](https://user-images.githubusercontent.com/68943060/100253332-414ee000-2f41-11eb-8481-d0e5fb46d235.png)

**Comment by srp-at-ema** [comment]
I modified the example to use google and enter a search term. Same problem, the highlight is below to the right.
![highlight2](https://user-images.githubusercontent.com/68943060/100255864-5a0cc500-2f44-11eb-8a01-283de289addc.gif)

**Comment by zabil** [comment]
> I see that every time, but it's bound to one machine.

Ok, that's very strange. Can you try deleting the `node_modules` folder so that the latest versions of chromium and taiko is downloaded again?

**Comment by srp-at-ema** [comment]
I modified the example to use google and enter a search term. Same problem, the highlight is below to the right.
![highlight3](https://user-images.githubusercontent.com/68943060/100257431-30549d80-2f46-11eb-9aa7-d8ec1abb6963.gif)

**Comment by srp-at-ema** [comment]
This last shot is from a different project than the initial one. After deleting `node_modules`, am I supposed to `npm init` or something else? For when I call `gauge run specs` it is not working anymore.

**Comment by zabil** [comment]
You can get all the dependencies back after running

```
npm install
```
In your project folder.

**Comment by srp-at-ema** [comment]
So I did exactly that (`npm install`). But as expected it has not changed much.

**Comment by srp-at-ema** [comment]
Thanks for your help by the way. Much appreciated. And it's no high prio, as it works in my work remote environment, just not on my own laptop.

**Comment by srp-at-ema** [comment]
I found it! I have a 4k screen:
![image](https://user-images.githubusercontent.com/68943060/100260088-4e6fcd00-2f49-11eb-8982-5d7846e0b75c.png)

**Comment by srp-at-ema** [comment]
If I go to 100% it's ok.

**Comment by srp-at-ema** [comment]
Is that a bug or a limitation? Thank you.

**Comment by zabil** [comment]
Oh wow, good catch. This should not be happening, it could be a bug. Will take a look at it soon.

**Comment by zabil** [comment]
Closing this as the zoom value  should be 100% for the highlight to work.
