### ISSUE TITLE
Cannot navigate to non http url

### ISSUE THREAD

**Issue by Willmiff** [getgauge/taiko#1720]
**Describe the bug**
When trying to navigate to a page hosted as part of a chrome extension, taiko adds http before the url is passed to the browser, so navigating to chrome-extension://gjaerjgaerjeoareapoj/internalPage.html becomes http://chrome-extension://gjaerjgaerjeoareapoj/internalPage.html

If you debug it, and set the url back to chrome-extension://gjaerjgaerjeoareapoj/internalPage.html after taiko has modified it, everything works just fine.

**To Reproduce**
Steps (or script) to reproduce the behavior:

```
await goto('chrome-extension://gjaerjgaerjeoareapoj/internalPage.html')
```

**Expected behavior**
There should be some way to override the default url manipulation. 

**Screenshots**

**Versions:**
 - Taiko: 1.0.28
 - OS Windows 10 [Version 10.0.18363.1198]
 - Node.js 14.15.0

```
gauge -v
Gauge version: 1.1.5
Commit Hash: f455126

Plugins
-------
html-report (4.0.12)
screenshot (0.0.1)
ts (0.1.0)
```

**Comment by zabil** [comment]
@Willmiff this change is now available in `master` you can test it out using

```
npm install https://github.com/getgauge/taiko
```
