### ISSUE TITLE
Text Box with label not found

### ISSUE THREAD

**Issue by gurashish-relicx** [getgauge/taiko#1744]
Taiko is unable to write a text into a textBox with a user visible label in some cases.

HTML of the element in question
`
<input class="form-control" placeholder="Department Name" autofocus="autofocus" type="text" name="department[name]" id="department_name">
`

**To Reproduce**
Steps (or script) to reproduce the behavior:
```
const { openBrowser, goto, click, textBox, into, write, closeBrowser } = require('taiko');
(async () => {
    try {
        await openBrowser();
        await goto('https://surveyor-appl-prod.herokuapp.com/departments');
        await click('Add Department');
        // This commands fails to find the textBox
        await write('Marketing', into(textBox('Department Name')));
        //  ✘ Error: TextBox with label Department Name  not found, run `.trace` for more info.
        // we are able to find the element by Id however
        await write('Marketing', into(textBox({id:'department_name'})));
    } catch (error) {
        console.error(error);
    } finally {
        await closeBrowser();
    }
})();
```

The following script for a similar element but a different page works fine
HTML element:
`
<input class="form-control" placeholder="Insurer Name" autofocus="autofocus" type="text" name="insurance[name]" id="insurance_name">
`
Script for discovering and writing by label (this works)
```
(async () => {
    try {
        await openBrowser();
        await goto('https://surveyor-appl-prod.herokuapp.com/insurances');
        await click('Add Insurance');
        // This case Taiko is able to discover the textBox by label
        await write('Pemco', into(textBox('Insurer Name')));
    } catch (error) {
        console.error(error);
    } finally {
        await closeBrowser();
    }
})();
```

**Expected behavior**
Taiko should have been able to discover the element by placeholder text in the element, which is visible to the user

**Versions:**
 - Taiko: Version: 1.1.0 (Chromium: 88.0.4314.0) RELEASE
 - OS: macOS Catalina 10.15.7 (19H2)
 - Node.js v15.3.0

**Comment by zabil** [comment]
Thanks for the detailed report. I can replicate this. But I am sure this is because of the following structure

```
<div class="col-sm-2 control-label">
 <label for="department_department_name">Department name</label>
</div>
<div class="col-sm-8">
 <input class="form-control" 
     placeholder="Department Name" 
     autofocus="autofocus" type="text" 
     name="department[name]" id="department_name">
</div>
```

Notice the `<label for="department_department_name">Department name</label>` points to an invalid inout text id. It must be`<label for="department_name">Department name</label>`

In this case Taiko pointed out to a failure in the accessibility of the page and wrong html sematic. Which ideally is valid and this page is likely to break on screen readers.

**Comment by gurashish-relicx** [comment]
Thanks Zabil for the analysis. I verified that the issue goes away when I
corrected the label
>
> <label for="department_name">Department name</label>


I think you are right in this case the test should fail.

However the error message is not very intuitive, atleast to naive eyes. It
wasnt obvious to me, and I believe most testers would think the page is
fine and the bug is in the test infra.

If we have a better message showing that the id "department_department_name"
accessibility hint in label does not exist, then it would be easier to
convince the developer/tester to accept the bug is in their page and not a
fault of the test infra.

Thanks
Gurashish

**Comment by zabil** [comment]
> If we have a better message showing that the id "department_department_name"

Ideally yes. But this is pretty hard to print out in the current implementation as the selector logic fails and Taiko does not read the values. Taiko does expect semantically correct HTML. 

The right way to actually do this is running [lighthouse](https://www.npmjs.com/package/lighthouse) or [axe-core](https://www.npmjs.com/package/axe-core) on the page to point these issues and then running Taiko scripts.
