### ISSUE TITLE
[DOC] URL https://docs.taiko.dev/api/focus no longer found (HTTP 404)

### ISSUE THREAD

**Issue by klhex** [getgauge/taiko#1789]
**Describe the bug**
Trying to access the URL https://docs.taiko.dev/api/focus (from within https://docs.taiko.dev/api/reference/) leads to an HTTP 404 error (page not found).

**To Reproduce**
Steps (or script) to reproduce the behavior:
1. Go to https://docs.taiko.dev/api/reference/
2. Locate 'focus' entry and click on it.

**Expected behavior**
API documentation for page action 'focus' is shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/71178731/104431969-cf7e3480-5588-11eb-9705-aa183a8499e2.png)

**Comment by zabil** [comment]
Fixed with 58994f8
