### ISSUE TITLE
Detect no display and default to headless mode in taiko REPL

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#179]
**Proposed behavior**
Detect no display and default to headless mode in taiko REPL

**Current behavior**
* Checkout the example project https://github.com/getgauge-examples/js-taiko
* Build docker `docker build . --tag test`
* Run docker in bash `docker run -t test bash`
* Run taiko in REPL `taiko`
* openBrowser()
> The REPL hangs

**Version**
```
commit - eb776a3e0aac915c63c0a8a77c6de8ffc2ccfed8
```

**Comment by BugDiver** [comment]
This can be achieved by simply adding `headless` option to `openBrowser` API.
Ex. `openBrowser({headless:true})`

For docker it would be `openBrowser({headless: true, args: ['--no-sandbox', '--disable-setuid-sandbox']});`
