### ISSUE TITLE
New targets (popups) not properly attached

### ISSUE THREAD

**Issue by Niek** [getgauge/taiko#1790]
**Describe the bug**
New targets such as popups are not properly attached. Here is some sample REPL:

```js
> openBrowser()
 ✔ Browser opened
> emulateDevice('iPhone 6')
 ✔ Device emulation set to iPhone 6
> goto('https://server.niekvandermaas.nl/crbug1070568.html')
 ✔ Navigated to URL https://server.niekvandermaas.nl/crbug1070568.html
> click(text('Click me to test.'))
 ✔ Clicked element with text Click me to test.  1 times
```

**Expected behavior**
The newly opened tab should have the iPhone 6 user agent as well. Instead, it gets the non-emulated device user agent.

**Versions:**
 - Taiko: 1.1.2
 - OS: macOS 11
 - Node.js: v15

**Comment by zabil** [comment]
This seems to be the default behavior for new windows opened outside the emulation mode when using chromium devtools. The workaround would be call `emulate` again to set the view port.
