### ISSUE TITLE
click(link(...)) not working when link text is line wrapped?

### ISSUE THREAD

**Issue by klhex** [getgauge/taiko#1792]
**Describe the bug**
I have several links within a text section (belonging to a checkbox):
![image](https://user-images.githubusercontent.com/71178731/104649405-f76ab680-56b4-11eb-8f4c-e4d194f17be5.png)
I can successfully click (new tab opens with linked PDF file) on every link via ```click(link(...))``` like so (one example):

```await click(link('Sonderbedingungen zum Girokonto'));``` etc.

except for the first one "Allgemeinen Geschäftsbedingungen" where

```await click(link('Allgemeinen Geschäftsbedingungen'));``` 

seems to click the entire two lines which include the link text but not the actual link and therefore does not open the linked PDF file.

My assumption is that the click(link()) on "Allgemeinen Geschäftsbedingungen" does not work because the link text is wrapped over two lines as you can see in the screenshot above.

**To Reproduce**
Here's the corresponding HTML code (FQDNs, file/folder names removed/changed):
```html
<label class="c-checkbox"><input id="terms-checkbox" name="termsAgreed" class="c-checkbox__input"
        type="checkbox" /><span class="c-checkbox__label">Ich habe die folgenden Informationen der Bank GmbH
        heruntergeladen: Die
        <a href="https://[FQDN]/AGB.pdf" target="_blank">Allgemeinen
            Geschäftsbedingungen</a>, die
        <a href="https://[FQDN]/folder/Giro_Bed.pdf"
            target="_blank">Sonderbedingungen zum Girokonto</a>, die
        <a href="https://[FQDN]/folder/GK_Online.pdf"
            target="_blank">vorvertraglichen Informationen</a>
        inkl. der Informationen nach den Vorschriften des Fernabsatzes und der
        Widerrufsbelehrung, die
        <a href="https://[FQDN]/folder/Entgeltinformation.pdf"
            target="_blank">Entgeltinformation</a>, sowie die
        <a href="https://[FQDN]/folder/I_GK_Online.pdf"
            target="_blank">europäischen Verbraucherinformationen bei Überziehungskrediten</a>.&nbsp;*</span></label>
```

Repro case test code can also be provided (via mail or personal chat) if necessary.

**Expected behavior**
```click(link(...))``` also opens the link with the text "Allgemeinen Geschäftsbedingungen" and the linked PDF file is accessed.

**Versions:**
 - Taiko: 1.1.2
 - OS macOS 11.1 (20C69)
 - Node.js v14.13.1

**Additional context**
This issue looks similar (or maybe it's the same thing?) to https://github.com/getgauge/taiko/issues/366.

While the workaround mentioned in issue #366 (focus(), then press 'Enter') works here as well, I think it should work in the original way (click/link) also.

**Comment by NivedhaSenthil** [comment]
Closing as we wont be able fix this..please use the workaround
