### ISSUE TITLE
Incomplete support for event 'targetNavigated' (DOC / Typescript)

### ISSUE THREAD

**Issue by klhex** [getgauge/taiko#1797]
**Describe the bug**

1. If you're trying to use the code example ```await click(link('open new tab'),{waitForEvents:['targetNavigated']})``` from https://docs.taiko.dev/frequently_asked_questions/#how-can-i-customize-taiko's-wait-events%3F in Typescript, then you get the following error message upon compilation: "TS2322: Type '"targetNavigated"' is not assignable to type 'BrowserEvent'."

2. It is currently not listed in the test code of ```click()``` in types/taiko/test/page-actions.ts.

3. The value "targetNavigated" is currently not listed in the [documentation](https://docs.taiko.dev/api/click) of the ```click()``` api:
![image](https://user-images.githubusercontent.com/71178731/104813322-c4393c00-5808-11eb-8516-59f883bb9e6f.png)

**To Reproduce**
1. https://github.com/getgauge/taiko/blob/2af5fb3f9575048991c540cf070be5e50e652907/types/taiko/index.d.ts#L10-L17
2. https://github.com/getgauge/taiko/blob/2af5fb3f9575048991c540cf070be5e50e652907/types/taiko/test/page-actions.ts#L152-L179
3. https://github.com/getgauge/taiko/blob/2af5fb3f9575048991c540cf070be5e50e652907/lib/taiko.js#L902

**Expected behavior**
'targetNavigated' is accepted as valid value for option 'waitForEvents' in ```click()```.

**Versions:**
 - Taiko: 1.1.3

**Additional context**
If the locations listed above are the only ones where support for targetNavigated is missing, I could raise a PR for adding it to there. But maybe it would also have to be added to the documentation/test code of ```goBack(), goForward(), reload(), openTab(), closeTab(), openIncognitoWindow(), closeIncognitoWindow(), goto(), press(), mouseAction(), tap(), evaluate()``` ?

**Comment by NivedhaSenthil** [comment]
yes, `targetNavigated` event can be added to all api that accepts `waitForEvents` as an option. Will be happy to review a PR 👍

**Comment by klhex** [comment]
Thanks for the information, that sounds feasible for me. Will give it a try most likely this week (incl. week-end). :thumbsup:
