### ISSUE TITLE
Code of action performed on the focused element should give the selector

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#18]
**Proposed behavior**
The .code of actions performed should give the selector used.

**Current behavior**
It gives only the user specified parameters

**Example of proposed behavior**
* start taiko
* openBrowser()
* goto("google.com")
* write("something")
* .code
Now the .code has `write("something")`
instead it can give `write("something","selector_used")

**Version**
```
taiko - 0.0.9
```

**Comment by NivedhaSenthil** [comment]
If taiko has to do this, the behaviour of the script might vary from that of REPL as `write('something')` will write into the element whichever has focus which can change depending on the application, but if we add the selector it will always write into the particular selector even if it is not the one that has default focus.
