### ISSUE TITLE
Taiko should work with Windows

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#180]
**Expected behavior**
Taiko should work on Windows OS

**Actual behavior**
When taiko is executed on bash, it exits and comes back to the bash.

**Steps to replicate**
* globally install
* Run the command `taiko` 
> It exits and returns to the bash

**Version**
```
commit - ef1c0db432e86a4328961b31fddeaafdefab07b7
```
Blocks https://github.com/getgauge/taiko/issues/166

**Comment by Apoorva-GA** [comment]
Fix should be available in commit 09afc93.
