### ISSUE TITLE
Ability to set waitForEvents in config, add LargestContentfulPaint

### ISSUE THREAD

**Issue by orsi-crey** [getgauge/taiko#1831]
**Is your feature request related to a problem? Please describe.**
I had a problem where a page was seemingly completely loaded, but I still got the error of Navigation took more than 30000ms. I tried setting it higher with the same result. It seemed like the firstMeaningfulPaint event never arrived. When I changed to firstContentfulPaint, the problem stopped.
Also, I couldn't see it on the Performance tab of chrome dev tools, and it seems like it'll be changed to LargestContentfulPaint as per https://web.dev/first-meaningful-paint/

**Describe the solution you'd like**
I'd like to be able to set waitForEvents in setConfig, not just whether waitForNavigation is true or false but which event should be the default for all actions that use waitForEvents.
Additionally, if largestContentfulPaint would be added or maybe even set as default, that might be nice.

**Describe alternatives you've considered**
As workarounds, I can set waitForEvents false in setConfig, and letting a bigger interval for other functions to locate elements, or wrap all needed functions in another function that just adds firstContentfulPaint as a waitForEvents item.

**Additional context**
E.g checking github on the devtools tab:
![image](https://user-images.githubusercontent.com/58974927/106281111-12096780-623f-11eb-8537-b41823be4a69.png)

**Comment by CDFriend** [comment]
+1 to this!

**Comment by NivedhaSenthil** [comment]
Can you please let us know which version of Taiko you are on ? Taiko has moved way from waiting for `firstMeaningfulPaint` long back since that hypothesis dint work out. Currently taiko wait for page load and other network calls. If you are on latest version of Taiko please check if there were any unresolved requests. 

Adding waitForEvents as part of `setConfig` can be a good option, will be happy to review a PR.

**Comment by orsi-crey** [comment]
Sure, sorry i forgot to add. Locally it was a bit behind (1.0.28), but in azure it always ran with the latest release (so currently 1.2.0, or when I last had the 30000ms timeout it was 1.1.4). I've checked https://docs.taiko.dev/api/goto/ for the default value, maybe it's outdated?
Changing goto to firstContentfulPaint seems to stop the issue so far.

**Comment by NivedhaSenthil** [comment]
Thanks for pointing that out, yes docs seems outdated.

**Comment by CDFriend** [comment]
I can take a look at this one in the next couple of days. 

@NivedhaSenthil @orsi-crey Did we want to set LargestContentfulPaint as the default for waitForEvents moving forward?

**Comment by CDFriend** [comment]
@orsi-crey I just created a draft pull request which allows the default WaitForEvents parameter to be set globally in `setConfig`.

I had a couple documentation questions before publishing the PR:
1. Currently we state that `waitForEvents` has a default value of `firstMeaningfulPaint`. Looking at the code, the default value is actually undefined, meaning "just wait for the navigation event". Should we change the docs so these say `[]` instead?
2. Should we be indicating somehow that `waitForEvents` and `waitForNavigation` will default to the parameters in the Taiko config if unspecified?

**Comment by orsi-crey** [comment]
@CDFriend wow, thanks!! :) 
I agree it would be good to update the docs with both points, although I'm a bit confused which event does it actually wait for then?

**Comment by CDFriend** [comment]
Looking at the `doActionAwaitingNavigation` function, there's no default for the `waitForEvents` parameter. When we don't pass in a set of events, we go down a different code path and wait for `target-nagivated` from the browser. 

![2021-02-10 08_51_41-doActionAwaitingNavigation js - taiko - Visual Studio Code](https://user-images.githubusercontent.com/8661121/107542773-61c02b00-6b7d-11eb-9204-a449e5fe104f.png)

Based on this, I think the default `waitForEvents` parameter should be listed as `[]`.

@NivedhaSenthil apologies, I meant to tag you in my questions above. Should we be adjusting the documentation for the waitForEvents parameter?

**Comment by NivedhaSenthil** [comment]
yes @CDFriend Taiko don't wait for lifecycle events now by default...navigation wait checks if the document readyState is `complete` to resolve https://github.com/getgauge/taiko/blob/c0eef59e0bd917e16a7880c3f71502c77de5ba90/lib/doActionAwaitingNavigation.js#L126, this logic can stay as is and we could just provide an option to set waitForEvents as a global config and update the outdated docs accordingly. Hope this helps

**Comment by NivedhaSenthil** [comment]
Closing as we can set `waitForEvents` as a global settings from Taiko 1.2.1

**Comment by orsi-crey** [comment]
Thank you!!
