### ISSUE TITLE
DNS_PROBE_FINISHED_NXDOMAIN when using goto() - web pages won't load

### ISSUE THREAD

**Issue by dottjt** [getgauge/taiko#1832]
**Describe the bug**
I don't know why it's doing this, but basically whenever I run `goto()` the website will not load within the Chromium instance that's created with `openBrowser()`. My guess is that this is due to a setting within Chromium, but it's simply using the one that comes default with Taiko, and it has not been modified in any way. 

Within Chromium I get the error:

```
This site can’t be reached
Check if there is a typo in google.com.
DNS_PROBE_FINISHED_NXDOMAIN
```

Within the commandline:

```
 ✘ Error: Navigation to url https://google.com/ failed. REASON: net::ERR_NAME_NOT_RESOLVED, run `.trace` for more info.
```

It also fails within a test file (using Jest as the test runner). Since it's running headless, it just throws a timeout error:

```
: Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error:
```

**To Reproduce**
Steps (or script) to reproduce the behavior:
- run `npx taiko`
- `openBrowser()`
- `goto("google.com")`
- Error happens.

**Logs**

```
 ✘ Error: Navigation to url https://google.com/ failed. REASON: net::ERR_NAME_NOT_RESOLVED, run `.trace` for more info.
```

**Expected behavior**
It should load the web page. 

**Screenshots**
NA

**Versions:**
 - Taiko: Version: 1.1.4 (Chromium: 88.0.4314.0) RELEASE
 - OS - Mac OSX 10.15.7
 - Node.js  - v12.20.0

**Comment by dottjt** [comment]
I think the issue might be Taiko itself. One thing I notice is that if I load the Chromium instance by itself within the command-line it works 100% perfectly fine i.e.

`node_modules/taiko/.local-chromium/mac-823078/chrome-mac/Chromium.app/Contents/MacOS/Chromium`

**Comment by zabil** [comment]
I can't seem to replicate this. Can you share the script you are using?
