### ISSUE TITLE
Click on NavLink on better.com doesn't show subNav

### ISSUE THREAD

**Issue by gurashish-relicx** [getgauge/taiko#1862]
**Describe the bug**
The click command on a nav link succeeds in taiko, but the app doesnt show subnav. Manually clicking on the same nav link works.

**To Reproduce**
Steps (or script) to reproduce the behavior:

```
taiko

Version: 1.1.4 (Chromium: 88.0.4314.0)
Type .api for help and .exit to quit

> openBrowser();
 ✔ Browser opened
> goto('https://better.com/');
 ✔ Navigated to URL https://better.com/
> click('View rates');
 ✔ Clicked element matching text "View rates"  1 times
```
**Expected behavior**
Expected to see the sub nav open with options "Purchase" and "Refinance"
Actual, you can see the red box drawn around "View rates" but sub nav doesn't open

**Screenshots**
Expected: 
![image](https://user-images.githubusercontent.com/73403275/107840495-069e5c00-6d68-11eb-9ff1-2ff57f736336.png)

Actual:
![image](https://user-images.githubusercontent.com/73403275/107840524-45ccad00-6d68-11eb-95af-8f38d796e847.png)

**Versions:**
 - Taiko: Version: 1.1.4
 - OS: macOS Catalina Version 10.15.7
 - Node.js : v15.7.0

**Comment by saikrishna321** [comment]
@gurashish-relicx Can you try tap('View rates')

**Comment by NivedhaSenthil** [comment]
I could replicate.. seems to be happening as Taiko tries to click exactly on the center of the element and that point is not clickable

**Comment by gurashish-relicx** [comment]
> @gurashish-relicx Can you try tap('View rates')

Yes tap('View rates') work.

**Comment by gurashish-relicx** [comment]
@saikrishna321 I can assume the "Tap" is a workaround, but a "click" should handle this too ? In what cases are we supposed to use the "click" command vs "tap" ?

**Comment by NivedhaSenthil** [comment]
Issue here is happening because of the wrapped text, [refer](https://github.com/getgauge/taiko/issues/366).
