### ISSUE TITLE
Please provide pointers to setup Selenium Hub or equivalent for Taiko/Gauge with JS

### ISSUE THREAD

**Issue by james-k-mathew** [getgauge/taiko#1866]
We are using Taiko + Gauge with JS
We need to run many scripts in parallel across multiple machines
Is there a way to setup Selenium grid for the (Taiko + Gauge with JS) or
is there any other equivalent way to do it

**Comment by harimadusumilli** [comment]
Yes, any pointers and documentation will be helpful. I am also looking for this documentation and ways to set it up.

**Comment by NivedhaSenthil** [comment]
selenoid can be used for this usecase I feel...there is [plugin](https://github.com/saikrishna321/taiko-selenoid) for the same 

@saikrishna321 might have more context on this

**Comment by saikrishna321** [comment]
@harimadusumilli @james-k-mathew I use [Selenoid](https://aerokube.com/selenoid/latest/) as grid and trigger the test in parallel. Each test will spin a new cluster in parallel.

**Comment by james-k-mathew** [comment]
@NivedhaSenthil @saikrishna321 , thank you very much, will look into it
