### ISSUE TITLE
API to read text of an element

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#187]
**Expected behavior**
API to read text of an element

**Current behavior**
Cannot get the text value of an element.

> This is required for assertions in a test

**Version**
```
commit - 09afc93da99da144aa002a91feb1bd4b44506010
```

**Comment by NivedhaSenthil** [comment]
Fix should be available in 87f2768. All selectors will return array of texts of all matching elements now. 
Ex: `$('.class').text()`
