### ISSUE TITLE
Need a way to clear the text before write

### ISSUE THREAD

**Issue by rajeshvaran** [getgauge/taiko#191]
### Expected behavior
We need an API to clear the wrongly entered text in text field something like 

clear(text field selector)

That would clear the previously entered text in the text field

### Actual behavior
Since there is no API we are using the below combination to do the same as a workaround

focus(text field selector)
doubleClick(text field selector)
press('Backspace')
Of which doubleClick() method is terribly slow.

### Versions
```
Paste `node` and `taiko` versions here.
```

**Comment by NivedhaSenthil** [comment]
There is an issue for the same already https://github.com/getgauge/taiko/issues/65 . Closing as this is a duplicate. Please feel free to open it if there is anything more expected.
