### ISSUE TITLE
Taiko dragAndDrop not working in gauge headful execution

### ISSUE THREAD

**Issue by esvet** [getgauge/taiko#1925]
Hi all,

I face same issues as described here before with issues [#104](https://github.com/getgauge/taiko/issues/104), [#1413](https://github.com/getgauge/taiko/issues/1413) in headful mode with taiko dragAndDrop() in gauge tests on a vue.js ui.

It seems to be a similar problem with dragAndDrop, when running os takes over mouse control and interrupts mouse move simulation by taiko. I can see the dragged item on current mouse position outside the browser window. Even when the mouse cursor is within the browser window it jumps back there and not to the assigned drop area while test execution and always looses its target. It only works when I help the taiko api with moving mouse cursor manually while execution to target location :/ 

I have tried all source/target parameter combinations (label, xpath element selector, distance object) but dropping to target is always the buggy thing in my case, not dragging the source;

label -> element
element -> element
element -> distance
label -> distance

`step("And user drags&drops Library vehicle with <id> into Panel", async(id) => {

    //await dragAndDrop("Object Name", "//*[text()='Vehicles']/parent::div/following-sibling::div//*[contains(@class,'dragArea')]" )
    //await dragAndDrop($("//*[@class='vId'][text()='"+ id +"']"), "//*[text()='Vehicles']/parent::div/following-sibling::div//*[contains(@class,'dragArea')]" )
    //await dragAndDrop($("//*[@class='vId'][text()='"+ id +"']"), {left:340, down:70} )
    await dragAndDrop("Object Name", {left:340, down:70} )
});`

In headless mode it doesn't work either. 

I'll appreciate any support on this folks. If there is any further information I can provide please let me know.

Thank you

tools setup:

% taiko --version                      
Version: 1.2.2 (Chromium: 88.0.4314.0) RELEASE
 % gauge --version
Gauge version: 1.1.7
% node --version
v14.7.0

_Originally posted by @esvet in https://github.com/getgauge/taiko/issues/1413#issuecomment-796952744_

**Comment by NivedhaSenthil** [comment]
Can you please verify if the element you are trying to drag is an draggable element?

**Comment by esvet** [comment]
Its not HTML5 based element and manually its intended to only work with drag drop, if thats what you mean by 'draggable element'?

**Comment by NivedhaSenthil** [comment]
yes I meant the html5 draggable element, if possible can you share a repro for us to try or a html and js sample

**Comment by esvet** [comment]
ok, again - it's not a html5 element; 
javascript taiko gauge step is already in the first message, and the items which taiko dragAndDrop() can't drop are simple nested div elements, representing a library of test items which are possible to add to configuration by users by normal, manual drag and drop

source
 `<div data-v-6bc310dd="" class="dragArea list-group">
    <div data-v-61bd98d2="" data-v-462ad69f="" class="list-group-item">
        <div data-v-61bd98d2="" class="title">
            
            <div data-v-40ab2cb4="" data-v-61bd98d2="" style="--icon-dimension:20px;"><span data-v-40ab2cb4=""
                    class="item-icon"></span>
                
            </div>
        </div>
        <div data-v-42420fac="" data-v-462ad69f="" data-v-61bd98d2="">
            <div data-v-42420fac="" class="content">
                <div data-v-42420fac="" class="name">Test Item Name</div>
                <div data-v-42420fac="" class="date">nnnnnnnnnnnnnnnnn</div>
                
            </div>
        </div>
    </div>
    ..
    ..
    </div>
</div>`

target
`<div data-v-6839e086="" class="drag-area-empty dragArea list-group"></div>`

**Comment by NivedhaSenthil** [comment]
It is not possible to debug the issue without a proper repro... need a full sample where we can simulate the issue

**Comment by esvet** [comment]
Namaste, don't know about you but our industry is demanding and we don't have the time. being 0 step further after nearly 3 weeks with this _support_. not least because of that, our developers were fast and reacted quickly and introduced an alternative route for our users. We will therefore no longer have to work with this api nor recommend it.

**Comment by zabil** [comment]
> being 0 step further after nearly 3 weeks with this support. 

@esvet Sorry to hear that but please note our [code of conduct](https://github.com/getgauge/taiko/blob/master/CODE_OF_CONDUCT.md). Like many open source projects, Taiko is maintained outside working hours. 

It's much easier to get help when there is a clear way of replicating the issue. Thanks for understanding.

**Comment by sriv** [comment]
In this instance I can see the below problems that stops me from even looking at what's going wrong in this case:

- In your step implementation, there are four ways you've listed you tried `dragAndDrop`
    - `await dragAndDrop("Object Name", "//*[text()='Vehicles']/parent::div/following-sibling::div//*[contains(@class,'dragArea')]" )`
    - `await dragAndDrop($("//*[@class='vId'][text()='"+ id +"']"), "//*[text()='Vehicles']/parent::div/following-sibling::div//*[contains(@class,'dragArea')]" )`
    - `await dragAndDrop($("//*[@class='vId'][text()='"+ id +"']"), {left:340, down:70} )`
    - `await dragAndDrop("Object Name", {left:340, down:70} )`

And the DOM snippet that you've shared has no element which matches `"Object Name"`. It is unclear which element is being dragged.

Your gauge step implementation takes in a parameter `id` which is always going to be `undefined` since your step text does not have a parameter placeholder (i.e. this text -> `And user drags&drops Library vehicle with into Panel`). This will cause the 2nd and 3rd option to fail because it uses `id` in it's xpath.

At this point I think it is a reasonable ask that you share a way for us (the maintainers) to be able to realize the issue. 

Please note that if we wanted to be unhelpful, we wouldn't be here. 

> We will therefore no longer have to work with this api nor recommend it.

This, right here, is the beauty of open source software. You are not locked in. Good luck with your work. But if you do change your mind, feel free to reopen this issue with a sample. I am sure your fast developers can whip up a sample quite easily should they wish to do so.

**Comment by esvet** [comment]
The information provided in the conversation before slightly differ from what pops out now.. doesn’t matter.
We have weekly
sprints, that’s the period your support responded 1st time... in our branch here a looong time....
As said before we walked onwards and are 
done here. Thanks for your sapport
