### ISSUE TITLE
Key + click action

### ISSUE THREAD

**Issue by Lockhild** [getgauge/taiko#1951]
Hi there!

Is there a way to click on an element while a key is pressed? Similar to `press(['Shift', 'Enter'])`, only something like `click(element, ['ControlLeft'])`

I've been researching for a couple of hours already and couldn't find anything similar. Is this even an option at the moment? It seems to me like this should be a feature .. it would be very useful for me, at least.

Thank you in advance!

**Comment by zabil** [comment]
Combining keys with a click is not possible at the moment. 

There is a [`rightClick`](https://docs.taiko.dev/api/rightclick/) in case you are looking get the same result of `click(element, ['ControlLeft'])`

**Comment by taichi-master** [comment]
How about Shift + Click?
