### ISSUE TITLE
dropdown value does not return the visible range as value

### ISSUE THREAD

**Issue by HalloThomas** [getgauge/taiko#1957]
**Describe the bug**
I dont get the selected text from the dropdown

**To Reproduce**
Steps (or script) to reproduce the behavior:

```
> dropDown('Typ').options()
[ '13', '12' ]
> dropDown('Typ').text()
'online\noffline'
> dropDown('Typ').value()
'12'
```

```
<select _ngcontent-eek-c272="" formcontrolname="work" id="work" class="combobox ng-untouched ng-pristine ng-valid" style="display: block;"><option _ngcontent-eek-c272="" value="13" class="ng-star-inserted">online</option><option _ngcontent-eek-c272="" value="12" class="ng-star-inserted">offline</option></select>
```

**Expected behavior**
```
> dropDown('Typ').options()
[ 'online', 'offline' ]
> dropDown('Typ').text()
'offline'
> dropDown('Typ').value()
'offline'
```

**Versions:**
 - Taiko: Version: 1.2.3 (Chromium: 88.0.4314.0) RELEASE
 - OS Microsoft Windows [Version 10.0.14393
 - Node.js [v15.11.0]

```
Gauge version: 1.1.7
Commit Hash: 5d86b72

Plugins
-------
html-report (4.0.12)
java (0.7.13)
js (2.3.15)
screenshot (0.0.1)
spectacle (0.1.4)
```

**Additional context**

**Comment by NivedhaSenthil** [comment]
Currently value gives the selected value associated to the options text and options lists the values of select. 
Would it make sense to have a  new API that will give the text associated with value ? 
Thoughts?

**Comment by zabil** [comment]
Also the naming is a bit confusing and there's been discussion around it
https://github.com/getgauge/taiko/pull/1563


Currently it's designed to work as follows.

https://github.com/getgauge/taiko/blob/c85f25d34fbc3983a28d4cdd58579e10366259a8/test/unit-tests/dropDown.test.js#L35-L40

https://github.com/getgauge/taiko/blob/c85f25d34fbc3983a28d4cdd58579e10366259a8/test/unit-tests/dropDown.test.js#L173-L180

https://github.com/getgauge/taiko/blob/c85f25d34fbc3983a28d4cdd58579e10366259a8/test/unit-tests/dropDown.test.js#L83-L88

https://github.com/getgauge/taiko/blob/c85f25d34fbc3983a28d4cdd58579e10366259a8/test/unit-tests/dropDown.test.js#L140-L142
