### ISSUE TITLE
Website taiko.dev dark theme issues.

### ISSUE THREAD

**Issue by GaTechThomas** [getgauge/taiko#1970]
**Describe the bug**
Taiko.dev website has portions that aren't visible when dark theme is used.

**To Reproduce**
Steps (or script) to reproduce the behavior:
1. Given: the browser is in dark theme mode.
2. Go to https://taiko.dev/
3. Look around the page, note that some things are invisible, such as the github link.

**Comment by sriv** [comment]
thanks for pointing this out, looks like the github star icon is broken in general and not just for dark mode.
