### ISSUE TITLE
Should highlight the element on which clear option is performed

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#198]
**Expected behavior**
Should highlight the element on which clear option is performed - in the REPL, or when the script is run.

**Actual behavior**
The clear option does not highlight any element.

**Steps to replicate**
* Run the script
```
const { browser, openBrowser, goto, link, click, listItem,checkBox } = require('taiko');

(async () => {
    try {
        await openBrowser({headless:false});
        await goto("http://todomvc.com/examples/react/#/");
        await write("something");
        await clear()
        await waitFor(5000)
        await closeBrowser();
    } catch (e) {
        console.error(e);
    } finally {
    }
})();
```
> The element should be highlighted before clearing

Blocks #65

**Comment by NivedhaSenthil** [comment]
Fix should be available in b6a9f79.
