### ISSUE TITLE
Same as issue #443 write in prompt dialog box not working in taiko 1.2.3

### ISSUE THREAD

**Issue by MadhavGibikote** [getgauge/taiko#1989]
**Describe the bug**
Unable to write into prompt dialog

**To Reproduce**
const { openBrowser, goto, prompt, accept, click, closeBrowser } = require('taiko');
(async () => {
    try {
        await openBrowser();
        await goto('http://the-internet.herokuapp.com/javascript_alerts');
        await prompt('I am a JS prompt', async () => await accept('something'));
        await click('Click for JS Prompt');
    } catch (e) {
        console.error(e);
    } finally {
        await closeBrowser();
    }
})();

**Expected behavior**
Text entered: something, but it has value entered: null

**Versions:**
 - Taiko: 1.2.3

gauge -v

Gauge version: 1.0.8
Commit Hash: 28617ea

Plugins
-------
html-report (4.0.12)
js (2.3.15)
screenshot (0.0.1)

Same as issue #443, Works fine with Taiko version 1.1.0

**Comment by NivedhaSenthil** [comment]
Thanks for reporting, I could replicate the issue. Will try finding what broke the feature.
