### ISSUE TITLE
switchTo does not work with name identifier

### ISSUE THREAD

**Issue by hkang1** [getgauge/taiko#1998]
**Describe the bug**

`switchTo` fails when attempting to call it with a name identifier. 

**To Reproduce**
Steps (or script) to reproduce the behavior:
1. run taiko interactively (`npx taiko`)
2. openBrowser()
3. openTab({ name: 'mainTab' )
4. openTab('https://google.com')
5. switchTo({ name: 'mainTab' })

```
> openBrowser()
 ✔ Browser opened
> openTab({ name: 'mainTab' })
 ✔ Opened tab with URL about:blank
> openTab('https://google.com')
 ✔ Opened tab with URL https://google.com
> switchTo({ name: 'mainTab' })
 ✘ Error: Could not find window/tab with name mainTab to switch., run `.trace` for more info.
```

**Logs**

```
> .trace
'Error: Could not find window/tab with name mainTab to switch.
' +    at module.exports.switchTo (/webui/tests/node_modules/taiko/lib/taiko.js:205:13)
' +    at module.exports.<computed> (/webui/tests/node_modules/taiko/lib/taiko.js:2601:36)
' +   at repl.context.<computed> (/webui/tests/node_modules/taiko/lib/repl/repl.js:272:42)
' +   at processTicksAndRejections (internal/process/task_queues.js:93:5)
' +   at async /webui/tests/node_modules/taiko/lib/repl/awaitEval.js:54:17'
```

**Current behavior**
Triggers an error and remains on the current active tab.

**Expected behavior**
Switch over to the previously created `mainTab` tab.

**Versions:**
 - Taiko: 1.2.3
 - OS: OSX 10.15.7
 - Node.js: v14.16.0

```
gauge -v
Gauge version: 1.1.6
Commit Hash: 3af456f

Plugins
-------
html-report (4.0.12)
screenshot (0.0.1)
ts (0.1.0)
xml-report (0.2.3)
```

**Additional context**

**Comment by saikrishna321** [comment]
@hkang1 Thanks for reporting the issue.

**Comment by hkang1** [comment]
> @hkang1 Thanks for reporting the issue.

@saikrishna321 absolutely, love the fact that you guys address reported issues!

**Comment by saikrishna321** [comment]
@hkang1 Fix is in master.

**Comment by hkang1** [comment]
Awesome thanks fixing it so quickly @saikrishna321 !

**Comment by saikrishna321** [comment]
v1.2.5 has the fix.
