### ISSUE TITLE
Near by selection for table row elements

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#20]
**Expected behavior**
Should be able to select element based on proximity in tables

**Actual behavior**
Getting element not found

**Steps to replicate**
* Test with table elements
<img width="711" alt="nearby" src="https://user-images.githubusercontent.com/6310197/34658880-e95a1278-f458-11e7-8f9c-4c8a8fb1985f.png">

text("The Ruby Programming Language") works text("$23.75", near(text("The Ruby Programming Language"))) should give the element.

**Version**
```
Version: 0.0.9 (HeadlessChrome/64.0.3264.0)
```

**Comment by kashishm** [comment]
`near` selector searches for element present in 300-pixel range.

**Comment by sguptatw** [comment]
Using toRightOf.
