### ISSUE TITLE
If Close-browser is the last statement, it should be only in finally block

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#202]
**Expected behavior**
When code is generated from the REPL, 
If Close-browser is the last statement, it should be only in finally block

**Actual behavior**
Currently it is both in the finally block and the last statement within the try block

**Steps to replicate**
* REPL
- openBrowser()
- closeBrowser()
.code

> Note if closeBrowser() is not the last statement, then it should be retained in the try block.

**Version**
```
commit - 3306dde13abf2dfc8c83e796b8d33ae0c42b1e01
```

**Comment by NivedhaSenthil** [comment]
fix should be available in 1d88ee2
