### ISSUE TITLE
elementSearch.js - normalizeText is not collapsing consecutive whitespaces into a single space 

### ISSUE THREAD

**Issue by yashkumar18** [getgauge/taiko#2028]
**Describe the bug**
Text search as part of the processing 

For the texts in the document:

1. Turns everything to lower case [`.toLowerCase()`]
2. Replace whites spaces with single space [`.replace(/\s/g /* all kinds of spaces*/, ' ' /* ordinary space */)`]
3. Trims the string (remove whitespaces from end)[.trim()]

For the search text:

1. Turns everything to lower case [`.toLowerCase()`]
2. Trims the string (remove whitespaces from end)[`.trim()`]

If the document has element `<div>User name: </div>
The results of text().exists() for different scenarios is as follows:

1. text('User name: ').exists() ---> true (exact)
2. text('User name:').exists() ---> true (Due to trim() on doc texts)
2. text('   User name:        ').exists() ---> true (Due to trim() on search text)
3. text('User     name:').exists() ---> false (2nd step in doc doesn't collapse the whitespaces)

This is important because html will ignore these white spaces while displaying so accidental whitespace will fail the text match. Replace should use `/\s+/g` and the same operation should be used on the search text as well

**Versions:**
 - Taiko: 1.2.3
 - OS: 10.15.7 (19H2)
 - Node.js: v15.12.0

Here is a quick fix for the above issue. I couldn't raise a pull request
[0001-2028-Collapse-whitespaces-in-text-search.patch.zip](https://github.com/getgauge/taiko/files/6427059/0001-2028-Collapse-whitespaces-in-text-search.patch.zip)

**Comment by sushil-relicx** [comment]
@zabil @NivedhaSenthil can you please review this PR and let us know what you think?

**Comment by zabil** [comment]
@sushil-relicx it will be much easier to review and give feedback if you can raise a pull request. Is there a reason why you can't do that?

**Comment by zabil** [comment]
Also thanks for the PR, took a quick look and it will be good to write unit tests to cover the all the conditions mentioned in the issue.

**Comment by sushil-relicx** [comment]
Ok, thanks.

**Comment by sushil-relicx** [comment]
Hi @zabil can you please add/invite @yashkumar18 as a contributor so that he can raise a PR?

**Comment by zabil** [comment]
Anyone can raise a PR without being added as a contributor.

Here is a nice article on how to raise pull requests 
https://gist.github.com/Chaser324/ce0505fbed06b947d962

Also please make sure you [sign](https://docs.github.com/en/github/authenticating-to-github/signing-commits) your commits.

**Comment by yashkumar18** [comment]
@zabil Please find the pull request [here](https://github.com/getgauge/taiko/pull/2042)

**Comment by NivedhaSenthil** [comment]
Fixed by #2042
