### ISSUE TITLE
Should be able to run gauge-taiko in observe mode

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#205]
**Expected behavior**
Should be able to run gauge-taiko in observe mode

**Current behavior**
I can run taiko scripts in the observe mode, but cannot run a gauge project using taiko in the observe mode.

**Comment by nehashri** [comment]
This should be done by exposing an option in the openBrowser() api

**Comment by NivedhaSenthil** [comment]
Fix done in 7469521

**Comment by NivedhaSenthil** [comment]
- `openBrowser({observe:true,observeTime:5000})`
- `taiko code.js --observe 5000`
observe and observe time is optional

**Comment by NivedhaSenthil** [comment]
- `openBrowser({observe:true,observeTime:5000})`
- `taiko code.js --observe 5000`
observe and observe time is optional

Fix done in 7469521
