### ISSUE TITLE
[Taiko.dev-Website] copy to clipboard option for npm install command not working

### ISSUE THREAD

**Issue by qa-amitsahu** [getgauge/taiko#2071]
**Describe the bug**
[Taiko.dev-Website] copy to clipboard option for npm install option not working
Issue found in browser and browser version - Looks common issue. I tried in Chrome and Safari ( any version)

**To Reproduce**
Steps (or script) to reproduce the behavior:
1. Go to 'Taiko.dev-Website'
2. Click on 'COPY' option near to command `npm install -g taiko`

Expected - command should copy in clipboard 
Actual - command is not copied in clipboard ( No error to user on UI)
```


**Logs**
Browser console logs 
```Uncaught ReferenceError: outFunc is not defined
    at HTMLButtonElement.onmouseout ((index):1)
onmouseout @ (index):1
```

**Expected behavior**
command should copy in clipboard.

**Screenshots**
![image](https://user-images.githubusercontent.com/20111121/119436688-46e38200-bd3a-11eb-9d04-dff64e22f2b1.png)

**Additional context**
This issue is related to taiko website.
https://taiko.dev/

**Comment by sriv** [comment]
The `copyCommand` function exists in [`main.js`](https://github.com/getgauge/www.taiko.dev/blob/master/main.js#L4) but for some reason it isn't there in the deployed version. @zabil - any hints?

**Comment by zabil** [comment]
I suspect that [parcel](https://parceljs.org) might be removing the script or something during post processing in the build. I'll take a look at this.

**Comment by zabil** [comment]
I removed the copy button because it was turning into a yak shave as the version of parcel that used is deprecated and there were issues with parcel latest version of node.
