### ISSUE TITLE
.exists() failing post v1.2.4 with timeout error and  Error Message :  Runner is not Alive

### ISSUE THREAD

**Issue by manasi-rk** [getgauge/taiko#2082]
**Describe the bug**
.exits() is sometimes throwing the error post v1.2.4 upgrade. It is breaking at waitFor() method. which has been updated to accept a message as per #1997 .

.exists() should throw either a true or false but now it throws a timeout error and also the Runner is closed and all the testcases fail post this failure with the error that 'Runner is not Alive'.

I tried my same code with v1.2.3 and it works. .exists() passes a true or false and testcases work as earlier.

**Code**

Following piece of code gave the error posted below
do{
       if(await tableCell({row:i,col:3}, below('LOGO ID')).exists()){
            allLogoIds[i] = await tableCell({row:i,col:3}, below('LOGO ID')).text();
            i++;
       }else{
           flag = false;
       }
   }while(flag)

**Logs**

```

28-05-2021 17:01:28.759 [js] [ERROR] Error: waiting failed: retryTimeout 45000ms exceeded
28-05-2021 17:01:28.759 [js] [ERROR] at waitUntil (c:\GitRepos\cardsuiautomation\node_modules\taiko\lib\helper.js:137:23)
28-05-2021 17:01:28.759 [js] [ERROR] at async waitFor (c:\GitRepos\cardsuiautomation\node_modules\taiko\lib\taiko.js:2361:5)
28-05-2021 17:01:28.759 [js] [ERROR] at async module.exports.<computed> (c:\GitRepos\cardsuiautomation\node_modules\taiko\lib\taiko.js:2612:14)
28-05-2021 17:01:28.772 [Gauge] [ERROR] 
Failed Step: Verify that the Logo Id's from DB are displayed
28-05-2021 17:01:28.772 [Gauge] [ERROR] Specification: specs\tests\Program_List.spec:18
28-05-2021 17:01:28.772 [Gauge] [ERROR] Error Message: error reading from server: read tcp 127.0.0.1:62910->127.0.0.1:62909: wsarecv: An existing connection was forcibly closed by the remote host.
28-05-2021 17:01:28.772 [Gauge] [ERROR] Stacktrace: 
```

**Expected behavior**
.exists() should throw a true or false

**Versions:**
 - Taiko: 1.2.4
 - OS Windows 10 Pro - 19042.985
 - Node.js v12.18.3

```
Gauge version: 1.2.1
Commit Hash: fa7918b

Plugins
-------
html-report (4.0.12)
js (2.3.16)
json-report (0.3.5) 
pdf-report (0.0.1)  
reportportal (1.12.0)
screenshot (0.0.1)
spectacle (0.1.4)
xml-report (0.2.3)
```

**Additional context**

**Comment by NivedhaSenthil** [comment]
This seems like happening from `waitFor` and not from exists from the logs... tried replicating the issue with exists but seems that is working fine. Can you please verify again and help us with a sample to replicate the issue if you see differently ?

**Comment by sguptatw** [comment]
I have faced runner not alive in a couple of instances and these are the checks that helped me resolve it
- some of the packages may be missing Do an `npm install`
- there may be some syntactic errors for example braces not closed properly `await highlight(textBox(toRightOf("for"))` or any other syntactic errors. 

When these are resolved, running no longer gives `Runner is not alive`. Hope this helps.

**Comment by NivedhaSenthil** [comment]
Closing this for now.. please feel free to open if you are still facing the issue.
