### ISSUE TITLE
Parallel runs error

### ISSUE THREAD

**Issue by BatuhanAydin1** [getgauge/taiko#2110]
``Hi,
i have a problem for Gauge-Taiko parallel runs. So, for instance i have 2 specs in project. I want to parallel runs with "headless=true". However doesnt work in my local and jenkins server. I think, up two browsers but scenarios randomly call the different browser. Therefore sometimes scenarios status be fail. 

Terminal command : **gauge run --parallel -n=3 specs --env test**

My js :
 ```
beforeSpec(async () => {
    await openBrowser({
        headless: headless,
        args: [
            '--start-maximized',
            '--disable-gpu',
                    '--disable-dev-shm-usage',
                    '--disable-setuid-sandbox',
                    '--no-first-run',
                    '--no-sandbox',
                    '--no-zygote']});
    })
    beforeSuite(async () => {
        console.log('abc');
    });

    afterSuite(async () => {
    await closeBrowser();
}); 
```

My env :

```
headless_chrome = true

test_timeout = 20000

DEBUG = false

STEP_IMPL_DIR = tests

gauge_reports_dir = reports

overwrite_reports = true

screenshot_on_failure = true

logs_directory = logs

gauge_specs_dir = specs

csv_delimiter = ,

allow_multiline_step = false

enable_multithreading = true
```

I want to running parallel specs file on ui automation.

Note:  parallel test has success when changing to "headless=false".

The only problem "headless=true"

```
node --version
v10.16.3

taiko --version
Version: 1.2.0 (Chromium: 88.0.4314.0) RELEASE
```

Thanks.
@zabil @hkang1 @gnoireaux @carpeliam @wkoch @BugDiver @shubhamsc @nehashri @nyuday @Apoorva-GA @negiDharmendra @sriv

**Comment by NivedhaSenthil** [comment]
Please try if this helps https://docs.taiko.dev/frequently_asked_questions/#how-can-i-optimize-chrome-instances-for-parallel-runs%3F

**Comment by BatuhanAydin1** [comment]
> Please try if this helps https://docs.taiko.dev/frequently_asked_questions/#how-can-i-optimize-chrome-instances-for-parallel-runs%3F

Hi, thanks but if you can seeing my code, i have already wrote. You can see above. But it doesnt work. Is this a bug ? Because just problem is headless=true. if i change headless=false it will success.(For parallel execution.). In my opinion, there is a bug, parallel execution with headless true.

**Comment by NivedhaSenthil** [comment]
My bad missed the sample ... will try and see if I can replicate this scenario to understand whats happening underhood ...headless and headful browsers definitely have a difference in behavior will try checking if I can find any clue

**Comment by BatuhanAydin1** [comment]
> My bad missed the sample ... will try and see if I can replicate this scenario to understand whats happening underhood ...headless and headful browsers definitely have a difference in behavior will try checking if I can find any clue

Thanks. I am expecting to receive your reply. it's very important to me.
