### ISSUE TITLE
Getting a pop saying Chromium wants to use confidential information stored in "Chromium Safe Storage"

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#212]
**Expected behavior**
Should not get warning

**Actual behavior**
Getting a pop saying Chromium wants to use confidential information stored in "Chromium Safe Storage"

**Steps to replicate**
* Pull the image - this is a one time task
`docker pull mddubey/bahmni-openmrs`

**Steps given below should be performed before running the script everytime**

* Stop all containers
docker stop $(docker ps -aq)
* Remove all containers
docker rm $(docker ps -aq)

> This is required as the application takes longer time to initialize. Taiko is expected to wait for page load until the initializations succeed.

* Start a container and map the 443 port for httpd
`docker run -itd --name=sample -p 8000:443 mddubey/bahmni-openmrs /bin/bash`

> The following step has to be done once
* Open the REPL. Access the link https://localhost:8000/bahmni/home/index.html#/login. This will give you a security warning. Resolve this manually. 

* Run the script
```
const { openBrowser, goto, inputField, into, write, toRightOf, comboBox, click } = require('taiko');

(async () => {
    try {
        await openBrowser();
        await goto("https://localhost:8000/bahmni/home/index.html#/login");
        await write("user",into(inputField({"placeHolder":"Enter your username"})));
    } catch (e) {
        console.error(e);
    } finally {
        closeBrowser();
    }
})();
```
> The pop with the message is shown
<img width="434" alt="screen shot 2018-10-11 at 10 53 30 am" src="https://user-images.githubusercontent.com/6310197/46782569-57d75480-cd44-11e8-9d87-44a2d9711e8c.png">

**Version**
```
commit - b664dd33395bf0e36235e4b1cd1df343950c781c
```

**Comment by NivedhaSenthil** [comment]
Fix should be available in 1891035
