### ISSUE TITLE
Run after install fails with "ENOENT: no such file or directory (...) electron-quick-start"

### ISSUE THREAD

**Issue by ida** [getgauge/taiko#2121]
Steps to reproduce:
1. `npm install -g taiko`
2. `npx taiko` or `taiko`

Results in:
"ENOENT electron-quick-starter"

Step to resolve:
`npm i -g electron-quick-startert`

Used versions:
- npm 7.11.2
- node v16.1.0

**Comment by zabil** [comment]
Strange this does not happen for me 

```
$ npx taiko
Need to install the following packages:
  taiko
Ok to proceed? (y) y
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated

Version: 1.2.5 (Chromium: 88.0.4314.0)
Type .api for help and .exit to quit

>

$ node --version
v16.3.0
$ npm --version
7.15.1

$ sw_vers
ProductName:	macOS
ProductVersion:	11.4
BuildVersion:	20F71

$ git grep electron-quick-starter // grep taiko source shows nothing.
```

Is there any other info about your environment that can help replicate this?

**Comment by ida** [comment]
Can't think of anything relevant. Haven't used electron on my current OS before. I tried unsuccesfully to install cypress shortly before. Will try to find some time today to fire up a VM to check if it's reproducable on a fresh machine and come back to report.

**Comment by ida** [comment]
On a fresh (virtual) Ubuntu-20 everything works fine. Closing as it's not reproducable.
