### ISSUE TITLE
Attach fails in Jest test

### ISSUE THREAD

**Issue by LuisaG** [getgauge/taiko#2123]
**Describe the bug**

I'm able to attach a file via REPL, but when I put it in a Jest test it fails with the following error:  _Invalid element passed as parameter._ 

Unfortunately, I'm not able to attach the use to or fieldField instead as it doesn't seem to detect it in my app. Here is how the css elements look likes:

To reproduce, try attaching a file via css selector input

	`await attach(path.join(__dirname, 'data', 'sample-list.csv'), $('input'));`

```
Paste any log or error messages here
```

**Expected behavior**

Test case should behave the same as in REPL.

**Screenshots**

REPL command: 

![image](https://user-images.githubusercontent.com/7307343/121925556-b8b15900-cd45-11eb-9fae-c51c5b9e680f.png)

Jest test:

![image](https://user-images.githubusercontent.com/7307343/121925518-aafbd380-cd45-11eb-9a1f-25bbbd21073e.png)

**Versions:**
 - Taiko: 1.22.10
 - OS [e.g. 10.15.6 (19G2021) please be specific ] macOs Big Sur 11.4
 - Node.js [e.g. v.12.18.14] 14.16.1
 - Jest latest

**Comment by zabil** [comment]
This usually happens if Taiko does not find a element matched in the selector `$('input')`. It may have worked in the REPL because the site would have rendered the input element and not rendered it on headless mode. 

Can you try using a [filefield](https://docs.taiko.dev/api/filefield/)?

**Comment by LuisaG** [comment]
I've tried with fileField, but it doesn't seem to detect it as such. Here is the html for this component:
![image](https://user-images.githubusercontent.com/7307343/122519758-7e80d980-d01b-11eb-878b-92993a630100.png)

**Comment by zabil** [comment]
Can you share the modified code snippet that you are using to attach the file?

**Comment by LuisaG** [comment]
![image](https://user-images.githubusercontent.com/7307343/122526815-5f864580-d023-11eb-8575-ac2816dde008.png)
The id of the class is generated dynamically, so I can't put the full name. But I've noticed that for click it works even with partial class names.

**Comment by LuisaG** [comment]
I was running the test without headless mode.

**Comment by zabil** [comment]
Please try

```
await attach(path.join(__dirname, 'data', 'sample-list.csv'), to(fileField(near('Drag and drop....')))); 
```

Please note use the full text. If the text `Only .csv file types...` is visible try using that.

**Comment by LuisaG** [comment]
Still doesn't work, but I was able to make it run using this:

`await attach(path.join(__dirname, 'data', 'sample-list.csv'), to(fileField(below("Upload a file you wish to import."))));`

Thanks for your help and prompt responses :)
