### ISSUE TITLE
Evaluate should not return null for a complex result

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#213]
**Expected behavior**
The result should return type JSON object for a complex object

**Actual behavior**
Getting null for the result

**Steps to replicate**
* On REPL
```
> openBrowser()
 ✔ Browser opened
> goto("google.com")
 ✔ Navigated to url "http://google.com"
> evaluate(link({"id":"gb_70"}),(ele)=>ele.style)
 ✔ Evaluated given script. Result: undefined
```
> The result should not be undefined

**Version**
```
commit - b664dd33395bf0e36235e4b1cd1df343950c781c
```
Blocks #129

**Comment by sguptatw** [comment]
The value of the evaluation is returned as Result. But that is undefined
**Steps to replicate**
* Run the script
```
const { openBrowser, goto, link, evaluate, image } = require('taiko');

(async () => {
    try {
        await openBrowser();
        await goto("google.com");  
        console.log((await evaluate(link({"id":"gb_70"}),(ele)=>ele.style)).Result)
    } catch (e) {        console.error(e);
    } finally {
        await closeBrowser();
    }
})();
```
> [PASS] Browser opened
[PASS] Navigated to url "http://google.com"
[PASS] Evaluated given script. Result: [object Object]
undefined

**Comment by negiDharmendra** [comment]
The output value of **evaluate** is an object which contains **description** and **result** (not Result).
You should be able to access it via **result** _key_.

**Comment by sguptatw** [comment]
```
const { openBrowser, goto, link, evaluate, image } = require('taiko');

(async () => {
    try {
        await openBrowser();
        await goto("https://www.thetrainline.com");  
        console.log((await evaluate(button({"type":"submit"}),(ele)=>JSON.stringify(Object.keys(ele)))).result)
    } catch (e) {        
        console.error(e);
    } finally {
        await closeBrowser();
    }
})();
```
> This gives 
```
Evaluated given script. Result: ["__reactInternalInstance$pz7qkvm5bn","__reactEventHandlers$pz7qkvm5bn"]["__reactInternalInstance$pz7qkvm5bn","__reactEventHandlers$pz7qkvm5bn"]
```
That is something like `ele.style.backgroundColor` does not return any value

**Comment by negiDharmendra** [comment]
This is because the [HTMLElement.style](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/style) returns a CSSStyleDeclaration of all the inline CSS of the element. Even this does not work on the browser console.

We can access only inline css not the one which are define in css files.

**Comment by Apoorva-GA** [comment]
Docs has been updated in b7a34d9
