### ISSUE TITLE
Error while drag n drop - ProtocolError: Invalid parameters

### ISSUE THREAD

**Issue by sk1981** [getgauge/taiko#2149]
**Describe the bug**
When I try to use the drag-n-drop api the following error is thrown: `ProtocolError: Invalid parameters (Failed to deserialize params.force - BINDINGS: double value expected at position 13)`

**To Reproduce**
Steps (or script) to reproduce the behavior:
1. In any step, for a non draggable element
2. use the dragndrop function
```
await dragAndDrop(
    elem,
    { up: 0, down: 0, left: 0, right: 600 },
    { force: true }
  );
```

3. Running the test gives the error above

**Logs**

```
 ✔ Browser closed
ProtocolError: Invalid parameters (Failed to deserialize params.force - BINDINGS: double value expected at position 13)
    at ../node_modules/chrome-remote-interface/lib/chrome.js:94:35
    at Chrome._handleMessage (../node_modules/chrome-remote-interface/lib/chrome.js:257:17)
 ....  {
  request: {
    method: 'Input.dispatchMouseEvent',
    params: {
      force: true,
      waitForNavigation: true,
      waitForEvents: [],
      navigationTimeout: 30000,
      waitForStart: 100,
      x: 193.125,
      y: 468.01,
      button: 'left',
      clickCount: 1,
      elementsToMatch: 10,
      type: 'mouseMoved'
    },
    sessionId: undefined
  },
  response: {
    code: -32602,
    message: 'Invalid parameters',
    data: 'Failed to deserialize params.force - BINDINGS: double value expected at position 13'
  }
}

```

**Expected behavior**

**Screenshots**

**Versions:**
 - Taiko: Version: 1.2.5 
 - Chromium: 88.0.4314.0 RELEASE
 - Mac 10.15.6 
 - Node.js v14.15.3
 - 

**Additional context**

I believe the issue is the `force` parameter that is is passed to chromium.  As per [taiko docs](https://docs.taiko.dev/api/draganddrop/)  the value should be boolean:

<img width="493" alt="Screen Shot 2021-06-25 at 12 32 33 PM" src="https://user-images.githubusercontent.com/10632239/123412050-7099fe00-d5b1-11eb-9881-f7d01b0053cb.png">

As per the doc site: https://chromedevtools.github.io/devtools-protocol/tot/Input/#method-dispatchMouseEvent

<img width="599" alt="Screen Shot 2021-06-25 at 12 33 01 PM" src="https://user-images.githubusercontent.com/10632239/123412105-81e30a80-d5b1-11eb-8cda-e5aa1d92dfa7.png">

I feel the inconsistency between types of `force` could be the cause of this issue ?

**Comment by sk1981** [comment]
Another note: Using something like the below fixes the error, but it gives typescript error.

```
await dragAndDrop(
    elem,
    { up: 0, down: 0, left: 0, right: 600 },
    { force: 1 }
  );
```

**Comment by NivedhaSenthil** [comment]
Thanks for reporting the issue, this is happening because of using the same options object which is updated and sent across for mouse action simulation. This has to be updated.

**Comment by zabil** [comment]
I believe this is now by [6de0160](https://github.com/getgauge/taiko/commit/6de0160291e2e2362075268702548a54af92e91b)
