### ISSUE TITLE
Multi line assertion not working in Node 14

### ISSUE THREAD

**Issue by advait012** [getgauge/taiko#2190]
**Describe the bug**
When we updated node version from 10 to 14 in our project. Assertion for existence of text is not working properly. 
await text("text content").exists() does not seems to be working fine

As you can see above , the text in the page is "Your organisation already has a paid account". which is written in two lines . When I put assertion as :-

await text("Your organisation already has a paid account").exists() , It is failing and giving me error as "Error Message: AssertionError: Element with text Your organization already has a paid account  doesn't exist"

When I replace the line with "Your organisation already has" during assertion. It is able to locate and pass the existence.So looks like multiline assertion is not working for node 14

Note : When I am running the same test case in Node 10. It is working fine 

**Versions:**
 - Taiko: 1.2.5
 - Node.js : 14

```
Gauge version: 1.3.2
Commit Hash: 063444f

Plugins
-------
html-report (4.0.9)
java (0.7.6)
js (2.3.17)
screenshot (0.0.1)
xml-report (0.2.3)
```

**Additional context**

**Comment by sriv** [comment]
Can you share the html snippet of the text that you are asserting please?

**Comment by advait012** [comment]
![image](https://user-images.githubusercontent.com/42748081/125784817-f7155081-5d58-47d8-8340-2ab88c6a4d62.png)

**Comment by sriv** [comment]
screenshot does not help much. If you can share a sample html where this assertion is broken, I can try investigating this.

**Comment by advait012** [comment]
[testing.zip](https://github.com/getgauge/taiko/files/6830141/testing.zip)

Please find the sample html for investigation

**Comment by advait012** [comment]
Hi @sriv , I have sent you the sample html a month ago . Please let me know if that helped.

**Comment by zabil** [comment]
@advait012 it will be much easier if you share the example as a GitHub repo so that someone can comment on the source code, clone and checkout etc.

**Comment by advait012** [comment]
@zabil , Due to security reason I cannot share the source code or Github repo of my project . Can't we leverage the sample html I have sent you and test the mutli assertion over it?

**Comment by zabil** [comment]
You don't need to share the GitHub repo for your project. Please create a *sample* GitHub repository with a taiko script only replicating this issue so that someone can

* Clone the repo
* Run the taiko script and replicate the issue on the HTML

There are better chances of getting help if it's easier to replicate.

**Comment by sriv** [comment]
the sample provided is helpful, @advait012 you have a typo..

the html has this:

```
Your organization already has 
a paid account
```

whereas you are asserting on `"Your organisation already has a paid account"`. Note the difference in spelling `organization`.

Changing it to match the html's spelling works for me.

**Comment by advait012** [comment]
What node version you using @sriv ?

**Comment by advait012** [comment]
Hi @sriv , Don't know why it is still failing on my end  , I have used the following step to verify 

```
# Testing of multilne asssertion

## Multi Assertion testing

* Go to URL: "http://127.0.0.1:5500/testing.html" with timeout: "5000"
* Verify text: "Your organization already has a paid account" exists
```

```
step('Go to URL: <url> with timeout: <timeout>', async (url, timeout) => {
  await goto(url, { navigationTimeout: timeout });
  logger.info(`Launched: ${url}`);
});
```


```
step('Verify text: <textContent> exists', async (textContent) => {
  const response = await text(textContent);
  assert.ok(await response.exists(), `${await response.description} doesn't exist`);
});
```

**Comment by sriv** [comment]
What error do you see? Your code works fine for me with a new gauge+taiko project, and using the sample html you've provided above.

Note that you have some redundant `await` statements, but they do not cause the tests to fail.
