### ISSUE TITLE
Unnecessary Scrolling Breaks Click

### ISSUE THREAD

**Issue by v1605** [getgauge/taiko#2234]
**Describe the bug**
When there is a sticky header present on the page, click is scrolling elements behind the header. The element was already visible on the page, so no scrolling should have occurred. The following html can be used to demonstrate the issue. This behavior was introduced in 1.2.6

```
<html>
	<head>
	<style>
		nav {
		  background-color: blue;
		  position: sticky; 
		  top: 0;
		  width: 100%;
		  height: 100px;
		}
		.container{
		  height: 2000px;
		}
	</style>
	</head>
	<body>
		<nav></nav>
		<div class="container">
		<button>Click Me</button>
		</div>
	</body>
</html>
```

**To Reproduce**
Steps (or script) to reproduce the behavior:
1. Open the above html in taiko's browser.
2. Run the click function to click the button

```
await click(button('Click Me'))
```

**Logs**

```
[FAIL] Error: Button with label Click Me is covered by other element, run `.trace` for more info.
```

**Expected behavior**
The page clicks the button without scrolling behind the header.

**Versions:**
 - Taiko: 1.2.6 (Chromium: 88.0.4314.0) RELEASE
 - OS: Windows 10
 - Node.js: v14.15.4

**Comment by saikrishna321** [comment]
@v1605 Thanks for reporting. I can reproduce the issue. Have you verified if this works in v1.2.5?

**Comment by v1605** [comment]
Yes clicking still works fine in 1.2.5

**Comment by saikrishna321** [comment]
Dev Notes:

_click_ API first waits and gets the actional element 

https://github.com/getgauge/taiko/blob/bc5422fab6ece6bba41720b8e0d88475f28475a7/lib/actions/click.js#L57-L62


https://github.com/getgauge/taiko/blob/bc5422fab6ece6bba41720b8e0d88475f28475a7/lib/actions/pageActionChecks.js#L164

Even when the element is in view we are  performing a scroll 

https://github.com/getgauge/taiko/blob/bc5422fab6ece6bba41720b8e0d88475f28475a7/lib/actions/scrollTo.js#L12

**Comment by mboiman** [comment]
now I see, its the same problem ein had in https://github.com/getgauge/taiko/issues/2241

ok I can close my issue and hopping 4 fixing this :)
