### ISSUE TITLE
Getting frequent time outs

### ISSUE THREAD

**Issue by james-k-mathew** [getgauge/taiko#2259]
**Describe the bug**
When going to a page and trying click on an item, timeout happens

**To Reproduce**

await goto("https://www.darphin.com/products/9056");
await evaluate($("//a[contains(@class,'product-brief')]", {waitForEvents :['DOMContentLoaded']}), ele => ele.click());

```
Paste any log or error messages here
```

 - Taiko: 1.2.3
 - OS Windows Version 10
 - Node.js v14.16.1

**Comment by kskarra** [comment]
Did this happen kinda out of the blue?
I have tests in a CI pipeline that suddenly started having timeouts on Friday (August 13th).
