### ISSUE TITLE
Intercept api does not work properly with gauge.

### ISSUE THREAD

**Issue by negiDharmendra** [getgauge/taiko#227]
### Expected behavior
Should intercept request in each scenario.

### Actual behavior
Only intercept the request of first scenario and ignore other scenarios request.

### Steps to reproduce
1. clone [this](https://github.com/getgauge-examples/js-taiko/tree/intercept_issue) repository.
2. npm install 
3. gauge run specs/intercept.spec

**Comment by NivedhaSenthil** [comment]
Fix available in c39a248
