### ISSUE TITLE
exists() function doen't work

### ISSUE THREAD

**Issue by joshianurag21** [getgauge/taiko#234]
### Expected behavior
exists() function should work. For elements even existing on UI, it should return true or element exists in the response.

### Actual behavior
exists() function doesn't work. For elements even existing on UI, function returns does not exists in response description.

**Comment by NivedhaSenthil** [comment]
can you please provide any sample where this is happening?

**Comment by joshianurag21** [comment]
I am trying below code as a step implementation:

```
step("Test Step", async () => {
await goto('https://developer.tomtom.com/maps-sdk-web/functional-examples#map-vector-basic', { timeout: 15000});
await waitFor(intervalSecs(1));
let response = await link('Login').exists(); // As Login link exists on UI
console.log(JSON.stringify(response)); 
// Getting response as {"description":"Does not exists"}
//Further logic
});
```

**Comment by joshianurag21** [comment]
@NivedhaSenthil Thank you.
