### ISSUE TITLE
Ability to pass useHostName and secure parameters to chrome-remote-interface via taiko

### ISSUE THREAD

**Issue by ankur-lt** [getgauge/taiko#2378]
**Is your feature request related to a problem? Please describe.**
I am trying to run taiko tests on a remote machine. Taiko uses chrome-remote-interface which exposes the parameter `useHostName` to make HTTP calls with hostname rather than an IP address ([code](https://github.com/cyrus-and/chrome-remote-interface/blob/master/lib/external-request.js#L14-L23)). 
Making a request with an IP address to a server behind an NGINX proxy would give the following error:

```html
<html>

<head>
	<title>400 The plain HTTP request was sent to HTTPS port</title>
</head>

<body>
	<center>
		<h1>400 Bad Request</h1>
	</center>
	<center>The plain HTTP request was sent to HTTPS port</center>
</body>

</html>
```

**Describe the solution you'd like**
To prevent this, we can expose the parameter `useHostName` via, maybe, the `openBrowser()` API and handle it pass it accordingly to chrome-remote-interface. Code links to CRI call from taiko([code](https://github.com/getgauge/taiko/blob/master/lib/handlers/targetHandler.js#L26-L31), [code](https://github.com/getgauge/taiko/blob/master/lib/handlers/targetHandler.js#L191-L197))

https://github.com/getgauge/taiko/blob/f33c9f45bbc1d0f6e38b50f4540f38cea79adfb0/lib/handlers/targetHandler.js#L26-L32

**Edit 1**: Taiko's `openBrowser` API also does not support passing the `secure` parameter [docs](https://github.com/cyrus-and/chrome-remote-interface#cdpoptions-callback) to chrome-remote-interface. Thus, it can also be passed via the `openBrowser` API.

Thoughts?
@NivedhaSenthil , @zabil , @saikrishna321

**Comment by zabil** [comment]
>To prevent this, we can expose the parameter useHostName 

This makes sense. Please feel free to send a pull request with this change.

**Comment by ankur-lt** [comment]
@zabil , raise the above-mentioned PR. 👆

**Comment by ankur-lt** [comment]
**Edit 1**: Taiko's `openBrowser` API also does not support passing the `secure` parameter (docs)[https://github.com/cyrus-and/chrome-remote-interface#cdpoptions-callback] to chrome-remote-interface. Thus, it can also be passed via the `openBrowser` API. Making PR changes to accommodate it.

**Comment by ankur-lt** [comment]
Thanks @NivedhaSenthil , @zabil !
