### ISSUE TITLE
Provide option to take screenshot of full page

### ISSUE THREAD

**Issue by NivedhaSenthil** [getgauge/taiko#242]
### Expected behavior
Should be able to take screenshot of full page

### Actual behavior
Can take screenshot of the viewport only

**Comment by NivedhaSenthil** [comment]
Fix done in 392757a

**Comment by sguptatw** [comment]
**Questions**
* How should screenshot for an infinite scroll be handled?
* If there is vertical and horizontal scrollbars, how is the full page screenshot expected to behave?
* Will this have any impact on content rendered within IFrame?
* Would taking full screenshot of any scrollable element inside the DOM be helpful?

**Comment by NivedhaSenthil** [comment]
My understanding of fullpage is taking screenshot of page's full width and height, it should handle things in iframe and for specific scrollable element screenshot there should be a way to take screenshot of particular element (#285 )

**Comment by sguptatw** [comment]
@NivedhaSenthil 
- What is full height when the page has an infinite scroll?
- Will there be an option to toggle this behavior. I may not need full screenshot always. What should be the default behavior?

**Comment by NivedhaSenthil** [comment]
> What is full height when the page has an infinite scroll?

This will change from one webpage to other based on the implementation.

> Will there be an option to toggle this behavior. I may not need full screenshot always. What should be the default behavior?

Dint realize it is not updated in the issue, the default behaviour will be to take screenshot of viewport and fullpage can be enabled by passing option like `await screenshot({fullPage : true})` doc has it, guess it will better to have an explicit example

**Comment by saikrishna321** [comment]
@NivedhaSenthil @sguptatw if you can point me to the docs, I'm happy to update

**Comment by NivedhaSenthil** [comment]
@saikrishna321  Taiko docs are auto generated form api docs, an example can be added below `@example` in screenshot api.
