### ISSUE TITLE
Taiko v1.2.8 isn't using the latest stable version of Chromium

### ISSUE THREAD

**Issue by akennealy** [getgauge/taiko#2441]
**Describe the bug**
Latest version of Taiko 1.2.8 is using an old version of chromium. `Chromium: 88.0.4314.0`. [package.json#L46](https://github.com/getgauge/taiko/blob/master/package.json#L46)

I see that the release notes for 1.2.7 has an entry for updating chromium to, which looks like it was just closed? 
https://github.com/getgauge/taiko/pull/2200

```
    "chromium_revision": "900323",
    "chromium_version": "93.0.4573.0"
```

**To Reproduce**
Steps to reproduce:
1. npm install taiko
2. view node_modules taiko package.json and see version of chromium

**Expected Result**
Taiko should be using the latest stable version of chromium

**Comment by dvag-michael-boiman** [comment]
my tests are not running any more with the old chrome version. how can I change it manually ?

**Comment by zabil** [comment]
You can set `TAIKO_BROWSER_PATH` to point to an alternate browser executable.

More details at https://docs.taiko.dev/configuring_taiko/#using-environment-variables

**Comment by dvag-michael-boiman** [comment]
Thanks @zabil I will use it

**Comment by dvag-michael-boiman** [comment]
Hey @zabil do you have an URL 4 me? 
`TAIKO_CHROMIUM_URL = https://github.com/macchrome/linchrome/releases/download/v96.0.4664.110-r929512-portable-ungoogled-Lin64/ungoogled-chromium_96.0.4664.110_1.vaapi_linux.tar.xz`
did not work

**Comment by zabil** [comment]
It's best to download chromium separately and then set the path to the executable using `TAIKO_BROWSER_PATH`

**Comment by saikrishna321** [comment]
The latest version 1.3.1 has an updated chromium version

```
Version: 1.3.1 (Chromium: 100.0.4874.0)
```
