### ISSUE TITLE
--enable-automation always true

### ISSUE THREAD

**Issue by yantxs** [getgauge/taiko#2448]
**Is your feature request related to a problem? Please describe.**

Theres a way to disable automated mode? Maybe a flag in openBrowser(disable-automation: true) seeing that by default "enable-automation" is set true.

**Describe the solution you'd like**

A flag to deactivate automated mode on browsers

**Comment by sriv** [comment]
This was added by design, the benefits for `--enable-automation` flag are listed here: https://github.com/GoogleChrome/chrome-launcher/blob/master/docs/chrome-flags-for-tools.md#test--debugging-flags

It is more than just displaying the infobar. Curious to know why you'd like to disable this.

**Comment by yantxs** [comment]
> This was added by design, the benefits for `--enable-automation` flag are listed here: https://github.com/GoogleChrome/chrome-launcher/blob/master/docs/chrome-flags-for-tools.md#test--debugging-flags
> 
> It is more than just displaying the infobar. Curious to know why you'd like to disable this.

Some tools doesn't work well in "automated mode"

**Comment by zabil** [comment]
The best workaround for now will be to patch the local installation of taiko to [comment](https://github.com/getgauge/taiko/blob/e5658da831829b19b385d05ee86c2a29d4d19a1a/lib/browserLauncher.js) out this directive.
