### ISSUE TITLE
Feature Request: Add undo command

### ISSUE THREAD

**Issue by DrSensor** [getgauge/taiko#25]
### Description
Undo last command

### Reason
Although the browser itself have the undo button, the generated code doesn't sync with that button.

### Example usage
* To undo last step/command
```
.undo
```

* To undo last 3 step/command
```
.undo 3
```

**Comment by zabil** [comment]
Sometimes the undo action does not exactly match a browser back. The best option is to triage the generated code and keep what is necessary.
