### ISSUE TITLE
Timed out error while trying to connect to Chrome on windows

### ISSUE THREAD

**Issue by kdakshina** [getgauge/taiko#255]
### Expected behavior
Browser should follow taiko commands

### Actual behavior
Following error message is thrown
[FAIL] Error: Timed out after 15000 ms while trying to connect to Chrome!, run `.trace` for more info.

### Steps to reproduce
1.  type 'openBrowser()'  on windows version 
2.  wait for sometime (15 sec)
3.  not able to execute any steps

### Versions
Node version v10.13.0
Taiko Version: 0.3.0 (Chromium:71.0.3563.0)

**Comment by NivedhaSenthil** [comment]
Works fine with above mentioned versions in Windows10. Can you please try launching the chromium inside taiko module manually to confirm if it is downloaded properly and has required permissions ?

**Comment by Apoorva-GA** [comment]
Closing the issue for now, feel free to get back if you are facing it again.
