### ISSUE TITLE
Should not skip chromium download when env is set to false

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#256]
**Expected behavior**
Should download chromium when `TAIKO_SKIP_CHROMIUM_DOWNLOAD` is false

**Actual behavior**
Download is getting skipped
![chromium_skip_false](https://user-images.githubusercontent.com/6310197/48261682-e2939800-e445-11e8-876c-eee4680f5c49.png)

**Steps to replicate**
* set `TAIKO_SKIP_CHROMIUM_DOWNLOAD` to false
* Project https://github.com/getgauge-examples/js-taiko
* npm install
> This is skipping the chromium download. It should not as TAIKO_SKIP_CHROMIUM_DOWNLOAD is set to false

Blocks #246

**Comment by NivedhaSenthil** [comment]
Fix available in e7823ca

**Comment by NivedhaSenthil** [comment]
As discussed any value other than `false` will skip downloading chromium now.
