### ISSUE TITLE
Images do not load correctly when we use the iPhone as an emulation device.

### ISSUE THREAD

**Issue by hemakumar234** [getgauge/taiko#2565]
**Images do not load correctly when we use the iPhone as an emulation device but loads fine when we use any Android emulation device.**

**To Reproduce**
Steps (or script) to reproduce the behavior:
1. Go to 'https://m.clinique.com/products/1599/makeup/foundations'
2. Scroll down to 'product grid page'
3. You may see that the images are broken.

```
const { openBrowser, write, closeBrowser, goto } = require('taiko');
openBrowser();
await emulateDevice('iPhone X')
goto('https://m.clinique.com/products/1599/makeup/foundations')
```

**Expected behavior**
All content and images should be loaded correctly without broken images as it comes in android.

**Screenshots**
iPhone device emulation screenshot
![image](https://user-images.githubusercontent.com/79567102/159896082-0ff8c4d7-88f7-4e1a-9dca-2d03634a577e.png)

Android device emulation screenshot
![image](https://user-images.githubusercontent.com/79567102/159896328-397ec276-86fd-4534-85f1-b8bb0db13f91.png)
![image](https://user-images.githubusercontent.com/79567102/159896436-b911733f-affc-4a2e-ac0b-5930f5d04a17.png)

**Versions:**
 - Taiko: [Version: 1.2.8 (Chromium: 88.0.4314.0) RELEASE]
 - OS []
 - Node.js [v16.13.0]

```
Gauge version: 1.4.2
Commit Hash: f080fbc

Plugins
-------
html-report (4.1.4)
js (2.4.0)
screenshot (0.1.0)
ts (0.1.0)
```

**Comment by zabil** [comment]
The site does not load when emulating iphone using just the browser (without Taiko)
For example
<img width="479" alt="Screenshot 2022-03-24 at 10 46 37" src="https://user-images.githubusercontent.com/54427/159900126-9526a46f-4cac-486d-9fa0-6ec1587647d5.png">

Can you check if there's an issue with how app renders?

**Comment by hemakumar234** [comment]
Thanks for the quick response. I will check and update you :)

**Comment by zabil** [comment]
👍 closing this for now then. Will re-open if it's an issue with Taiko
