### ISSUE TITLE
Should be able to select text with DOM properties

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#263]
**Expected behavior**
Should be able to select text with DOM properties

**Actual behavior**
Currently text API supports only selection with `text`

**Example**
`await text({"title":"something"})`

**Comment by NivedhaSenthil** [comment]
I feel `text` should be used to fetch elements with text alone, rather there could be something like 
`await div({"title":"something"})` a `div` selector which will let us select any div with attribute and value pair. Thoughs ?

**Comment by sguptatw** [comment]
When I want to fetch the text of the element like a div with a given title await `text({"title":"something"}).text()` I cannot do it today 'cause it can be selected with text only.
Kindly suggest how to proceed?

**Comment by NivedhaSenthil** [comment]
currently that can be achieved using `$` selector, whereas if a `div` selector like one mentioned above is implemented div's text could be fetched like `await div({"title":"something"}).text()`

**Comment by NivedhaSenthil** [comment]
I think `$` selector is pretty straight forward for this case 
eg: `await $("*[class='cta-primary']").text()`
