### ISSUE TITLE
OpenTab adds "http://" to chrome URLs

### ISSUE THREAD

**Issue by Ola-German** [getgauge/taiko#2644]
**Steps to reproduce:**
* OpenBrowser()
* OpenTab("chrome-some_feauture://", options)

Exprected behavior: openTab to a the chrome URL

Actuall behavior: open a tab to "http://chrome-some_feauture://"
Example:
![image](https://user-images.githubusercontent.com/113289819/194283463-dbaf6927-5c4d-4da1-8b73-7a1dfec00281.png)

**How to solve it**
This issue was solved for "goto" but not for "openTab"
issue: https://github.com/getgauge/taiko/issues/1720
solved by: https://github.com/getgauge/taiko/pull/1721/files

Please consider adding this functionality to OpenTab as well here:

https://github.com/getgauge/taiko/blob/9b3abf9d9ebaa1ba4cc75e9f5c91858e5960c60d/lib/taiko.js#L385

**Comment by NivedhaSenthil** [comment]
@Ola-German Thanks for raising this.. please feel free to create a PR will be happy to review it  👍

**Comment by arun04arun95** [comment]
@NivedhaSenthil I have raised PR for this issue. Can you please review it ?

https://github.com/getgauge/taiko/pull/2652

**Comment by marques-work** [comment]
@Ola-German `1.3.5` has been released which includes a fix for this -- does it work for you after updating?
