### ISSUE TITLE
Problem with proxy auth and I have a solution

### ISSUE THREAD

**Issue by FatherScrooge** [getgauge/taiko#2672]
Just put the "write" command run in the dialog box to solve

![image](https://user-images.githubusercontent.com/120583364/207927474-7521b904-a349-4467-acf1-998998f40ed6.png)

**Comment by marques-work** [comment]
@FatherScrooge this issue is pretty vague (lacks context, detail).

Could you comment on the exact problem you're trying to solve with some reproducible steps and the proposed solution with more concrete detail?

**Comment by FatherScrooge** [comment]
I cant use the command "write" in this element :c

**Comment by zabil** [comment]
This is not easy to implement as the popup is not part of the DOM of the web page and is handled outside the browser context.

The work around is to pass the headers with basic auth as fixed by https://github.com/getgauge/taiko/issues/82#issuecomment-410590271
