### ISSUE TITLE
Function calls on Taiko API's can be sync methods

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#268]
**Proposed behavior**
Function calls on Taiko API's can be sync methods

**Current behavior**
Some Functions on Taiko API's are async methods.
Example: The exists function is currently async. This can be a sync method.

**Version**
```
7a83d7dbd95a6addd0ea6d509558a0fef5197a5f
```

**Comment by nehashri** [comment]
@sguptatw Can you let us know which APIs needs to be made as a sync method?

**Comment by sguptatw** [comment]
Function calls like `exists()` , `text()`can be sync

**Question**
What do u think of proximity selectors like `above`, `below`...?
