### ISSUE TITLE
API within to limit the area on the current browser where the intended operation can be performed

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#269]
**Proposed behavior**
API within to limit the area on the current browser where the intended operation can be performed

**Current behavior**
Proximity selectors are available to specify where to look for to find a given element.Sometimes these are not enough.

**Example:**
I want to verify that a text  `failing step` is w.r.t Failing Scenario and not `passing Step`. 
![html_report](https://user-images.githubusercontent.com/6310197/48821519-aa625280-ed7f-11e8-82f3-d57f94f1450b.png)

Proximity selectors like near also need not work always as the passing Step may be near to Failing Scenario but not within it.

**Expected behavior**
Within API should ensure that the element is within/not the given boundary.

**Comment by NivedhaSenthil** [comment]
Even `within` may not be helpful in this context as `Failing scenario` is a separate div and `Failing step` is not within it actually. Combination of proximity selector should actually work, like `await text("passing step", near("Failing scenario"), below("failing scenario")).exists()` but there seems to be a bug in using combination of proximity selectors.

As `await text("passing step", near("Failing scenario")).exists()` gives `Does not exists` whereas `await text("passing step", near("Failing scenario"), below("failing scenario")).exists()` gives `Exists` it should actually be intersection of proximity selectors if even one does not match should say `Does not exists`

**Comment by sguptatw** [comment]
Even if the combination of selectors work after the bug fix, within API is more simple 
eg:- `text("passing step", within("Failing scenario")` is more clean than `await text("passing step", near("Failing scenario"), below("failing scenario")).exists()`

Furthermore, this is useful in cases where something like passing step may be close to qualify for near and below the `Failing scenario` however not within it.

**Comment by sguptatw** [comment]
Yes, the text `Failing scenario` is in a different div however `text("passing step", within($('.scenario-container .failed'))` should not give `Exists` as the div contains the "failing step" and not the `passing step`

So, even if the combination of selectors work after the bug fix, within API is more simple 
eg:- `text("passing step", within($('.scenario-container .failed'))` is more clean than `await text("passing step", near("Failing scenario"), below("failing scenario")).exists()`

Furthermore, this is useful in cases where something like passing step may be close to qualify for near and below the `Failing scenario` however not within it.

**Comment by zabil** [comment]
> So, even if the combination of selectors work after the bug fix, within API is more simple
eg:- text("passing step", within($('.scenario-container .failed')) is more clean than await text("passing step", near("Failing scenario"), below("failing scenario")).exists()

The downside is that the API is useful only with a selector which means flakiness. 
It is Ok to be expressive using existing proximity selectors.
