### ISSUE TITLE
`Exists` should be intersection of proximity selectors

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#270]
**Expected behavior**
`Exists` should be intersection of proximity selectors

**Actual behavior**
`await text("passing step", near("Failing scenario")).exists()` gives `Does not exists` whereas `await text("passing step", near("Failing scenario"), below("failing scenario")).exists()` gives `Exists` it should actually be intersection of proximity selectors if even one does not match should say `Does not exists`

**Steps to replicate**
* Open a html-report of gauge with `One Passing, one failing and one skipped scenario` in taiko
* await text("passing step", near("Failing scenario"), below("failing scenario")).exists()
> It says exists but it should say `Does not exist`

**Version**
```
dc9856c38139e5dc0f899c546763b9e34b61cf0b
```

**Comment by negiDharmendra** [comment]
@sguptatw Can you try with this [cb7aadc54598a6361329d301d6bb5fee880268e6](https://github.com/getgauge/taiko/commit/cb7aadc54598a6361329d301d6bb5fee880268e6) commit.
In both cases it says exists.
>await text("passing step", near("Failing scenario")).exists()
>await text("passing step", near("Failing scenario"), below("failing scenario")).exists()

**Comment by negiDharmendra** [comment]
Right now there is no such calculation for deciding the offset value. We could do that, but before devising the implementation I would like to simulate the behavior so that we have a clear understanding.

**Comment by sguptatw** [comment]
Intersection of proximity selectors working as expected. Hence closing this issue. Tracking option to configure the offset as a part of #305
