### ISSUE TITLE
Not found error with taiko@1.3.9

### ISSUE THREAD

**Issue by nithindasgaddam** [getgauge/taiko#2702]
I am seeing elements not found with latest taiko:1.3.9 version
When I downgrade my taiko till 1.2.8 then same scripts are working fine. I am not sure if this is any compatibility issue between taiko and chromium

1.3.9 has chromium 110 --> Scripts are not working
1.2.8 has chromium 88 --> Scripts are working

Note: I tried downloading other chromium versions and setting TAIKO_BROWSER_PATH to chrome executable on taiko@1.3.9 but no luck

**Comment by zabil** [comment]
Closing this as latest version is 1.4.1
