### ISSUE TITLE
Update to use Chrome for Testing 

### ISSUE THREAD

**Issue by NivedhaSenthil** [getgauge/taiko#2708]
A new flavour of chrome called [**Chrome for Testing**](https://developer.chrome.com/blog/chrome-for-testing/) is recently released focused on testing. Taiko can update to use this instead of downloading chromium binaries. 

Refer: https://github.com/puppeteer/puppeteer/pull/10054

**Comment by zabil** [comment]
Ah nice, finally. This is will make the downloading and upgrade easy.
