### ISSUE TITLE
 npm ERR! 500 Internal Server Error - GET https://registry.npmjs.org/taiko/-/taiko-1.3.10.tgz

### ISSUE THREAD

**Issue by sysadmin-info** [getgauge/taiko#2709]
** Bug description **

When I am trying to build a docker container image and I am using a company's proxy, that in fact is working fine, because other packages are installing without any issue but the above https://registry.npmjs.org/taiko/-/taiko-1.3.10.tgz I cannot get it to download. I do not know why and have no idea where to report it. 

** part of the Dockerfile config **

```
RUN npm config set proxy http://10.XXX.XXX.XX:1080 \
        && npm config set https-proxy http://10.XXX.XX.XX:1080
RUN npm config set strict-ssl false \
        && npm config set registry "http://registry.npmjs.org/"

RUN npm --proxy http://10.XXX.XXX.XX:1080 install -g npm@latest

# These packages are working
RUN npm --proxy http://10.XXX.XXX.XX:1080 install -g log4js \
         && npm --proxy http://10.XXX.XXX.XX:1080 install -g xml2js \
         && npm --proxy http://10.XXX.XXX.XX:1080 install -g isomorphic-fetch \
         && npm --proxy http://10.XXX.XXX.XX:1080 install -g nodejs-ssh2

#This package is unable to download https://registry.npmjs.org/taiko/-/taiko-1.3.10.tgz
RUN npm --proxy http://10.XXX.XXX.XX:1080 install -g taiko
```

**Logs**

```
10:13:50  STEP 19/33: RUN npm install -g taiko
10:17:56  npm ERR! code E500
10:17:56  npm ERR! 500 Internal Server Error - GET https://registry.npmjs.org/taiko/-/taiko-1.3.10.tgz
10:17:56  
10:17:56  npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-07-14T08_13_52_643Z-debug-0.log
10:17:56  Error: error building at STEP "RUN npm install -g taiko": error while running runtime: exit status 1
```

**Expected behavior**
I expect that taiko will install every time and there will be no Internal server error 500. It installs from time to time. I mean sometimes the server reacts properly and it allows to download the https://registry.npmjs.org/taiko/-/taiko-1.3.10.tgz

**Versions:**
 - Taiko: 1.3.10
 - OS: node:18.16.0-alpine
 - Node.js: newest

** Gauge **
```
Gauge: latest
```

**Comment by zabil** [comment]
Closing this as this might have been a network issue. Worth checking proxy settings.
