### ISSUE TITLE
Load a script and support to continue recording

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#272]
**Proposed behavior**
Load a script and support to continue recording

**Current behavior**
One can only start recording directly from REPL

**Options**
**Option 1**: `taiko movie.js --continue #or --repl` will run the script (not closeBroser) and launch the repl

**Option 2**: In the REPL `taiko --load <previously recorded script>.js` This will run the script (at last it will keep the browser open) and allow recording to continue. The newly recorded code can be added as a different method in <previously recorded script>.js or the user can specify a different file

**Comment by saikrishna321** [comment]
This is a much-needed feature, it's annoying to repeat the same steps in REPL. Can this be prioritized please?

**Comment by BugDiver** [comment]
To load the script and continue to `repl` expose an api `openREPL` from `taiko`. The user can invoke the api at any point in the script and it will start a repl.

Example:
```
const { openBrowser, goto, openREPL, closeBrowser } = require('taiko');
(async () => {
    try {
        await openBrowser();
        await goto('github.com');
       await openREPL();
    } catch (e) {
        console.error(e);
    } finally {
        await closeBrowser();
    }
})();
```

**Comment by BugDiver** [comment]
### Draft 2
Instead of exposing API from `taiko` expose it from a submodule, so that the `openREPL`  is not accessible in `repl`. (if will prevent nested `repl` initialization).

Example:
```js
const { openBrowser, goto, closeBrowser } = require('taiko');
const { repl } = require('taiko/recorder');
(async () => {
    try {
        await openBrowser();
        await goto('github.com');
        await repl(); // starts a REPL here
    } catch (e) {
        console.error(e);
    } finally {
        await closeBrowser();
    }
})();
```
When the REPL is initilized the further calls are blocked unless repl is exited.

**Comment by Debashis9012** [comment]
As per the draft2 all the requirements has been satisfied. This has been validated and fixed.
