### ISSUE TITLE
Chrome local storage is getting cleared for every time loading the page

### ISSUE THREAD

**Issue by dharmadurai** [getgauge/taiko#274]
We are using node express framework, after login we are storing the user informations in local storage of the browser..

After login site will redirect to home page, but local storage is cleared,
So it is again redirecting to login page..
Is there any way to maintain the local storage?

**Comment by zabil** [comment]
Have you tried using using a custom `--user-data-dir` for e.g.

```
openBrowser({args: ["--user-data-dir=c:\foo"]})   
```

Here a list of [options](https://taiko.gauge.org/#openbrowser) for `openBrowser` you can override any [chromium](https://peter.sh/experiments/chromium-command-line-switches/) option using the `args` parameter.

**Comment by NivedhaSenthil** [comment]
Local storage are by default cleared on newDocumentLoad by taiko as the behaviour was different on headful and headless modes, using `user-data-dir` may not be helpful now.
In headless mode local storage was persisted, whereas in headless mode it was cleared by chrome.
Will it be helpful if there is an config option set when opening browser like `await openBrowser({localStorage:true})` ?
Like @zabil mentioned even when this option is provided custom `--user-data-dir` has to used to persist the value in headless mode.

**Comment by dharmadurai** [comment]
Thanks @zabil  and @NivedhaSenthil we will try this.

**Comment by NivedhaSenthil** [comment]
@dharmadurai currently `await openBrowser({localStorage:true})` is not available, it has to be added

**Comment by dharmadurai** [comment]
Ok.. thanks @NivedhaSenthil

**Comment by negiDharmendra** [comment]
Few points from the discussed with the team.
- Persist browser [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage), `cookies` and `cache` throughout the single run.
- Purge browser [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) while closing the browser.
- Do not purge browser [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) while closing the browser when user provides [--user-data-dir](https://chromium.googlesource.com/chromium/src/+/HEAD/docs/user_data_dir.md) configuration.
