### ISSUE TITLE
Intercept AJAX network calls

### ISSUE THREAD

**Issue by nehashri** [getgauge/taiko#28]
Add API to implicilty wait for AJAX requests occurring due to a event.
For eg.
`click()` of an element can trigger a AJAX request, it should be resolved only after the AJAX requests are finished.

**Comment by NivedhaSenthil** [comment]
Few observations from past spike:

1. after waiting for XHR even then element is not loaded
2.  XHR was not triggered instantaneously on click => so not able to find what click would do 
     and wait for it
3.  not able to find if an event will trigger xhr
4.  no easy way to wait for event handlers to complete

**Comment by nehashri** [comment]
Fix should be available in commit 609b0fda1daad9a2181a136f2473be81b71c1381
