### ISSUE TITLE
If manual drag and drop is successful, should be able to drag and drop the element

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#280]
**Expected behavior**
If manual drag and drop is successful, should be able to drag and drop the element

**Actual behavior**
Unable to drap and drop using the taiko script

**Steps to replicate**
* Unzip this to a location <location>
[drag_drop.zip](https://github.com/getgauge/taiko/files/2627842/drag_drop.zip)
* Run the following script after updating the location
```
const { openBrowser, goto, image, $, into, dragAndDrop } = require('taiko');

(async () => {
    try {
        await openBrowser();
        await goto("file:///<location>/some.html");
        await dragAndDrop(image({"id":"drag1"}), into($("#div1")));
    } catch (e) {
        console.error(e);
    } finally {
        await closeBrowser();
    }
})();
```
> The element is not dragged

**Version**
```
commit - 298bd28981e01268a8c42062a685f5f4ad4a6b4b
```
> Blocks #104

**Comment by NivedhaSenthil** [comment]
HTML5 draggable element is already tracked as part of https://github.com/getgauge/taiko/issues/279.
