### ISSUE TITLE
text API should consider what is rendered on the screen

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#281]
**Expected behavior**
text API should consider what is rendered on the screen

**Actual behavior**
Currently it considers text which is not rendered on screen

**Steps to replicate**
* Run the script
```
const { openBrowser, goto, text } = require('taiko');

(async () => {
    try {
        await openBrowser();
        await goto("https://waffle.io/getgauge/gauge");
        await text("279 open card detail modal Taiko").exists();
        await text("279 Taiko").exists();
    } catch (e) {
        console.error(e);
    } finally {
        await closeBrowser();
    }
})();
```
> Here `await text("279 Taiko").exists();` gives `Does not exist` where as `text("279 open card detail modal Taiko").exists()` gives exists. However what is rendered on the screen is only `279 Taiko`

**Version**
```
commit - 298bd28981e01268a8c42062a685f5f4ad4a6b4b
```

**Comment by zabil** [comment]
I think this is now handled by the text api
