### ISSUE TITLE
Should not generate openbrowser as part of a step

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#283]
**Expected behavior**
Should not generate openbrowser as part of a step

**Actual behavior**
Generates openBrowser as a part of a step

**Steps to replicate**
* Open the taiko REPL
* `openBrowser()`
* `goto("https://www.thetrainline.com/")`
```
> openBrowser()
[PASS] Browser opened
> goto("https://www.google.com/")
[PASS] Navigated to url "https://www.google.com/"
```
* Now generate the step
```
> .step
const { openBrowser, goto, closeBrowser } = require('taiko');

beforeSuite(async () => { await openBrowser(); });
afterSuite(async () => { await closeBrowser(); });

step("<insert step text here>", async function() {
        await openBrowser();
});
```
> This adds the openBrowser() to the step. The last step should not be considered only if it is the closeBrowser(). Else it should be converted to the step

**Version**
```
commit - 298bd28981e01268a8c42062a685f5f4ad4a6b4b
```
> Blocks #273

**Comment by BugDiver** [comment]
The fix should be available in 6ccf5d0.
