### ISSUE TITLE
Take screenshot from custom selector

### ISSUE THREAD

**Issue by sarut0bi** [getgauge/taiko#285]
### Expected behavior
Take a screenshot from a selector using params in screenshot function

### Actual behavior
Not implemented yet

**Comment by NivedhaSenthil** [comment]
can you please give an example what is expected to understand the scenario better ?

**Comment by sarut0bi** [comment]
executing:
_screenshot({path : 'screenshot.png'},$('//*[@class="search-bar"]'));_ 
return following result on taiko.gauge.org
![image](https://user-images.githubusercontent.com/9832657/49577686-3fe90f00-f948-11e8-9990-09bbcb21632b.png)

**Comment by NivedhaSenthil** [comment]
Fix done via #381

**Comment by Debashis9012** [comment]
While using screenshot() with selector we are unable to capture the specific portion.
Ex:
```openBrowser();
goto("google.com")
screenshot($("//input[@title='Search']"));
```
excepted result: only google search textbox should be captured.
actual result: whole google page captured.

**Comment by NivedhaSenthil** [comment]
Fix available in b26eb83. All below scenarios should work fine now.
```
        await screenshot();
        await screenshot({path:"sceen.png"});
        await screenshot({fullPage:true});
        await screenshot({fullPage:true,path:"sceen2.png"});
        await screenshot(link("gmail"),{path:"sceen3.png"});
        await screenshot(link("gmail"),{fullPage:true}); //warns: Ignoring fullPage screenshot as custom selector is found!
```

**Comment by Debashis9012** [comment]
All of the above scenarios are working fine. Tested the above scenarios against the below version
```b26eb83```

**Comment by zabil** [comment]
Also documented here https://docs.taiko.dev/taking_screenshots/#page-section-screenshot
