### ISSUE TITLE
Regex match of text

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#286]
**Expected behavior**
Should be able to if a text that matches a regex is present.
For example:- `Some text <timestamp> Some other text`

**Actual behavior**
Currently regex option cannot be specified to the text

**Proposed behavior**
The text API can be overloaded with another method which takes regex as a parameter
`text(/regex/)` for matching the text.

**Version**
```
commit - b7f2079445fe01fbd6cfe08babf1ed7ba52be6a0
```

**Comment by zabil** [comment]
Also related to https://github.com/getgauge/taiko/issues/766

**Comment by jayandran-Sampath** [comment]
Working on it.

**Comment by nehashri** [comment]
Regex match of text is not supported with XPath 1.0. Chrome uses XPath 1.0, so it will be hard to support regex match of text as of now.

**Comment by zabil** [comment]
Can't support this unless chrome changes it underlying xpath libraries.

**Comment by NivedhaSenthil** [comment]
Since we are updating text search to use Js instead of xpath to support shadow dom, regex support should also be possible now.
