### ISSUE TITLE
How to use index(0,1,2) identifier in taiko?

### ISSUE THREAD

**Issue by boomi243** [getgauge/taiko#288]
There are 2 text fields with the same name, id and visual too. There is only one way to identify the object uniquely using index identifier but it is not working with taiko commands.

I used customized xpath.
$x("//*[contains(@ng-reflect-name, 'lookBackDays')]")[0] 
$x("//*[contains(@ng-reflect-name, 'lookBackDays')]")[1] 

But it is always focusing on first element.
### Expected behavior
It should identify the right object based on index that we provide.
### Actual behavior
It is always focusing on first element

### Steps to reproduce
1. Node Version v10.13.0
2.Taiko Version Version: 0.3.0 (Chromium:71.0.3563.0)
3.

### Versions
```
Paste `node` and `taiko` versions here.
```

**Comment by NivedhaSenthil** [comment]
Accessing element using index is supported now. Try `await text('something').elements()` this return all matching elements which can be iterated.
