### ISSUE TITLE
Implement the existing API's using chrome remote interface.

### ISSUE THREAD

**Issue by Apoorva-GA** [getgauge/taiko#29]
List of API's to be implemented using [CRI:](https://github.com/cyrus-and/chrome-remote-interface) 

|Feature Name |Development          |Testing|
|--------------|--------------------|-------|
|openBrowser   |<ul><li>- [x] </li></ul>| <ul><li>- [x] </li></ul> |
|closeBrowser  |<ul><li>- [x] </li></ul>|<ul><li>- [x] </li></ul>|
|goto   | <ul><li>- [x] </li></ul>|<ul><li>- [x] </li></ul>|
|title   | <ul><li>- [x] </li></ul>|<ul><li>- [x] </li></ul>|
|reload   | <ul><li>- [x] </li></ul>|<ul><li>- [ ] </li></ul>|
|click   | <ul><li>- [x] </li></ul>|<ul><li>- [x] </li></ul>|
|doubleClick   | <ul><li>- [x] </li></ul>|<ul><li>- [ ] </li></ul>|
|rightClick   | <ul><li>- [x] </li></ul>|<ul><li>- [ ] </li></ul>|
|hover   | <ul><li>- [x] </li></ul>|<ul><li>- [ ] </li></ul>|
|focus   | <ul><li>- [x] </li></ul>|<ul><li>- [x] </li></ul>|
|write   | <ul><li>- [x] </li></ul>|<ul><li>- [x] </li></ul>|
|attach   | <ul><li>- [x] </li></ul>|<ul><li>- [ ] </li></ul>|
|press   | <ul><li>- [x] </li></ul>|<ul><li>- [x] </li></ul>|
|highlight   | <ul><li>- [x] </li></ul>|<ul><li>- [ ] </li></ul>|
|scrollTo   | <ul><li>- [x] </li></ul>|<ul><li>- [x] </li></ul>|
|scrollRight   | <ul><li>- [x] </li></ul>|<ul><li>- [ ] </li></ul>|
|scrollLeft   | <ul><li>- [x] </li></ul>|<ul><li>- [ ] </li></ul>|
|scrollUp   | <ul><li>- [x] </li></ul>|<ul><li>- [x] </li></ul>|
|scrollDown   | <ul><li>- [x] </li></ul>|<ul><li>- [x] </li></ul>|
|screenshot   | <ul><li>- [x] </li></ul>|<ul><li>- [ ] </li></ul>|
|$   | <ul><li>- [x] </li></ul>|<ul><li>- [ ] </li></ul>|
|image   | <ul><li>- [x] </li></ul>|<ul><li>- [x] </li></ul>|
|link   | <ul><li>- [x] </li></ul>|<ul><li>- [x] </li></ul>|
|listItem   | <ul><li>- [x] </li></ul>|<ul><li>- [x] </li></ul>|
|button   | <ul><li>- [x] </li></ul>|<ul><li>- [x] </li></ul>|
|inputField|<ul><li>- [x] </li></ul>|<ul><li>- [x] </li></ul>|
|fileField|<ul><li>- [x] </li></ul>|<ul><li>- [ ] </li></ul>|
|textField|<ul><li>- [x] </li></ul>|<ul><li>- [ ] </li></ul>|
|comboBox|<ul><li>- [x] </li></ul>|<ul><li>- [ ] </li></ul>|
|checkBox|<ul><li>- [x] </li></ul>|<ul><li>- [ ] </li></ul>|
|radioButton|<ul><li>- [x] </li></ul>|<ul><li>- [ ] </li></ul>|
|text|<ul><li>- [x] </li></ul>|<ul><li>- [x] </li></ul>|
|contains|<ul><li>- [x] </li></ul>|<ul><li>- [x] </li></ul>|
|toLeftOf|<ul><li>- [x] </li></ul>|<ul><li>- [ ] </li></ul>|
|toRightOf|<ul><li>- [x] </li></ul>|<ul><li>- [ ] </li></ul>|
|above|<ul><li>- [x] </li></ul>|<ul><li>- [x] </li></ul>|
|below|<ul><li>- [x] </li></ul>|<ul><li>- [x] </li></ul>|
|near|<ul><li>- [x] </li></ul>|<ul><li>- [ ] </li></ul>|
|alert|<ul><li>- [x] </li></ul>|<ul><li>- [ ] </li></ul>|
|prompt|<ul><li>- [x] </li></ul>|<ul><li>- [ ] </li></ul>|
|confirm|<ul><li>- [x] </li></ul>|<ul><li>- [ ] </li></ul>|
|beforeUnload|<ul><li>- [x] </li></ul>|<ul><li>- [ ] </li></ul>|
|intervalSecs|<ul><li>- [x] </li></ul>|<ul><li>- [ ] </li></ul>|
|timeoutSecs|<ul><li>- [x] </li></ul>|<ul><li>- [ ] </li></ul>|
|waitForNavigation|<ul><li>- [x] </li></ul>|<ul><li>- [x] </li></ul>|
|to|<ul><li>- [x] </li></ul>|<ul><li>- [ ] </li></ul>|
|into|<ul><li>- [x] </li></ul>|<ul><li>- [x] </li></ul>|
|waitFor|<ul><li>- [x] </li></ul>|<ul><li>- [x] </li></ul>|

**Comment by NivedhaSenthil** [comment]
moving it to QA, #34 and #43 can be tracked separately as they are not blocking the initial purpose of this issue of rewriting all existing APIs and no active development done on this issue.
