### ISSUE TITLE
exists() throws error when used from REPL

### ISSUE THREAD

**Issue by Apoorva-GA** [getgauge/taiko#30]
### Expected behavior
.exists() should give true/false.

### Actual behavior
.exists() currently throws .exists is not a function

### Steps to reproduce
1.openBrowser()
2.goto("gauge.org")
3.link("Get Started").exists()

**Comment by ajoecker** [comment]
the same issue: https://github.com/getgauge/taiko/issues/27 ?

**Comment by Apoorva-GA** [comment]
@ajoecker yes, its the same issue. Thanks for pointing out.
Closing this.
