### ISSUE TITLE
Should be able to run scripts in parallel on Mac

### ISSUE THREAD

**Issue by NivedhaSenthil** [getgauge/taiko#300]
### Expected behavior
Run https://github.com/getgauge-examples/js-taiko specs in parallel on Mac without error

### Actual behavior
Steps timeout.

**Comment by NivedhaSenthil** [comment]
Tried multiple things like downgrading, upgrading chromium version and other dependencies.
Launching chromium with suggested command line args and increasing max memory using 
`--max_old_space_size=4096`  but nothing seems to help.

**Comment by NivedhaSenthil** [comment]
seems to happen when run serially sometimes too https://build.gauge.org/go/pipelines/Taiko/442/functional-tests/4, 
one thing which was causing flakiness was the size of iframes in the test, since it was very small page's scrollHeight became long causing `firstMeaningfulPaint` event to get triggered after a long time. Updating the size helped to minimise the flakiness still seems to happen occasionally,
suspected mac firewall even turning it off dint affect it.

**Comment by Debashis9012** [comment]
#369

**Comment by NivedhaSenthil** [comment]
one observation is that the test suite works runs fine in parallel when run in headful mode but times out when run in headless mode. Need to investigate if its an upstream bug

**Comment by NivedhaSenthil** [comment]
Works fine with fix ef48f7b
