### ISSUE TITLE
Spike on support for firefox

### ISSUE THREAD

**Issue by NivedhaSenthil** [getgauge/taiko#301]
Some references,
Juggler (patch on firefox to support automation protocol) - https://github.com/GoogleChrome/puppeteer/tree/master/experimental/juggler
Juggler firefox builds - https://storage.googleapis.com/juggler-builds/

**Comment by NivedhaSenthil** [comment]
Currently [Juggler's protocol](https://github.com/GoogleChrome/puppeteer/blob/master/experimental/juggler/src/Protocol.js) has some variations from CDP, thus taiko may not work out of box with Juggler builds.  

If we have to support we will have to reimplement taiko apis using Juggler protocol.
Some reference from firefox regarding CDP experiments https://wiki.mozilla.org/WebDriver/Meetings/2018-11-26.

**Comment by RBLG** [comment]
Hi,
i am a bit confused by the current state of taiko support for firefox, is there some news on it since 2018?
from what i understand so far, taiko need CDP-like API in firefox and since 2018 it seem like firefox made that CDP API under the name Remote (at least as experimental)?
https://wiki.mozilla.org/Remote
So, does that mean anything for taiko, can we expect firefox to be suported in a near future?
(i would like to help but i dont really know how soooo :/ )

**Comment by sriv** [comment]
Hi @rblg, You are correct, Firefox has support for CDP, but not the entire protocol. I believe, Firefox plans to implement CDP endpoints required to support puppeteer for firefox. Taiko requires additional CDP message/events. So the last I checked Taiko was only able to bring up Firefox, but navigation etc are broken.

**Comment by RBLG** [comment]
@sriv ok i see,
is there still hope for a firefox support from what we got/know so far or more waiting has to be expected for anything to be doable?

**Comment by RBLG** [comment]
im asking because if it is possible i could propose to my company to help implement it since we would require it

**Comment by sriv** [comment]
I see where you're coming from, but there is not much that we can do in Taiko to enable this. I believe firefox remote team is working on CDP support, so I wouldn't rule this out just yet. However unless there is support from browser, there is no guarantee.

**Comment by RBLG** [comment]
Ok, thank you for the answers!

**Comment by mrpink76** [comment]
Just read that puppeteer 2.1.0 now has firefox support 🙂

**Comment by zabil** [comment]
Done via https://github.com/getgauge/taiko/pull/1317#event-3452941757
