### ISSUE TITLE
Provide an option to specify custom offset for nearby

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#305]
_From @sguptatw on December 24, 2018 10:3_

**Expected behavior**
Provide an option to specify custom offset

**Actual behavior**
There is no way to specify a custom offset for nearBy

**Example**
```
const { browser, openBrowser, goto, click,comboBox } = require('taiko');

(async () => {
    try {
        await openBrowser({headless:false});
        await goto("google.com");
        await click("I'm Feeling Lucky");
        await click("About");
        await comboBox(near(inputField({"placeholder":"Search Doodles"}),{"offset":"40"})).select("‪हिन्दी‬");
        await click("Doodles संग्रह");
        await closeBrowser();
    } catch (e) {
        console.error(e);
    } finally {
    }
})();
```
> This should pass. Currently the offset is 37px between the combo and the inputField

**Version**
commit - c184a28f73a14c8bfd25a9c9f3e319c0c3b23a02

_Copied from original issue: getgauge/gauge-vscode#320_

**Comment by sguptatw** [comment]
Can we consider https://github.com/getgauge/taiko/issues/270#issuecomment-449789545 while implementing this?

**Comment by NivedhaSenthil** [comment]
Since `px` is also proportional to resolution we will stay with that. 
References:
https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag?redirectlocale=en-US&redirectslug=Mobile%2FViewport_meta_tag#A_pixel_is_not_a_pixel, https://webplatform.github.io/docs/tutorials/understanding-css-units/

**Comment by sguptatw** [comment]
The FT for offset passes locally with value 50. However on CI it is failing to find the comboBox nearBy given the same offset. https://build.gauge.org/go/tab/build/detail/Taiko/422/functional-tests/1/linux-specs
Needs investigation

**Comment by NivedhaSenthil** [comment]
It is failing because the site is rendering differently in CI https://build.gauge.org/go/files/Taiko/424/functional-tests/1/linux-specs/reports/html-report/specs/selectors.html

**Comment by sguptatw** [comment]
The test has now been changed however it is now failing 'cause nearby is selecting the wrong element https://github.com/getgauge/taiko/issues/335
