### ISSUE TITLE
The script seems to hang when element not found

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#306]
**Expected behavior**
The script should not hang when element not found

**Actual behavior**
The script seems to hang when element not found

**Steps to replicate**
* Run the following script
```
const { browser, openBrowser, goto, click,comboBox } = require('taiko');

(async () => {
    try {
        await openBrowser({headless:false});
        await goto("google.com");
        await click("I'm Feeling Lucky");
        await click("About");
        await comboBox(near(inputField({"placeholder":"Search Doodles"}))).select("‪हिन्दी‬");
        await click("Doodles संग्रह");
        await closeBrowser();
    } catch (e) {
        console.error(e);
    } finally {
    }
})();
```
> Blocks #270

**Version**
commit - c184a28f73a14c8bfd25a9c9f3e319c0c3b23a02

**Comment by NivedhaSenthil** [comment]
`await closeBrowser()` missing in `finally` or `catch` block. 
Action on failure has to be handled if user code captures it.
