### ISSUE TITLE
Drag and drop should drop the element in the selected element

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#308]
**Expected behavior**
Drag and drop should drop the element in the selected element

**Actual behavior**
It does not drop in the specified location

**Steps to replicate**
```
const { openBrowser, goto, text, inputField, rightClick, $, dragAndDrop } = require('taiko');
(async () => {
    try {
        await openBrowser();
goto("https://www.w3schools.com/HTML/html5_draganddrop.asp",{timeout:60000});
        await dragAndDrop($("#drag1"),$("#div2"));
    } catch (e) {
        console.error(e);
    } finally {
        await closeBrowser();
    }
})();
```
**Version**
commit - c184a28f73a14c8bfd25a9c9f3e319c0c3b23a02

> Blocks #107

**Comment by NivedhaSenthil** [comment]
Happening because of https://github.com/getgauge/taiko/issues/279
