### ISSUE TITLE
Should be able to attach a file

### ISSUE THREAD

**Issue by sswaroopgupta** [getgauge/taiko#309]
**Expected behavior**
Should be able to attach a file

**Actual behavior**
Getting an error `Error: Custom selector $([object Object]) not found, run `.trace` for more info.`

**Steps to replicate**
* Create a newFile.html
```
<html>
<body>
​
<form action="/action_page.php">
  <input id="some" type="file" name="pic" accept="image/*">
  <input type="submit">
</form>
​
<p><strong>Note:</strong> The accept attribute of the input tag is not supported in Internet Explorer 9 (and earlier versions), and Safari 5 (and earlier).</p>
<p><strong>Note:</strong> Because of security issues, this example will not allow you to upload files.</p>
​
</body>
</html>
```
* In the REPL
```
> goto("file:///.../newFile.html")
 ✔ Navigated to url "file:///.../newFile.html"
> attach('/Users/sswaroop/Downloads/html-report.zip', to($({"id":"some"})))
 ✘ Error: Custom selector $([object Object]) not found, run `.trace` for more info.
```
> Blocks #107

**Comment by NivedhaSenthil** [comment]
`$` selector accepts only css/xpath selectors. try 
`attach("/Users/sswaroop/Downloads/html-report.zip",$('*[id="some"]'))`
or `attach("/Users/sswaroop/Downloads/html-report.zip",fileField({id:'some'}))`
