### ISSUE TITLE
npm install fail in internal pipeline

### ISSUE THREAD

**Issue by lchrennew** [getgauge/taiko#314]
Hi, there!

I want to integrate my test project into my CI pipeline which is isolated from public network.
My shell runs `npm install --registry=<My internal npm mirror>` and it fails because it will download gauge runner and chromium from public network.

My question is: is there any way that I can install taiko successfully without access to public network by shell?

**Comment by NivedhaSenthil** [comment]
Hi @lchrennew chromium installation can be skipped by setting `TAIKO_SKIP_CHROMIUM_DOWNLOAD` env variable to `True` or custom chromium download path can be given using `TAIKO_CHROMIUM_URL` and custom executable path can be given using ` TAIKO_BROWSER_PATH` during runtime.
Some reference on env variables #246.

**Comment by lchrennew** [comment]
> And installing taiko does not download gauge runner

`npm install @getgauge/cli` does

**Comment by lchrennew** [comment]
> And installing taiko does not download gauge runner

`npm install @getgauge/cli` does

**Comment by lchrennew** [comment]
> And installing taiko does not download gauge runner

And how about installing @getgauge/cli ?

**Comment by NivedhaSenthil** [comment]
Installing @getgauge/cli installs taiko but not vice versa.

**Comment by NivedhaSenthil** [comment]
Correction even installing @getgauge/cli does not taiko, only with `gauge init js` taiko is installed.

**Comment by NivedhaSenthil** [comment]
To summarise the discussion. 
Below env variables can be used for custom chromium,
TAIKO_SKIP_CHROMIUM_DOWNLOAD - (true/false) to skip chromium download when installing taiko
TAIKO_CHROMIUM_URL - custom download url for chromium to be set when installing taiko
TAIKO_BROWSER_PATH  - custom browser executable path to be used runtime

Installing taiko does not install gauge runner and installing @getgauge/cli  does not install taiko.
Only when `gauge init js` is used to initialise a gauge-js project it will download taiko as the sample is written using taiko.
