### ISSUE TITLE
Intelligently find input fields bound to element painted like them 

### ISSUE THREAD

**Issue by NivedhaSenthil** [getgauge/taiko#317]
### Expected behavior
Should be able to do action on hidden input fields as it a common practice to paint other element like input fields and bind them to actual hidden fields for form actions. Or provide better message to guide fetching right element.

### Actual behavior
Currently there is no way to find any hidden input field bound to elements painted like them, User have to manually inspect dom to do actions on such kind of elements.

### Steps to reproduce
```
const { openBrowser, goto, inputField, into, below, write, press, reload, text, link, click, focus, button, toLeftOf, radioButton } = require('taiko');
(async () => {
    try {
        await openBrowser({headless:false});
        await goto("https://www.makemytrip.com/");
        await write("Bangalore",inputField(below("From")));
        await press("Enter");
        await write("Goa");
        await press("Enter");
        await click(link("21",below(text("December"))));
        await focus(inputField(below("Return")));
        await click(link("24",below(text("December"))));
        await click(button("Search"));
        await radioButton(toLeftOf("IndiGo 6E-6236")).select()
    } catch (e) {
        console.error(e);
    } finally {
        await closeBrowser();
    }
})();
```
Currently says radio button not found as it is hidden, but there is `span` bound to the radiobutton on which action has to be performed.

**Comment by varayal** [comment]
I'm under the impression taiko text() ignores hidden elements.

I'm running a script that uses  `await text('Resumen de tu pedido').exists(timeoutSecs(15))` and I got a this error

`# Order creation with Cash on Delivery
  ## Make sure the order is created with Cash on Delivery in MX	 ✔ ✔ ✔ ✘
        Failed Step: Click on PROCESAR COMPRA
        Specification: specs/order/MX/cod.spec:10
        Error Message: Error: Object id doesn't reference a Node
        Stacktrace:
        Error: Object id doesn't reference a Node
            at _enqueueCommand (node_modules/chrome-remote-interface/lib/chrome.js:90:34)
            at Chrome._handleMessage (node_modules/chrome-remote-interface/lib/chrome.js:252:17)
            at WebSocket._ws.on (node_modules/chrome-remote-interface/lib/chrome.js:230:22)
            at WebSocket.emit (events.js:189:13)
            at Receiver.receiverOnMessage (node_modules/ws/lib/websocket.js:789:20)
            at Receiver.emit (events.js:189:13)
            at Receiver.dataMessage (node_modules/ws/lib/receiver.js:422:14)
            at perMessageDeflate.decompress (node_modules/ws/lib/receiver.js:379:23)
            at _decompress (node_modules/ws/lib/permessage-deflate.js:298:9)`

I replaced ` await text('Resumen de tu pedido').exists(timeoutSecs(15))` to `    await button('Procesar Compra').exists()` and my script works again

**Comment by NivedhaSenthil** [comment]
@varayal  this issue seems to be happening because of https://github.com/getgauge/taiko/issues/521, can you please verify with the commit version that has the fix?

**Comment by zabil** [comment]
Closing this as it's been a while. Please feel free to re-opne if it it still and issue.
