### ISSUE TITLE
Should be able to record flow with popup from REPL

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#318]
**Expected behavior**
Should be able to record flow with popup from REPL

**Actual behavior**
The control does not come back to the REPL until user manually clicks on the pop-up option

**Steps to replicate**
* Create html
```
<html>
<body>

<h2>The Button Element</h2>
<button type="button" onclick="alert('Hello world!')">Click Me!</button>
 
</body>
</html>
```
* Open the taiko in REPL mode
```
> openBrowser()
 ✔ Browser opened
> goto("file:///.../taikoTestCases/iframes/button.html")
 ✔ Navigated to url "file:///.../taikoTestCases/iframes/button.html"
> click("Click Me!")
 ✔ Clicked element matching text "Click Me!"
```
> The control does not come back to the REPL

**Version**
```
commit - e3952e957e4c49f248c26b1fd9ce7505cc8b57a8
```

**Comment by NivedhaSenthil** [comment]
`alerts` has to be handled using [alert](https://taiko.gauge.org/#alert) api .

**Comment by sguptatw** [comment]
The syntax is something like this
```
    alert('Message 2', async () => await accept());
    await click(button("Alert"));
```
But while recording until the user clicks on the button and then the alert comes up. Though this is a technically feasible solution, it is not user friendly. Is there a better way to record this scenario?

**Comment by NivedhaSenthil** [comment]
Currently not possible, CDP does not provide any api to find if there is a dialog other than listening on `javascriptDialogOpening` which has to be added before the alert is opened so that the event will not be missed.

**Comment by sguptatw** [comment]
Moving this issue to Backlog
