### ISSUE TITLE
Taiko fails to intercept calls with OPTIONS

### ISSUE THREAD

**Issue by saikrishna321** [getgauge/taiko#327]
I was expecting taiko to intercept api and mock data, but it fails when when API calls have both OPTIONS and GET/POST

### Versions
`
Latest master 
Version: 0.4.0 (Chromium:73.0.3638.0)
`

### Code to reproduce:

     await intercept(
       "https://qn2q6ebgr6/sai/product?somthing=",
       req => {
         console.log(req);
       }
     );

i don't see the request getting console.logged

**Comment by NivedhaSenthil** [comment]
Raised a question to verify if there is a better way to intercept requests that triggers preflight requests. https://github.com/ChromeDevTools/devtools-protocol/issues/140 
Until then we can go with the work around of disabling CORS check.

**Comment by zabil** [comment]
I see a lot of testers wasting their time trying to figure that they need to set 

```
await openBrowser({ headless: false, args: ["--disable-web-security"] });
```

For `intercept` to work like https://github.com/getgauge/taiko/issues/1028 this flag should be set by default.
