### ISSUE TITLE
Taiko to allow users to evaluate page script

### ISSUE THREAD

**Issue by saikrishna321** [getgauge/taiko#329]
Currently, I don't see any way that Taiko can help users to addScript to the current browser session.

The application I test needs local storage to have access_token to use the app else it redirects the users to the login screen which is time killer and its flaky as its thirty party SDK.

Workaround:

`
    client().Page.addScriptToEvaluateOnNewDocument({
      source:
        'console.log(localStorage.setItem("token",JSON.stringify({"access_token":"eyJ0eXAiOiJKV1QiLCJub25jZSI6IkFRQUJBQUFBQUFDNXVuYTBFVUZnVElGOEVsYXh0V2pUT3g0e"})))'
    });
`

CDP API:
https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-addScriptToEvaluateOnNewDocument

**Comment by BugDiver** [comment]
@saikrishna321 This [plugin](https://www.npmjs.com/package/taiko-storage) can be used to interact with the browser's storage.
