### ISSUE TITLE
Taiko fails with jest and mocha runner

### ISSUE THREAD

**Issue by saikrishna321** [getgauge/taiko#330]
Tried running taiko with jest and mocha runners and it failed to the launch the session.

```
 TypeError: timeoutId.unref is not a function
        at Promise (/Users/sai.krishna/Documents/git/taiko-pricing/node_modules/taiko/lib/browserFetcher.js:215:23)
        at new Promise (<anonymous>)
        at BrowserFetcher.waitForWSEndpoint (/Users/sai.krishna/Documents/git/taiko-pricing/node_modules/taiko/lib/browserFetcher.js:205:16)
        at Object.<anonymous>.module.exports.openBrowser (/Users/sai.krishna/Documents/git/taiko-pricing/node_modules/taiko/lib/taiko.js:107:43)
        at <anonymous>
```

<img width="1196" alt="screen shot 2019-01-08 at 1 16 48 pm" src="https://user-images.githubusercontent.com/4045041/50833025-dd6c9f80-1347-11e9-8f9d-fe4673a6a154.png">

**Comment by saikrishna321** [comment]
@nehashri @NivedhaSenthil few findings 

When running test with taiko this [line](https://github.com/getgauge/taiko/blob/master/lib/browserFetcher.js#L215) returns the Timeout object when the same test is triggered using jest it returns integer _3_. Removing the unref fixes this. Not sure why unref and what would be the side effects removing the unref.


```
Timeout {
  _called: false,
  _idleTimeout: 30000,
  _idlePrev:
   TimersList {
     _idleNext: [Circular],
     _idlePrev: [Circular],
     _timer: Timer { '0': [Function: listOnTimeout], _list: [Circular] },
     _unrefed: false,
     msecs: 30000,
     nextTick: false },
  _idleNext:
   TimersList {
     _idleNext: [Circular],
     _idlePrev: [Circular],
     _timer: Timer { '0': [Function: listOnTimeout], _list: [Circular] },
     _unrefed: false,
     msecs: 30000,
     nextTick: false },
  _idleStart: 1894,
  _onTimeout: [Function: onTimeout],
  _timerArgs: undefined,
  _repeat: null,
  _destroyed: false,
  domain:
   Domain {
     domain: null,
     _events: { error: [Function: debugDomainError] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] },
  [Symbol(asyncId)]: 37,
  [Symbol(triggerAsyncId)]: 0 }
```

**Comment by jaydeepc** [comment]
Just to add to @saikrishna321 , was going through [this link](https://www.bennadel.com/blog/3301-calling-timeout-unref-with-settimeout-does-not-appear-to-be-a-best-practice-in-node-js.htm) to understand "unref" mystery. And the author talks about not knowing why _unref_ is used at all. Hope this helps!

**Comment by Apoorva-GA** [comment]
To give some background on `unref`, it was added to fix https://github.com/getgauge/taiko/issues/166.
Looks like we need to revisit and see if we can get rid of `unref`.

**Comment by zabil** [comment]
Will be picking this soon.

In the meantime although not the best solution for you (best solution for us though ;) might want to consider using Gauge in the short term.

The syntax of Gauge with Jest is very similar for example

```
step("Do something", async () => {
 await goto('google.com');
});
```

```
test("Do something", () => {
 await goto('google.com');
});
```

Even the hooks have a similar format. When the issue is fixed it should just be a matter of renaming `step` to `test`

getting started with a template is as easy as.

```
gauge init js
```

**Comment by Apoorva-GA** [comment]
@saikrishna321 I have removed the `unref` on timeoutId. Please verify if that solves your issue with jest and mocha runners.

Meanwhile our QA will also verify the same.
Fix available in commit 2d2cc90

**Comment by saikrishna321** [comment]
@Apoorva-GA Works great!!! I'm able to run the test using jest/mocha. Any issues will report back.

Thanks for the fix  🚀

**Comment by jaydeepc** [comment]
Thanks @Apoorva-GA
