### ISSUE TITLE
Add CI into taiko

### ISSUE THREAD

**Issue by saikrishna321** [getgauge/taiko#333]
Team,
I couldn't find any CI configured to build and run taiko master on commit/PR. Would azure pipeline be an appropriate one or is there any that you would suggest?

Happy to pick this and send PR

**Comment by sriv** [comment]
hi @saikrishna321 - adding a pipeling would be great.

For the other repos we run builds on travis and appveyor to cover all the OS we support. But feel free to send a PR with azure as well.

**Comment by saikrishna321** [comment]
@NivedhaSenthil Has the taiko pipeline been authorized with Azure?

**Comment by saikrishna321** [comment]
Sorry my bad, macOS is failing to download gauge 
2019-02-05T21:23:37.4213910Z Fetching download url for Gauge version 1.0.4
2019-02-05T21:23:37.5519380Z Error: No download link found for version 1.0.4, OS: darwin, Arch: x86_64
2019-02-05T21:23:37.5520760Z     at Request.request.get [as _callback] (/Users/vsts/agent/2.146.0/work/1/s/test/functional-tests/node_modules/@getgauge/cli/src/install.js:54:24)

Still the build is Green

**Comment by NivedhaSenthil** [comment]
We need to investigate on why that flakiness is happening. In linux there are two tests which keeps failing intermittently and in windows gauge times out which should not be happening as navigation timeout in taiko is 30s whereas gauge step timeout is 60s, Taiko should have timed out before.
