### ISSUE TITLE
browser back and forward functionality

### ISSUE THREAD

**Issue by jaydeepc** [getgauge/taiko#339]
### Expected behavior
A functionality to perform going back and forward in browser. This is specifically needed to check scenarios like Session timeout, checking specific things after clicking back and forward.

### Actual behavior
The functionality does not exist.

**Comment by NivedhaSenthil** [comment]
Fix available in c61e1c9

**Comment by NivedhaSenthil** [comment]
This needs to be tested before closing.

**Comment by Debashis9012** [comment]
Browser navigations apis `goBack` and `goForward` working as excepted.
Tested with the below version
`0.5.0 (Chromium:73.0.3665.0)`

**Comment by saikrishna321** [comment]
@Debashis9012 `0.5.0 (Chromium:73.0.3665.0)` is released version. You needs to mention the commit you verified

**Comment by Debashis9012** [comment]
@saikrishna321  Have updated my comments.
