### ISSUE TITLE
Feature Request: Press "Down Arrow" & currentFocused selector

### ISSUE THREAD

**Issue by lchrennew** [getgauge/taiko#344]
Hi there,
I want two features:
1. support `press('Down Arrow')`
2. support `textField(currentFocused)` in order to do further assertion

**Comment by negiDharmendra** [comment]
@lchrennew 
> support press('Down Arrow')

Please use `ArrowDown` instead of `Down Arrow`. Refer to [this doc](https://github.com/getgauge/taiko/blob/master/lib/USKeyboardLayout.js) for a list of supported key in [press](https://taiko.gauge.org/#press) API.

**Comment by negiDharmendra** [comment]
> support textField(currentFocused) in order to do further assertion.

It would be great if you can provide more information about your use case.
You can also try [write](https://taiko.gauge.org/#write) API.

**Comment by jaydeepc** [comment]
@lchrennew , you can use `focus(<selector_for_textfield>)` if that's what you meant.
