### ISSUE TITLE
Provide callback option and args for network emulation

### ISSUE THREAD

**Issue by NivedhaSenthil** [getgauge/taiko#347]
Should be able to pass callback to network emulation like below, 
```
emulateNetwork("Good2g", ()=> {
   goto("google.com")
   write("search")
   click("Google Search")
})
```
and pass it as arg to runner
`taiko google.js --network=Good2g`

Related: #151, #340

**Comment by saikrishna321** [comment]
@NivedhaSenthil 

Should we switch back to default network after the execution within the callback() is completed?

**Comment by NivedhaSenthil** [comment]
Ya taiko should be switching back to default and only the actions within callback should run in given emulation. For setting it globally user can use env variable or it can be added as part of config https://github.com/getgauge/taiko/issues/328 or as a flag when using taiko runner.

**Comment by negiDharmendra** [comment]
#### Proposed behavior for `emulateNetwork` API
----
**Scenarios:**
 - **Without any callback:** Network emulation would be applicable for all subsequent action.
 - **With callback:**  Network emulation would be applicable to the callback only and should switch back to the default network.

**Comment by negiDharmendra** [comment]
There are a few pros and cons.

Pros:

- Makes it clear that only the actions being performed within the callback are running in an emulated network.
- And the user doesn't have to explicitly reset it back to the default network. 
- Works well with tests running in parallel.
    
Cons: 
- Not sure how well will it work with other frameworks

**Comment by sriv** [comment]
Another Con of callback that I can think of is it is perhaps applicable only for one API at a time. So if you wanted to do a combination of simulation (or any other setup), ex. `emulateNetwork` and `emulateDevice` or `setViewPort` when it would lead to nested callbacks. This can lead to some really nasty code, and worse a potentially illegible stacktrace.

ex:

```
emulateNetwork('2g', () => emulateDevice('IPhone 4s', () => {//actual test}))
```

**Comment by NivedhaSenthil** [comment]
For consistency across api's we will follow start and stoping of emulation.
