### ISSUE TITLE
Should click visible link elements

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#35]
**Actual behavior**
Tries to click a hidden anchor element

**Steps to replicate**
* Create a directory test
`git clone https://github.com/getgauge/taiko.git`
* Checkout branch taiko-cri
`git checkout taiko-cri`
* install taiko
npm install <fullPath> -g
* Create a testDirectory
Add file visibleLinks.js
```
const { browser, openBrowser, goto, click, link, listItem, title } = require('taiko');
(async () => {
    try {
        await openBrowser();
        await goto("https://gauge.org/");
        await click("Plugins",{waitForNavigation:true});
        await click(listItem("Reports"));
        await click(link("Read more"),{waitForNavigation:true});
    } catch (e) {
        console.error(e);
    } finally {
        if (browser()) {
            closeBrowser();
        }
    }
})();
```
* run this `taiko visibleLinks.js`
> Times out - cannot find element

**Version**
```
Version: 0.0.9 (HeadlessChrome/69.0.3452.0)
```
Blocks #29

**Comment by NivedhaSenthil** [comment]
Fix done in [commit](https://github.com/getgauge/taiko/commit/3ba3d752db0ac55bc8794566a1f1d3e97f5bc23f)
