### ISSUE TITLE
Feature suggestion: get browser URL

### ISSUE THREAD

**Issue by NicholasEF** [getgauge/taiko#351]
### Expected behavior
Would like ability to get a handle on window's current URL, to run assertions against it, or perform other checks.

### Actual behavior
Taiko does't provide a direct handle on this, but other functions do use:
`runtimeHandler.runtimeEvaluate('window.location.toString()');`

Also don't seem to be able to get a handle on this using `evaluate`, which looks to primarily be intended for browser page elements.

### Proposed changes (can submit a PR if preferred)
`taiko.js`
```
/**
 * Returns window's URL.
 * 
 * @example
 * var myURL = getURL();
 * assert(myURL.includes('/sign_in/'));
 *
 * @returns {Promise<String>}
 */
module.exports.getURL = async () => {
    validate();
    const windowURL = await runtimeHandler.runtimeEvaluate('window.location.toString()');
    return(windowURL.result.value);
};
```
```
module.exports.metadata = {
    'Browser actions': ['..., 'getURL'],
```

### Versions
```
`node 6.5.0` and `taiko 0.5.0`
```

**Comment by NivedhaSenthil** [comment]
>Also don't seem to be able to get a handle on this using evaluate 
 
`await evaluate(()=>{return window.location.toString()})` should give that

Will be great if a PR can be created and the api can be `URL` or `currentURL` to keep it consistent with other apis like `title`

**Comment by NicholasEF** [comment]
Ah OK, I will use evaluate in that format for now. 

JD's fork looks great, very thorough. Would love to see that in master soon, or even a new release, along with all the recent optimizations. Thanks!
