### ISSUE TITLE
Refractor and split taiko.js

### ISSUE THREAD

**Issue by SrinivasanTarget** [getgauge/taiko#352]
The idea behind this card is to split taiko.js (2.5k lines) into separate files/classes,

- Browser specific functions
- Page specific functions
- Element specific., etc

**Comment by zabil** [comment]
(Something to keep in mind while splitting)

It's originally kept as a single file to make sure that user has
* Only one import
* Jump to documentation and source in one step from the IDE
* Easy to generate documentation
