### ISSUE TITLE
Open Browser with popup allowed

### ISSUE THREAD

**Issue by joshianurag21** [getgauge/taiko#355]
### Expected behavior
Chromium browser should be opened with all popup allowed with --disable-popup-blocking option.

### Actual behavior
Chromium browser is getting opened but with all popups blocked even we used --disable-popup-blocking option

### Steps to reproduce
1. Please find below before suite code:
beforeSuite(async () => {
    await openBrowser(
        {
            headless: false ,
            args: ['--disable-popup-blocking']
        });
}); 
2. It is opening a chromium browser, but with all popups blocked. Because of which my goto() function is not working. 

### Versions
```
node version: v8.10.0
taiko version: 0.5.0
```

**Comment by NivedhaSenthil** [comment]
I could disable pop up blocking in the below example, 

```
(async () => {
    try {
        await openBrowser();
        await goto("http://www.popuptest.com/popuptest1.html");
        await closeBrowser();
        await openBrowser({args:['--disable-popup-blocking']});
        await goto("http://www.popuptest.com/popuptest1.html");
    } catch (e) {
        console.error(e);
    } finally {
        await closeBrowser();
    }
})();
```
Could you explain your scenario more? seems to be a different issue

**Comment by joshianurag21** [comment]
This http://www.popuptest.com/popuptest1.html works for me as well. 

But the page that I am trying to redirect to has a authentication popup where user is supposed to enter username and password. 
When I am trying to automate this flow using goto() function authentication popup is not coming up and my test is getting timed out. Can you please suggest a way to achieve this.

Screenshot:
![image](https://user-images.githubusercontent.com/20928877/51472011-47506480-1d9e-11e9-854f-55773b4b81d0.png)

In chromium browser when I disable popup blocker, I was able to open required page manually.

**Comment by saikrishna321** [comment]
@joshianurag21  

> function authentication popup is not coming up 

coz you have set the argument as {args:['--disable-popup-blocking']} to openBrowser()

So in this case you want to enter the userName and password as valid flow right ?

**Comment by joshianurag21** [comment]
@saikrishna321 
The solution provided by you worked like a charm !!!!! Thank you.

**Comment by NivedhaSenthil** [comment]
Great that it worked, Closing the issue.
