### ISSUE TITLE
Navigation took more than undefinedms

### ISSUE THREAD

**Issue by saikrishna321** [getgauge/taiko#357]
When the goto API has headers as options and timeout missing throws undefinedms error

> goto('http://the-internet.herokuapp.com/basic_auth',{headers:{'Authorization': 'Basic YWRtaW46YWRtaW4='},waitForNavigation:false})
 ✘ Error: Navigation took more than undefinedms. Please increase the timeout., run `.trace` for more info.

**Comment by NivedhaSenthil** [comment]
Fix available in 6e9aa9f

**Comment by Debashis9012** [comment]
Working as excepted. Currently its displaying the time period if it takes more than defined time.
Tested Version:
```6e9aa9f```
