### ISSUE TITLE
Functional tests against one website

### ISSUE THREAD

**Issue by nehashri** [getgauge/taiko#363]
Currently the Functional tests are against many different websites. Ideally, we should be able to write tests against a single website.
http://the-internet.herokuapp.com/ website captures prominent and ugly functionality found on the web and serves as a good testing platform.
Create tests against each of the available examples in http://the-internet.herokuapp.com/

**Comment by zabil** [comment]
The functional tests now runs on a local version of the internet express app.
https://github.com/getgauge/taiko/blob/919f776de73185ab4c497916d4244448d9e3d715/test/functional-tests/specs/pageActions.spec#L4
