### ISSUE TITLE
Not possible to click wrapped link

### ISSUE THREAD

**Issue by mk654321** [getgauge/taiko#366]
### Expected behavior
click(link("...")) should open the link if link is wrapped unevenly

### Actual behavior
If the link is wrapped unevenly eg:

"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW 
taiko.gauge.org"

centre of the element is not clickable therefore it is not possible to open a link using 
click(link("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW taiko.gauge.org"))
The link gets "red highlight" as if it was clicked however and taiko reports a success opening the link however the target page does not open.

### Steps to reproduce
1. $ ./mygaugeproject/node_modules/.bin/taiko
> openBrowser({args:['--no-sandbox', '--disable-setuid-sandbox']})
 ✔ Browser opened
> goto("file:///path/to/wrappedLink.html")
 ✔ Navigated to url "file:///path/to/wrappedLink.html"
> click(link("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW taiko.gauge.org"))
 ✔ Clicked link with text WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW taiko.gauge.org 
> 

### Gauge version
```
Gauge version: 1.0.3
Commit Hash: ff6c0c3

Plugins
-------
html-report (4.0.6)
js (2.3.2)
screenshot (0.0.1)

```
### Taiko version
```
Version: 0.3.0 (Chromium:71.0.3563.0)
```

### Example of html page:
```
<html>
	<head><title>Wrapped link</title></head>
	<body>
		<div style='font-family:monospace; width: 25em;'><a href='https://taiko.gauge.org'>WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW taiko.gauge.org</a></div>
	</body>
</html>

```

**Comment by saikrishna321** [comment]
With the below HTML when click action is performed, taiko fails 

```
Error: Link with text WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW taiko.gauge.org  is coverred by other element
    at click (/Users/saikrisv/git/taiko/lib/taiko.js:609:15)
    at <anonymous>
```
```
<html>
	<head><title>Wrapped link</title></head>
	<body>
		<div style='font-family:monospace; width: 25em;'><a href='https://taiko.gauge.org'>WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW taiko.gauge.org</a></div>
	</body>
</html>
```

**Comment by mk654321** [comment]
Found a work-around:
focus(link("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW taiko.gauge.org"))
press("Enter")

**Comment by saikrishna321** [comment]
@zabil @NivedhaSenthil  it would be great to have API like 

```
click(link(startsWith("something")));
```

**Comment by NivedhaSenthil** [comment]
Wont be fixing this currently, please follow the work around suggested by @mk654321.
@saikrishna321  please add your thoughts here https://github.com/getgauge/taiko/issues/286 for partial text matching
