### ISSUE TITLE
Timeout error when we run from terminal in 100 percent maximise mode

### ISSUE THREAD

**Issue by Debashis9012** [getgauge/taiko#369]
### Excepted behaviour 
Should not through timeout error

### Actual behaviour
Throwing timeout Error

** Steps to reproduce **
> Observed in mac

* open terminal type "taiko"
* maximise terminal 100 percent
* Write the below commands 
  openBrowser();
  goto("google.com")

### Observation:
 Browser is navigated to the url "google.com"
 but in terminal is throwing the below error message:
 ` ✘ Error: Navigation took more than 30000ms. Please increase the timeout., run `.trace` for more info.`
 This happens when the terminal is in maximise mode.

**Comment by NivedhaSenthil** [comment]
Fix available in a12670c

**Comment by Debashis9012** [comment]
Its working as excepted.
Tested with the below version
`a12670c`
