### ISSUE TITLE
Update taiko runner to use CLI framework

### ISSUE THREAD

**Issue by NivedhaSenthil** [getgauge/taiko#370]
Spike on available CLI framework and incorporate it with taiko runner as there are more command line args being added and the code is becoming complicated handling all cases.

**Comment by SrinivasanTarget** [comment]
@NivedhaSenthil @zabil I would rather not close the PR's rather merge that and provide an option to users temporarily and hear back from our users till this been picked up. @saikrishna321 thoughts?

**Comment by negiDharmendra** [comment]
I have analyzed a few libraries as an option to the CLI framework.

### [oclif](https://github.com/oclif/oclif)
#### Pros
- Well maintaned
- Supports difrrent types of options/flags ( `boolean`, `string`, `number`)
- Supports args
#### Cons
- Does not support non boolean options with optional value.
   Example: `taiko --observe` | `taiko --observe 5000`
- Does not provide version and help option out of the box.

### [yargs](https://github.com/yargs/yargs)
#### Pros
- Well maintaned.
- Supports difrrent types of options/flags ( `boolean`, `string`, `number`).
- Supports args.
- Provides `version` and `help` option out of the box.
#### Cons
- Does not support non boolean options with optional value.
   Example: `taiko --observe` | `taiko --observe 5000`

### [commander]()
#### Pros
- Well maintaned.
- Supports difrrent types of options/flags ( `boolean`, `string`, `number`).
- Supports args.
- Provides `version` and `help` option out of the box.
#### Cons
- Does not support non boolean options with optional value.
   Example: `taiko --observe` | `taiko --observe 5000`


### [minimist]()
#### Pros
- Light weight
- Supports different types of options/flags ( `boolean`, `string`, `number`)
#### Cons
- Not maintained. Ative development was stopped after `Aug 29, 2015`
- Does not provide version and help option out of the box.

[commander-vs-oclif-vs-yargs-vs-minimist](https://www.npmtrends.com/commander-vs-oclif-vs-yargs-vs-minimist)

**Comment by zabil** [comment]
Also worthwhile noting that commander is the only library with [zero](https://github.com/tj/commander.js/blob/68545af7130967bc1a35ae30e9567d78c5e56d8a/package.json#L27) dependencies

**Comment by Debashis9012** [comment]
This enhancement has been verified with the below verison.

``` b26eb83 ```
