### ISSUE TITLE
Taiko documentation site is broken in print view

### ISSUE THREAD

**Issue by zabil** [getgauge/taiko#373]
#### Steps to reproduce
* Go to https://taiko.gauge.org
* Print the page and view the print preview.
* The layout is broken

<img width="571" alt="screenshot 2019-01-31 at 9 24 42 am" src="https://user-images.githubusercontent.com/54427/52029663-3213cc80-253a-11e9-9c89-9d79cbe34cbc.png">

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed in preview site.
