### ISSUE TITLE
The ListItem does not let you select list elements based on its indexes

### ISSUE THREAD

**Issue by rakhid** [getgauge/taiko#378]
### Expected behavior
When I define a list using the selector listItem it should let me access the elements of the list based on its indexes

### Actual behavior
When I define a list using the selector listItem it does not let me access the elements of the list based on its indexes

### Steps to reproduce
1. Define any list in DOM using id or class or xpath  eg.
list in DOM looks something like this:
<img width="505" alt="screen shot 2019-02-01 at 2 37 46 pm" src="https://user-images.githubusercontent.com/22073843/52113386-29e98900-262f-11e9-9c81-c508cd6e0707.png">
2.  define it by:
a=listItem($("//div[contains(@class,'searchResultGrid')]"));
3. I cannot access the elements of this list by using any "ElementWrapper" which this listItem returns or even through simple indexing like a[0], a[1].

### Versions
```
taiko: Version: 0.5.0 (Chromium:73.0.3638.0)
node: v8.11.1
Paste `node` and `taiko` versions here.
```

**Comment by zabil** [comment]
> a=listItem($("//ul[contains(@Class,'searchResultGrid')]"));

Does using indexes inside the XPATH work?

```
a=listItem($("//ul[contains(@Class,'searchResultGrid')][2]"));
                                                        ^
```

**Comment by rakhid** [comment]
@zabil NO it doesn't check the screenshot here.
<img width="695" alt="screen shot 2019-02-01 at 3 19 16 pm" src="https://user-images.githubusercontent.com/22073843/52115529-d7ab6680-2634-11e9-9640-851bc783cb5a.png">

**Comment by NivedhaSenthil** [comment]
if using $ selector that alone is sufficient, nesting it inside other selector like listItem is not supported
try `click($("//ul[contains(@class,'searchResultGrid')][0]"))`

**Comment by rakhid** [comment]
@NivedhaSenthil : It's not about using selector $ , It's about defining a List and accessing its elements. You can define the ListItem by using class or ID as well and still not access its elements using indexes. Pls ignore the fact that I used $ selector inside ListItem.

**Comment by NivedhaSenthil** [comment]
But when it is nested inside other selector Taiko wont be able to recognise it, did this `click($("//ul[contains(@class,'searchResultGrid')][0]"))` help ?
out of box support for indices should be added via #288

**Comment by NivedhaSenthil** [comment]
Closing this issue as accessing elements based on index will be handled in #288 . Feel free to open new issue if you face any other problem.
