### ISSUE TITLE
Cannot access the array elements returned by the ElementWrapper function text()

### ISSUE THREAD

**Issue by rakhid** [getgauge/taiko#379]
### Expected behavior
I should be able to access the elements inside the returns array by ElementWrapper function text () either by indexing or any other mechanism

### Steps to reproduce
1. Defined an element as:
a=$("//section[contains(@class,'searchResultCount')]").text();

2. returns  value:
[ '1-30 von 22.608\nSort.' ]

3. No way to access the string inside the array.

a[0] / a [1] doesn't work .

### Versions
taiko: Version: 0.5.0 (Chromium:73.0.3638.0)
node: v8.11.1
Paste `node` and `taiko` versions here.

**Comment by NivedhaSenthil** [comment]
try `a= await $("//section[contains(@Class,'searchResultCount')]").text();` , a[0] should be accessible  once the promise is resolved

**Comment by rakhid** [comment]
<img width="630" alt="screen shot 2019-02-01 at 3 24 19 pm" src="https://user-images.githubusercontent.com/22073843/52115800-894a9780-2635-11e9-8707-f17d2369e971.png">

@NivedhaSenthil  Thank you, It worked. 
pls, include this bit in the documentation as well. It's not very clear from the documentation that it can be achieved using the above.

**Comment by NivedhaSenthil** [comment]
Sure will update docs to reflect async methods properly. And we always welcome Pull requests :) 
Taiko docs can be found here https://github.com/getgauge/taiko/tree/master/docs
