### ISSUE TITLE
Taiko does not respond with click when JS Alert is present

### ISSUE THREAD

**Issue by saikrishna321** [getgauge/taiko#382]
Code to reproduce 

```
const { openBrowser, goto, accept, alert, click, closeBrowser } = require('taiko');
(async () => {
    try {
        await openBrowser({headless: false});
        await goto('http://the-internet.herokuapp.com/javascript_alerts');
        await click('Click for JS Alert');
    } catch (e) {
        console.error(e);
    } finally {
        await closeBrowser();
    }
})();
```

Once has click on JS Alert is performed I was expecting the test to complete. Instead, the click command is not complete and test holds.

<img width="994" alt="screen shot 2019-02-02 at 5 38 51 pm" src="https://user-images.githubusercontent.com/4045041/52167334-7dcc9e80-2711-11e9-8237-1b9a2cbf390f.png">

**Comment by zabil** [comment]
The alert has to be setup before performing the action.
https://gitter.im/getgauge/chat?at=5c3ee7898ce4bb25b8bcce46

Keeping this issue open for the documentation to be updated with an example

**Comment by saikrishna321** [comment]
@zabil Sorry I have updated the original issue. The problem is not with alert the problem is with click action.

**Comment by NivedhaSenthil** [comment]
Seems CDP does not give back control if alert is acted on, need to check if there is any way to get a work around for this.

**Comment by jaydeepc** [comment]
Did a "googling" about this and seems there might be an issue with Chromium itself. Tried handling this with CDP's "handleJavaScriptDialog" but looks like the event is not even getting recognised.

```
module.exports.accept = async (options) => {
  return await page.handleJavaScriptDialog({accept: true});
}
```

**Comment by NivedhaSenthil** [comment]
`alert` can be handled like below, alert listener has to be added before it is triggered

```
(async () => {
    try {
        await openBrowser({headless: false});
        await goto('http://the-internet.herokuapp.com/javascript_alerts');
        await alert('I am a JS Alert',accept);
        await click('Click for JS Alert');
    } catch (e) {
        console.error(e);
    } finally {
        await closeBrowser();
    }
})();
```

**Comment by saikrishna321** [comment]
@NivedhaSenthil this needs to documented

**Comment by Debashis9012** [comment]
This has been verified and fixed in preview portal.

**Comment by amitsarkar007** [comment]
How can I handle an alert which asks for a username and password?

I tried setting up the listener like this
```
await prompt("Username", async () => await accept("admin")); 
await prompt("Password", async () => await accept("admin")); 
await goto("https://the-internet.herokuapp.com/download_secure")
```
But the page simply hangs.

I am able to handle regular alerts and prompts like this
```
await goto("https://the-internet.herokuapp.com/javascript_alerts");
await alert("I am a JS Alert", async () => await accept()); 
await click('Click for JS Alert');
await confirm("I am a JS Confirm", async () => await accept()); 
await click('Click for JS Confirm');
await prompt("I am a JS prompt", async () => await accept("prompt clicked successfully"));
await click('Click for JS Prompt');
```

**Comment by NivedhaSenthil** [comment]
`https://the-internet.herokuapp.com/download_secure` is not an html alert or prompt .. it is a dialog for basic authentication which has to be handled by setting auth headers in goto. Refer https://docs.taiko.dev/#goto.

Example:
```
goto("https://the-internet.herokuapp.com/basic_auth",{headers:{'Authorization':'Basic YWRtaW46YWRtaW4='}})
```
