### ISSUE TITLE
Feature Request: allow random selection or pass several options to select from comboBox

### ISSUE THREAD

**Issue by suleytron** [getgauge/taiko#388]
### Expected behavior
When selecting a option from a comboBox would be good if you could ask for a random selection or pass and array of options to select from to build some entropy into the test scenarios.

### Actual behavior
You have to predefine a specific option to select from those available, every time the test case runs it passes the same option

### Versions
```
Version: 0.5.0 (Chromium:73.0.3638.0)
node v8.15.0
```

**Comment by NivedhaSenthil** [comment]
This can be currently achieved by choosing random number using js. 

```
let options = ['opt1','opt2','opt3'];
let random = Math.floor(Math.random() * Math.floor(options.length));
await comboBox('something').select(options[random]);
```

**Comment by suleytron** [comment]
Hey @NivedhaSenthil that's how I am currently doing it, but thought there might be a more streamlined way. thx

**Comment by zabil** [comment]
It's better to keep randomisation outside the Taiko for better control of the randomisation technique.
However this is a great idea for a plugin https://github.com/getgauge-contrib/taiko-diagnostics/issues/1

**Comment by BugDiver** [comment]
@suleytron Closing this. Please add your thoughts for the plugin this [thread](https://github.com/getgauge-contrib/taiko-diagnostics/issues/1)
