### ISSUE TITLE
Below API should work to select an element in a list

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#39]
**Actual behavior**
Below works when the element is the immediately next element in the DOM. However when inside a list like <ul>...</ul> Getting the following error
```
Error: Element not found
    at elements (.../taiko/lib/taiko.js:968:46)
```

**Steps to replicate**
* Create a directory test
`git clone https://github.com/getgauge/taiko.git`
* Checkout branch taiko-cri
`git checkout taiko-cri`
* install taiko
npm install <fullPath> -g
* Create a testDirectory
Add a insideList.js file with 
```
const { browser, openBrowser, goto, click,below } = require('taiko');
const assert = require("assert");

(async () => {
    try {
        await openBrowser();
        await goto("https://gauge.org/index.html");
        await click(link("Gauge Commands",below(link("Roadmap"))));
        await closeBrowser();
    } catch (e) {
        console.error(e);
    } finally {
    }
})();
```
* run this `taiko insideList.js`
> Getting the above error. 

**Version**
```
Version: 0.0.9 (HeadlessChrome/69.0.3452.0)
```
Blocks #29

**Comment by NivedhaSenthil** [comment]
The text is miss-spelled in gauge.org.  It is "Gauge Commmands" in there.

const { browser, openBrowser, goto, click,below } = require('taiko');
const assert = require("assert");

```
(async () => {
    try {
        await openBrowser();
        await goto("https://gauge.org/index.html");
        await click(link("Gauge Commmands",below(link("Roadmap"))));
        await closeBrowser();
    } catch (e) {
        console.error(e);
    } finally {
    }
})();
```
This script works fine.

**Comment by NivedhaSenthil** [comment]
seems like same issue with #38, element is visible in dom but not in viewport.

**Comment by NivedhaSenthil** [comment]
Fix should be available in [commit](https://github.com/getgauge/taiko/commit/9c8c5093d31870619b46aca7ea0497be1a550351)
