### ISSUE TITLE
To run more than one script as an argument to taiko

### ISSUE THREAD

**Issue by varayal** [getgauge/taiko#391]
Is there any way to execute more than one script as an argument in Taiko?

i.e taiko test1.js test2.js --observe

I noticed when passing two scripts just the only one is being executed.

I'm just trying to execute a list of scripts sequentially (That's my goal)

### Versions
```
➜  tests node -v
v11.8.0
➜  tests taiko -v
Version: 0.5.0 (Chromium:73.0.3638.0)
```

**Comment by NivedhaSenthil** [comment]
Currently not possible with taiko runner.

**Comment by varayal** [comment]
any chance to have it going forward?

**Comment by zabil** [comment]
Unfortunately this won't be implemented as Taiko's runner is designed to be basic and only for simple scripts and feedback.

To run multiple scripts use a full fledged framework like [Gauge](https://gauge.org), [Jest](https://jestjs.io)

Or chain the commands for example in bash

```
$ taiko test1.js --observe; taiko test2.js --observe
```

This way you can even handle cases like running test2 only when test1 fails and run test2 despite test1 failure and so on.

Closing this for now. But feel free to comment and carry forward the discussion.
