### ISSUE TITLE
Timeout error displayed even after navigating to URL successfully.

### ISSUE THREAD

**Issue by Prakash0989** [getgauge/taiko#395]
Issue: I can see the specified URL in launched/navigated successfully but still getting Timeout error. Issue is inconsistent.. sometime I am able to see success message such as “Navigated to url”

Please refer attached screenshot.

### Expected behavior
After successful navigation to URL, timeout error should not be displayed.

### Actual behavior
After successful navigation to URL, timeout error is displayed.

### Steps to reproduce
1. OpenBrowser()
2. goto("http://devtlnx4017.stbc2.jstest2.net/webui/",{timeout:60000})

### Versions
```
Paste `node` and `taiko` versions here.
```

**Comment by saikrishna321** [comment]
@Prakash0989 Do you get the timeout error running your tests in headless as well? Or its always in the REPL?
