### ISSUE TITLE
REPL must display useful information after executing commands

### ISSUE THREAD

**Issue by zabil** [getgauge/taiko#4]
To debug and understand the result on executing commands with taiko. The REPL must display useful information. For e.g

```
>> click("Get Started")
Clicked button "Get Started"
>> scrollDown()
Scrolled down 100 pixels
```

taiko API can return functions that's parsed and displayed by the REPL

**Comment by zabil** [comment]
This must also handle error conditions. Prefix a status (tick/cross or ok/not ok)
```
>> click("Get Started") 
ok - Clicked button "Get Started"
>> click("Get Started")
not ok - Cannot find any element with the text "Get Started"
```

**Comment by kashishm** [comment]
Implemented.

**Comment by sguptatw** [comment]
**Expected behavior**
>> click("element not present")
not ok - Cannot find any element with the text "element not present"

**Actual behavior**
>>click("element not present")
 Error: Navigation Timeout Exceeded: 30000ms exceeded, run `.trace` for more info.

**Comment by zabil** [comment]
That's the correct behavior.

Click must wait for the element as in single page applications the pages are not rendered upfront. Elements can be rendered after actions on the page.

**Comment by sguptatw** [comment]
On Windows Command prompt the tick and cross mark do not appear. A ? appears instead

<img width="336" alt="unicode" src="https://user-images.githubusercontent.com/6310197/32877086-b81ae8ac-cac5-11e7-963d-e0e09bfcf833.png">

**Comment by kashishm** [comment]
Windows output
```
> openBrowser()
[PASS] Browser and page initialized
> closeBrowser()
[PASS] Browser and page closed
> closeBrowser()
[FAIL] Error: Browser or page not initialized...
```
