### ISSUE TITLE
click(link(toLeftOf('text'))) can't find appropriate link adjacent to identifier to select.

### ISSUE THREAD

**Issue by suleytron** [getgauge/taiko#400]
Linked to issue  #397 
### Expected behavior
click(link(toLeftOf('text'))) should click the link in a table immediately to the left of the text. 
e.g click(link(toLeftOf('flight alcohol test'))) should click '1000028968'.

![screen shot 2019-02-12 at 5 15 50 pm](https://user-images.githubusercontent.com/5919033/52713486-57b7c180-2f8f-11e9-8d7c-0322a4c2bcc5.png)

### Actual behavior
Taiko is unable to 'see' this link and instead clicks the top left of the screen and takes user home.

### Steps to reproduce
1. click(link(toLeftOf('flight alcohol test')))
2. Taiko clicks outside of the table on home button
3. The html in txt format [table.txt](https://github.com/getgauge/taiko/files/2860453/table.txt)

### Versions
```
npm install -g taiko@git+https://github.com/getgauge/taiko.git latest REPL
```

**Comment by NivedhaSenthil** [comment]
From the html I understand the product Ids are not actually a link rather they are span,
`click($('.menulink',toLeftOf('flight alcohol test')))` hopefully should work for this case.

**Comment by saikrishna321** [comment]
<img width="962" alt="screen shot 2019-02-14 at 8 16 27 am" src="https://user-images.githubusercontent.com/4045041/52772630-dfa1d800-3030-11e9-82db-1dee605a7554.png">

**Comment by Prakash0989** [comment]
It is working fine. Thanks for the solution.
