### ISSUE TITLE
exists functionality is broken does not take interval and timeout anymore

### ISSUE THREAD

**Issue by NivedhaSenthil** [getgauge/taiko#406]
### Expected behavior
`link('something').exists(1000,20000)` should wait for 20 secs for the element to appear.

### Actual behavior
`exists` method ignores the times given

**Comment by Apoorva-GA** [comment]
Fix should be available in 6bfaede.

**Comment by Debashis9012** [comment]
**Observation:**
It waits to find the web-element for specified interval of time. Based on the observation this issue
has been verified and found fixed. Tested with the below version

``` 6bfaede```
