### ISSUE TITLE
Timeout error after scenario if scenario uses steps from multiple test files

### ISSUE THREAD

**Issue by nwai90** [getgauge/taiko#410]
### Expected behavior
Should move on to next scenario after all steps have passed for a scenario and after Chromium browser has been closed

### Actual behavior
Getting an error message: 
```
Error Message: Error: Timed out
    Stacktrace: 
    Error: Timed out
        at Timeout.<anonymous> (/Users/WC/.gauge/plugins/js/2.3.4/src/test.js:43:23)
        at ontimeout (timers.js:427:11)
        at tryOnTimeout (timers.js:289:5)
        at listOnTimeout (timers.js:252:5)
        at Timer.processTimers (timers.js:212:10)
```

### Steps to reproduce
1. Create a test suite with multiple scenarios, using `beforeScenario(async() => await openBrowser({headless: false}));` for setup and `afterScenario(async() => await closeBrowser());` for cleanup
2. Run test specs

### Versions
Node version: v10.5.0
Taiko version: Version: 0.5.0 (Chromium:73.0.3638.0)

**Comment by Apoorva-GA** [comment]
@nwai90 I am able to run the spec with multiple scenarios successfully.

The attached is the sample project I am running.
[tmp.zip](https://github.com/getgauge/taiko/files/2883320/tmp.zip)

Versions
Node : v11.7.0
taiko : Version: 0.5.0 (Chromium:73.0.3665.0)

**Comment by NivedhaSenthil** [comment]
If there are lot of actions in your step which takes time, you can try increasing the gauge step timeout `test_timeout = 120000` in `env/default/js.properties`  it takes time in milliseconds.

**Comment by nwai90** [comment]
Hi @Apoorva-GA @NivedhaSenthil I tried increasing timeout; this doesn't help as all the steps are already passing - the timeout happens only at the very end of each scenario.

I did however manage to reproduce the issue, and have attached a modified version of the sample project.

In the attached example, the workflows to be automated have been organised into different phases (using a pipelined approach). Each test file comprises several steps that may be grouped by domain or other logic, and a single scenario might include one or more steps from each test file.

The timeout at end of scenario seems to occur whenever a scenario uses steps from multiple test files, even though every file already contains an `afterScenario` cleanup step.
[tmp.zip](https://github.com/getgauge/taiko/files/2883551/tmp.zip)

**Comment by Apoorva-GA** [comment]
@nwai90 I see that you have two `afterScenario` hooks defined in the project. Gauge executes all the hooks defined. Since one `afterScenario` had already closed the browser when executing the other hook the step is timing out.

**Comment by nwai90** [comment]
@Apoorva-GA I see, was under the impression that only the hooks in files that contained steps which would be run for a given scenario would be executed. Just tried and it works well if all extra `afterScenario` hooks are removed. Many thanks for your help; will close this issue.

**Comment by gokultw** [comment]
I'm also facing this issue intermittently, I have an after-scenario hook that stops the video recording and closes the browser.
Randomly I'm getting this error.

```
 beforeSuite - clear video record directory
            beforScenario - openBrowser & startVideo Recording
            afterScenario - stop video recording, delete video file if the test is passed & close the browser
 afterSuite - empty
 ```

 After-scenario is failing randomly
