### ISSUE TITLE
API to simulate touch

### ISSUE THREAD

**Issue by ErRei** [getgauge/taiko#411]
Hey there,

this is my first "Issue" in github, so im not sure how to mark this as a feature request.

I am currently writing tests for a mainly mobile used website. It would be nice to have touch events to interact with the website. 
To have some kind of motion like swipe would be awesome. Maybe touchStart and touchEnd with some coordinates?

### Expected behavior
Interact with the website with touch events. 

### Actual behavior
Not implemented right now.

Thank you in advance.

**Comment by saikrishna321** [comment]
>> I am currently writing tests for a mainly mobile used website

Can you please elaborate more on this? Are you emulating a device resolution and then its mobile site?

**Comment by ErRei** [comment]
We are using a webview to deploy the application on mobile devices. But we are testing outside of this webview and emulate device resolution.

My main reason for this feature request is, that we currently swipe list items to delete them. It would be nice if this is testable with taiko. Maybe I've should have wrote in first place...
But all touch-event would be handy.

**Comment by saikrishna321** [comment]
> that we currently swipe list items to delete them 

Is the element loaded in the dom or only on swipe the element loads?


can you see if these API would help https://taiko.gauge.org/#scrollup

**Comment by ErRei** [comment]
It's loaded but hidden. And it shows up on touch/swipe.
I already tried scroll and drag and drop. Both didn't work for me.

**Comment by NivedhaSenthil** [comment]
There is an api to simulate touch in CDP https://chromedevtools.github.io/devtools-protocol/tot/Input/#method-dispatchTouchEvent, we could make use of that to simulate touch events like swipe, tap etc.

**Comment by NivedhaSenthil** [comment]
Closing since `tap` api is implemented in Taiko https://docs.taiko.dev/api/tap/
