### ISSUE TITLE
Provide option to give custom events to wait for navigation

### ISSUE THREAD

**Issue by NivedhaSenthil** [getgauge/taiko#414]
Currently `goto` by default waits for `LoadEventFired` `NetworkIdle` and `FirstMeaningfulPaint`. Provide option to wait for custom events so that user will have flexibility to choose events based on scenarios. Default event can `FirstMeaningfulPaint` if not overridden.

**Comment by NivedhaSenthil** [comment]
Fix available in 86ded09. Can be used like `await goto("google.com",{waitForEvents:['loadEventFired']})`

**Comment by Debashis9012** [comment]
This enhancement has been verified with the below version.
``` 86ded09 ```
