### ISSUE TITLE
Make goto, reload, goback and forward to use doActionAwaitingNavigation

### ISSUE THREAD

**Issue by NivedhaSenthil** [getgauge/taiko#418]
Cleanup waiting for navigation logic in two places. Currently goto, reload, goback and forward uses different logic and other actions use  `doActionAwaitingNavigation` make both use the same and provide option to wait for custom events for other actions too.

**Comment by Apoorva-GA** [comment]
Should be fixed in 26858ab.

**Comment by Apoorva-GA** [comment]
Things to test: 
APIs :  goto, reload, goBack, goForward and openTab
Also all APIs can now wait for custom events. So that can be tested.

**Comment by Debashis9012** [comment]
Required api has been tested and found fixed with the version ``` 9a876b8 ```
