### ISSUE TITLE
Avoid blocking information from the current tab to an external modal

### ISSUE THREAD

**Issue by varayal** [getgauge/taiko#427]
I'm facing the following issue

As part of my e2e test, I have to pass information (token, SessionID, and others) to another external webpage (modal, popup) when clicking a button.

I noticed when clicking a button the modal is being opened but it remains blank. So I'm under the impression that Chromium is blocking data passing from the current tab to the external modal.

I created the same script using another automation library that uses Chrome instead of Chromium and the modal is being loaded with the proper information as expected.

Any thoughts about which args should I pass to Chromium to avoid blocking data from the current tab to the external modal?

I have attached the screenshot by using taiko.

<img width="594" alt="screen shot 2019-03-02 at 12 01 11 am" src="https://user-images.githubusercontent.com/15387072/53677993-633d0500-3c7e-11e9-8372-711751b553c4.png">

I have attached the screenshot about the modal using another automation library

<img width="925" alt="screen shot 2019-03-01 at 10 30 54 pm" src="https://user-images.githubusercontent.com/15387072/53677962-ef9af800-3c7d-11e9-804b-1fc907e4fa84.png">

**Comment by varayal** [comment]
An option could be preserving the cookies or changing the browser

**Comment by NivedhaSenthil** [comment]
Can you please give repro for this scenario ?

**Comment by varayal** [comment]
What do you mean with repro?

**Comment by NivedhaSenthil** [comment]
some script that we can use to reproduce the scenario you are facing

**Comment by varayal** [comment]
I just shared to you a private repo with a simple script with test credentials where you can see the issue when pressing the PayPal button.

In addition as part of the script, there is a button called "GUARDAR Y CONTINUAR" - I got a timeout from taiko even when is pressed. It's weird.

Thanks for your help!

**Comment by NivedhaSenthil** [comment]
Fix available in 6b6cba8

**Comment by varayal** [comment]
thank you very much!

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed with ```6d41672```
