### ISSUE TITLE
Should scrollUp should scroll to the first occurrence of element above

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#43]
**Actual behavior**
It is scrolling to the first occurrence of the element on screen

**Steps to replicate**
* Create a directory test
`git clone https://github.com/getgauge/taiko.git`
* Checkout branch taiko-cri
`git checkout taiko-cri`
* install taiko
npm install <fullPath> -g
* Create a testDirectory
Add a scrollUp.js file with 
```
const { browser, openBrowser, goto, listItem, click, link } = require('taiko');
const assert = require("assert");

(async () => {
    try {
        await openBrowser();
        await goto("https://gauge.org/index.html");
        await click(link("Documentation"),{waitForNavigation:true});
        await click("Write Specifications",{waitForNavigation:true})
        await scrollTo(link("Refactoring"))
        await scrollUp("Example")
        await waitFor(5000);

        await closeBrowser();
    } catch (e) {
        console.error(e);
    } finally {
    }
})();
```
* run this `taiko scrollUp.js`
> > There are many Example links on the page above the refactoring link. But scrollUp is taking the screen to the first Example link on the page

**Version**
```
Version: 0.0.9 (HeadlessChrome/69.0.3452.0)
```
Blocks #29

**Comment by NivedhaSenthil** [comment]
`scrollUp` api is used scroll up particular element  and for scrolling to `scrollTo` can be used.
