### ISSUE TITLE
Unable to input value in specified text field using toRightOf("Field name").Instead, inputed under incorrect(Non specified) text field

### ISSUE THREAD

**Issue by Prakash0989** [getgauge/taiko#432]
Scenario/Issue: I have two different fields such as 'Brand Name' and 'Sub Brand Name'. I was trying to input under 'Sub Brand Name' hence i have provided the below code of line(Specified the attribute name) to input under Sub Brand Name

 - > write("test", toRightOf("Sub Brand Name"));

Note: I understand every-time it inputs into the focused element which is not the ideal behavior since user has clearly mentioned to input toRightOf("field name").Refer the screenshot attached. 

### Expected behavior
Should input under Sub Brand Name

### Actual behavior
Inputed under Brand Name

### Steps to reproduce
1. Log into application
2. write("test", toRightOf("Sub Brand Name"));

### Versions
```
Paste `node` and `taiko` versions here.
```
[Inputed against non specified text field.docx](https://github.com/getgauge/taiko/files/2939794/Inputed.against.non.specified.text.field.docx)

**Comment by NivedhaSenthil** [comment]
write does not support direct proximity selectors. Something like below can be done 
`await  write('test',into(inputField(toRightOf("Sub Brand Name"))))`

**Comment by Prakash0989** [comment]
@NivedhaSenthil  As expected below code doesn't input into Sub brand name since i can see the web element html is 'Textarea'. I guess below code will work only if web element html is 'input'. Refer the screenshot attached. can you also add an option to input when web element html is 'Textarea'. If it makes sense. 

<img width="1163" alt="screen shot 2019-03-08 at 10 19 11 am" src="https://user-images.githubusercontent.com/45254050/54008371-72dfb080-418c-11e9-8161-b2565f9a9c90.png">

**Comment by NivedhaSenthil** [comment]
`textField` api can be used to write in that case
`await write('test',into(textField(toRightOf("Sub Brand Name"))))`

**Comment by Prakash0989** [comment]
No luck, still i don't see its working. Refer the screenshot attached. 
<img width="1178" alt="screen shot 2019-03-08 at 10 51 06 am" src="https://user-images.githubusercontent.com/45254050/54009275-2eeeaa80-4190-11e9-8cc1-21c7d3cd7b84.png">

**Comment by NivedhaSenthil** [comment]
Can you please share sample html for your usecase? will be helpful to debug

**Comment by Prakash0989** [comment]
You can always refer my screenshot for html.

<div class="FormFieldWidget" id="Sub_Brand_Name" data-step-component-id="SubBrandName"><textarea class="stibo-Value validator-text stibo-Value-Text"></textarea><div class="value-validation-message"></div></div>

<textarea class="stibo-Value validator-text stibo-Value-Text"></textarea>

**Comment by NivedhaSenthil** [comment]
Need the html with label to find why proximity selector is not able to find textarea next to it, just textarea wont be helpful. Or some other site where we can replicate the issue.

**Comment by Prakash0989** [comment]
Please let me know if this can .
<div class="FormFieldWidget" id="Sub_Brand_Name" data-step-component-id="SubBrandName"><textarea class="stibo-Value validator-text stibo-Value-Text"></textarea><div class="value-validation-message"></div></div>

<img width="1304" alt="screen shot 2019-03-08 at 11 37 00 am" src="https://user-images.githubusercontent.com/45254050/54010873-898b0500-4196-11e9-942e-03b94e85f07e.png">

**Comment by Prakash0989** [comment]
Please let me know if this can be helpful..
----- <div class="FormFieldWidget" id="Sub_Brand_Name" data-step-component-id="SubBrandName">

---- <textarea class="stibo-Value validator-text stibo-Value-Text"></textarea><div class="value-valid
<img width="1304" alt="screen shot 2019-03-08 at 11 37 00 am" src="https://user-images.githubusercontent.com/45254050/54010918-b9d2a380-4196-11e9-98b4-295eb5fe9e93.png">
ation-message"></div></div>

**Comment by Prakash0989** [comment]
please let me know if my attachement helps you. I have added html with label inside the my attachment. 
[html for debug.docx](https://github.com/getgauge/taiko/files/2944563/html.for.debug.docx)

**Comment by Prakash0989** [comment]
#436

**Comment by Prakash0989** [comment]
Linking #436 to address textarea

**Comment by NivedhaSenthil** [comment]
found that the textField api handles only input with type text, will be adding support for textarea and input text both in new api `textBox` and deprecate the existing `textField`

**Comment by NivedhaSenthil** [comment]
as a workaround meanwhile you can try 
`await write('test', into($('textarea',toRightOf('Sub Brand Name'))))`

**Comment by Prakash0989** [comment]
@Prakash0989 Workaround is working fine. Many thanks.Meanwhile Will keep this issue open until feature request #436 is added.

**Comment by NivedhaSenthil** [comment]
Fix to add support for textarea is available in 56c63b9

**Comment by Prakash0989** [comment]
@NivedhaSenthil Thanks for the fix. I installed taiko from master and it worked. Also keep us posted once all these changes are released.

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed. Tested with the below version.

 ``` 56c63b9 ```
