### ISSUE TITLE
API to support textarea.

### ISSUE THREAD

**Issue by Apoorva-GA** [getgauge/taiko#436]
### Expected behavior
Should be able to access textarea with attributes, label or proximity selectors.

### Actual behavior
No support for textarea currently

### Versions
```
taiko : 0.6.0
```

**Comment by NivedhaSenthil** [comment]
Fix available in 56c63b9

**Comment by Debashis9012** [comment]
This feature has been verified and found fixed with the version ```0ae7ff5 ```
