### ISSUE TITLE
Add support to generate plugin template 

### ISSUE THREAD

**Issue by BugDiver** [getgauge/taiko#439]
The commit bdfb5fe400cded6d303b0e3e00e475441f95eecf adds plugin support for taiko.
But the plugin needs to expose some methods which are used by `taiko` to initiate the plugin.
It would be really helpful for plugin authors if `taiko` can generate a basic plugin `template` from the command line.

## Proposal
* Add a `--generate-plugin` command in `taiko` to scaffold the plugin.
* Add  few other options to choose the styling for plugin `babel`, `typescript` or `commonjs`

### Example
1. `taiko --generate-plugin` will scaffold the plugin `commonjs` code.
2. `taiko --generate-plugin --babel` will scaffold the plugin es6 code with `babel` configurations and build scripts.
3. `taiko --generate-plugin --typescript`  will scaffold the plugin Typescript code with relevant configurations and build scripts.

**Comment by zabil** [comment]
Closing this as Gauge will not be implementing this feature.
