### ISSUE TITLE
button selector should select input field with button type.

### ISSUE THREAD

**Issue by sriv** [getgauge/taiko#441]
### Expected behavior
`button` api should select elements of `<input type='button'`.

### Actual behavior
`button` does not select `input` fields.

### Steps to reproduce
1. `goto("http://the-internet.herokuapp.com/upload")`
2. `button("Upload").exists()`
3. Note that the output says `Does not Exist`

### Versions
```
> taiko
Version: 0.7.0 (Chromium:74.0.3723.0)

> node --version
v10.15.3

```

**Comment by Debashis9012** [comment]
After the fix this issue has been verified and found fix. Tested with latest master build.
