### ISSUE TITLE
"Getting Started with Taiko" depends on Locale

### ISSUE THREAD

**Issue by odedpeer** [getgauge/taiko#442]
### Expected behavior
Running "Getting Started with Taiko" should just work.

### Actual behavior
"Getting Started with Taiko" doesn't work because Google uses the browser locale/location to change the text on the buttons.
This is how it looks when I run taiko from Israel:
![image](https://user-images.githubusercontent.com/335466/54126509-63709980-4410-11e9-9ed9-d588febe6541.png)
This might be a problem when sharing scripts in a geo-distributed team.

### Versions
```
Node v8.12.0, Taiko 0.6.0
```

**Comment by NivedhaSenthil** [comment]
Thanks for pointing out, we will look at making the sample generic.

**Comment by shubhamsc** [comment]
The sample of getting started with Taiko is changed from Google to Github search. The fix is available in https://github.com/getgauge/gauge-repository/commit/3564779

**Comment by Debashis9012** [comment]
This has been verified and found fixed.
