### ISSUE TITLE
Support to write in prompt dialog box 

### ISSUE THREAD

**Issue by shubhamsc** [getgauge/taiko#443]
### Expected behaviour
Should to able to write something in a prompt dialog box while accepting it.

### Actual behaviour
Not able to write in a prompt dialog box.

### Steps to reproduce
Run this script 
```
const { openBrowser, goto, prompt, accept, click, closeBrowser } = require('taiko');
(async () => {
    try {
        await openBrowser();
        await goto('http://the-internet.herokuapp.com/javascript_alerts');
        await prompt('I am a JS prompt', async () => await accept('something'));
        await click('Click for JS Prompt');
    } catch (e) {
        console.error(e);
    } finally {
        await closeBrowser();
    }
})();
```
page should have `You entered: something`, but it has `You entered: null`

### Versions
```
node : v11.11.0
taiko : 0.6.0 (Chromium: 73.0.3665.0)
```

**Comment by Debashis9012** [comment]
Tested after the fix. We are able to write the value in dialog box. This issue has been tested and based on the observation this has been fixed. Tested with latest master.

**Comment by MadhavGibikote** [comment]
Hi, I see the same issue in 1.2.3 version of Taiko.
