### ISSUE TITLE
Elements are not found with space

### ISSUE THREAD

**Issue by shubhamsc** [getgauge/taiko#446]
### Expected behaviour
Elements should get with space

### Actual behavior
Not getting the elements with space

### Steps to reproduce
Run this script
```
(async () => {
    try {
        await openBrowser();
        await goto('https://github.com/getgauge/');
        await click('Sign in')
    } catch (e) {
        console.error(e);
    } finally {
        await closeBrowser();
    }
})();
```
Not able to click on `sign in`. In html it is written as `sign&nbsp;in`

**Comment by Debashis9012** [comment]
This issue has been verified and found fix with the version ```f0fa3cb```
