### ISSUE TITLE
There's no way to pass parameters to evaluate callback

### ISSUE THREAD

**Issue by dmolin** [getgauge/taiko#450]
### Expected behavior
When calling `evaluate(callback)` I would expect to be possible to provide arguments for the callback to evaluate when called.

Example: 
```
async function checkPath (path) {
  await evaluate((...args) => {
    console.log(`checking path ${args[0]}`);
  }, { args: [path] } );
} 
```
This is essential when running code in the browser that requires arguments. Lexical context does not apply here, since the callback runs in another context (the browser console), so I cannot simply do something like this:

```
async function checkPath (path) {
  await evaluate(() => {
    console.log(`checking path ${path}`);
  });
} 
```

This comprehensibly fails; The only way I've found to provide parameters to my evaluated code is to set a cookie in the browser before calling `evaluate` (with the JSON.stringified array of params), consume it in the callback and then remove it once the call to evaluate returns.  Definitely a Hack, but I've not been able to find any other way to provide arguments to the callback executed inside of the browser.
### Actual behavior
Evaluate simply cannot provide any argument to the callback. The only argument the callbacks seems receiving is the root node element of my DOM hierarchy (a React node in my case).

### Steps to reproduce
1. Write a taiko test using code with evaluate and try to pass arguments to the callback...

### Versions
All versions

```
node: 8.11.4
taiko: 0.6.0
```

**Comment by Debashis9012** [comment]
This has been verified with tested with the version ``` dd6bb6f ```

**Comment by combinesoma** [comment]
Hi Team -  In the current version of the evaluate API, we need to pass an element along with the args param, is there any way where we can pass only arguments to the callback function?
https://docs.taiko.dev/api/evaluate/
