### ISSUE TITLE
support reverse-i-search on REPL

### ISSUE THREAD

**Issue by sriv** [getgauge/taiko#453]
### Expected behavior
As a terminal user (on bash), I am used to locating commands I've used before by hitting <kbd>CTRL</kbd> + <kbd>R</kbd>. It would be good to have this in `taiko` REPL as well.

### Actual behavior
This is currently not possible.

### Steps to reproduce
1.
2.
3.

### Versions
```
$ node --version
v10.15.3

$ taiko
Version: 0.7.0 (Chromium:74.0.3723.0)

```

**Comment by Debashis9012** [comment]
Now in taiko REPL reverse-i-search supports properly. This feature has been tested and verified with ```6d41672 ```
