### ISSUE TITLE
support contenteditable input

### ISSUE THREAD

**Issue by sriv** [getgauge/taiko#454]
### Expected behavior
Modern browsers allow elements with `contenteditable` attribute set to be edited inline in the browser. Taiko should recognize these editable fields.

### Actual behavior
There isn't a way to locate a field with `contenteditable`.

### Steps to reproduce
1. Sample html"

```
<!DOCTYPE html>
<html>
<body>

<div>Editable Demo</div>
<p contenteditable="true">This is a paragraph. It is editable. Try to change this text.</p>

</body>
</html>
```
2. There is no API to select the contenteditable paragraph.

### Versions
```
$ node --version
v10.15.3

$ taiko
Version: 0.7.0 (Chromium:74.0.3723.0)
```

**Comment by Debashis9012** [comment]
This has been verified and found fixed with the version ```a262d2a ```
