### ISSUE TITLE
Provide option to turn off highlighting element on action

### ISSUE THREAD

**Issue by NivedhaSenthil** [getgauge/taiko#462]
Element on action is highlighted by default and there is no way to turn off that currently. Provide an option so that user can turn off if not needed.

**Comment by saikrishna321** [comment]
@NivedhaSenthil adding an env variable makes sense. `process.env.HIGHTLIGHT = true`

**Comment by Apoorva-GA** [comment]
Added an env variable `TAIKO_HIGHLIGHT_ON_ACTION` with default value `true`.
When `TAIKO_HIGHLIGHT_ON_ACTION` is set to `false`  the element on action will not be highlighted.

Available in commit a466ef8

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed with the commit version ```a466ef8```
