### ISSUE TITLE
Unable to provide input value in text area using "textBox" selector

### ISSUE THREAD

**Issue by Debashis9012** [getgauge/taiko#464]
**Excepted Result:**
Should provide the input value in the text area.

**Actual Result:** 
Input value printed in text box which is available near to the text area field.

**Steps to reproduce:**
1. Navigate to webpage
2. To print the value in "address" test area use the below command:
    write('This is for test',textBox(below('GENDER')));

**Note: Tested with latest master. Kindly find the attached html webpage.**

**Comment by NivedhaSenthil** [comment]
Fix available in d6e6611

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed. Tested with the below version.

```d6e6611 ```
