### ISSUE TITLE
add matchers to help assert on page state

### ISSUE THREAD

**Issue by sriv** [getgauge/taiko#465]
### Expected behavior
There should be some way to add asserts on taiko api values that give proper messages out of the box. Consider adding helpers for something like `chai` so that these are possible:

- `expect(await text('foo')).to.exist` 
- `expect(text('foo')).to.exist // note the lack of await keyword` 

### Actual behavior
The assertions work like this:

`expect(await(text('foo).exists()).to.be.true;`

and this leads to failure messages such as `expected false, got true`

### Versions
```
$ node --version
v10.15.3

$ taiko
Version: 0.7.0 (Chromium:74.0.3723.0)
```

**Comment by zabil** [comment]
Taiko will not be adding this feature as it's much better to use an assertions library for this.
