### ISSUE TITLE
goto should handle 4xx / 5xx http errors

### ISSUE THREAD

**Issue by sriv** [getgauge/taiko#467]
### Expected behavior
When there is a http error 4xx or 5xx taiko should report failure

### Actual behavior
taiko reports navigation successful and goes to execute the next line. As a result, the falure is reported late and with insufficient information.

### Steps to reproduce
1. open taiko repl
2. `openBrowser()`
3. `goto('https://google.com/foo')`
4. observe the console output, it says navigation successful whereas it isn't.

### Versions
```
$ node --version
v10.15.3

$ taiko
Version: 0.7.0 (Chromium:74.0.3723.0)
```

**Comment by NivedhaSenthil** [comment]
Fix available in 8040820

**Comment by NivedhaSenthil** [comment]
Fix for running in windows available in 95d994b

**Comment by Debashis9012** [comment]
This issue has been resolved and found fixed with the version ``` 95d994b ```.

**Comment by galliroberto** [comment]
Why? I expect a 404, ho to check the http status?

**Comment by zabil** [comment]
This was done to point out failures if the original test page became obsolete and returned a 404.
If you want to test a 404 page you could catch the error and check the http status.

**Comment by sriv** [comment]
you can also get the response in a variable and check it like this:

```
const { openBrowser, goto, closeBrowser } = require('taiko');
(async () => {
    try {
        await openBrowser();
        var resp = await goto("https://google.com");
	console.log(`Response status  code = ${resp.status.code}`);
    } catch (error) {
        console.error(error);
    } finally {
        await closeBrowser();
    }
})();
```

**Comment by umairzameer523** [comment]
const { openBrowser, closeBrowser } = require('taiko');
(async () => {
    try {
	;
	openBrowser;
	openBrowser;
        await openBrowser();
        var resp = await goto("https://aamerbackofficeuat.azurewebsites.net");
        	console.log(`Response status  code = ${resp.status.code}`);
    } catch (error) {
        console.error(error);
    } finally {
        await closeBrowser();
    }
})();



Error: Navigation to url https://aamerbackofficeuat.azurewebsites.net failed.
 STATUS: 404, STATUS_TEXT: Not Found
    at Object.handleNavigation (C:\Users\zaidh PC\AppData\Roaming\npm\node_modules\taiko\lib\handlers\pageHandler.js:199:13)
    at async C:\Users\zaidh PC\AppData\Roaming\npm\node_modules\taiko\lib\taiko.js:745:16
    at async doActionAwaitingNavigation (C:\Users\zaidh PC\AppData\Roaming\npm\node_modules\taiko\lib\doActionAwaitingNavigation.js:61:5)
    at async module.exports.goto (C:\Users\zaidh PC\AppData\Roaming\npm\node_modules\taiko\lib\taiko.js:744:3)
    at async module.exports.<computed> (C:\Users\zaidh PC\AppData\Roaming\npm\node_modules\taiko\lib\taiko.js:2620:14)
    at async global.<computed> (C:\Users\zaidh PC\AppData\Roaming\npm\node_modules\taiko\bin\runFile.js:38:15)

why does this error shows i can normly enter my websites without automation but when i try to automate it this error throws
