### ISSUE TITLE
Fix Readme example

### ISSUE THREAD

**Issue by pemalhamutamang** [getgauge/taiko#470]
Example given in the readme is missing an import
Given example
const { openBrowser, goto, write, click } = require('taiko'); // missing closeBrowser

(async () => {
    try {
        await openBrowser();
        await goto("google.com");
        await write("taiko test automation");
        await click("Google Search");
    } catch (e) {
            console.error(e);
    } finally {
            closeBrowser();
    }
})();

Error: closeBrowser is not defined.

### Steps to reproduce
1.Copy the example to file index.js
2.run using node ./index.js
3. running with taiko ./index.js won't give the error.

### Versions
```
node: v10.14.2
taiko: 0.6.0
```

**Comment by NivedhaSenthil** [comment]
fix done via #471.

**Comment by Debashis9012** [comment]
Read me file has been rectified correctly.
