### ISSUE TITLE
Element not found error but gauge test is passed

### ISSUE THREAD

**Issue by shahidawan1** [getgauge/taiko#476]
### Expected behavior
Either the test should be failed if there is an error element not found or if test is passed why its showing error

### Actual behavior
Test was executed but gauge prompts an error that "element is not found" but test result shown is passed.

### Steps to reproduce
![download](https://user-images.githubusercontent.com/11165825/55800611-8c5a7c00-5aed-11e9-8f33-02e91d862889.png)

### Versions
Gauge version: 1.0.4
Commit Hash: 3a9a647

Plugins
-------
html-report (4.0.8)
js (2.3.4)
screenshot (0.0.1)
spectacle (0.1.3)

Taiko:
Version: 0.6.0 (Chromium: 73.0.3665.0)

**Comment by osandadeshan** [comment]
@shahidawan1 
This is happening because the whole script is in a try catch block. In that case, the exception will be thrown but the script will get passed.
