### ISSUE TITLE
Make plugin ecosystem more controlled

### ISSUE THREAD

**Issue by NivedhaSenthil** [getgauge/taiko#482]
Currently all the CRI options are exposed to plugins.. which may lead to break taiko's native api flow when a plugin does something like `client.removeAllListeners()`. Figure out a way to have a controlled ecosystem for plugin.

**Comment by NivedhaSenthil** [comment]
Initial thoughts on what all a plugin can do
- combine set of taiko actions and provide apis for it (eg: taiko-paypal - which can let users do paypal payment)
- expose more of ChromeDevtoolsProtocols apis (eg: taiko-diagnostics - which can let users perform diagnostics actions over the website which will not be taiko's core api, taiko-screencast - which can let users record a video of the script running)
- provide selectors based on frameworks (eg: taiko-react - which can give selectors specific to react frameworks)
- override taiko apis (eg: taiko-android - which can override `openBrowser` api to launch browser in android device)

please do add more usecases that strikes you

**Comment by NivedhaSenthil** [comment]
#### More points to consider:

- loadPlugin api should be initialising the plugin, only this should do a callback to give back event emitters and taiko api control
- Everything else can be event based
- Event handler in plugin shouldn’t be allowed to emit, they should only listen on events from taiko to avoid clashing events. Plugin should be using separate event handler for anything needed in there.
- Use proxy on CRI client given to plugin to give controlled access.

#### Dynamically loading plugins:

##### Pros:
- Will let users decide which plugins can be loaded on runtime unlike doing `loadPlugin` in users script
- Less overhead when an api has to be overridden like `openBrowser` in taiko-android plugin
- Removes the clutter of adding lot of loadPlugin apis in the script incase user has to use many

##### Cons:
- Not every explicit for user to understand from script  which all plugin is being loaded
- Configuration based could be quite hard to get started with

##### Open questions:
- Auto completion when authoring in IDE ?
- How should the configuration be ? (https://github.com/saikrishna321/taiko-diagnostics/issues/1#issuecomment-458432292)

**Comment by negiDharmendra** [comment]
I have done a spike on loading plugin dynamically. Made necessary changes in **taiko** and **[taiko-android](https://github.com/saikrishna321/taiko-android)**. Changes for **taiko-android** are [here](https://github.com/negiDharmendra/taiko-android/tree/autoload_plugin)

With autoload plugin changes, the user no longer needs to require the [openAndroidBrowser api](https://github.com/negiDharmendra/taiko-android/tree/autoload_plugin#openandroidbrowser-command).

**Example 1: With autoloading plugin feature**

    const { openBrowser, goto, write, press, closeBrowser , inputField, into} = require('taiko');

    (async () => {
        try {
             await openBrowser();
             await goto('google.com');
             await write('taiko', into(inputField()));
             await press('Enter');
       } catch (e) {
            console.log(e);
      } finally {
            await closeBrowser();
      }
    })();


**Example 2: Without autoloading plugin feature**

    const { goto, write, press, inputField, into} = require('taiko');
    const { ID, clientHandler, openAndroidBrowser, closeAndroidBrowser } = require('taiko-android');

    loadPlugin(ID, clientHandler);

    (async () => {
        try {
             await openAndroidBrowser();
             await goto('google.com');
             await write('taiko', into(inputField()));
             await press('Enter');
       } catch (e) {
            console.log(e);
      } finally {
            await closeAndroidBrowser();
      }
    })();

**package.json**

        ...
       "dependencies": {
             "taiko": "github:getgauge/taiko",
             "taiko-android": "file:<path-to-taiko-android-dir>"
       }
       ...


**Note:** Right now it does not work with the globally installed plugins.

**Comment by zabil** [comment]
cc @saikrishna321

**Comment by saikrishna321** [comment]
@negiDharmendra  From the above example how does await openBrowser(); know it should open the android browser ?

**Comment by NivedhaSenthil** [comment]
currently in the spike it is done by loading plugins reading dependencies ... some more points to consider

- will be great to have a way to say which all plugins has to be loaded on runtime instead of loading all dependencies(that could be a fallback option) (eg) say there are two plugins `taiko-android` and `taiko-awslambda` both overriding the `openbrowser` user should be able to decide on runtime which plugin should be used. 

- need to watch out for performance of initial load, since dynamic loading can take more time incase if there is no package.json when using `taiko` runner or repl we may have to look for globally installed plugins

**Comment by NivedhaSenthil** [comment]
Discussion updates: 

## Taiko will be dynamically loading plugins and will let plugins override apis.

- run with env variable like 
```
TAIKO_PLUGIN='android'
TAIKO_PLUGIN='awslambda'
```
- or using taiko runner like `taiko code.js --plugin 'android'` 
- as a fallback can load plugins from dependencies
- export plugin object instead of exporting apis from plugin (eg: `taiko-screencast` plugin apis will exports via object named `screencast` and apis can be accessed like `screencase.start()` ) 
- use convention `taiko-<plugin>` - all taiko plugin should prefix `taiko-`

## Execution capability in plugin

Example: `taiko diagnostics http://gauge.org`

- Load plugins installed globally as a subcommand when initializing `commander.js`
- `taiko -help` will list all possible subcommands
- Add capability execution in plugins `package.json` to avoid loading plugins that does not have execution capability 
- `exec()` function in plugin should be executed for the subcommand

## Event driven pattern on actions 

- Plugins should not have taiko as dependencies it should use the same used in users code
- `loadPlugin()` api should give `taiko` and `eventHandler` to plugin via callBack - callback is currently named `clientHandler` could be called `init` which will initialize the plugin (may not need an plugin id if dynamic loading is done)
- all other communication between plugin and taiko should be based on event (eg: whenever a connection is done taiko emits an emit so that plugin can listen and update its cri client)

## Proxies for client and event handler

Proxy for client and event handler can be added like below to restrict asses to certain apis

```
const handler = {
        get: function(target, name) {
            if(['removeListener'].includes(name)) throw new Error(`Unsupported action ${name} on client`);
            return target[name];
        }
    };
const clientProxy = new Proxy(client,handler);
return clientProxy;
```    

#### List of apis to restrict 

- removeListener
- emit
- removeAllListener
- check for alias and wrapper

**Comment by NivedhaSenthil** [comment]
Above decisions will be implemented via following issues:
- Dynamic loading and event driven #562 
- Proxies for client #563 
- Execution capability in plugin #515
