### ISSUE TITLE
Make runner's console log event based

### ISSUE THREAD

**Issue by NivedhaSenthil** [getgauge/taiko#483]
Currently it is done by creating wrapper around api's to log based on the description return, which leads to doing hacks like altering functionality of apis like `exists`. Instead use event based logging so that altering of api is not needed and plugins can also listen to them if needed.

**Comment by Apoorva-GA** [comment]
Fix should be available in 91ec390.

**Comment by Debashis9012** [comment]
This has been verified and found fixed with the version ``` 91ec390 ```
