### ISSUE TITLE
Raspberry pi

### ISSUE THREAD

**Issue by edouardmenayde** [getgauge/taiko#485]
### Expected behavior
It should work on an rpi.

### Actual behavior
Chrome does not launch because it's not an arm build.

### Steps to reproduce
1. Use Taiko on an rpi

Puppeteer has a similar problem but at least has a thread addressing the issue.

To solve the issue for the moment: how could I specify which build of chromium I want Taiko to use so that I can use an arm build of chromium ?

**Comment by Apoorva-GA** [comment]
@edouardmenayde You can download the desired version of chromium and set the env [`TAIKO_BROWSER_PATH`](https://taiko.gauge.org/#taiko-env-variables) to required chrome executable path.

**Comment by edouardmenayde** [comment]
Thanks for the quick answer ! I will try it

**Comment by edouardmenayde** [comment]
I was able to make it work using `chromium-browser` package for Raspbian.
