### ISSUE TITLE
Support for Coffeescript and other languages

### ISSUE THREAD

**Issue by tkshnwesper** [getgauge/taiko#490]
I'm developing a [plugin](https://github.com/tkshnwesper/taiko-react) for taiko which is written in Coffeescript.

During development, I am requiring `taiko` as a `devDependency` to write some functional tests. These tests are also written in Coffeescript (and have a `.coffee` extension) and compiled on the fly to Javascript by Mocha (using `coffeescript/register`) prior to running them.

The following line gives the error message that I am receiving:

https://github.com/getgauge/taiko/blob/01997aa88e293953c4fc3d12fa531172a50ee360/bin/taiko.js#L33

I believe it is caused because there is explicit checking of the file extension, and since I am using a Coffeescript file, it is not allowing me to run my code.

https://github.com/getgauge/taiko/blob/01997aa88e293953c4fc3d12fa531172a50ee360/bin/taiko.js#L32

Do you feel this constraint could be made a little more flexible?

**UPDATE**
I previously closed this issue because I somehow got it working, but now I know what I did to get it to work.

If I installed taiko using `npm install taiko` I would get that error. However, if I simply added the git repository to my `package.json` the program would run flawlessly. [That is also what I am currently doing 😄 ](https://github.com/taiko-react/taiko-react-functional-tests/blob/8f638f37b09f9d3af6e9671c1834dd1178e29971/package.json#L33)

I'm not exactly sure what's at play here, because the code that I have referenced above is also present in the latest commit.

Thanks and regards,
Saurabh

**Comment by tkshnwesper** [comment]
Looks like it started working fine without any modifications.

**Comment by negiDharmendra** [comment]
@tkshnwesper The code you have mentioned is only used for taiko CLI.  As you can see this check [here](https://github.com/getgauge/taiko/blob/01997aa88e293953c4fc3d12fa531172a50ee360/bin/taiko.js#L86)

**Comment by tkshnwesper** [comment]
Happens even when I import taiko as a dependency.

<img width="694" alt="image" src="https://user-images.githubusercontent.com/7362366/56919670-d3c99c00-6ade-11e9-8ad8-ade21a84520e.png">

The problem is that this condition evaluates to true:
https://github.com/getgauge/taiko/blob/9e086d8c9bb76b9ce2c55cf0f0520d97e6ead56e/lib/util.js#L25
That's causing it to take the CLI's course of execution.

You could try it out on [this](https://github.com/taiko-react/taiko-react-functional-tests) repo.
Just change the version of taiko in `package.json` and run `npm install` and then `npm run test-functional`.

**Comment by tkshnwesper** [comment]
I think I realized why there is a discrepancy between when I clone the repo and when I use version `0.6.0`.

In `v0.6.0` the line says:
https://github.com/getgauge/taiko/blob/f86cf3ffd436f515b305b0f8a96b1f331d005ef6/lib/util.js#L24

Whereas in `master` the same line says:
https://github.com/getgauge/taiko/blob/9e086d8c9bb76b9ce2c55cf0f0520d97e6ead56e/lib/util.js#L25

So there has been a change between the two versions, and the change in `master` is fixing my issue it would seem.

**Comment by negiDharmendra** [comment]
@tkshnwesper Thaks for sharing your finding.

**Comment by negiDharmendra** [comment]
Feel free to reopen this issue if you face this issue again.
