### ISSUE TITLE
TypeError: module.constructor._nodeModulePaths is not a function

### ISSUE THREAD

**Issue by negiDharmendra** [getgauge/taiko#492]
### Expected behavior
Multiple jest specs should run fine.

### Actual behavior
Fails with `TypeError: module.constructor._nodeModulePaths is not a function`

### Steps to reproduce
1. Clone [taiko-diagnostics](https://github.com/negiDharmendra/taiko-diagnostics)
2. Change `"taiko": "git://github.com/getgauge/taiko.git"` to `"taiko": "git://github.com/getgauge/taiko.git#814bad677d3fc608d862596ef412c9fcbbd9f78f"` in `package.json` file
3. run `npm install && npm run integration` 

### Versions
```
node : v10.11.0
taiko : commit - 814bad677d3fc608d862596ef412c9fcbbd9f78f

```

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed with ```0ae7ff5178b59cf802ae378c6e507943660b6aec ``` version.
