### ISSUE TITLE
Combobox selector does not show user response message

### ISSUE THREAD

**Issue by Debashis9012** [getgauge/taiko#496]
### Expected behavior
In taiko repl after selecting the value from a combobox successfully, it should display the user response message. 

### Actual behavior
In taiko repl Combobox selector does not show the user response message.

### Steps to reproduce
1. openBrowser()
2. goto("https://the-internet.herokuapp.com/dropdown")
3. comboBox(below(text("Dropdown List"))).select("Option 1");
<img width="510" alt="Screen Shot 2019-04-19 at 3 48 22 PM" src="https://user-images.githubusercontent.com/46309201/56420198-b1ec4000-62ba-11e9-84da-ef9faadb09dc.png">

### Versions
```
7d43b16c0ee97fca99f3ac8effc1e139043b5252
```

**Comment by Apoorva-GA** [comment]
Should br fixed as part of https://github.com/getgauge/taiko/issues/483.

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed. 
Kindly find the below screenshot
```
> comboBox({name:'country'}).select('ALGERIA')
 ✔ Selected ALGERIA
```


version: ```0ae7ff5178b59cf802ae378c6e507943660b6aec ```
