### ISSUE TITLE
Deprecate intervalSecs and timeoutSecs

### ISSUE THREAD

**Issue by negiDharmendra** [getgauge/taiko#497]
[intervalSecs](https://taiko-preview.gauge.org/#intervalsecs) and [timeoutSecs](https://taiko-preview.gauge.org/#timeoutsecs) should not be two different utility API  as both of them are to converts second to the millisecond.

Instead, provide a common utility API.

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed with the commit version: ```50bbc072ae68dfe41964d7c4bcb5194541883afe ```
