### ISSUE TITLE
openBrowser() should not lose focus from the terminal

### ISSUE THREAD

**Issue by zabil** [getgauge/taiko#5]
Current behavior.

* Open the REPL
* Type `openBrowser()`

The browser opens and focuses on the location bar.

Expected behavior

* Focus must remain on the REPL

**Comment by zabil** [comment]
Happens only on elementary os
Info
```
Distributor ID:	elementary
Description:	elementary OS 0.4.1 Loki
Release:	0.4.1
Codename:	loki
```

**Comment by jackperalta** [comment]
I do not know about elementary os, but I have the same problem on Windows 10

**Comment by shubhamsc** [comment]
openBrowser() is working properly in windows 10.
