### ISSUE TITLE
Issue with a specific css selector

### ISSUE THREAD

**Issue by priyanshus** [getgauge/taiko#503]
Selector like "#dropdown>option:nth-child(1)" does not work in click().

### Expected behavior
In click($("#dropdown>option:nth-child(1)")), selector like "#dropdown>option:nth-child(1)" should work. **It works in other tools like WebDriver, Cypress etc.**

### Actual behavior
Error: Custom selector $(#dropdown>option:nth-child(1)) not found
    at elements (**/the-internet-express/tests/node_modules/taiko/lib/taiko.js:2115:15)

### Steps to reproduce
openBrowser()
 ✔ Browser opened
> goto('http://localhost:3000/dropdown')
 ✔ Navigated to url "http://localhost:3000/dropdown"
> click('#dropdown > option:nth-child(1)')
 ✘ Error: Element with text #dropdown > option:nth-child(1) not found, run `.trace` for more info.

**Comment by negiDharmendra** [comment]
`#dropdown>option:nth-child(1)` is an valid css selector and works fine in devtool console.

Looks like an issue with the way taiko determine the visibility of an element.
 https://github.com/getgauge/taiko/blob/b7a34d9a458e57d9d1efce87abe2f4a1cead7f96/lib/taiko.js#L2351

As `offsetHeight` and `offsetWidtht` is zero for the element.

**Comment by nehashri** [comment]
The offsetHeight and offsetWidth for a option element in chrome gives the value 0, in firefox it inherits from its parent element (select) and is a non-zero integer. Finding the visibility of an option element is not easy. 
Also with taiko, we actively encourage you to use our smart selectors like `dropdown` in this case. Css selectors can be used only if it is not possible to perform the action via other selectors. 
So to select a option, you could do
```
        await goto('http://localhost:3000/dropdown');
        await dropDown().select('Option 1');
```
See [here](https://github.com/getgauge/taiko/blob/master/examples/05-dropdown.js) for complete example.

However, this still seems to be a issue and we will revisit this issue. In the meantime, please look at using the workaround mentioned above.
