### ISSUE TITLE
Outdated docker image

### ISSUE THREAD

**Issue by ad-m** [getgauge/taiko#504]
In several places Taiko documentation ( https://github.com/getgauge/taiko/search?q=docker&unscoped_q=docker ) mention Docker support. There is even Docker image ( https://hub.docker.com/r/getgauge/taiko ). Unfortunatly, that docker image is out-dated (version 0.2.0) and no source available

Is there any play to provide recommended minimal docker images for Taiko?

**Comment by sriv** [comment]
hi @ad-m - please see relevant discussion here: https://github.com/getgauge-contrib/gauge-docker/issues/3
