### ISSUE TITLE
custom code generation

### ISSUE THREAD

**Issue by worc** [getgauge/taiko#508]
Are there any options or plans for options around customizing the code generation from REPL? There's some manual linting that has to be done on my end to make the generated code match an in-house styleguide. Specifically we don't use semi-colons, and avoid self-executing function definitions.

**Comment by sriv** [comment]
I don't think we've discussed this before, but seems like a good thing to do.

Perhaps we could hook up a linter post generation?  Or if there is way we could introduce some templating that gives control on what sort of style guide the generated code should follow?

For the former, we could try using something like `eslint`. For the latter, I do not know of any package that can help.

**Comment by zabil** [comment]
There's also [prettier](https://prettier.io/docs/en/install.html) which has an api for formatting. 
I assume a user must be able to plug a custom formatter. So maybe an option to pass a command that `.code` will pipe to before printing the results on the REPL.

**Comment by zabil** [comment]
Taiko must add support for code generation plugins.
Apart from the case mentioned here currently `.step` is currently implemented in taiko. This should be pulled out of Taiko into a `taiko-gauge` plugin that can add these capabilities. 

This can then be extended to support code generation for other frameworks like `.mocha` or `.jest`

**Comment by zabil** [comment]
Closing this as Taiko will only have the Javascript code generator. Hoping that the styles can be applied after importing and modifying the generated code.
