### ISSUE TITLE
Add an observe mode to slow interactions while running a script

### ISSUE THREAD

**Issue by zabil** [getgauge/taiko#51]
### Current behavior

Taiko runs scripts fast and headless making it hard to see what's exactly happening. This forces a tester to add waits in the code.

for e.g. 
```
await click(checkBox('class','toggle',near('to remove')));
await waitFor(5000);
await hover(button('class','destroy'));
await click(button('class','destroy'));
await waitFor(5000);
```

### Expected behavior

Add flag `--observe` to `taiko` command line that introduces a three seconds wait between all commands and runs the script in non-headless mode.

For e.g.

```
$ taiko sample.js --observe
```

Make the wait time configurable in seconds.

Alternate names for the flag
* `--slow-mo`
* `--watch`

**Comment by NivedhaSenthil** [comment]
Available with [commit](https://github.com/getgauge/taiko/commit/d2aa9686c6e527cb237ed067a9edfc5c7a73c956)

**Comment by sguptatw** [comment]
Usage: `$ taiko sample.js --observe`
