### ISSUE TITLE
failed commands aren't saved in REPL

### ISSUE THREAD

**Issue by worc** [getgauge/taiko#510]
if a command errors out—for example on a syntax error—the REPL doesn't save that command in history. it should save the command in history so that you can go back one in history and fix a typo.

**Comment by NivedhaSenthil** [comment]
I could see the failed commands on history, they just don't get added to the script generated using `.code` and not removed from history. You should be able to get them by pressing up arrow or using `.history` in REPL. If you are expecting something else can you please give an example ?

**Comment by worc** [comment]
yeah, the bug we ran into was trying some commands on a page, but we had either typos or small syntax errors in the commands. i think it was specifically a `click(near('text')` with a missing parenthesis and it timed out. so naturally we tried hitting the up arrow to retrieve the last command and fix the syntax, but the command wasn't in the REPL history

**Comment by Debashis9012** [comment]
@worc  As @NivedhaSenthil  mentioned failed command wont get added to  script while generationg the script ```.code```. I am able to get the failed command by hitting the up arrow kindly find the below code :

Version: 0.8.0 (Chromium:74.0.3723.0)
Type .api for help and .exit to quit
```
> openBrowser()
 ✔ Browser opened
> goto("Google.com")
 ✔ Navigated to url http://Google.com
> write("taiko automation testing tool")
 ✔ Wrote taiko automation testing tool into the focused element.
> click("googleeee search")
 ✘ Error: Element with text googleeee search not found, run `.trace` for more info.
> click("googleeee search"))
{ [SyntaxError: Unexpected token, expected ; (1:40)
] pos: 40, loc: Position { line: 1, column: 40 } }
> click("googleeee search"))
                         ^

SyntaxError: Unexpected token )

> click("googleeee search")) --------> By hitting the up arrow we got the last used failed command 
```
Also i am able to find the failed command from repl history by using ```.history```
```
click("googleeee search"))
.history
```
Could you please answer below queries which will be helpful for us to figure out the problem you are facing

1. what version of taiko you are using?
2. Could you please try this in the latest release of taiko and let us know the outcome?
    Refer: https://github.com/getgauge/taiko/releases/tag/v0.7.1
    use: ```npm install taiko -g``` to get the latest release version of taiko.

**Comment by worc** [comment]
any reason to close this? the .history file isn't necessarily the same as arrow-up while in interactive mode

**Comment by Apoorva-GA** [comment]
@worc thanks for confirming.
Feel free to reopen the issue if you see the problem again.
