### ISSUE TITLE
Add support for plugins to extend taiko via subcommands

### ISSUE THREAD

**Issue by zabil** [getgauge/taiko#515]
Plugins must be able to extend Taiko and add sub commands for example. For example `taiko-diagnostics` plugin can extend Taiko with

```
$ taiko diagnostics https://example.com
```

This must be delegate the subcommand to the plugin which can read parameters. In this case the plugin can implement the subcommand to access `https://example.com` and print a list of default diagnostics like CSSCoverage, JS Coverage, Performance Metrics

**Comment by NivedhaSenthil** [comment]
- Load plugins installed globally as a subcommand when initializing `commander.js`
- `taiko -help` will list all possible subcommands
- Add capability execution in plugins `package.json` to avoid loading plugins that does not have execution capability 
- `exec()` function in plugin should be executed for the subcommand

**Comment by NivedhaSenthil** [comment]
Fix available in 51a2b4c

**Comment by Debashis9012** [comment]
This enhancement has been verified and found fixed with the commit version : ```51102a49067dd7e7b9af671f071b45c5d435db4e```
