### ISSUE TITLE
Unable to click on the Active window after goto()

### ISSUE THREAD

**Issue by supraja-kr** [getgauge/taiko#516]
### Expected behavior
Should be able to enter details into Username text field

### Actual behavior
Able to enter details into Username field, only after I manually refresh the page loaded. Else getting a Timeout error.

### Steps to reproduce
1. openBrowser()
2. goto('https://testsite.com', {timeout:30000 });

### Versions
taiko -version
Version: 0.6.0 (Chromium: 73.0.3665.0)

**Comment by negiDharmendra** [comment]
@supraja-kr Please provide more steps of the script you are using.

**Below script works fine for me with taiko latest [commit](https://github.com/getgauge/taiko/commit/9e086d8c9bb76b9ce2c55cf0f0520d97e6ead56e)** 

    const { openBrowser, goto, click, below, write, press, closeBrowser } = require('taiko');
    (async () => {
          try {
                 await openBrowser( { headless: false});
                 await goto('testsite.com');
                 await click('Sign in');
                 await click('Sign in', {waitForEvents: ['firstMeaningfulPaint'] }, below('sign in now'));
                 await write('user name');
                 await press('Tab');
                 await write('password');
             } catch (e) {
                 console.error(e);
          } finally {
                await closeBrowser();
         }
     })();

**Comment by supraja-kr** [comment]
Here is my sample script
const headless = process.env.headless_chrome.toLowerCase() === 'true';
{
    await openBrowser({headless: headless});
    await goto('https://testabc.com', {timeout:30000 });
    await click(inputField(near("Username")));
    await write('suprajakr', into('username'));
    await click('password');
    await write('test', into('password'));
    await click('Login');

**Comment by nehashri** [comment]
@supraja-kr Unfortunately 'https://testabc.com' doesn't have any username feild. It doesn't seem to be a valid site. So I am not able to run the above script. Please provide a valid script where we can try to reproduce this issue.
Also as @negiDharmendra mentioned, this may work with the latest commit of taiko. Can you try using the latest commit hash and let us know if it works.
You can use the latest commit of taiko with npm as such (https://docs.npmjs.com/files/package.json#github-urls) i.e, "taiko" : "getgauge/taiko#cc2c1dc".

**Comment by supraja-kr** [comment]
Thank you so much @nehashri , pulling the latest commit solved the issue.
