### ISSUE TITLE
clear api gives wrong acknowledge response

### ISSUE THREAD

**Issue by Debashis9012** [getgauge/taiko#522]
### Expected behavior
```clear``` api should give the correct acknowledge response

### Actual behavior
> clear()
 ✔ Clicked
 ✔ [object Object] 
### Steps to reproduce
1.  goto("Google.com")
2. write("java")
3. clear()

### Versions
```
 0.7.0 (Chromium:74.0.3723.0)
commit: cc2c1dc  

```

**Comment by Apoorva-GA** [comment]
Fix available in commit d9e89e2

**Comment by Debashis9012** [comment]
This bug has been verified and found fixed with the commit version ```d9e89e2```
