### ISSUE TITLE
Text should support contains

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#53]
**Current behavior**
Contains is currently available on UI elements

**Steps to replicate**
* Add a file `textMatch.js`
```
const { browser, openBrowser, goto, link, click, listItem } = require('taiko');
const assert = require("assert");

(async () => {
    try {
        await openBrowser();
        await goto("http://google.com");
        await click(contains('Gmai'))
        assert.ok(await text(contains('Meet your')).exists());
    } catch (e) {
        console.error(e);
    } finally {
        closeBrowser();
    }
})();
```
* Run with taiko
`taiko textMatch.js`
> Should match the partial text

**Version**
```
Version: 0.0.9 ()
```

**Comment by sguptatw** [comment]
Work around `assert.ok(await contains('Meet your').exists())`

**Comment by NivedhaSenthil** [comment]
Fix done in [commit](https://github.com/getgauge/taiko/commit/43027b055af5f9e92b6b2fcb9ca3b8fb96c71605)
