### ISSUE TITLE
Add command line argument and environment variable to emulate network

### ISSUE THREAD

**Issue by zabil** [getgauge/taiko#532]
Extend the [emulate network](https://taiko.gauge.org/#emulatenetwork) to add emulation for taiko command line for e.g

```
$ taiko script.js --emulate-network 2G
```

and for integration with runners, add an environment variable `TAIKO_EMULATE_NETWORK`

**Comment by Debashis9012** [comment]
This enhancement has been verified and found fixed.
Observations:
1. ```emulateNetwork``` in command line working properly with required networks.
2.  After adding environment variable ```TAIKO_EMULATE_NETWORK ``` with required network value. It works as excepted.

commit version: ``` 7493c6afa8565c8482f8f01ada43c32dd1185627```
