### ISSUE TITLE
comboBox is a misleading name for Dropdown element

### ISSUE THREAD

**Issue by rakhid** [getgauge/taiko#534]
### Expected behavior
In general developer terms, ComboBox and Dropdowns have a very different meaning.
As of today we in Taiko, we use "combo box" to access the dropdown element.

### Actual behavior
either make 2 elements to be used for a different purpose. Or rename combo box to drop down

### Versions
Node : v8.11.1
Taiko : Version: 0.7.0 (Chromium: 74.0.3723.0)

**Comment by zabil** [comment]
Adding the definition of combo box vs dropdown from wikipedia to explain the difference

https://en.wikipedia.org/wiki/Combo_box

> In both Java and .NET, "combo box" is not a synonym for "drop-down list".[2][3] Definition of "drop down list" is sometimes clarified with terms such as "non-editable combo box" (or something similar) to distinguish it from "combo box".

**Comment by NivedhaSenthil** [comment]
Fix available in bfa3f5f. comboBox is now deprecated and renamed as dropDown

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed with the commit version ```bfa3f5f9ffc760011ac32bffa4b6994fc53463a4 ```
