### ISSUE TITLE
intercept request  to redirect does not work without PROTOCOL in the URL(2nd argument to intercept command))

### ISSUE THREAD

**Issue by rakhid** [getgauge/taiko#535]
### Expected behavior
when using intercept in the following manner should work 👍 
intercept("www.google.com","www.ibibo.com")
goto("www.google.com") should open "ibibo.com" for me.
but that does not happen because "www.ibibo.com" is written without a protocol.

Now when I mention intercepting command as 👍 intercept("www.google.com","http://www.ibibo.com")
goto("www.google.com")
then re-direction works absolutely fine

### Versions
node:v8.11.1
Taiko :Version: 0.7.0 (Chromium: 74.0.3723.0)

**Comment by Apoorva-GA** [comment]
Fix should be available in commit f00e82a

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed with the commit version ```f00e82a ```
