### ISSUE TITLE
warning messages in case of multiple intercepts applied is wrong/misleading

### ISSUE THREAD

**Issue by rakhid** [getgauge/taiko#536]
Pls have a look at the following example 👍 

> openBrowser()
 ✔ Browser opened
> goto("www.google.com")
 ✔ Navigated to url http://www.google.com
> intercept("www.google.com","http://www.bing.com")
 ✔ Interceptor added for www.google.com
> goto("www.google.com")
 ✔ Navigated to url http://www.google.com
> intercept("www.google.com","http://www.goibibo.com")
 ✔ Interceptor added for www.google.com
> goto("www.google.com")
WARNING: More than one intercept ["www.google.com","www.google.com"] found for request "http://www.google.com/".
 **Applying "www.google.com"**
WARNING: **More than one intercept ["www.google.com","www.google.com"]** found for request "https://www.google.com/ads/ga-audiences?v=1&aip=1&t=sr&_r=4&tid=UA-9782412-14&cid=1902665717.1557394358&jid=1334884118&_v=j73&z=135664653".
 Applying "www.google.com"
WARNING: More than one intercept ["www.google.com","www.google.com"] found for request "https://www.google.com/ads/ga-audiences?v=1&aip=1&t=sr&_r=4&tid=UA-9782412-14&cid=1902665717.1557394358&jid=1144344859&_v=j73&z=101807266".
 Applying "www.google.com"

### Expected behavior
Tell us what should happen

Applying "www.google.com" message should point to which intercept request is it applying internally? 
the one to bing or the one to goibibo?
It's very unclear to the user from the trace that what is happening .. except the fact that "www.google.com" was intercepted twice.

### Versions
node:v8.11.1
Taiko :Version: 0.7.0 (Chromium: 74.0.3723.0)

**Comment by NivedhaSenthil** [comment]
True. Will be better if the action being applied is also added along with the warning.

**Comment by Apoorva-GA** [comment]
Fix should be available in commit : e754e5a

**Comment by Debashis9012** [comment]
This issue has been verified and fixed with the commit version ```e754e5a```
