### ISSUE TITLE
Chromium browser should be launched with automation enabled.

### ISSUE THREAD

**Issue by nehashri** [getgauge/taiko#541]
When a chromium browser is launched, it should be launched with the `--enable-automation` flag. This displays the banner that `chrome is being controlled by automated test software` along with other features. Refer https://github.com/GoogleChrome/chrome-launcher/blob/master/docs/chrome-flags-for-tools.md#--enable-automation for more information.

**Comment by zabil** [comment]
https://github.com/getgauge/taiko/pull/542

**Comment by nehashri** [comment]
Fix available in commit `097c1fb65ab788823a7e362b48e0162ce812c945`

**Comment by Debashis9012** [comment]
Observation after fix:
when taiko opens chromium browser it open with ```--enable-automation``` flags. As a result we can see the banner  **chrome is being controlled by automated test software** in browser.
Tested version: ``` 097c1fb65ab788823a7e362b48e0162ce812c945 ```
