### ISSUE TITLE
Should be able to click text case insensitive

### ISSUE THREAD

**Issue by NivedhaSenthil** [getgauge/taiko#543]
### Expected behavior
Click on text irrespective of the case

### Actual behavior
Element selection fails when there is a change in case

### Steps to reproduce

taiko.html
```
<html>
<body>
<form>
<button type="submit" style="text-transform: uppercase;">
          Iniciar sesión segura
        </button>
</form>
</body>
</html>
```

sample.js
```
const { openBrowser, goto, click, closeBrowser } = require('taiko');
(async () => {
    try {
        await openBrowser();
        await goto("file://.../taiko.html");
        await click("INICIAR SESIÓN SEGURA");
    } catch (e) {
        console.error(e);
    } finally {
        await closeBrowser();
    }
})();
```

### Versions
works fine on `0.6.0` fails in master

**Comment by NivedhaSenthil** [comment]
This is happening because of the non-alphabetic character in the DOM which is not getting converted to lowercase by `translate` as it considers only alphabets currently.  Since chrome supports only xpath1.0 there is no cleaner way to support non-alphabetic characters to be matched case insensitive.
Was working earlier because we were doing `toLowerCase()` from javascript for user given text which will work only one way if the text in DOM is in upperCase this would fail hence that fix cannot be added.

**Comment by zabil** [comment]
Closing this as a Xpath 1.0 limitation
