### ISSUE TITLE
https://taiko.gauge.org/ redirects to https://taiko-preview.gauge.org

### ISSUE THREAD

**Issue by Debashis9012** [getgauge/taiko#546]
### Expected behavior
While searching docs in ```https://taiko.gauge.org``` result should not redirect to other url.

### Actual behavior
While searching docs in ```https://taiko.gauge.org``` result redirects to ```https://taiko-preview.gauge.org``` site.

### Steps to reproduce
1. Hit https://taiko.gauge.org
2. search for any api. For example: ```setConfig```

**Comment by shubhamsc** [comment]
The fix is available in https://taiko-preview.gauge.org, It will not redirect to https://taiko.gauge.org while searching.
For https://taiko.gauge.org, need to release to work properly.

**Comment by Debashis9012** [comment]
Tested this issue as per the above comment.
**Observation**
When we are trying to search docs in https://taiko-preview.gauge.org/ site there is no auto suggestions for the user. 
Kindly find the below screenshot:
<img width="754" alt="Screen Shot 2019-05-27 at 3 38 58 PM" src="https://user-images.githubusercontent.com/46309201/58413403-4d30bc00-8096-11e9-9e51-969f4465a543.png">

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed for both ```https://taiko.gauge.org``` and ```https://taiko-preview.gauge.org``` sites.
