### ISSUE TITLE
Should not hang on a script failure

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#55]
**Actual behavior**
- [ ] Hangs when a `ReferenceError` occurs
- [ ] Hangs when comboBox is not found
- [ ] Hangs when there is an Assertion failure

**Steps to replicate**
* Add a file `scriptFailure.js`
```
const { browser, openBrowser, goto, click,comboBox } = require('taiko');
const assert = require('assert');

(async () => {
    try {
        await openBrowser();
        await goto("google.com");
        await click("I'm Feeling Lucky",{waitForNavigation:true});
        await click(link("About"));
        assert.ok(await comboBox(toLeftOf(image("id","lang-icon"))).exists())
        await comboBox(toRightOf(image("id","lang-icon"))).select("hi");
        await click("Doodles Archive",{waitForNavigation:true});
        await closeBrowser();
    } catch (e) {
        console.error(e);
    } finally {
    }
})();
```
* Run the above script with taiko `taiko scriptFailure.js`
> The ReferenceError exception occurs and the script hangs
* Now correct the comboBox is not found hence the script hangs 
* When there is an assertionError then the script hangs
Use assert.ok(true,false) in the script.

Blocks #29

**Comment by NivedhaSenthil** [comment]
Fix done in [commit](https://github.com/getgauge/taiko/commit/ab73800e370f6afa5b50d223f1c92908c40fd696)

**Comment by sguptatw** [comment]
Replicable on [commit](https://github.com/getgauge/taiko/commit/ab73800e370f6afa5b50d223f1c92908c40fd696)

**Steps to replicate**
```
const { browser, openBrowser, goto, click,comboBox } = require('taiko');
const assert = require('assert');

(async () => {
    try {
        await openBrowser({headless:false});
        await goto("google.com");
        await click("I'm Feeling Lucky",{waitForNavigation:true});
        await click(link("About"));
        assert.ok(await comboBox(toLeftOf(image("id","lang-icon"))).exists())
        await comboBox(toRightOf(image("id","lang-icon"))).select("whatever");
        await click("Doodles Archive",{waitForNavigation:true});
        await closeBrowser();
    } catch (e) {
        console.error(e);
    } finally {
    }
})();
```

**Comment by NivedhaSenthil** [comment]
Seems to be happening when there is a try catch in script and closeBrowser is not called either from catch or finally. Tried getting hold of the end of catch block to terminate but not able to.
