### ISSUE TITLE
Wrong element is getting clicked 

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#558]
### Expected behavior
The element given in the script should get clicked 

### Actual behavior
`Book a table` is getting clicked instead of `Order Food Online`. `Some offers` and `terms and conditions` are having an effect of sliding in after the page is loaded. The location is calculated before this effect. Hence wrong element is getting clicked 

### Steps to reproduce
* Run the taiko script
```
const { openBrowser, goto, text, click, below, link, toRightOf } = require('taiko');

(async () => {
    try {
        await openBrowser({headless:false});
        await goto("www.zomato.com/bangalore");
        await click(text("Pocket-Friendly Delivery"));
        await click("Order Food Online");
    } catch (e) {
        console.error(e);
    } finally {
        closeBrowser();
    }
})();
```
### Versions
```
nodejs - v10.15.3
taiko - commit 3bb2ade397840ad2326026bb7fad840161e673ea
```

**Comment by Apoorva-GA** [comment]
Since there is a new window(both terms and conditions and zomato gold) is coming up. User should make sure that they exists and then do the remaining actions. The below mentioned code should work.
```
const { openBrowser, goto, text, click, below, link, toRightOf } = require('taiko');

(async () => {
    try {
        await openBrowser({headless:false});
        await goto('www.zomato.com/bangalore');
        await click(text('Pocket-Friendly Delivery'));
        await text('We made changes to our').exists();
        await click('Order Food Online');
    } catch (e) {
        console.error(e);
    } finally {
        closeBrowser();
    }
})();
```

**Comment by nehashri** [comment]
Since new elements are getting loaded, the waitFor elements api (refer https://github.com/getgauge/taiko/issues/531) should be useful.

**Comment by Debashis9012** [comment]
The above steps to reproduce has been verified and tested. This is working as excepted in commit: ``` 7493c6afa8565c8482f8f01ada43c32dd1185627 ```
