### ISSUE TITLE
Should be able to select link with given class

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#56]
**Actual behavior**
Getting the error
Error: Link with [class = "<classname>"]  not found

**Steps to replicate**
* Use taiko to run the following script
```
const { browser, openBrowser, goto, listItem, click, link } = require('taiko');
const assert = require("assert");

(async () => {
    try {
        await openBrowser();
        await goto("https://gauge.org/index.html");
     assert.ok(link("class","github_star").exists())

        await closeBrowser();
    } catch (e) {
        console.error(e);
    } finally {
    }
})();
```
> Should be able get the link with the given class

**Version**
```
Version: 0.0.9 ()
```

Blocks #29

**Comment by NivedhaSenthil** [comment]
Seems to be happening because the class is associated with a span inside anchor tag and not on the link. There is no link with class "github_star".

**Comment by sguptatw** [comment]
Tracked as a part of https://github.com/getgauge/taiko/issues/57
