### ISSUE TITLE
Spike on browser contexts 

### ISSUE THREAD

**Issue by NivedhaSenthil** [getgauge/taiko#560]
Spike on letting user create new browser contexts instead of opening new browser instances whenever a fresh instance is needed. Might improve performance since it reduces the overhead of launching a new browser for every scenario. https://chromedevtools.github.io/devtools-protocol/tot/Target/#method-createBrowserContext

**Comment by aerskine** [comment]
I wanted to enquire after the intent of this issue. 

Is the intent to provide special Taiko-based tooling around browser contexts, or merely to enable the use of browser contexts via chrome remote interface?

The reason I ask, is that I can't get the latter to work:

```
openBrowser()
cl=client()
cl.Target.getBrowserContexts()
```

(and variants) results in:

```
Thrown:
Not allowed
```

Thanks for any clarification!

**Comment by sriv** [comment]
I guess the original motive is to reuse a browser instance and use contexts as a mean for isolation. 

If memory serves me right, someone in the community was asking for a feature to test role-based-user flows and having to manage multiple instances can become an overhead. @NivedhaSenthil can shed more detail.

**Comment by saikrishna321** [comment]
@aerskine  

> cl=client()
cl.Target.getBrowserContexts()

This can't be done right now with `client()` as the `openBrowser` API attaches the instance to the blank page target. If we want to use anything related to browserContexts. 

We need to first create `createBrowserContext` and then `getBrowserContexts()
`

@sriv @zabil @NivedhaSenthil I'm currently working on fixing this I was thinking 

1. `openBrowser ` to accept incognito as options and then createBrowserContext internally. 
2. `openBrowser` to accept incognito and new API `createIncognitoBrowserContext`

usage

```
before() => openBrowser({incognito: true})
beforeEach() => createIncognitoBrowserContext()

after() => closeBrowser()
afterEach() => closeIncognitoBrowserContext()
```

**Comment by aerskine** [comment]
Thank you for your answers @sriv and @saikrishna321 ! They clear things up a lot. I will remain subscribed.
