### ISSUE TITLE
Create Proxies for client passed to plugins

### ISSUE THREAD

**Issue by NivedhaSenthil** [getgauge/taiko#563]
## Proxies for client and event handler

Proxy for client and event handler can be added like below to restrict asses to certain apis

```
const handler = {
        get: function(target, name) {
            if(['removeListener'].includes(name)) throw new Error(`Unsupported action ${name} on client`);
            return target[name];
        }
    };
const clientProxy = new Proxy(client,handler);
return clientProxy;
```    

#### List of apis to restrict 

- removeListener
- emit
- removeAllListener
- check for alias and wrapper

**Comment by shubhamsc** [comment]
Proxies are added to block these APIs to work with the client.
- removeListener 
- emit
- removeAllListeners
- setMaxListeners
- off

**Comment by shubhamsc** [comment]
Proxies are added to block these APIs to work with the client.
- removeListener 
- emit
- removeAllListeners
- setMaxListeners
- off
