### ISSUE TITLE
Unable to run taiko tests in RHEL Linux machine

### ISSUE THREAD

**Issue by boomi243** [getgauge/taiko#565]
### Expected behavior
We should be able to run taiko tests in RHEL Linux machine without any issues.

### Actual behavior
Unable to run taiko tests. it is taking lot of time for initial setup. Please provide us the step by step installation details

### Steps to reproduce
[runner: 1]
        Failed Step: Open Browser
        Specification: specs/createSettingsLocations.spec:7
        Error Message: Error: Failed to launch chrome!
        [0521/193141.658560:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
        #0 0x559380266f29 base::debug::CollectStackTrace()
        #1 0x5593801cc593 base::debug::StackTrace::StackTrace()
        #2 0x5593801e0d1e logging::LogMessage::~LogMessage()
        #3 0x55938184990e service_manager::ZygoteHostImpl::Init()
        #4 0x55937fe221b7 content::ContentMainRunnerImpl::Initialize()
        #5 0x55937fe54fca service_manager::Main()
        #6 0x55937fe20791 content::ContentMain()
        #7 0x5593844bc178 headless::(anonymous namespace)::RunContentMain()
        #8 0x5593844bc205 headless::HeadlessBrowserMain()
        #9 0x55937fe53ca3 headless::HeadlessShellMain()
        #10 0x55937dd8b1ac ChromeMain
        #11 0x7f19d20383d5 __libc_start_main
        #12 0x55937dd8b02a _start

We tried no sand box options too. but still not working.

### Versions

Taiko:
Version: 0.7.0 (Chromium:74.0.3723.0)
Type .api for help and .exit to quit

Node:
v10.13.0

**Comment by BugDiver** [comment]
@boomi243 Are you trying to run tests inside a Docker container?

**Comment by adea11** [comment]
> @boomi243 Are you trying to run tests inside a Docker container?

Hi @boomi243 . Is there any known issue with with running taiko inside docker container please?. I have been trying it for a week now but no joy at all.

**Comment by BugDiver** [comment]
@adea11 Not necessarily. I asked the question about docker was to help us investigate the issue.

**Comment by adea11** [comment]
> @adea11 Not necessarily. I asked the question about docker was to help us investigate the issue.

@boomi243 please can you assist with issue I rised at  https://github.com/getgauge/taiko/issues/567.

**Comment by BugDiver** [comment]
@boomi243 If you are trying with docker can you please follow the instructions https://github.com/getgauge/taiko/issues/567#issuecomment-497225334, and see if it works.

**Comment by nehashri** [comment]
@boomi243 @adea11 Any updates on this issue?

**Comment by adea11** [comment]
Hi @nehashri, the issue I had was with https://github.com/getgauge/taiko/issues/567 which has now been resolved and closed.  Thanks

**Comment by boomi243** [comment]
@nehashri, Yes We are now able to successfully run taiko scripts on RHEL machine. Thanks Nivedha for your assistance.

We are not trying to run tests inside a Docker container.
