### ISSUE TITLE
Unable to Install gauge taiko 

### ISSUE THREAD

**Issue by adea11** [getgauge/taiko#566]
### Expected behavior
Taiko should install successfully and download chromium m dependency 

### Actual behavior
/usr/local/bin/taiko -> /usr/local/lib/node_modules/taiko/bin/taiko.js

> taiko@0.7.0 install /usr/local/lib/node_modules/taiko
> node lib/install.js

ERROR: Failed to download Chromium r637110! Set "TAIKO_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/taiko/.local-chromium']
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/local/lib/node_modules/taiko/.local-chromium' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! taiko@0.7.0 install: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the taiko@0.7.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

### Steps to reproduce
1. execute: sudo npm install -g taiko
2.
3.

### Versions
node -v:  v10.15.3

**Comment by shubhamsc** [comment]
@adea11 This is npm related issue when npm is not install properly in your system. To resolve this issue check https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

you can install taiko without sudo. try with `npm install -g taiko`

**Comment by adea11** [comment]
> npm install -g taiko
adding -g requires permission.....


MCHRMAC0005:-gauge-testing $ npm install -g taiko
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ade.ajayi/.npm/_logs/2019-05-23T10_40_18_341Z-debug.log

**Comment by shubhamsc** [comment]
@adea11 Can you give a try to install taiko after reinstalling node. 

Try with the following steps-
1. uninstall node completely
2. install node again with `brew install node`
3. then install taiko with `npm install -g taiko`

**Comment by adea11** [comment]
> @adea11 Can you give a try to install taiko after reinstalling node.
> 
> Try with the following steps-
> 
> 1. uninstall node completely
> 2. install node again with `brew install node`
> 3. then install taiko with `npm install -g taiko`

Thank @shubhamsc this issue has been resolved using the link you shared earlier : https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally
