### ISSUE TITLE
 Failed to launch chrome! -While executing taiko in a docker container

### ISSUE THREAD

**Issue by adea11** [getgauge/taiko#567]
### Expected behavior
Chromium browser should open 

### Actual behavior
Error Message: Error: Failed to launch chrome!
/usr/src/app/node_modules/taiko/.local-chromium/linux-637110/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory

Stacktrace:
Error: Failed to launch chrome!
node_modules/taiko/.local-chromium/linux-637110/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory

  at onClose (node_modules/taiko/lib/browserFetcher.js:221:24)
  at Interface.helper.addEventListener (node_modules/taiko/lib/browserFetcher.js:210:60)
  at emitNone (events.js:111:20)
  at Interface.emit (events.js:208:7)
  at Interface.close (readline.js:368:8)
  at Socket.onend (readline.js:147:10)
  at emitNone (events.js:111:20)
  at Socket.emit (events.js:208:7)
  at endReadableNT (_stream_readable.js:1064:12)
Error Message: Error: Browser or page not initialized. Call openBrowser() before using this API
Stacktrace:
Error: Browser or page not initialized. Call openBrowser() before using this API
at validate (node_modules/taiko/lib/taiko.js:2431:30)
at module.exports.closeBrowser (node_modules/taiko/lib/taiko.js:202:5)
at module.exports.(anonymous function) (node_modules/taiko/lib/taiko.js:2543:42)
at Object.afterSuite (tests/step_implementation.js:12:11)
Successfully generated html-report to => /usr/src/app/reports/html-report/index.html
Specifications: 0 executed 0 passed 0 failed 0 skipped
Scenarios: 0 executed 0 passed 0 failed 0 skipped

Total time taken: 211ms

### Steps to reproduce
1. install gauge: brew install gauge
2. npm install : Downloading Chromium r637110 - 85.9 Mb [====================] 100% 0.0s 
Chromium downloaded to /Users/Workspace/gauge-testing/node_modules/taiko/.local-chromium/mac-637110
npm WARN gauge-taiko-template@0.0.1 No repository field.
npm WARN gauge-taiko-template@0.0.1 No license field.

added 210 packages from 155 contributors and audited 358 packages in 25.195s
found 0 vulnerabilities

3. execute test using exiting docker image:....../docker run -it -v `pwd`:/gauge getgauge/taiko gauge run specs/

### Versions
gauge-1.0.5
npm -v6.9.0
taiko 0.7.0 (Chromium:74.0.3723.0)

**Comment by shubhamsc** [comment]
@adea11 Are you seeing this error after reinstalling taiko?

**Comment by adea11** [comment]
> @adea11 Are you seeing this error after reinstalling taiko?

@shubhamsc yes I'm still getting the error. Its executes successfully if I run 'npm test' or gauge run specs/' 

But I get the error when ran from docker.

I'm using your docker image pulled from dockerhub repo and I assume this already already has taiko installed at....   https://hub.docker.com/r/getgauge/taiko







I also tried 'docker-compose up' using your Dockfile at: https://github.com/getgauge-contrib/gauge-docker/blob/master/taiko.dockerfile........ but still no joy
FROM node

LABEL taiko.version="0.2.0"\
gauge.version="1.0.1"\
description="debian image with node, dependencies for headless chrome, gauge and taiko npm packages"\
repository="getgauge/taiko"

ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
ENV PATH=$PATH:/home/node/.npm-global/bin

requirements for chrome headless
https://github.com/Googlechrome/puppeteer/issues/290#issuecomment-322838700
RUN apt-get update &&\
apt-get install -y git-all gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \
libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 \
libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 \
libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates \
fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget &&\
rm -rf /var/lib/apt/lists/* &&\
mkdir -p /gauge &&\
chown -R node:node /gauge &&\
chmod 755 /gauge

USER node

RUN npm install -g taiko @getgauge/cli

WORKDIR /gauge

CMD gauge run specs/

**Comment by BugDiver** [comment]
@adea11 The repo https://github.com/getgauge-contrib/gauge-docker is deprecated. We do not maintain the docker images anymore.
You can use base `node` image to run taiko inside the docker container.

**Comment by adea11** [comment]
Hi @BugDiver  thanks for your response. However, this seem to be an issue beyond the docker image used. I have tried using base node image but got exactly the same error

**Comment by Apoorva-GA** [comment]
@adea11 Check if https://github.com/getgauge-contrib/gauge-docker/issues/3#issuecomment-472386420 helps?

**Comment by BugDiver** [comment]
@adea11 I was able to run `taiko` in a dokcer container using the base `node` image.  The docs have been updating with the instructions. The site might take some time to reflect the changes.
Attaching a screenshot which shows steps to set up the image
<img width="1656" alt="Screenshot 2019-05-30 at 11 29 52 AM" src="https://user-images.githubusercontent.com/15309877/58614023-dfbe9e80-82d4-11e9-81b0-c65ff896330f.png">

If you are trying to use `taiko` along with `gauge`  you might not have to install it globally. If you are facing issue in installing `@gauge/cli` try `npm install @getgauge/cli --unsafe-perm=true --allow-root`

Make sure `openBrowser` API is called with `haedless: true` and `--node-sandbox` args (shown in the screenshot).

Let us know if this helps

**Comment by adea11** [comment]
> @adea11 I was able to run `taiko` in a dokcer container using the base `node` image. The docs have been updating with the instructions. The site might take some time to reflect the changes.
> Attaching a screenshot which shows steps to set up the image
> <img alt="Screenshot 2019-05-30 at 11 29 52 AM" width="1656" src="https://user-images.githubusercontent.com/15309877/58614023-dfbe9e80-82d4-11e9-81b0-c65ff896330f.png">
> 
> If you are trying to use `taiko` along with `gauge` you might not have to install it globally. If you are facing issue in installing `@gauge/cli` try `npm install @getgauge/cli --unsafe-perm=true --allow-root`
> 
> Make sure `openBrowser` API is called with `haedless: true` and `--node-sandbox` args (shown in the screenshot).
> 
> Let us know if this helps




Hi @BugDiver thanks for your reply. Your suggestion worked when executing taiko REPL in a docker container but what I intended is to run my SPEC files on docker using 'npm test' or 'gauge run specs/'  cmd so it can be used for CI on Jenkins. But this can't be executed on taiko REPL you suggested

**Comment by adea11** [comment]
> @adea11 Check if [getgauge-contrib/gauge-docker#3 (comment)](https://github.com/getgauge-contrib/gauge-docker/issues/3#issuecomment-472386420) helps?

Thanks @Apoorva-GA, what I intended is to run my SPEC files on docker using 'npm test' or 'gauge run specs/' cmd so it can be used for CI on Jenkins.

**Comment by BugDiver** [comment]
@adea11 We are happy to help you with your issue. I have created a sample gauge + taiko project which runs gauge tests inside a container.
Here the link of the repo https://github.com/BugDiver/GaugeTaikoDocker
Please follow the README.md for instructions.

Let me know if this helps.

**Comment by adea11** [comment]
> @adea11 We are happy to help you with your issue. I have created a sample gauge + taiko project which runs gauge tests inside a container.
> Here the link of the repo https://github.com/BugDiver/GaugeTaikoDocker
> Please follow the README.md for instructions.
> 
> Let me know if this helps.

Hi @BugDiver, thanks .  Your mockup project was very helpful and test executed successfully.
