### ISSUE TITLE
Create plugin to allow Taiko to test site accessibility

### ISSUE THREAD

**Issue by RoscoV3** [getgauge/taiko#568]
Create a plugin for Taiko that would allow users to assess the accessibility of a site page. 

**Here is a snippet of text from the puppeteer class**
The Accessibility class provides methods for inspecting Chromium's accessibility tree. The accessibility tree is used by assistive technology such as screen readers or switches.

Accessibility is a very platform-specific thing. On different platforms, there are different screen readers that might have wildly different output.

Blink - Chrome's rendering engine - has a concept of "accessibility tree", which is then translated into different platform-specific APIs. Accessibility namespace gives users access to the Blink Accessibility Tree.

Most of the accessibility tree gets filtered out when converting from Blink AX Tree to Platform-specific AX-Tree or by assistive technologies themselves. By default, Puppeteer tries to approximate this filtering, exposing only the "interesting" nodes of the tree. 

Puppeteer has this functionality.
https://pptr.dev/#?product=Puppeteer&version=v1.16.0&show=api-class-accessibility

**Comment by andreas-ku** [comment]
@RoscoV3 is there anything else you are looking for besides inspecting the accessibility tree? It would be nice if you could share your usecase.

**Comment by RoscoV3** [comment]
I would like it to provide incite into the % of accessibility coverage the site has so that a company can make sure that their site is more user friendly for the disabled.

**Comment by zabil** [comment]
Have you tried using [lighthouse](https://github.com/GoogleChrome/lighthouse#using-the-node-cli) cli?

From their documentation, you can get an accessibility report by running the following command

```
lighthouse <url> --only-categories=accesibility
```

Is there something else that's not available in this report that you want from Taiko's plugin?

**Comment by andreas-ku** [comment]
@RoscoV3 I created a first draft of a plugin for accessibility testing. Can you check if this fits your usecase or otherwise create an issue on the plugin repo with the changes you would require? https://www.npmjs.com/package/taiko-accessibility https://github.com/andreas-ku/taiko-accessibility

**Comment by andreas-ku** [comment]
@RoscoV3 The plugin (https://www.npmjs.com/package/taiko-accessibility) now calculates the percentage as 'score', so you can do something like:

const audit = await runAudit();
expect(audit.score).toBeGreaterThan(80);

Please let me know if this solves your problem or if anything else is needed from your side.
