### ISSUE TITLE
Should be able to select text with given class

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#57]
**Actual behavior**
Getting the error
```
Invalid arguments passed, only relativeSelectors are accepted
```
**Steps to replicate**
* Using taiko run the following script
```
const { browser, openBrowser, goto, listItem, click, link } = require('taiko');
const assert = require("assert");

(async () => {
    try {
        await openBrowser();
        await goto("https://gauge.org/index.html");
        assert.ok(text("class","github_star").exists())
        await click(link(toRightOf(text("class","github_star"))),{waitForNavigation:true});
        await waitFor(5000);

        await closeBrowser();
    } catch (e) {
        console.error(e);
    } finally {
    }
})();
```
**Version**
```
0.0.9
```
Blocks #29

**Comment by NivedhaSenthil** [comment]
```text()``` does not support fetching using attribute and values, text api can be used to fetch elements matching exact text.

await has to be added before checking exists so that the promise gets resolved, there it was asserting against a promise. ```assert.ok(await text("class","github_star").exists())```

For clicking on github star something like this worked,
```click(listItem("class","githubstar-box"))```

**Comment by sguptatw** [comment]
Though this is not supported currently it would be a nice feature. Here is my use case I want to access the text with the given class.

**Comment by sguptatw** [comment]
This can be done using $
example - `await click(link(toRightOf($(".github_star"))));`
