### ISSUE TITLE
npm run examples not working with node version 12+

### ISSUE THREAD

**Issue by luciferankon** [getgauge/taiko#578]
### Expected behavior
It should work with node version 12+

### Actual behavior
It fails with an error message `pkg-config` command not found

### Steps to reproduce
1. update node version to 12+
2. delete node_modules from examples
3. run npm run examples

### Versions: 
node version - v12.3.1

**Comment by Apoorva-GA** [comment]
Have created a [issue](https://github.com/eugeneware/gifencoder/issues/42) in gifencoder.

**Comment by nehashri** [comment]
This seems to be an issue with our screencast plugin. We will have add support for the plugin with node 12 too. If gifencoder is not working, we will have to look for an alternate.

**Comment by Debashis9012** [comment]
`npm run examples` works properly with node version 12.
