### ISSUE TITLE
openTab throws navigation timeout error when url is not given

### ISSUE THREAD

**Issue by nehashri** [getgauge/taiko#583]
**Actual Behaviour**
`openTab()` throws navigation timeout error when url is not specified.

**Expected Behaviour**
`openTab()` should open an empty tab if url is not specified.

**Comment by Apoorva-GA** [comment]
Fix should be available in commit 44e2441

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed ```44e2441b5f6319b4d5bb42774aab8662374e2a25```
