### ISSUE TITLE
Write method do not triggers onInput or onchange events

### ISSUE THREAD

**Issue by BorjaRobles** [getgauge/taiko#590]
### Expected behavior
On write on inputs that generate an XHR the request should be generated

### Actual behavior
The input is filled with the text but the XHR request is not sent

### Steps to reproduce
1. Write in input field that have generates XHR request
2. The event is not trigger

### Versions
```
node v11.10.1
taiko Version: 0.7.1 (Chromium: 74.0.3723.0)
```

**Comment by Apoorva-GA** [comment]
@BorjaRobles Could you please give us an example as to where this happens? It would be easier for us to fix this.

**Comment by NivedhaSenthil** [comment]
There are some changes pushed in related to `write` api. Can you please verify if it works fine with master ? 
`npm install git+https://git@github.com/getgauge/taiko.git -g`

**Comment by negiDharmendra** [comment]
@BorjaRobles Please give a try to the latest *taiko* as @NivedhaSenthil has suggested.

**Comment by BorjaRobles** [comment]
oh looks fixed now ! thx @NivedhaSenthil
