### ISSUE TITLE
Check if Firewall message popup on openBrowser can be handled

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#601]
## Expected behavior
Shouldn't get the below popup on openBrowser
<img width="421" alt="Screen Shot 2019-06-06 at 10 34 11 PM" src="https://user-images.githubusercontent.com/6310197/59085777-55ea8300-891d-11e9-888c-3bd7065a434a.png">

## Actual behavior
Getting this pop-up on openBrowser until the Firewall setting is changed as suggested

## Steps to replicate
* On the REPL
> openBrowser()
 ✔ Browser opened

In less than a minute this pop-up is shown

## Discussion Update
This might be caused by a missing or wrong digital signature. - https://superuser.com/questions/912656/how-do-i-stop-my-mac-from-asking-to-accept-incoming-network-connections.

However, We can't code sign the chromium binaries.
Chromium might be accessing a few urls on start up? Maybe an update url or something. We could explore if there is a flag to turn it off.

**Comment by Apoorva-GA** [comment]
One option is to resign/create self-signed ad-hoc certificate by executing the following command
`sudo codesign --force --deep --sign - path-to-the-app.app`
More details [here](https://wpguru.co.uk/2015/06/how-to-kill-the-accept-incoming-connections-dialogue-on-your-mac-forever/)
