### ISSUE TITLE
REPL for headless mode

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#605]
## Expected behavior
Should be able to record scenarios for the headless mode

## Actual behavior
Today in the REPL, one can record scenarios only for the headful mode. Sometimes sites render differently in headless mode.

## Example
As mentioned in  https://github.com/getgauge/taiko/issues/297

**Comment by svtfrancisco** [comment]
you may try [Chrome Headless](https://github.com/GoogleChrome/puppeteer)
