### ISSUE TITLE
.code should have the closeBrowser in the finally section

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#61]
**Actual behavior**
Currently finally block is empty.

**Steps to replicate**
* Open the REPL
* openBrowser()
* .code
> The generated code does not have the closeBrowser() method

**Version**
```
commit 9e7a26ea5ee96a68d090452e3352e709230d59f2 (HEAD -> master, origin/master, origin/HEAD)
Author: NivedhaSenthil <nivedhasenthil@gmail.com>
Date:   Thu Jul 19 12:15:41 2018 +0530

    Update time gap between key strokes
```

**Comment by Apoorva-GA** [comment]
Should be available in commit 306d8cae7f9e05386a9587875865c48f1809a875.
