### ISSUE TITLE
Taiko does not export plugin correctly.

### ISSUE THREAD

**Issue by negiDharmendra** [getgauge/taiko#616]
### Expected behavior
A user would expect a taiko plugin called `taiko-xyz-plugin` to be exported as `xyzPlugin` or `xyz_plugin`.  Though `xyzPlugin` looks more idiomatic to me.

### Actual behavior
Taiko plugin `taiko-xyz-plugin` gets exported as `'xyz,plugin'`. Which will require the user to do the correct mapping.

**Example:**
```
const {openBrowser, closeBrowser, 'xyz,plugin':xyzPlugin} = require('taiko');
```

**Problematic piece of code** https://github.com/getgauge/taiko/blob/2a3f39e971d0a455720d2e0462975736a99e4b33/lib/taiko.js#L2407

**Comment by zabil** [comment]
Ideally `taiko-xyz-plugin` must be exported as `txyz-plugin` this also follows https://www.npmjs.com/package/module-best-practices#naming-conventions for modules

**Comment by zabil** [comment]
However `-` is not allowed in the import statements. This this case declare the variable as follows.
```
const {openBrowser, closeBrowser, 'xyz-plugin':xyzPlugin} = require('taiko');
```

**Comment by luciferankon** [comment]
Should not we export it like `xyzplugin` itself?

**Comment by zabil** [comment]
That increased the chances of plugin name clashes, reduces readability and increases difficulty in locating the plugin.

for e.g. when I look at 

```
const {openBrowser, closeBrowser, 'xyz-plugin':xyzPlugin} = require('taiko');
```

I know I can search for the npm package `taiko-xyz-plugin` when it is `xyzplugin` I am not sure what the actual plugin name is.

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed.
Tested version: ```1d5dc1e18014fb608c1cbfc99161c8feae3b7668```
