### ISSUE TITLE
Unable to run Taiko v.0.8.0 in Node.js version 8

### ISSUE THREAD

**Issue by chris-kobrzak** [getgauge/taiko#633]
### Expected behavior
Typing `taiko` in command line should launch the Recorder.

### Actual behavior
Getting the following console error:

```
TypeError: npmModule.isSymbolicLink is not a function
    at fs.readdirSync.filter.npmModule (/Users/<user>/.nvm/versions/node/v8.10.0/lib/node_modules/taiko/lib/plugins.js:42:27)
    at Array.filter (<anonymous>)
    at getPluginsInstalledOn (/Users/<user>/.nvm/versions/node/v8.10.0/lib/node_modules/taiko/lib/plugins.js:41:10)
    at getExecutablePlugins (/Users/<user>/.nvm/versions/node/v8.10.0/lib/node_modules/taiko/lib/plugins.js:25:25)
    at Object.<anonymous> (/Users/<user>/.nvm/versions/node/v8.10.0/lib/node_modules/taiko/bin/taiko.js:69:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

```

### Steps to reproduce
1. `npm install -g taiko`
2. `$ taiko`

### Versions
```
v0.8.0
```

**Comment by Debashis9012** [comment]
@chris-kobrzak For me its working as excepted. kindly find the below code snippet 

```
Version: 0.8.0
➜  ~ taiko

Version: 0.8.0 (Chromium:76.0.3803.0)
Type .api for help and .exit to quit

> openBrowser()
 ✔ Browser opened
> goto("Google.com")
 ✔ Navigated to URL http://Google.com
```
Could you please let us know while getting this issue what commit version of taiko and OS you are using ?

**Comment by chris-kobrzak** [comment]
Hey @Debashis9012,

Here you go:

OS: macOS Mojave 10.14.4
Node.js: 8.10.0 installed via NVM; also tried 8.16.0
NPM: 6.9.0
Taiko: 0.8.0

Please note, Taiko *is* working as expected when you switch to Node.js 10 (10.16.0 in my case). Having established that, I'm going to update the title of this issue accordingly.

Many thanks!

**Comment by chris-kobrzak** [comment]
It looks like 51a2b4c is the culprit where we have a call to [isSymbolicLink](https://nodejs.org/api/fs.html#fs_dirent_issymboliclink) which is method only available in Node.js v10

**Comment by strdr4605** [comment]
@chris-kobrzak , has the same error! Fixed by updating node from **v10.9.0** to **v10.16.0**!

**Comment by lungu25** [comment]
@chris-kobrzak , had the same error! Fixed by updating node from v10.9.0 to v10.16.0!

**Comment by nehashri** [comment]
We will be looking at fixing this and supporting node 8 soon.

**Comment by negiDharmendra** [comment]
Fix is available in [ae609a1](https://github.com/getgauge/taiko/commit/ae609a16fc7910c8226ff5ac433b9a5e3237f777) commit

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed. 
Tested version: `d3df4b58510c99eea7defd9c0c5f5fdd560e92fc`

**Comment by chris-kobrzak** [comment]
Many thanks for turning this one around so quickly! Could you please give us a rough estimate on when this fix might be released?

**Comment by NivedhaSenthil** [comment]
@chris-kobrzak We are aiming for a release next week.
