### ISSUE TITLE
Unable to attach a file to an invisible element

### ISSUE THREAD

**Issue by mbjeffbird** [getgauge/taiko#634]
### Expected behavior
If a file input element is invisible(hidden), I should still be able to upload a file.

### Actual behavior
When the file input is hidden, I am unable to use attach() to upload a file to it.

### Steps to reproduce
1. Locate a file input on a site that is hidden. (usually another button is there to initiate the file browser on the computer)
2. Use Taiko's attach() feature to attempt to upload a file.

### Versions
```
Taiko: 0.7.1 (Chromium: 74.0.3723.0)
Node: v11.11.0
```

**Comment by Debashis9012** [comment]
Unable to attach with the hidden element with proximity selector
Reference: https://codepen.io/jeremili/pen/BzPKzZ
Getting below error:
`> attach("/Users/debas/dadebash/work/Screenshot-1558690681522.png",to(fileField({id:"file-input"},{selectHiddenElement:true})))
 ✘ Error: Could not compute box model., run `.trace` for more info.
`

Tested with the latest build: ```ead0ab9b52c68989c32abe6ca5e675792bfeb8ae```

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed with the version: ```1d5dc1e18014fb608c1cbfc99161c8feae3b7668```
Note:
1. Taiko cannot highlight hidden elements.
2. Proximity selectors cant be used with attach api.

**Comment by nehashri** [comment]
Related https://github.com/getgauge/taiko/issues/630
