### ISSUE TITLE
**await deleteCookies()** Atleast URL or Domain needs to be specified for deleting cookie

### ISSUE THREAD

**Issue by adea11** [getgauge/taiko#639]
### Expected behavior
await deleteCookies() >> should clear all browser cookies 

### Actual behavior
 Error Message: Error: Atleast URL or Domain needs to be specified for deleting cookies
            Stacktrace: 
            Error: Atleast URL or Domain needs to be specified for deleting cookies

### Steps to reproduce
1. apply await deleteCookies() as part of step implementation 

### Versions
taiko version 0.7.1 (Chromium: 74.0.3723.0)
node version v12.4.0

**Comment by nehashri** [comment]
@adea11 `deleteCookies()` clears all browser cookies as of taiko version 0.8.0. Please update Taiko to make use of this functionality.
