### ISSUE TITLE
Should be able to select first required element w.r.t a proximity selector

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#64]
**Actual behavior**
The element is not selected. This is in a table row. The first column is the alphabet. W.r.t the alphabet I am trying to click the first link available after it.
         `await click(link(toRightOf("D")))`
> However this does not select the element

**Steps to replicate**
Run the following script in taiko
```
const { browser, openBrowser, goto, click,link,image } = require('taiko');

(async () => {
    try {
        await openBrowser({headless:false});
        await goto("https://in.bookmyshow.com/bengaluru");
        // await click("Bengaluru");
        // await write('NCR', into(await inputField("placeholder","Search for your city")));
        // await click("NCR");
        await click("View All");
        await click(link("English"))
        await click(image("Hotel Transylvania 3: A Monster Vacation"))
        await click(link("Book Tickets"))
        await waitFor("5000")

        //await hover(link("5:20 PM",toRightOf(link("Carnival: Rockline Mall"))))
        await click(link(contains("4:20 PM"),toRightOf(link("Cinepolis: Binnypet Mall"))))
        await click(link('Accept'))
        await click(listItem(contains("1")))
        await click(link(toRightOf("D")))
        await click("Select Seats")
        await waitFor("5000")
        await closeBrowser();
    } catch (e) {
        console.error(e);
    } finally {
    }
})();
```
> link element next to the alphabet is not getting selected

**Version**
```
commit version - 306d8cae7f9e05386a9587875865c48f1809a875
```

**Comment by sguptatw** [comment]
Note: Even though link next to right of alphabet `D` is not selected, the action is considered successful next set of scripts are executed.

**Comment by sguptatw** [comment]
Updating the script to select a generic English movie for the 1st movie time
```
const { browser, openBrowser, goto, click,link,image } = require('taiko');

(async () => {
    try {
        await openBrowser({headless:false});
        await goto("https://in.bookmyshow.com/bengaluru");

        await click("Bengaluru");
        await write('NCR', into(await inputField({"placeholder":"Search for your city"})));
        await click("NCR");
        await click("View All");
        await click(link("English"))
        await click(image(below(link("Now Showing"))))
        //await click(link("Book Tickets"))
// This step has to be done manually as of now.

        await waitFor("5000")

        await click(link({"class":"__showtime-link"}))
        await click("Accept")
        await click("Select Seats")
        
        await click(link(toRightOf("D")))
        await waitFor("5000")
    } catch (e) {
        console.error(e);
    } finally {
        await closeBrowser();
    }
})();
```
One more observation, toRightOf w.r.t `D` is selecting the row In `C`. 'Cause the number of seats are uneven. I mean C has all seats. And proximity wise C1 is closer than D 1st seat. However the horizontal element should be given preference. You need uneven seating to replicate this issue.

**Comment by nehashri** [comment]
To give more context, I think what @sguptatw is trying to do here is to book seats in a movie theater. In this case there is an uneven seating arrangement like so
```
D     [1][2] 
C  [1][2][3]
```
In this case when we say toRightOf("D"), the seats C[1] is getting selected. This is because C[1] is much closer to element D than D[1]. Taiko doesn't really know if an element is exactly horizontal to an element or not. 
I think this behaviour is perfectly fine as only in cases like this we will have elements that are properly horizontal. In most cases this is not the case, hence preference should not be given to the element which is perfectly horizontal to a given element. 
PS: Taiko has other selectors than the proximity ones. Maybe another kind of selector is best suited for this scenario.

**Comment by NivedhaSenthil** [comment]
doing a combination of proximity selectors might help here, like
```await click(link(toRightOf("D"),above("C")))```
