### ISSUE TITLE
Should be able to select InputField with no explicit type with TextBox API

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#640]
### Expected behavior
Should be able to select InputField with no explicit type with TextBox API

### Actual behavior
Currently I have to use inputField(deprecated) or $ for selecting this

### Steps to reproduce
1. Script
```
const assert = require('assert');

const { openBrowser, goto, write, press, click, near, checkBox, inputField,closeBrowser } = require('taiko');
(async () => {
    try {
        await openBrowser({headless:false},{timeout:60000});
        await goto("http://todomvc.com/examples/typescript-backbone/");

        await write('Complete Task',into(inputField({placeholder:"What needs to be done?"})));
    } catch (e) {
        console.error(e);
    } finally {
        await closeBrowser();
    }
})();
```
> The HTML of the inputField looks like this
```
<input class="new-todo" placeholder="What needs to be done?" value="" data-reactid=".0.0.1">
```
> Should be able to use textBox instead of inputField
### Versions
```
commit - c4bd3810aa5790692479555507e40dc66a2a4fe3
```

**Comment by Debashis9012** [comment]
This enhancement has been verified and found fixed.
Now textBox api supports no explicit type api attribute.
Tested version: `364f6b088a7b3d31eb4dbbbd49c1f14d5333ab25`

**Comment by SudhiHathwar** [comment]
@negiDharmendra , Is this fix released?

**Comment by zabil** [comment]
@SudhiHathwar yes it is. 

The best place to look for fixes against releases are here
https://github.com/getgauge/taiko/releases

You can also use npm to install the latest master version or a specific commit using

```
npm install git+https://git@github.com/getgauge/taiko.git
```
