### ISSUE TITLE
taiko -v for release version should provide correct output

### ISSUE THREAD

**Issue by Debashis9012** [getgauge/taiko#641]
### Expected behavior
`taiko -v` should not give "Undefined".
Either it should provide `Release` or `commit version`

Example:
`Version: 0.9.0 (Chromium: 76.0.3803.0) 557605e6120efa4eb3276c5ecf52aa467d04ca14`
`Version: 0.9.0 (Chromium: 76.0.3803.0) Release`

### Actual behavior
On release version it provides the below output
**Version: 0.8.0 (Chromium: 76.0.3803.0) undefined**

**Comment by Apoorva-GA** [comment]
Fix available in d3df4b5

**Comment by Debashis9012** [comment]
This has been verified and found fixed.
