### ISSUE TITLE
Should enter text in the correct field when used in loop

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#646]
### Expected behavior
Should enter text in the correct field when used in loop

### Actual behavior
The text is being entered in the last text field

### Steps to reproduce
1. clone https://github.com/sguptatw/loopIssueTaiko.git
2. cd loopIssueTaiko
3. npm install
4. gauge run

### Versions
```
taiko - c4bd3810aa5790692479555507e40dc66a2a4fe3
Gauge version: 1.0.5

Plugins
-------
html-report (4.0.8)
js (2.3.5)
screenshot (0.0.1)
```

**Comment by sguptatw** [comment]
**Work around**
Use for loop instead of for each in code

**Comment by BugDiver** [comment]
@sguptatw The `forEach` does not handle `async` callbacks. So you have to use `for` loop instead of `forEach` for `async` tasks.

**Comment by Debashis9012** [comment]
The node's forEach does not handle the  async callbacks. So any await inside the callback will not be considered, and the loop will go to the next element without completing the first task.
