### ISSUE TITLE
Should be able to playback a recorded script successfully

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#653]
### Expected behavior
Should be able to playback a recorded script successfully

### Actual behavior
When I playback the script I get the exception
```
 STATUS: 403, STATUS_TEXT: 
    at Object.handleNavigation (.../taiko/lib/pageHandler.js:104:15)
```

### Steps to reproduce
1. open the REPL
2. Record the flow
```
> openBrowser()
 ✔ Browser opened
> goto("https://www.zomato.com/bangalore/taco-bell-koramangala-6th-block/order") 
 ✔ Navigated to URL https://www.zomato.com/bangalore/taco-bell-koramangala-6th-block/order
> .code
const { openBrowser, goto, closeBrowser } = require('taiko');
(async () => {
    try {
        await openBrowser();
        await goto("https://www.zomato.com/bangalore/taco-bell-koramangala-6th-block/order");
    } catch (error) {
        console.error(error);
    } finally {
        await closeBrowser();
    }
})();
```
3. Now, execute the recorded flow
> Get the exception
```
Error: Navigation to url https://www.zomato.com/bangalore/taco-bell-koramangala-6th-block/order failed.
 STATUS: 403, STATUS_TEXT: 
    at Object.handleNavigation (.../taiko/lib/pageHandler.js:104:15)
```

### Versions
```
commit - 7a49c17886d51b619dcfa53717fd88518d6499dc
```

**Comment by NivedhaSenthil** [comment]
This is happening because zomato blocks accessing the site when launched in headless mode. Hence the 403 status code which denotes `Forbidden`.

**Comment by sguptatw** [comment]
**Observations**
The script is recorded for the headful mode in the REPL. But when it is played back it is in the headless mode. There can be a difference in the behaviour of headful and headless modes. This is not evident while replaying the recorded script. Maybe it is worth considering that the REPL mode and generated code both are consistent in the modes they run? Currently headful is the only state that the REPL supports.

**Comment by Debashis9012** [comment]
This we should update in our documentation.
