### ISSUE TITLE
Unable to select dropDown option based on index and Value

### ISSUE THREAD

**Issue by vasanthdama** [getgauge/taiko#661]
Unable to select dropDown option based on index and Value

### Expected behavior
User should be able to select dropDown option based on option index & value, now currently taiko supporting only text / label

### Actual behavior
Now by using taiko we can select option based on text only..
EX:
"`<div name="ReasonText"> Reason: </div>
<select class="select" name="reasonselection">
    <option  value="-99"> Select </option>
    <option value="9092">Reason1</option>
    <option value="9093">Reason2</option>
<select>`"
### Steps to reproduce
await dropDown(below("Reason:")).select("Reason1"); - Only it allows text

### Versions
```
node: v10.16.0
taiko: Version: 0.8.0 (Chromium: 76.0.3803.0)

**Comment by Debashis9012** [comment]
This enhancement has been verified and found fixed.
Commit: ```636b83f0bcf5a08fa79f949fe0c0972c4a069bdb```

**Comment by vasanthdama** [comment]
@Debashis9012 When I will get this changes to master build / I mean when I need to use this fix

**Comment by Debashis9012** [comment]
@vasanthdama  you can use the fix version for this enhancement. Kindly install taiko from master or you can use fix version:
`npm install git+https://github.com/getgauge/taiko.git#636b83f0bcf5a08fa79f949fe0c0972c4a069bdb
-g`
`npm install https://github.com/getgauge/taiko -g `
