### ISSUE TITLE
File does not exists but attach api shows successful message

### ISSUE THREAD

**Issue by Debashis9012** [getgauge/taiko#679]
### Expected behavior
attach api should not throw the successful message if file does not exists in specified path.

### Actual behavior
```
> attach("/Users/debas/dadebash/work/Screenshot-1558690681522.png",to(fileField({id:"file-input"},{selectHiddenElement:true})))
Error: File /Users/debas/dadebash/work/Screenshot-1558690681522.png does not exist.
    at fs.open (/Users/debas/.nvm/versions/node/v10.15.3/lib/node_modules/taiko/lib/taiko.js:1143:19)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
> WARNING: Taiko cannot highlight hidden elements.
 ✔ Attached /Users/debas/dadebash/work/Screenshot-1558690681522.png to the file field[@id = concat('file-input', "")]
```

### Steps to reproduce
in repl:
1. openBrowser()
2. goto("file:///Users/work/hiddenTest.html")
3. attach("/Users/debas/dadebash/work/Screenshot-1558690681522.png",to(fileField({id:"file-input"},{selectHiddenElement:true})))

Reference: https://codepen.io/jeremili/pen/BzPKzZ

### Versions
```
Version: 1.0.1 (Chromium: 76.0.3803.0) 1d5dc1e18014fb608c1cbfc99161c8feae3b7668
node: v10.15.3
```

**Comment by rparthas** [comment]
@Debashis9012 Attach api throws the error message and it does not emit success message. I could see descevent.emit much below the error and code does not reach in case of error. I used the existing ElementsApI.spec but was unable to reproduce the issue

**Comment by Debashis9012** [comment]
The above issue has been verified and found fixed.
Its gives the below error:
```
 ✘ Error: File /Users/debas/dadebash/work/Screenshot-1558690681522.png does not exist., run `.trace` for more info.

```
Tested version: Version: 1.0.3 (Chromium: 76.0.3803.0) f32acae28ff332f5af46541764a5b0cc42a43ca4
```
