### ISSUE TITLE
support fetch

### ISSUE THREAD

**Issue by kaldown** [getgauge/taiko#683]
### Expected behavior
I want be able to use fetch, like
```
fetch('https://127.0.0.1:8080/123')
.then(res => res.json())
.then(write(res.body, into(textBox({placeholder: "data"}))))
```

### Actual behavior

> Thrown:
> fetch is not defined

### Versions
```
taiko --version
Version: 1.0.0 (Chromium: 76.0.3803.0) RELEASE
(my local browser)

node --version
v11.15.0
```

**Comment by saikrishna321** [comment]
The fetch API is not implemented in Node.

You need to use an external module for that, like node-fetch.

Install it in your Node application like this

`npm i node-fetch --save`
then put the line below at the top of the files where you are using the fetch API:

const fetch = require("node-fetch");

**Comment by kaldown** [comment]
Could you please tell, can I extend **taiko** usage in extended cases, like
automation robot for some flow which in the end include payment process ?
Thank you

**Comment by saikrishna321** [comment]
@kaldown Sorry, I quite don't understand. 

>> automation robot 

 What you mean by this ?

**Comment by kaldown** [comment]
I mean how is it safe yo use taiko NOT in a test purposes?
what if I'm going to use it as a crawler or as a solution to achieve automation with a payment services who had no public API ?
Is usage taiko for such cases legal and safe?

**Comment by zabil** [comment]
I can comment on legality and safety. But yes, although it's built for testing, you can use it as crawler. However, we do not have any examples or demos yet.
