### ISSUE TITLE
additional write option to hide text from output

### ISSUE THREAD

**Issue by Brodan** [getgauge/taiko#688]
### Expected behavior
The `write` page action ([docs](https://taiko.gauge.org/#write)) should accept a boolean option (`hidden` for example) that explicit prevents the text being written to screen.

### Actual behavior
Currently there exists logic ([here](https://github.com/getgauge/taiko/blob/master/lib/taiko.js#L1043)) which will output `*****` if the active element's `isPassword` is True. However, there may be additional types of text other than passwords that one would not want written to terminal/logged.

**Comment by Brodan** [comment]
closing this as #709 has been merged. thank you for the quick review and merge!

**Comment by Debashis9012** [comment]
It has been verified and found fixed with the version:
```version: 1.0.1 (Chromium: 76.0.3803.0) 7b4db1995facc68d8a93cd62fa5ed6e29e37a171```
