### ISSUE TITLE
Cannot run on WSL (Windows Subsystem for Linux)

### ISSUE THREAD

**Issue by gtbono** [getgauge/taiko#693]
Hello, I'm running Taiko 1.0.0 and Node.JS 12.6.0, but I am trying to run on WSL, is it possible to run? it gives me the error below:

![image](https://user-images.githubusercontent.com/1094843/61260866-3c2b2f80-a756-11e9-96ac-4becf04e78cb.png)

Is there a way I can point to a Chrome executable? I can point to my Chrome executable on the Windows side so it can open it maybe.

Have you guys tried it on WSL?

**Comment by luciferankon** [comment]
@gtbono Hey you need to install the dependencies for taiko. You can find those [here](https://taiko.gauge.org/#debian-dependencies).
Even though openBrowser will fail in REPL mode. As in repl mode taiko launches the browser in headful mode and it will not be able to launch the display.
So you need to write the script in a file and perform the actions you want to perform.
Report back if you have any issues.

**Comment by Apoorva-GA** [comment]
Closing this for now. Feel free to reopen if are facing the issue.
