### ISSUE TITLE
Not able to connect to remote machine

### ISSUE THREAD

**Issue by luciferankon** [getgauge/taiko#695]
### Expected behavior
Taiko should be able to connect to remote browsers

### Actual behavior
It's not connecting to remote browsers

### Steps to reproduce
1. launch remote debugging mode on a machine
2. try to connect to it using host and port from a different machine

### Versions
taiko : Version: 1.0.0 (Chromium: 76.0.3803.0)

**Comment by zabil** [comment]
Don't this this is an issue anymore.
