### ISSUE TITLE
Constant timeout when gauge/taiko is executed in Jenkins or Docker container

### ISSUE THREAD

**Issue by adea11** [getgauge/taiko#700]
### Expected behavior
When multiple Specs file are executed on Jenkins and default test_timeout is set 120000 the test should not timeout 

### Actual behavior
Test constantly timeout 

### Steps to reproduce
1) Attached ssh and Jenkins file to Gauge/Taiko framework
2) execute test on Jenkins by triggering build process

### Versions
node : v10.15.3
Gauge version: 1.0.5
flash (0.0.1)
html-report (4.0.8)
js (2.3.5)
json-report (0.3.1)
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.1)

**Comment by luciferankon** [comment]
@adea11 Hey can you please share a sample project to replicate the same thing?

**Comment by adea11** [comment]
@luciferankon. I there are already existing logs about this issue. See https://github.com/getgauge/gauge/issues/1255 and https://github.com/getgauge/taiko/issues/393. I suppose this is a known issue and just wonder when a fix will be available. I can't  exactly provide a sample project as It only  occur (for me) when gauge/taiko is executed remotely either via Jenkins or Docker. 

I have about 7 scenarios in 5 specs but as soon as any times out the rest also time out as well. See some Jenkins error attached 


>>Error Message: Error: Navigation took more than 30000ms. Please increase the timeout.
        Stacktrace: 
        Error: Navigation took more than 30000ms. Please increase the timeout.
            at node_modules/taiko/lib/taiko.js:2661:19
            at async doActionAwaitingNavigation (node_modules/taiko/lib/taiko.js:2631:5)
            at async module.exports.write (node_modules/taiko/lib/taiko.js:1063:5)<<


>>Error Message: Error: Timed out
        Stacktrace: 
        Error: Timed out
            at Timeout.<anonymous> (/home/jenkins/.gauge/plugins/js/2.3.5/src/test.js:43:23)
            at listOnTimeout (internal/timers.js:531:17)
            at processTimers (internal/timers.js:475:7)<<

**Comment by zabil** [comment]
The timeout happens when a web page does not load in the specified time. So it will help understand what web page you are trying to load. The issues you have pointed to are errors that we fixed by identifying why the page does not load under 30000ms. There may not be a fix for Taiko on this. 

The when running in docker the tests run in headless mode. Perhaps the site works different when it is accessed via a headless browser. 

I will help immensely if there is some way you can set up a test project to replicate this. It will be very difficult to solve it without knowing what is being tested.

**Comment by adea11** [comment]
Sorted!!!.  Test is now executing as expected, thanks

**Comment by zabil** [comment]
What was the problem?

**Comment by adea11** [comment]
There is a browser validation on the app. Which interestingly seem not to be an issue locally only when triggered via CI on Jenkins

**Comment by Noob7** [comment]
What did you do to fix it :( i increased the timeout but it stil timeouts randomly. What can i do to fix it

**Comment by sriv** [comment]
@Noob7 - perhaps you could open a new issue with some context about your problem? I fear that your case may perhaps be different from @adea11 's.

**Comment by tester-mind** [comment]
> Sorted!!!. Test is now executing as expected, thanks

Hi @Noob7 - I am also facing the same issue running scripts in the GitLab pipeline, can you please provide the resolution for the issue?
