### ISSUE TITLE
[improvement] Retrieve response of a request that have been intercepted

### ISSUE THREAD

**Issue by sarut0bi** [getgauge/taiko#704]
hi, 
currently there is no way to retrieve response of a request that have been intercepted & continued ?
I think it should be a nice improvement,
Regards,

**Comment by chandresh-n** [comment]
Hey @sarut0bi , to get clarity, are you talking about the 'case 3' mentioned here ?
https://github.com/getgauge/taiko/issues/98#issuecomment-419795664
> We will be following below design for intercepting APIs
> 
> case 1: block url => `intercept(url)`
> case 2: mockResponse => `intercept(url,{mockObject})`
> case 3: override request => `intercept(url,(request) => {request.continue({overrideObject})})`
> case 4: redirect => `intercept(url,redirectUrl)`
> case 5: mockResponse based on request =>
> `intercept(url,(request) => { //someaction; request.respond({mockResponseObject})} )`

**Comment by sarut0bi** [comment]
:+1:
