### ISSUE TITLE
Update documentation ( taiko screencast not on npm )

### ISSUE THREAD

**Issue by cmbirk** [getgauge/taiko#708]
### Expected behavior
Should be able to install `taiko-screencast`

### Actual behavior
`taiko-screencast` not found in npm

### Steps to reproduce
See issue in `taiko-screencast` repo here: https://github.com/getgauge-contrib/taiko-screencast/issues/6
1. `npm install --save-dev `taiko-screencast`
2. Get error from npm that the package doesn't exist

Would recommend reaching out to the package maintainer or removing that package from the taiko documentation. I've created the above GH issue to notify the package maintainer that it doesn't appear to be published to npm

**Comment by Apoorva-GA** [comment]
@cmbirk We will be releasing taiko-screencast to npm. Please track it as part of the [issue](getgauge-contrib/taiko-screencast#6) you raised. Hence closing this.
