### ISSUE TITLE
Taiko doesn't wait for element to be focusable in write APIs

### ISSUE THREAD

**Issue by nehashri** [getgauge/taiko#714]
**Actual behaviour**
If write and clear API is used with a selector, it doesn't wait for the element to become focusable before trying to write. 

**Expected behaviour**
If write and clear API is used with a selector, it should wait for the element to become focusable before trying to write. If no element is focusable, it should fail after a given time.

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed.
Tested version:
```
Version: 1.0.1 (Chromium: 76.0.3803.0) 5ada00f72c218606b9681f18966987ac606bcaba
