### ISSUE TITLE
Unable to clear text in text area

### ISSUE THREAD

**Issue by nehashri** [getgauge/taiko#715]
**Actual behaviour**
If clear API is used in a textarea field, only a single line is cleared, the whole field is not cleared.

**Expected behaviour**
It should clear the whole textarea field

**Steps to reproduce**
1. Create a html file(a.html) with the following
```
<!DOCTYPE html>
<html>
    <body>
        <label for="text_box">textbox</label>
        <textarea id="text_box"></textarea>
    </body>
</html>
```
2. Run the following script
```
const { openBrowser, goto, textBox, into, write, press, clear, closeBrowser } = require('taiko');
(async () => {
    try {
        await openBrowser();
        await goto('<path to a.html>');
        await write("hello", into(textBox("textbox")));
        await press("Enter");
        await write("Good Day");
        await clear(textBox("textbox"));
    } catch (error) {
        console.error(error);
    } finally {
        await closeBrowser();
    }
})();
```
3. Notice only the line "Good Day" is cleared, the textarea still contains "hello".

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed.
Tested version: 
```Version: 1.0.1 (Chromium: 76.0.3803.0) 5ada00f72c218606b9681f18966987ac606bcaba```
