### ISSUE TITLE
write api does not enter correct order of text

### ISSUE THREAD

**Issue by Debashis9012** [getgauge/taiko#717]
### Expected behavior
write api should enter the text in correct order

### Actual behavior
text order is incorrect

### Steps to reproduce
 openBrowser();
 goto("cleartrip.com");
 write("Bangalore",into(textBox(below("From"))));

Observations:
In repl it shows the below success message:
`✔ Wrote Bangalore into the text field Below From`
but in page it has entered as `angaloreB` value.
 Kindly find the below attached screenshot.

<img width="876" alt="Screen Shot 2019-07-26 at 2 31 38 PM" src="https://user-images.githubusercontent.com/46309201/61940859-e9ead980-afb3-11e9-995c-3459790cfd17.png">

```
 Version: 1.0.1 (Chromium: 76.0.3803.0) 7b4db1995facc68d8a93cd62fa5ed6e29e37a171
```

**Comment by bharath-nepoleon** [comment]
I would like to raise a PR for this. Will start investigating it. I was able to reproduce the issue only in the repl

```
> openBrowser();
 ✔ Browser opened
> goto("cleartrip.com");
 ✔ Navigated to URL http://cleartrip.com
> write("Bangalore",into(textBox(below("From"))));
 ✔ Wrote Bangalore into the text field Below From
```

**Comment by bharath-nepoleon** [comment]
I am able to reproduce this only in Cleartrip website. Weirdly this happens only when the browser is out of focus when the script is running. Looks like the cursor moves to start once the first letter is entered. This could be a issue on their site. Have to debug further to find the origin of this error.

**Comment by zabil** [comment]
The script mentioned above now works fine with Taiko 1.0.6
