### ISSUE TITLE
Issue goto on single page application

### ISSUE THREAD

**Issue by rsun-thoughtworks** [getgauge/taiko#727]
### Expected behavior
I open 

### Actual behavior
goto should be fine with every request.

### Steps to reproduce
```bash
goto("https://earth.nullschool.net/zh-cn/#2019/05/01/0600Z/wind/surface/level/overlay=temp/orthographic=-247.49,35.34,1092/loc=114.340,30.651")
```
works fine, but, after the first goto
```bash
goto("https://earth.nullschool.net/zh-cn/#2019/05/02/0600Z/wind/surface/level/overlay=temp/orthographic=-247.49,35.34,1092/loc=114.340,30.651")
```

The command line stuck and keeps waiting.

### Versions
taiko 1.0.0 (76.0.3803.0)
node v10.8.0
macOS

**Comment by Debashis9012** [comment]
@rsun-thoughtworks  I have tried with the same taiko version but not able to reproduce it. At first go its woking as excepted. Kindly find the below screenshot:
<img width="709" alt="Screen Shot 2019-07-31 at 11 05 11 AM" src="https://user-images.githubusercontent.com/46309201/62186250-343cd380-b383-11e9-8926-7a838297ad1b.png">

Could you please upgrade your taiko version (`npm install taiko -g`) and let us know whether you are facing same issue.

**Comment by rsun-thoughtworks** [comment]
> @rsun-thoughtworks I have tried with the same taiko version but not able to reproduce it. At first go its woking as excepted. Kindly find the below screenshot:
> <img alt="Screen Shot 2019-07-31 at 11 05 11 AM" width="709" src="https://user-images.githubusercontent.com/46309201/62186250-343cd380-b383-11e9-8926-7a838297ad1b.png">
> 
> Could you please upgrade your taiko version (`npm install taiko -g`) and let us know whether you are facing same issue.

Hi, According to my description, we have two steps to reproduce it:
```sh
goto("https://earth.nullschool.net/zh-cn/#2019/05/01/0600Z/wind/surface/level/overlay=temp/orthographic=-247.49,35.34,1092/loc=114.340,30.651")

goto("https://earth.nullschool.net/zh-cn/#2019/05/02/0600Z/wind/surface/level/overlay=temp/orthographic=-247.49,35.34,1092/loc=114.340,30.651")
```

According to your screen, you only call goto once.

You may reproduce what I have by run the gotos I provide, Thanks!

**Comment by Debashis9012** [comment]
@rsun-thoughtworks  Able to reproduce it. Thanks for pointing it out.
We will look into this.
updated screenshot:
<img width="718" alt="Screen Shot 2019-07-31 at 11 21 11 AM" src="https://user-images.githubusercontent.com/46309201/62186921-64857180-b385-11e9-8a93-5c90efb23466.png">

**Comment by suganya-sangith** [comment]
Hi will take up this issue

**Comment by suganya-sangith** [comment]
Observations made 
https://github.com/getgauge/taiko/blob/5ada00f72c218606b9681f18966987ac606bcaba/lib/handlers/pageHandler.js#L136

page.navigate is not emitting
https://github.com/getgauge/taiko/blob/5ada00f72c218606b9681f18966987ac606bcaba/lib/handlers/pageHandler.js#L131-L133

Tried directly in `chrome-remote-interface`, and filed an issue
https://github.com/cyrus-and/chrome-remote-interface/issues/399

They mentioned that this is an issue in Chromium
https://chromium-review.googlesource.com/c/chromium/src/+/999115/

@NivedhaSenthil @Debashis9012  I'm new to chrome-dev-tools, will try the fix they proposed and run the e2e. However not sure if this fix might affect existing code. Any comments?

**Comment by NivedhaSenthil** [comment]
Fix looks fine given the design of CDP, can be updated in `doActionAwaitingNavigation` where we wait for `loadEventFired` for navigation apis.

**Comment by suganya-sangith** [comment]
Seems to be the case for any within page navigation, following will also fail

```
goto("https://github.com/getgauge/taiko#whats-taiko")
goto("https://github.com/getgauge/taiko#whats-taiko")
```
Raised a PR for this @NivedhaSenthil

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed.
Tested version: `ef43f50bfcd74ac6512454789151a726adc2b8b7`

**Comment by rsun-thoughtworks** [comment]
@Debashis9012 Hi, do you know when we will release next version that fixs this issue?
