### ISSUE TITLE
issue on local html file on goto action

### ISSUE THREAD

**Issue by z04jmath** [getgauge/taiko#731]
### Expected behavior
await goto("file:///"+fullPath);
fullpath is in win32 format c:\temp.html 
shall open file localfile 

### Actual behavior
In windows 10, i have a timeout but browser is opened on the right file.
`      Error Message: Error: Timed out
        Stacktrace: 
        Error: Timed out
            at Timeout.<anonymous> (C:\Users\xx\AppData\Roaming\gauge\plugins\js\2.3.5\src\test.js:43:23)
            at ontimeout (timers.js:436:11)
            at tryOnTimeout (timers.js:300:5)
            at listOnTimeout (timers.js:263:5)
            at Timer.processTimers (timers.js:223:10)`

i have to do string replacement to make it work
`
  fullPath = fullPath.replace(/(\\)/g,'/');
  fullPath = fullPath.replace(/(c:)/g,'C:');
`

### Versions
```
$ node --version
v10.15.3

$ taiko --version
Version: 1.0.0 (Chromium: 76.0.3803.0) RELEASE

$ gauge --version
Gauge version: 1.0.4
Commit Hash: 3a9a647

Plugins
-------
html-report (4.0.8)
java (0.7.2)
js (2.3.5)
screenshot (0.0.1)

```

**Comment by Debashis9012** [comment]
This should not happen.
I have tested the same in win10 os. when i do `goto("file:///"+fullPath);`
where fullPath value is `fullPath= "c:\temp.html";`
I am getting file not found error which is excepted as its ignoring `t` from `temp.html` file for `\` character.
Kindly find below console log:
```
 Error Message: Error: Navigation to url file:///C:	emp.html failed.
         REASON: net::ERR_FILE_NOT_FOUND
```

gauge version:
```
Gauge version: 1.0.4
Commit Hash: 3a9a647

Plugins
-------
js (2.3.5)
```
could you please provide more information which will be helpful to replicate the same issue.

**Comment by Apoorva-GA** [comment]
@z04jmath Any update on this?

**Comment by nehashri** [comment]
@z04jmath Please reopen this issue with more details if you are still facing the problem.
