### ISSUE TITLE
dynamic dropDowns do not select in headless mode

### ISSUE THREAD

**Issue by tristanjclarke** [getgauge/taiko#734]
### Expected behaviour
Should be able to select an option from a dropDown which depends on a dropDown.
e.g. 
dropDown 1 - Option 1 selected 
dropDown 2 - Option 1.1 displays

dropDown 1 - Option 2 selected
dropDown 2 - Option 2.1 displays

### Actual behaviour
When I run the below code I get the reported error that the option can not be found. 

step("Select a team", async() => {
    await dropDown({name:'teamType'}).select('Publisher')
    await dropDown({name:'teamID'}).select('Publisher 1')
});

Error: Option not available in drop down

### Steps to reproduce
You can use the link and the code above to reproduce this issue. 
https://css-tricks.com/examples/DynamicDropdown/

### Versions
node v10.16.0
taiko Version: 1.0.0 (Chromium: 76.0.3803.0) RELEASE

**Comment by negiDharmendra** [comment]
@tristanjclarke Looks like it's not an issue with **Taiko's** `dropDown`.

My suggestion would be to pass the [`waitForStart`](https://taiko.gauge.org/#parameters-13) option to the `goto` api;
**Example:**
```
await goto('https://css-tricks.com/examples/DynamicDropdown/', {waitForStart:2000});
await dropDown({id:'text-one'}).select('Snacks');
await dropDown({id:'text-two'}).select('Chips');
```

**Comment by tristanjclarke** [comment]
How might this work when my dropDown is on a different page to the homepage? Currently when trying the below I get the same error as before. 

Flow
Fill in login details on login page. 
Click login on login page. 
    Taken to Profile page with Change Team modal
Fill in dynamic dropDown on profile page. 
Click save on profile page. 

Login Page:
step("Goto Login page", async () => {
    await goto("http://35.197.195.34/login", {waitForStart:2000})
});

step("Type in 'Email with: <emailAddress>", async (emailAddress) => {
    await write(emailAddress, into(textBox({name:'email'})))
});

step("Type in 'Password' with: <password>", async (password) => {
    await write(password, into(textBox({name:'password'})))
});

// Expects to be taken to Profile page.
step("Click on 'Login' button", async() => {
    await click(button('Login'))
});

Choose Team Page:
step("Fill in 'Change Team' modal with: <team>, <teamName>", async(team, teamName) => {
    await waitFor(1000)
    await dropDown({name:'teamType'}).select(team);
    await dropDown({name:'teamID'}).select(teamName);
});

**Comment by negiDharmendra** [comment]
@tristanjclarke Here is a list of API which supports `waitForStart` option.
`openTab, goto, reload, goBack, goForward, click, write, clear, press, mouseAction and evaluate`

So you can pass `waitForStart` to the API call which takes you to the dropdown page.

**Comment by tristanjclarke** [comment]
@negiDharmendra I have tried the `waitForStart` option with the `click` API which unfortunately did not work. 

The below code should open up a modal, and fill in the dynamic dropdown options. Unfortunately, when I run it I get the same error, "Option not available in drop down".

```
step("Click on 'Change Team' button", async() => {
    await waitFor(1000)
    await click('Change team', {waitForStart:5000})
});

step("TEST - Fill in 'Change Team' modal with: <team>, <teamName>", async(team, teamName) => {
    await waitFor(1000)
    await dropDown({name:'teamType'}).select(team);
    await dropDown({name:'teamID'}).select(teamName);
});
```

```
## Change Team Scenaio
* Click on 'Change Team' button
* TEST - Fill in 'Change Team' modal with: "Publisher", "Dev Publisher"
```

**Comment by tristanjclarke** [comment]
Hi @negiDharmendra is there any update on this issue?

**Comment by Apoorva-GA** [comment]
@tristanjclarke One more option is to wait for navigation to complete before you proceed with any other action on the dropdown page, so that the page is fully loaded.

So you can use the `navigationTimeout` option which is defaulted to `30 seconds`. Try and increase the value and then try to select a value from the dropdown. 

More details about `waitForNavigation ` [here](https://taiko.gauge.org/?#click).

**Comment by nehashri** [comment]
@tristanjclarke Are you still facing issues?

**Comment by negiDharmendra** [comment]
@tristanjclarke Please feel free to reopen this issue again if you face this issue again.

**Comment by nehashri** [comment]
This is reproducible if we have multiple dropdowns that are dependent on change events. If the change event is registered on the parent element of a dropdown it doesn't work. 
Eg html to reproduce the issue:
```
<div id="one">
  <label for="select-one">One</label>
  <select id="select-one" name="select" value="select">
     <option>Select One</option> 
     <option>Hot Beverages</option>
    </select>
</div>
<div id="two">
  <label for="select-two">Two</label>
  <select id="select-two" name="select" value="select">
     <option>Please select from above</option>
    </select>
</div>
<script>
  var textTwo = document.getElementById("select-two");
var divOne = document.getElementById("one");

divOne.addEventListener("change", function() {
  console.log("Hello");
  textTwo.innerHTML = "<option>Tea</option><option>Cofee</option>";
});
</script>
```

**Comment by Debashis9012** [comment]
This issue has been tested and verified. Multiple dropdown with change events works as excepted by using `dropdown` api.
Tested version: `f2208373c36bfea0b8e254b417486b9818993e6e`

**Comment by sandeepbantode** [comment]
When this fix will get release ?

I have similar issue with dropDown change event doesn't get fire 

Taiko Version: 1.0.2 (Chromium:76.0.3803.0)
