### ISSUE TITLE
Should be able to select contenteditable field with no explicit type with TextBox API

### ISSUE THREAD

**Issue by Debashis9012** [getgauge/taiko#738]
### Expected behavior
Should be able to select contenteditable field using `textBox` selector.

### Actual behavior
by using `textBox` selector contenteditable field was not found.
```
write("Hello", into(textBox("This is a paragraph is editable. Try to change this text.")))
 ✘ Error: Text field with label This is a paragraph is editable. Try to change this text.  not found, run `.trace` for more info.
```

### Steps to reproduce
Kindly follow the below html snippet:
```
<div>Editable Demo</div>
<p contenteditable="true">This is a paragraph is editable. Try to change this text.</p>
```
Follow the below steps in repl:
openBrowser()
goto("file:///Users/dadebash/taikoProject/HTMLElements.html")
write("Hello", into(textBox("This is a paragraph is editable. Try to change this text.")))
### Versions
```
Tested version:
Version: 1.0.1 (Chromium: 76.0.3803.0) bc62489640c9ba6f83e3d9ebf17aa754043f5682
```

**Comment by karuppiah7890** [comment]
@Debashis9012 in the above example there are no labels, so I think the example has to be updated. I tried the write with textBox with id option for the para and it worked
