### ISSUE TITLE
If an element is not found, REPL should not exit

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#74]
**Expected behavior**
If an element is not found, REPL should not exit

**Actual behavior**
The REPL exits

**Steps to replicate**
* Open the taiko REPL and record the following steps
```
        openBrowser();
        goto("amazon.in");
        click(image(below("Today's Deals")));
        click(radioButton(toLeftOf("With Exchange")))
```
> with the last step, the REPL exits

**Version**
```
e72d723ce592aa92ffef44c9d371ea01dbf1acca
Tue Jul 24 11:37:30 2018 +0530
```

**Comment by NivedhaSenthil** [comment]
Fix done on 024edb8
