### ISSUE TITLE
unable to hide text in textBox field

### ISSUE THREAD

**Issue by Debashis9012** [getgauge/taiko#740]
### Expected behavior
user should have the privilege to hide text while using with write API

### Actual behavior
unable to hide text in textBox field.
`✔ Wrote Debashis into the text field To right of Enter your name:`

### Steps to reproduce
1. openBrowser()
2. goto("https://www.w3schools.com/html/tryit.asp?filename=tryhtml_elem_input")
3. write("Debashis",into(textBox(toRightOf("Enter your name:"))),{hidetext:true})

[Reference](https://github.com/getgauge/taiko/pull/709)

### Versions
```
Tested version:
Version: 1.0.1 (Chromium: 76.0.3803.0) bc62489640c9ba6f83e3d9ebf17aa754043f5682
```

**Comment by karuppiah7890** [comment]
This issue has already been fixed according to https://github.com/getgauge/taiko/pull/743#issuecomment-523318473 in https://github.com/getgauge/taiko/commit/93c82f16f008c7a24f1060c9eb4a00e3a7cb97a8

**Comment by Debashis9012** [comment]
This issues has been verified and found fixed. 
Tested version: ``` 93c82f16f008c7a24f1060c9eb4a00e3a7cb97a8```
