### ISSUE TITLE
How to set 'AutoSelectCertificateForUrls' 

### ISSUE THREAD

**Issue by lingcarlos** [getgauge/taiko#749]
### Expected behavior
How to set https client certificate

### Actual behavior

I hope can set 'AutoSelectCertificateForUrls' 

exp:
```js
beforeSuite(async () => {
    await openBrowser({
        autoSelectCertificateForUrls: ["{\"pattern\":\"*\",\"filter\":{\"ISSUER\":{\"CN\":\"<Your issuer CN>\"}}}"],
        headless: headless
    });
});
```

**Comment by lingcarlos** [comment]
![image](https://user-images.githubusercontent.com/516161/63003073-fd4dde00-bea9-11e9-91f3-68f8b8b5fc45.png)

**Comment by negiDharmendra** [comment]
@lingcarlos There is no such option as of now. Please refer to this [example](https://github.com/getgauge-examples/client-certs-authentication-with-taiko) for a workaround.

**Comment by nehashri** [comment]
@lingcarlos Did the example help? Are you still facing issues?

**Comment by lingcarlos** [comment]
> @lingcarlos Did the example help? Are you still facing issues?

I use another method to solve the problem I encountered.
defaults write org.chromium.Chromium AutoSelectCertificateForUrls -array
defaults write org.chromium.Chromium AutoSelectCertificateForUrls -array-add -string '{
    "pattern": "*",
    "filter": {
        "ISSUER": {
            "CN": "xx"
        },
        "SUBJECT": {
            "CN": "xx"
        }
    }
}'
