### ISSUE TITLE
text is not iterable

### ISSUE THREAD

**Issue by saikrishna321** [getgauge/taiko#751]
### Expected behavior
When a non-string value is set to write API, taiko should fail with a friendly message

### Actual behavior

`
Error: text is not iterable, run `.trace` for more info.
`

### Steps to reproduce
write(12345)
write(null)
write(process.env.USER) // undefined

**Comment by sriv** [comment]
`write(12345)` seems to be legit. IMO taiko should attempt a `toString` for objects that have implemented toString and for primitives.

null values should be either a warning or could be treated as semantic equivalent of `clear`. Thoughts?

**Comment by zabil** [comment]
I agree to graceful handling. 
Do a null check, raise a warning and `clear` while convert to string for the rest.

**Comment by saikrishna321** [comment]
@sriv  @zabil 

Thanks for looking at the PR and feedbacks.


> write(12345) seems to be legit. IMO taiko should attempt a toString for objects

Sounds good!! I can make changes.

When the value is null or undefined why should we raise a warning and clear? Why not, throwback Error to the users?

**Comment by zabil** [comment]
> When the value is null or undefined why should we raise a warning and clear? Why not, throwback Error to the users?

An error means failing the test right? This will force the user to set do a null check if they want to handle it differently. If we handle the null with the warning they could choose to pass it or not. 

For example, if field is not mandatory. It's better for the actual application to report an error if that behaviour is wrong.

**Comment by saikrishna321** [comment]
https://github.com/getgauge/taiko/pull/764

**Comment by Apoorva-GA** [comment]
Fix available in commit afdffed50e9836a80407d249aef032ce7bf53a61.

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed.
Tested version: `9d90e1dde5db09db26721c6ce07828e34cb09e5f`
