### ISSUE TITLE
Taiko function to get value of a greyed out text field

### ISSUE THREAD

**Issue by adea11** [getgauge/taiko#771]
### Expected behavior
should be able to get value() of a greyedout text field using a function

### Actual behavior
textBox function does not work as field is not editable

### Steps to reproduce
1. const greyed_field_content = await textBox({id: 'field.content'}).value()
2. await greyed_field_content.value
3.

### Versions
Gauge version: 1.0.5
flash (0.0.1)
html-report (4.0.8)
js (2.3.5)
json-report (0.3.1)
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.1)

node v10.16.0
 taiko: "0.8.0"
```

**Comment by Apoorva-GA** [comment]
@adea11 In your case `greyed_field_content` is already the value of the textBox. So you don't have to do `greyed_field_content.value` in the next step.

**Comment by adea11** [comment]
Hi @Apoorva-GA , thanks for your reply but the main issue here is that seem to find any selector for fields like this one 
**<input style="; ; " class="form-control disabled " id="readonly.field.content" value="abcde" ng-non-bindable="" readonly="readonly">**

So even if I do :const greyed_field_content = await textBox({id: 'field.content'}).value()
console.log (field_content)

The output is "Text field not found"

**Comment by negiDharmendra** [comment]
@adea11 That's expected as the attribute value passed to `textBox` is not correct.

Please change `await textBox({id: 'readonly.field.content'}).value()` to `await textBox({id: 'readonly.field.content}).value()`

**Comment by adea11** [comment]
> @adea11 That's expected as the attribute value passed to `textBox` is not correct.
> 
> Please change `await textBox({id: 'readonly.field.content'}).value()` to `await textBox({id: 'readonly.field.content}).value()`

Hi @negiDharmendra the former and latter synax you sent are the same though

**Comment by negiDharmendra** [comment]
@adea11 Updated

**Comment by negiDharmendra** [comment]
@adea11 I tried with a sample `html` file
```
<!DOCTYPE html>
<html>
   
<body>
    <input class="form-control disabled " id="readonly.field.content" value="abcde" ng-non-bindable="" readonly="readonly"/>
</body>




</html>
```
and the below Taiko script.

```
const { openBrowser, goto, textBox, closeBrowser } = require('taiko');
(async () => {
    try {
        await openBrowser();
        await goto('file://<path-to-sample-html-file>');
        let value = await textBox({id:'readonly.field.content'}).value();
        console.log(value)
    } catch (error) {
        console.error(error);
    } finally {
        await closeBrowser();
    }
})();
```

It works fine for me.

**Comment by adea11** [comment]
Hi @negiDharmendra  I think the problem is that the Taiko functions  do not cater for: <input style="; ; "   which is  missing in your test.  Is there any other Taiko function (apart from textBox) I can apply here please?, as input type is NOT text. See the full html syntax below. 


<input style="; ; " " class="form-control disabled " id="readonly.field.content" value="abcde" ng-non-bindable="" readonly="readonly"/>



So even if I do :
const field_content = await textBox({id: 'readonly.field.content'}).value( )
console.log (field_content)

The output is "Text field not found"

**Comment by zabil** [comment]
> <input style="; ; " " class="form-control disabled " id="readonly.field.content" value="abcde" ng-non-bindable="" readonly="readonly"/>

This looks like an incomplete use of the input tag as the "type" attribute is missing. You should try adding a `type=text` for this field. The `style` attribute is only for styling

**Comment by adea11** [comment]
> > <input style="; ; " " class="form-control disabled " id="readonly.field.content" value="abcde" ng-non-bindable="" readonly="readonly"/>
> 
> This looks like an incomplete use of the input tag as the "type" attribute is missing. You should try adding a `type=text` for this field. The `style` attribute is only for styling

Thanks @zabil  what if type="HIDDEN", is there any applicable function please?

**Comment by nehashri** [comment]
ref: https://github.com/getgauge/taiko/issues/803

**Comment by nehashri** [comment]
@adea11 Are you facing anymore issue regarding this?

**Comment by adea11** [comment]
Hi @nehashri  I'm closing this as it's simply a duplicate of https://github.com/getgauge/taiko/issues/803
