### ISSUE TITLE
Text api to take a function as an option 

### ISSUE THREAD

**Issue by Apoorva-GA** [getgauge/taiko#773]
Text api to take a function as an option where user can decide what is the matching strategy they want to use.

**Comment by saikrishna321** [comment]
@Apoorva-GA would the default by exact match?

**Comment by nehashri** [comment]
@saikrishna321 I think the default would be contains, to support backward compatibility.

**Comment by zabil** [comment]
Closing this issue for a simple suggestion refer https://github.com/getgauge/taiko/issues/766#issuecomment-561595918
