### ISSUE TITLE
Remove use of external links in Taiko FTs

### ISSUE THREAD

**Issue by nehashri** [getgauge/taiko#776]
Taiko FTs may fail because of dependencies on external links. 
These links should be removed and should be replaced with static html files or it should use the internet app hosted locally.

**Comment by shubhamsc** [comment]
We are using Taiko API directly from the source to run Taiko FTs. Use Taiko as a dependency to run FTs instead of using from source.

**Comment by nehashri** [comment]
Some tests are still navigating to external urls.

**Comment by Apoorva-GA** [comment]
Fixing in commit c7e4b5f0e644499b7a7db52c04c4afd04498e760.
