### ISSUE TITLE
Set optimum content width and text alignment for documentation

### ISSUE THREAD

**Issue by zabil** [getgauge/taiko#777]
The current width is not readable as the paragraph extends beyond the optimum width of 40-50em

![Screenshot 2019-08-28 at 13 53 52](https://user-images.githubusercontent.com/54427/63858008-a3b2dc80-c99c-11e9-9b0a-0ba0b8da953e.png)

Fix this to be between 40-50em for example

![Screenshot 2019-08-28 at 13 55 47](https://user-images.githubusercontent.com/54427/63858038-b5947f80-c99c-11e9-8208-fbe4a8c7f777.png)

Also justify the text

**Comment by Pratyush1197** [comment]
I want to work on it!!

**Comment by ankurjain00** [comment]
@nehashri Working on this issue

**Comment by zabil** [comment]
Oops sorry, this is fixed currently on https://docs.gauge.org
