### ISSUE TITLE
Screenshot is not taken from browser window on step failure in headless mode

### ISSUE THREAD

**Issue by JaniJegoroff** [getgauge/taiko#779]
'step failure' screenshots are not taken from browser window when running tests in headless mode. Screenshots are taken from desktop instead.

### Expected behavior
When running tests in headless mode and in case of step failure the screenshot should be taken from browser

### Actual behavior
Screenshot is taken from desktop (not from browser)

### Steps to reproduce
1. Setup example taiko project: `gauge init js`
2. Modify `step_implementation.js` as follows:
```
beforeSuite(async () => {
    await openBrowser({ headless: true })
});
```
```
step("Page contains <content>", async (content) => {
    assert.ok(await text('FOO').exists());
});
```
3. Run test: `gauge run specs/example.spec`
4. Open report and check the screenshot

<img width="972" alt="Screenshot 2019-08-29 at 11 17 30" src="https://user-images.githubusercontent.com/2363231/63932244-b84fad00-ca4e-11e9-9eb9-0e921d527b2b.png">

### Console
```
mac:~ xxx$ mkdir taiko-test
mac:~ xxx$ cd taiko-test/
mac:taiko-test xxx$ gauge init js
Downloading js.zip
.
Copying Gauge template js to current directory ...

> taiko@1.0.0 install /Users/xxx/taiko-test/node_modules/taiko
> node lib/install.js

Downloading Chromium r662092 - 88.3 Mb [====================] 100% 0.0s
Chromium downloaded to /Users/xxx/taiko-test/node_modules/taiko/.local-chromium/mac-662092
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN gauge-taiko-template@0.0.1 No repository field.
npm WARN gauge-taiko-template@0.0.1 No license field.

added 55 packages from 65 contributors in 14.004s
Successfully initialized the project. Run specifications with "npm test" in project root.

mac:taiko-test xxx$ gauge run specs/example.spec
(node:62199) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
# Getting Started with Gauge
  ## Search Taiko Repository	 ✔DEPRECATION WARNING: inputField is deprecated, use textBox api instead
 ✔ ✘
        Failed Step: Page contains "getgauge/taiko"
        Specification: specs/example.spec:11
        Error Message: AssertionError [ERR_ASSERTION]: false == true
        Stacktrace:
        AssertionError [ERR_ASSERTION]: false == true

Successfully generated html-report to => /Users/xxx/taiko-test/reports/html-report/index.html
Specifications:	1 executed	0 passed	1 failed	0 skipped
Scenarios:	1 executed	0 passed	1 failed	0 skipped

Total time taken: 15.031s
Updates are available. Run `gauge update -c` for more info.
mac:taiko-test xxx$
```

### Environment
macOS 10.14.4 
taiko js Version: 1.0.0 (Chromium: 76.0.3803.0) RELEASE
node v12.6.0

**Comment by zabil** [comment]
@JaniJegoroff the default screenshot tool takes a picture of the desktop. For a screenshot of the browser you can [override](https://docs.gauge.org/writing-specifications.html#taking-custom-screenshots) the default screenshot functionality.

In Gauge and Taiko add this bit of code in any of the step implementation files.

```
// Return a screenshot byte array
gauge.screenshotFn = async function() {
    return await screenshot({ encoding: 'base64' });
};
```

**Comment by JaniJegoroff** [comment]
@zabil Ah, I see. That seems to be working fine. Thank you for your help 👍
