### ISSUE TITLE
Should be able to run scripts with Opera

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#783]
### Expected behavior
Should be able to run the taiko scripts on the Opera browser

### Actual behavior
Couple of Taiko FTs fail when run with the Opera browser, however they pass on Chrome. 

### Notes
Opera is based on Blink and Chromium so technically Taiko should work with Opera.

### Steps to reproduce
* Set TAIKO_SKIP_CHROMIUM_DOWNLOAD=true
and set the browser path to Opera
Run Taiko FTs using the Opera

### Versions
```
Opera - 63
commit - ae469d33798aec00b004bb7f2d5cd15d4516945e
```

**Comment by zabil** [comment]
I think this was an issue with opera versions.
