### ISSUE TITLE
Expose isDisabled api for selectors

### ISSUE THREAD

**Issue by luciferankon** [getgauge/taiko#784]
List of selectors should be changed:
- [ ] $
- [ ] image
- [ ] link
- [ ] listItem
- [ ] button
- [ ] fileField
- [ ] textBox
- [ ] dropDown
- [ ] checkBox
- [ ] radioButton
- [ ] text

**Comment by luciferankon** [comment]
Parking for now.
#808 needs to be done in order this to be worked on

**Comment by saikrishna321** [comment]
@luciferankon @zabil What you think 👉  https://github.com/saikrishna321/taiko/commit/ee2be4e23a081b78ddd8863e05064a4fa4ace9fc

**Comment by NivedhaSenthil** [comment]
done via #1021
