### ISSUE TITLE
CLI support for plugins: working example and better documentation needed

### ISSUE THREAD

**Issue by andreas-ku** [getgauge/taiko#789]
### Expected behavior
The documentation should give clear instructions and provide a working example of how to add CLI support when developing a plugin: https://github.com/getgauge/taiko/wiki/Taiko-Plugin.

### Actual behavior
All examples that are currently documented will result in an error message. The instructions in https://github.com/getgauge/taiko/wiki/Taiko-Plugin#conventions are not clear enough and don't show how the exec method can be implemented.

### Steps to reproduce

With the instructions given, I could not make it work and I noticed the CLI support of https://github.com/saikrishna321/taiko-diagnostics/#use-in-taiko-repl seems to be broken:

```taiko --plugin taiko-diagnostics

Version: 1.0.0 (Chromium:76.0.3803.0)
Type .api for help and .exit to quit

> openBrowser()
 ✔ Browser opened
> startTracing()
Thrown:
ReferenceError: startTracing is not defined
    at repl:2:2
    at repl:3:3
    at Script.runInContext (vm.js:133:20)
    at Object.defaultEval (repl.js:334:29)
    at bound (domain.js:402:14)
    at Object.runBound (domain.js:415:12)
> .startTracing()
Invalid REPL keyword```

If I follow the instructions in https://github.com/getgauge/taiko/wiki/Taiko-Plugin#execution-capability-in-plugin I get: 

```taiko diagnostics http://gauge.org
Invalid file extension. Only javascript files are accepted.```

### Versions
```
Paste `node` and `taiko` versions here.
taiko 1.0.0
node v10.16.3
```

**Comment by ankurjain00** [comment]
I would like to work on this issue

**Comment by zabil** [comment]
@ankurjain00 done. Please reach out here if you need any help with the docs.

**Comment by ankurjain00** [comment]
@zabil PR raised

**Comment by ankurjain00** [comment]
@zabil PR raised to add exec method implementation
