### ISSUE TITLE
Custom screenshots are not attached to html report

### ISSUE THREAD

**Issue by JaniJegoroff** [getgauge/taiko#790]
I'm unable to get custom screenshots attached to `html` report in case of step failure. This happens with the latest code from `master` branch.

I have tracked down breaking change to a commit https://github.com/getgauge/taiko/commit/7b4db1995facc68d8a93cd62fa5ed6e29e37a171
Commits before that seems to be working fine.

### Expected behavior
When running tests in headless mode and in case of step failure the custom screenshot should be attached to html report.

### Actual behavior
Custom screenshot is not attached to html report.

### Steps to reproduce
1. Setup example taiko project: `gauge init js`
2. Modify `step_implementation.js` as follows:
```
const { screenshot, openBrowser,write, closeBrowser, goto, press, text, focus, inputField, toRightOf } = require('taiko');
```
```
beforeSuite(async () => {
    await openBrowser({ headless: true })
});
```
```
gauge.screenshotFn = async function() {
    return await screenshot({ encoding: 'base64' });
};
```
```
step("Page contains <content>", async (content) => {
    assert.ok(await text('FOO').exists());
});
```
3. Run test: `gauge run specs/example.spec`
4. Open html report and you should see custom screenshot attached
<img width="990" alt="taiko-screenshot-ok" src="https://user-images.githubusercontent.com/2363231/64162263-e5c59d80-ce36-11e9-9245-f940903185b3.png">

5. Edit `package.json` as follows
```
"dependencies": {
    "taiko": "git+https://git@github.com/getgauge/taiko.git#7b4db1995facc68d8a93cd62fa5ed6e29e37a171"
}
```
6. Execute `rm -rf node_modules reports logs package-lock.json`
7. Execute `npm install`
8. Run test: `gauge run specs/example.spec`
9. Open html report and check custom screenshot
<img width="990" alt="taiko-screenshot-nok" src="https://user-images.githubusercontent.com/2363231/64162385-173e6900-ce37-11e9-8545-6275feeedd9b.png">

### Versions
```
macOS 10.14.6
taiko js Version: 1.0.0 (Chromium: 76.0.3803.0) RELEASE
node v12.6.0
```

**Comment by negiDharmendra** [comment]
@JaniJegoroff  Thank you very much for reporting this issue. We will be looking into it as soon as possible.

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed.
Tested version: `5ca0f5b226fa3b0de7a6681a1232aa35e9e29d0c`
