### ISSUE TITLE
[FAIL] Error: Chromium revision is not downloaded. Provide TAIKO BROWSER PATH or Install taiko again to download bundled chromium., run `.trace` for more info.

### ISSUE THREAD

**Issue by manavghaigithub** [getgauge/taiko#796]
I am getting this error when installing taiko from npm. How do i get chromium version? I tried installing taiko multiple times but i always get this message.

[FAIL] Error: Chromium revision is not downloaded. Provide TAIKO BROWSER PATH or Install taiko again to download bundled chromium., run `.trace` for more info.

**Comment by negiDharmendra** [comment]
@manavghaigithub Few things to consider.


Make sure your machine has access to the Internet.
Make sure that `https://storage.googleapis.com` is whitelisted if you are behind a firewall.

**Comment by negiDharmendra** [comment]
@manavghaigithub Forgot to mention a few details.

Taiko tries to download `Chromium` when we install it. That is why Taiko needs to have access to the internet.
If you don't want Taiko to download `Chromium`, you can download chromium your self and configure the **TAIKO_BROWSER_PATH** env variable.

**Comment by manavghaigithub** [comment]
Hi Dharmendra - Where do I need to configure
TAIKO_BROWSER_PATH In env variable?


Thanks,
Manav
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by negiDharmendra** [comment]
@manavghaigithub Yes in environment variable.

**Comment by nehashri** [comment]
@manavghaigithub Any updates on this issue?

**Comment by negiDharmendra** [comment]
@manavghaigithub Please feel free to reopen this issue again if you face the issue.

**Comment by shaifaliyadav** [comment]
I am getting this error while running tests locally in my system

Error: Chromium revision is not downloaded. Provide TAIKO BROWSER PATH or Install taiko again to download bundled chromium

**Comment by davidtmasin** [comment]
Hi, everyone!
I'm getting this error too.

Error: Chromium revision is not downloaded. Provide TAIKO_BROWSER_PATH or Install taiko again to download bundled chromium.
    at BrowserFetcher.getExecutablePath (D:\www\node_modules\taiko\lib\browserFetcher.js:237:13)
    at launchBrowser (D:\www\node_modules\taiko\lib\browserLauncher.js:327:44)
    at module.exports.openBrowser (D:\www\node_modules\taiko\lib\taiko.js:99:65)
    at module.exports.<computed> (D:\www\node_modules\taiko\lib\taiko.js:2626:36)
    at global.<computed> (D:\www\node_modules\taiko\bin\runFile.js:38:37)
    at D:\www\TestesAutomatizados\taiko\ToDoReactAPP\createatask.js:7:11
    at Object.<anonymous> (D:\www\TestesAutomatizados\taiko\ToDoReactAPP\createatask.js:15:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
WARNING: Browser or page not initialized. Call `openBrowser()` before using this API
