### ISSUE TITLE
Goto must handle locations with and without the protocol

### ISSUE THREAD

**Issue by zabil** [getgauge/Taiko#8]
Current behavior

```
$ taiko
> goto("getgauge.io")
 ✘ Error: Protocol error (Page.navigate): Cannot navigate to invalid URL undefined, run `.trace` for more info.
```

Expected

```
> goto("getgauge.io")
 ✔ Navigated to url "https://getgauge.io/"
```

**Comment by kashishm** [comment]
Implemented.

**Comment by kashishm** [comment]
![optimized](https://user-images.githubusercontent.com/5915802/32775920-e4778394-c956-11e7-9afc-63580f987cf4.gif)

**Comment by sriv** [comment]
the image above could possibly be on the README, gives a decent overview of `taiko`

**Comment by kashishm** [comment]
![optimized_repl](https://user-images.githubusercontent.com/5915802/32829214-6a4472dc-ca17-11e7-86dd-4944b8545164.gif)

**Comment by zabil** [comment]
Yes. This works. It gives a good overview.
