### ISSUE TITLE
.api command is not working

### ISSUE THREAD

**Issue by luciferankon** [getgauge/taiko#800]
### Expected behavior
Should list the apis

### Actual behavior
It's showing error `API usage not available.`

### Steps to reproduce
1. Install the latest taiko
2. launch repl
3. run `.api`

### Versions
taiko -v
`Version: 1.0.1 (Chromium: 76.0.3803.0) RELEASE`

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed.
Tested version: `ef43f50bfcd74ac6512454789151a726adc2b8b7`
