### ISSUE TITLE
It unsupport 12.x version for node? 

### ISSUE THREAD

**Issue by ariesZhou** [getgauge/taiko#801]

**Comment by ariesZhou** [comment]
![image](https://user-images.githubusercontent.com/46946479/64588528-3871fd00-d3d5-11e9-9cb6-8eb0767126e9.png)

**Comment by nehashri** [comment]
@ariesZhou Can you try installing taiko without using the sudo command?

**Comment by ariesZhou** [comment]
It will prompt that there is no permission.
I was already install success by this :
`sudo env TAIKO_SKIP... true npm install -g taiko`
 ,but I don't know set the blowserpath in which config.

**Comment by BugDiver** [comment]
@ariesZhou When you are using installing taiko globally with `sudo`, you have to pass `--unsafe-perm` to npm.
Can you please try running `sudo npm install-test -g taiko --unsafe-perm` and see if it helps?

**Comment by ariesZhou** [comment]
> @ariesZhou When you are using installing taiko globally with `sudo`, you have to pass `--unsafe-perm` to npm.
> Can you please try running `sudo npm install-test -g taiko --unsafe-perm` and see if it helps?

superb~! it ok , tks.
