### ISSUE TITLE
Taiko cannot find Hidden html class

### ISSUE THREAD

**Issue by adea11** [getgauge/taiko#803]
### Expected behavior
Taiko should find hidden html as webdriver does

### Actual behavior
Taiko output: Element not found 

### Steps to reproduce
1.  search for page element of an hidden field
2.
3.

### Gauge version
Gauge version: 1.0.6

Plugins
-------
flash (0.0.1)
html-report (4.0.8)
js (2.3.5)
json-report (0.3.1)
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.1)

```
"taiko": "^0.8.0"

**Comment by nehashri** [comment]
@adea11 The `$` selector returns a [ElementWrapper](https://taiko-preview.gauge.org/#elementwrapper) object. The `.value` function is only supported for combobox elements. You may want to try using 
`const hidden_field = $("//*[@id="hidden.field.number"]").get()` instead. It returns an array of elements.

**Comment by adea11** [comment]
> const hidden_field = $("//*[@id="hidden.field.number"]").get()

@nehashri , .get() return an empty list.

const hidden_field = $("//*[@id="hidden.field.number"]").get()
console.log(hidden_field)
........................................
Output: [ ]

**Comment by nehashri** [comment]
@adea11 This seems to be an issue. There isn't any way to select a hidden element in Taiko currently. We will try to fix this as soon as possible.

**Comment by nehashri** [comment]
Should be handled via https://github.com/getgauge/taiko/issues/811
