### ISSUE TITLE
Provide a option to omit descriptions in repl

### ISSUE THREAD

**Issue by BugDiver** [getgauge/taiko#806]
### Expected behavior
There has to be a way to omit the descriptions in taiko APIs

### Actual behavior 
Currently, the user can not omit the descriptions given from the APIs

### Use Case
In REPL mode all the taiko APIs prints a description about the action they performed. The plugins can also contribute to this feature by using the description event emitter which is passed to the plugins.
But when the plugin is using any of the taiko APIs within its own  APIs, The description of the taiko APIs also gets printed and that is kind of misleading.

Example: let's assume there is plugin logger which has a `printToConsole` API and usage `evaluate` API from taiko.

```javascript
export function printToConsole(message) {
    let options = { args: [message] };
    await taiko.evaluate((element, args) => {
        console.log(args);
    });
    descEvent.emit('success', 'Printed' + message + 'to the browser console.')
}
```

Now when this API gets called the message printed is

```console
> logger.printToConsole("Hello World")
✔ Evaluated given script. Result:undefined
✔ Printed 'Hello world' to the browser console
```
Which is wrong. Instead, it should be just
```console
> logger.printToConsole("Hello World")
✔ Printed 'Hello world' to the browser console
```

### Proposal

Add an `omitDescription` option to the APIs which tell APIs to not print the description.

```javascript
export function printToConsole(message) {
    let options = { omitDescription: true, args: [message] };
    await taiko.evaluate((element, args) => {
        console.log(args);
    }, options);
    descEvent.emit('success', 'Printed' + message + 'to the browser console.')
}
```

**Comment by MakodeAjay** [comment]
Hi @zabil, I want to contribute to this issue. Could you assign this to me?

**Comment by zabil** [comment]
@MakodeAjay Done! Please feel free to reach out here if you need any help.

**Comment by MakodeAjay** [comment]
@zabil PR raised
