### ISSUE TITLE
Expose elementList instead of returning the elementWrapper from the selectors

### ISSUE THREAD

**Issue by luciferankon** [getgauge/taiko#808]
For more information refer [here](https://github.com/getgauge/taiko/wiki/0001-expose-element-list)
Selectors need to be modified
- [x] button
- [x] image
- [x] link
- [x] listitem
- [x] fileField
- [x] textBox
- [x] dropDown
- [x] checkBox
- [x] radioButton
- [x] text
- [x] $

**Comment by Debashis9012** [comment]
This enhancement has been tested.
Tested version: `ff140a8a5a76be5be2b7d1a82f04bdab27ac91d0`
