### ISSUE TITLE
Expose isVisible api for selectors

### ISSUE THREAD

**Issue by nehashri** [getgauge/taiko#809]
List of selectors to support isVisible:
- [ ] $
- [ ] image
- [ ] link
- [ ] listItem
- [ ] button
- [ ] fileField
- [ ] textBox
- [ ] dropDown
- [ ] checkBox
- [ ] radioButton
- [ ] text

**Comment by o-x-y-g-e-n** [comment]
I would like to take the opportunity to work on this.

**Comment by saikrishna321** [comment]
API 👇 Done

- [x] image
- [x] link
