### ISSUE TITLE
Expose isClickable API for selectors

### ISSUE THREAD

**Issue by nehashri** [getgauge/taiko#810]
List of selectors to support isClickable:
- [ ] $
- [ ] image
- [ ] link
- [ ] listItem
- [ ] button
- [ ] fileField
- [ ] textBox
- [ ] dropDown
- [ ] checkBox
- [ ] radioButton
- [ ] text

**Comment by zabil** [comment]
Refer https://github.com/getgauge/taiko/issues/995
