### ISSUE TITLE
How is taiko different from puppeteer?

### ISSUE THREAD

**Issue by anilbhanushali** [getgauge/taiko#813]
Tried finding the article of the website but couldn't find one. However, I know that it is inspired by Puppeteer but there is no details available as on how it is different from Puppeteer ?

**Comment by bboydflo** [comment]
> That said you can read this [article](https://gauge.org/2019/08/21/how-taiko-compares-to-other-browser-automation-tools/) which compares other tools along with Taiko.

I am interested in the exact same question. I already read the artcile linked above and I am more interested in how these tools are different from a technical point of view. The article describes more of a feature comparison. I actually think it would be nice to have a small section in the docs pointing to the article and describing how it compares technically to other tools.

**Comment by zabil** [comment]
Like puppeteer Taiko uses Chrome DevTools protocol to interact with the browser.
Technically it's the same. The only difference is that Taiko is a much higher level API 
focused on writing readable tests.

**Comment by PhenX** [comment]
As I understand totally the API level difference, I think it would be good to consider using [Puppeteer](https://github.com/puppeteer/puppeteer), or [Playwright ](https://github.com/microsoft/playwright) as an underlying system inside Taiko. This would open new possibilities : to be able to test Firefox and WebKit in addition to Chromium based browsers would make the difference. 

What do you think ?

**Comment by zabil** [comment]
Taiko was initially built on puppeteer, however it ended using the Chrome Dev Tools protocol more than puppeteer's API to support most of the features. 

There's been good progress on CDP support for Firefox. Support to it should be coming soon.
