### ISSUE TITLE
element.text() should return the text

### ISSUE THREAD

**Issue by luciferankon** [getgauge/taiko#815]
### Expected behavior
It should return the text
`button('Input Button').text()` should return `Input Button`

### Actual behavior
It is returning an empty string for now.

html snippet:
```
<input type="button" value="Input Button" />
```

### Steps to reproduce
1. launch repl
2. goto the file
3. `button('Input Button').text()`

### Versions
```
taiko -v
Version: 1.0.2 (Chromium: 76.0.3803.0) RELEASE
```

**Comment by Apoorva-GA** [comment]
Fix should be available in commit 9b19c19dd976771f1b10bfb58b9596edcd2b95cf

**Comment by Apoorva-GA** [comment]
Reverted the fix for now. This needs more investigation as to which api needs what methods to be exposed.

**Comment by zabil** [comment]
This api is not required.
