### ISSUE TITLE
$ selector unable to select meta tags

### ISSUE THREAD

**Issue by qaryas** [getgauge/taiko#819]
I'm trying to assert if a certain meta tag exists with the "$" selector using XPath.
```
await $(`XPATH-HERE`).exists()
```

I've tried the following values for XPATH-HERE but all return false:
```
//html/head/meta
/html/head/meta
//head/meta
/head/meta
//meta
/meta
//html/head/meta[@content='ROBOTS']
```

### Versions
```
node v8.10.0
taiko 1.0.0
```

**Comment by nehashri** [comment]
This seems to be an issue because taiko tries to filter visible elements by default. https://github.com/getgauge/taiko/issues/811 adds a option to select hidden or invisible dom elements. It should also be able to select meta tags.

**Comment by zabil** [comment]
The workaround for this is to use evaluate for example.
```
const { openBrowser, closeBrowser, goto, $, evaluate } = require('taiko');
(async () => {
    try {
        await openBrowser():
        await goto('gauge.org');
        var metaContent = await evaluate( 
               () => { return document.querySelector("meta").getAttribute("content") });
        //assert on metaContent
    } catch (error) {
        console.error(error);
    } finally {
        await closeBrowser();
    }
})();
```

For now this api will only work on visible elements.
