### ISSUE TITLE
add wildcards to switchTo command

### ISSUE THREAD

**Issue by sarut0bi** [getgauge/taiko#821]
Hi it seem that curently it is impossible to use wildcards in switchTo function.
my use case is the following:
* The title of the page is language dependant ...
* url contains uuid :(

Is there a way to add regex rule like it have been already done for intercept api?

**Comment by zabil** [comment]
While implementing this modify the api to take a regex argument for example

```
switchTo(/http(s?):\/\/(www?).google.(com|co.in|co.uk)/)
```

**Comment by o-x-y-g-e-n** [comment]
@zabil, @Apoorva-GA  would this syntax work? If starts with r'(.....) consider the inner text as regex.
`switchTo('r(http(s?):\/\/(www?).google.(com|co.in|co.uk))')`

**Comment by o-x-y-g-e-n** [comment]
I would like to take this opportunity to implement this.

**Comment by sriv** [comment]
@o-x-y-g-e-n - please go ahead and work on this. You may use this issue for any discussions.

**Comment by zabil** [comment]
`switchTo` now supports regex
