### ISSUE TITLE
click is not defined

### ISSUE THREAD

**Issue by WilkieIT** [getgauge/taiko#825]
### Expected behavior
Open Browser
Go To Webpage
Enter the value 1234 into text box 
Click Button
Clear Form postback

### Actual behavior
Open Browser
Go To Webpage
Enter the value 1234 into text box 
Click Button
Error Returned
        **Failed Step: Enter Public Key "1234"
        Specification: ...\WebPageGenericTests.spec:6
        Error Message: {}
        Stacktrace: 
        ReferenceError: click is not defined**

Same result from cmd and VSCode

### Steps to reproduce
1.GoTo https://static.demo.ezidebit.com.au/EnterPublickey.aspx
2.Enter 1234 into public key field
3. Click Continue

### Versions
Gauge version: 1.0.4

node
v10.16.3

taiko
Version: 1.0.0 (Chromium: 76.0.3803.0) RELEASE
[WebPageGenericTests.zip](https://github.com/getgauge/taiko/files/3633857/WebPageGenericTests.zip)

**Comment by zabil** [comment]
the `click` method is missing in your require statement.

Please modify it to 
```
const { openBrowser, click, write, closeBrowser, goto, press, text, focus, textBox, toRightOf } = require('taiko');
```
