### ISSUE TITLE
switchTo with URL parameter

### ISSUE THREAD

**Issue by sarut0bi** [getgauge/taiko#828]
Hello all, seems that switchTo with URL parameter is not working:
Here is an example of step:

 ```
 var data  = '<html><title>plop</title><body><p>Click the button to open a new browser window.</p><button onclick="myFunction()">Try it</button><script>function myFunction() {  window.open("https://www.w3schools.com");}</script></body></html>'
  var file = Date.now()+'.html';
  fs.writeFile(file, data,  (err) => {
    if (err) console.log(err);
  });
  var fullPath = _path.resolve(file);
  await goto('file:///' + fullPath);

  await click(button('Try it'));
  await switchTo('plop')
  await switchTo('https://www.w3schools.com')
```

=> First switch is working (by title)
=> Second one (bu URL) is raising following error:
`        Failed Step: i temp
        Specification: c:\Users\Joffrey\Desktop\plop\plop\specs\temp.spec:5
        Error Message: Error: No target with given URL/Title found.
        Stacktrace: 
        Error: No target with given URL/Title found.
            at module.exports.switchTo (node_modules\taiko\lib\taiko.js:275:15)`

**Comment by shubhamsc** [comment]
@sarut0bi The given steps with sample HTML is working fine. I didn't see any error.
Please make sure you're passing the right URL from the spec file.

**Comment by sarut0bi** [comment]
@shubhamsc following step 'as it' do not work on my machine ...
```
$ gauge run specs/temp.spec
(node:19036) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
# temp
  ## temp        F
        Failed Step: i temp
        Specification: specs\temp.spec:5
        Error Message: Error: No target with given URL/Title found.
        Stacktrace:
        Error: No target with given URL/Title found.
            at module.exports.switchTo (node_modules\taiko\lib\taiko.js:275:15)

Successfully generated html-report to => C:\Users\Joffrey\Desktop\plop\plop\reports\html-report\index.html
Specifications: 1 executed      0 passed        1 failed        0 skipped
Scenarios:      1 executed      0 passed        1 failed        0 skipped

Total time taken: 5.324s
```

i am using windows 10 with
```
$ gauge --version
Gauge version: 1.0.4
Commit Hash: 3a9a647

Plugins
-------
html-report (4.0.8)
java (0.7.2)
js (2.3.5)
screenshot (0.0.1)
```

**Comment by sarut0bi** [comment]
I found why !
```
await switchTo('w3schools.com');
```
is Working !

**Comment by BugDiver** [comment]
@sarut0bi Great, you found the solution. Closing the issue. Feel free to reopen if you face it again.

**Comment by sarut0bi** [comment]
it is more likely a workaround for a bug in taiko no?
I have a very bad looking url.replace(/.*www\./g,'') in my step code 😞
