### ISSUE TITLE
How to use .step and run a .step generated code?

### ISSUE THREAD

**Issue by wshen001** [getgauge/taiko#835]
I use .step to generate code into a javascript file. But it always showing "ReferenceError: step is not defined". 

### Expected behavior
Taiko should be able to run a step javascript file.

```
node: v8.16.0
taiko: v1.0.0
```

**Comment by BugDiver** [comment]
@wshen001 .step is use to create step implementations for `gauge-js` which work with Gauge projects. The generated code by `.step` is not meant to be used standalone.
