### ISSUE TITLE
Fix documentation for `waitFor`

### ISSUE THREAD

**Issue by dennismphil** [getgauge/taiko#836]
Fix the documentation for `waitFor`. It mentions waitFor expects `seconds`. however, the implementation takes `milliseconds`

https://taiko.gauge.org/#waitfor

## Details
![Screen Shot 2019-09-26 at 9 22 13 PM](https://user-images.githubusercontent.com/4141366/65742172-dfc48480-e0a3-11e9-98cb-a7db4b920aed.png)

**Comment by BugDiver** [comment]
The docs have been updated.

**Comment by JaniJegoroff** [comment]
According to commit https://github.com/getgauge/taiko/commit/8b199d9148dc11ca7e7f420ee79b11d5e7e65b2e there is a small typo: `miliseconds` -> `milliseconds`

**Comment by BugDiver** [comment]
Done.
