### ISSUE TITLE
inputField deprecated without replacement for all types of input

### ISSUE THREAD

**Issue by jlane9** [getgauge/taiko#856]
### Suggestion
inputField is displaying:
`DEPRECATION WARNING: inputField is deprecated, use textBox api instead`.

However, textBox only works with inputs of type `text`, `password`, `url`, `search`, `number`, `email`, `tel` and textarea, but there are [additional types](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) that are available such as `date`, `time`, etc. that are excluded.

Is it possible to add these additional types to inputField, or would it be easier to list what types inputField can't be `button`, `checkbox`, `file`, `radio`, `reset` and `submit` and allow any other type?

### Versions
```
taiko: v1.0.0
```

**Comment by Apoorva-GA** [comment]
@jlane9 There is an open [issue](https://github.com/getgauge/taiko/issues/612) to support html5 input types.
Also `button`, `checkbox`, `file`, `radio`, `reset` and `submit` are covered as part of other apis.
Eg : [button](https://taiko.gauge.org/#button), [fileField](https://taiko.gauge.org/#filefield),[checkBox](https://taiko.gauge.org/#checkbox) and [radioButton](https://taiko.gauge.org/#radiobutton)
