### ISSUE TITLE
Copy button is not working for Taiko APIs

### ISSUE THREAD

**Issue by shubhamsc** [getgauge/taiko#861]
### Expected behavior
Copy button should copy the complete code block

### Actual behavior
It copies a single word from the code block.

### Steps to reproduce
1. open `https://taiko-preview.gauge.org/#openbrowser`
2. click on `copy`
3. it'll copy `in` word only from the code block instead of the code block.

**Comment by Debashis9012** [comment]
Fixed in `taiko-preview` site.
