### ISSUE TITLE
Feature request: Parallel running sessions

### ISSUE THREAD

**Issue by xdc0** [getgauge/taiko#862]
### Expected behavior
Add the ability to create multiple sessions that can run in parallel in a test so it is possible to test features with multiple users at the same time. Alternate frameworks, such as `testcafe` names this feature: "User roles".

Some example code on how it may look like:

```js
let userSession;
let adminSession;

beforeAll(async () => {
  userSession = await openBrowser('http://myapp/login')
  userSession.write('regularuser', textBox('username'))
  userSession.write('password', textBox('password'))

  adminSession = await openBrowser('http://myapp/login')
  adminSession.write('adminuser', textBox('username'))
  adminSession('password', textBox('password'))
})

afterAll(async () => {
  userSession.closeBrowser()
  adminSession.closeBrowser()
})

it('should save comments', async () => {
  await userSession.write('Foo', textBox('comment'))
  await userSession.click('Submit')
})

it('should show moderation options when appropriate', async () => {
  assert.fail(userSession.text('Moderate comments').exists())
  adminSession.text('Moderate comments').exists()
})
```

Take this example at face value, I'm not advocating for writing tests similar to this, but instead just showing the degree of control that would be cool to have by having an API similar to this to maintain a session.

**Comment by zabil** [comment]
Have you tried using tabs? You can open tabs and switch between them. However using tabs is a workaround.

To keep the core api simple I believe should think of adding this feature via a plugin.

**Comment by xdc0** [comment]
Using tabs shares the session with each other. So, if I have tab one tab logged as an admin and open a second tab, that second tab session will also be an admin. If I log off from the second tab, then I'll also be logged off from the first tab.

The current workaround is to have separate test cases and having a standalone function that runs the scenarios separately, you may abstract the initialization code of a session (logging in and so on) but it has to be repeated for each test.

**Comment by zabil** [comment]
Closing this to discuss a profile feature
https://github.com/getgauge/taiko/issues/921
