### ISSUE TITLE
Unable to Install Taiko on Windows 10 machine

### ISSUE THREAD

**Issue by harimadusumilli** [getgauge/taiko#875]
### Expected behavior
Taiko should be able to Install

### Actual behavior
The Installation of Taiko errors out.

### Steps to reproduce
1. At the command prompt in the terminal window of windows 10 machine I type the command as follows 
 npm install -g taiko

The out put I get is below
C:\Users\hadusumi\AppData\Roaming\npm\taiko -> C:\Users\hadusumi\AppData\Roaming\npm\node_modules\taiko\bin\taiko.js

> taiko@1.0.2 install C:\Users\hadusumi\AppData\Roaming\npm\node_modules\taiko
> node lib/install.js

ERROR: Failed to download Chromium r662092! Set "TAIKO_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1049:34)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket._finishInit (_tls_wrap.js:631:8) code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! taiko@1.0.2 install: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the taiko@1.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hadusumi\AppData\Roaming\npm-cache\_logs\2019-10-09T00_28_49_594Z-debug.log
2.
3.

The question I have is it possible to install chromium using npm and then install taiko skipping the chromium download by setting the environment variable.
If that is the case, I have tried that option too and taiko installs by setting the environnment variable to skip chromium download to true. I am not sure how to let Taiko know that I have the chromium down load in my npm packages.

If the above does not work, then can you please let me know, if there is a workaround or suggestion in order to have this installed.

**Comment by zabil** [comment]
You can download the chromium browser and set the environment variable  `TAIKO_BROWSER_PATH` to where you've installed it.

More details at https://taiko.gauge.org/#taiko-env-variables

**Comment by harimadusumilli** [comment]
I have tried your suggestion. I downloaded the complete Chromium from the Chromium site and tested by launching the chromium browser without Taiko and the browser launches.

I then set the environment variable TAIKO_BROWSER_PATH to the location or the path where my chromium browser is located and tried to launch it using Taiko.

The Chromium Browser version is : Version 79.0.3938.0 (Developer Build) (64-bit)

I get the following error :
C:\>taiko

Version: 1.0.2 (Chromium:76.0.3803.0)
Type .api for help and .exit to quit

> openBrowser()
'[FAIL] Error: Failed to launch chrome! spawn C:\\Tools\\Win_x64_704177_chrome-win\\chrome-win ENOENT
, run `.trace` for more info.'
> .trace
'Error: Failed to launch chrome! spawn C:\\Tools\\Win_x64_704177_chrome-win\\chrome-win ENOENT

    at onClose (C:\\Users\\hadusumi\\AppData\\Roaming\
pm\
ode_modules\\taiko\\lib\\browserFetcher.js:282:11)
    at ChildProcess.helper.addEventListener.error (C:\\Users\\hadusumi\\AppData\\Roaming\
pm\
ode_modules\\taiko\\lib\\browserFetcher.js:271:11)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:441:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)'

**Comment by harimadusumilli** [comment]
If you think the version of Chromium should be the same as Version: 1.0.2 (Chromium:76.0.3803.0). Can you please point me to a link to download the same version as I am unable to find the exact version that corresponds to this.

**Comment by sriv** [comment]
`ENOENT` signifies that the `File or Directory was not found`. Can you ensure that `C:\Tools\Win_x64_704177_chrome-win\chrome-win` is the executable chrome and you are able to launch it outside taiko?

Note that `TAIKO_BROWSER_PATH` should contain the path to the actual executable and not the location of the browser executable.

**Comment by harimadusumilli** [comment]
Thank you Sri and Zabil. I am able to launch the browser using Taiko. This can be closed.

I am definitely excited to play with this tool and would like to make this as our go to tool for doing UI based browser automation.
