### ISSUE TITLE
Script that works in the observe mode should work in the normal mode as well

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#88]
**Expected behavior**
Script that works in the observe mode should work in the normal mode as well

**Actual behavior**
The following script works in the observe mode only

**Steps to replicate**
* Run the following taiko script
> Please ensure there are no todo items before starting the script in http://todomvc.com/examples/react/#
```
const { browser, openBrowser, goto, link, click, listItem } = require('taiko');
const assert = require("assert");

(async () => {
    try {
        await openBrowser();
        await goto("http://todomvc.com/examples/react/#/");

        await write("flow");

        await press("Enter");

        await click(link("Active"));
        await click(checkBox({'class':'toggle'},near('flow')))

        await click(link("Completed"));

        await click(link("Clear completed"));
        await reload("http://todomvc.com/examples/react/#/",{waitForNavigation:true});

        await closeBrowser();
    } catch (e) {
        console.error(e);
    } finally {
    }
})();
```
**Version**
```
commit - 215a0767e673443e8f91ddaa0a56e984bad09a94
Fri Aug 3 09:34:39 2018 +0530
```

**Comment by Apoorva-GA** [comment]
@sguptatw What exactly is failing in non observe mode?

**Comment by sguptatw** [comment]
https://build.gauge.org/go/tab/build/detail/Taiko/149/specs/3/specs fails. We get that the error that element does not exist. This does not happen in the observe mode.

**Comment by Apoorva-GA** [comment]
@sguptatw Were you able to reproduce the same error in local/any docker image?

**Comment by sguptatw** [comment]
On my local this fails intermittently

**Comment by sguptatw** [comment]
To replicate this issue try the following

* Pull the image
docker pull mddubey/bahmni-openmrs

* Start a container and map the 443 port for httpd
docker run -itd --name=sample -p 8000:443 mddubey/bahmni-openmrs /bin/bash

* Run the script
```
const { openBrowser, goto, inputField, into, write, toRightOf, comboBox, click } = require('taiko');

(async () => {
    try {
        await openBrowser();
        await goto("https://localhost:8000/bahmni/home/index.html#/login");
        await write("superman",into(inputField({"placeHolder":"Enter your username"})));
        await write("Admin123",into(inputField({"placeHolder":"Enter your password"})));
        await comboBox(toRightOf("Location *")).select("General Ward");
        await click(button("Login"));
    } catch (e) {
        console.error(e);
    } finally {
        closeBrowser();
    }
})();
```
> The script succeeds in the observe mode, but fails in the observe mode.

**Comment by Apoorva-GA** [comment]
Observation : The script 
```
const { openBrowser, goto, inputField, into, write, toRightOf, comboBox, click } = require('taiko');

(async () => {
    try {
        await openBrowser();
        await goto("https://localhost:8000/bahmni/home/index.html#/login");
        await write("superman",into(inputField({"placeHolder":"Enter your username"})));
        await write("Admin123",into(inputField({"placeHolder":"Enter your password"})));
        await comboBox(toRightOf("Location *")).select("General Ward");
        await click(button("Login"));
    } catch (e) {
        console.error(e);
    } finally {
        closeBrowser();
    }
})();
```
works in normal mode when `await openBrowser({headless : false})` is used instead of `await openBrowser()`.  So issue is not something that works in observe mode and fails in normal mode.
On hitting the url `https://localhost:8000/bahmni/home/index.html#/login` it throws a security warning to resolve the same one has to click on `Advanced` and then `Proceed to localhost` link. It might be failing in headless mode because of this. To verify the same I tried taking screenshot but screenshot comes as empty and there is a [issue](https://github.com/getgauge/taiko/issues/114) for that.

**Comment by Apoorva-GA** [comment]
Script
```
const { browser, openBrowser, goto, link, click, listItem } = require('taiko');
const assert = require("assert");

(async () => {
    try {
        await openBrowser();
        await goto("http://todomvc.com/examples/react/#/");

        await write("flow");

        await press("Enter");

        await click(link("Active"));
        await click(checkBox({'class':'toggle'},near('flow')))

        await click(link("Completed"));

        await click(link("Clear completed"));
        await reload("http://todomvc.com/examples/react/#/",{waitForNavigation:true});

        await closeBrowser();
    } catch (e) {
        console.error(e);
    } finally {
    }
})();
```
Doesn't say where exactly to write you will have to do `await focus(inputField({"placeHolder":"What needs to be done?"}))` before `await write("flow");` or `await write("flow", into(inputField({"placeHolder":"What needs to be done?"})));`.

The same script works in observe mode because it has explicit wait there.

**Comment by sguptatw** [comment]
When executed in the normal mode, the script does not fail at the same point. Some times it passes for writing "flow" even without explicit focus in script but fails in clicking active.

![Screen Shot 2018-08-28 at 2.33.48 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/571dd284c8c2e113000ddd5a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6456fb6b7191a37af111284f5b575ecc3c4a4356bcbbd671f3e57862804e0eebd4395775906847afebd74bbf05bc208b4bd4b5ef8f4ed2f42f67b6d5db1063474f4dcbed5727a19141c95df54ee54952a5173562e6732431.png)

**Comment by Apoorva-GA** [comment]
Yeah, If you try `openBrowser({headless : false })` and run the above script. You will see that it has not written 'flow' in the input field and hence the link `Active` won't be visible so it fails there.

**Comment by sguptatw** [comment]
The problem is that taiko does not behave consistently when run the same script multiple times. 

* > If the problem was it does not where to write then why does it work sometimes

![Screen Shot 2018-08-28 at 2.45.05 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/571dd284c8c2e113000ddd5a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6456fb6b7191a37af1162e4f5f5a5ecc3c4a4356bcbbd671f3e57862804e0eebd4395775906847afebd74bbf05bc208b4bd4b5ef8f4ed2f42f67b6d5db1063474f4dcbed5727a19e41c95df54ee54952ac1b3263e7742431.png)

* > In the following case it writes partial text. Again the problem does not seem not knowing where to write. So makes me wonder if taiko is waiting sufficiently for all initializations. 'Cause observe mode works as expected.

![Screen Shot 2018-08-28 at 2.49.38 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/571dd284c8c2e113000ddd5a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6456fb6b7191a37af116224f5c575ecc3c4a4356bcbbd671f3e57862804e0eebd4395775906847afebd74bbf05bc208b4bd4b5ef8f4ed2f42f67b6d5db1063474f4dcbed5727a19e41c95df54ee5495da5143e67e1702431.png)

* > But sometimes it does not work and gives error

![Screen Shot 2018-08-28 at 2.50.40 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/571dd284c8c2e113000ddd5a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6456fb6b7191a37af1172b4f5b5f5ecc3c4a4356bcbbd671f3e57862804e0eebd4395775906847afebd74bbf05bc208b4bd4b5ef8f4ed2f42f67b6d5db1063474f4dcbed5727a19e41c95df54ee5495da5113e6ae0732431.png)

However it works consistently in the observe mode.

**Comment by Apoorva-GA** [comment]
Have a look at the below case : It says it has written 'flow' and pressed enter but nothing is actually done. 
<img width="1345" alt="screen shot 2018-08-28 at 15 07 12" src="https://user-images.githubusercontent.com/8462534/44715010-5a535700-aad4-11e8-82dc-4a304d4f4ed3.png">

Thats the reason I suggested to use explicit focus before writing or use into. Which will make things consistent.

**Comment by sguptatw** [comment]
Observation: All elements are not available immediately when user goes to the link. My assumption is that all elements are not available and taiko starts performing the action. In this case focus might solve the problem; but I think taiko must wait for all elements to be available before performing any action.

![Screen Shot 2018-08-28 at 3.09.38 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/571dd284c8c2e113000ddd5a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6456fb6b7191a37bf112224f5c575ecc3c4a4356bcbbd671f3e57862804e0eebd4395775906847afebd74bbf05bc208b4bd4b5ef8f4ed2f42f67b6d5db1063474f4dcbed5727a19e41c95df54ee5495ca6173062e37f2431.png)

![Screen Shot 2018-08-28 at 3.09.28 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/571dd284c8c2e113000ddd5a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6456fb6b7191a37bf112224f5d575ecc3c4a4356bcbbd671f3e57862804e0eebd4395775906847afebd74bbf05bc208b4bd4b5ef8f4ed2f42f67b6d5db1063474f4dcbed5727a19141c95df54ee5495ca6153764ee702431.png)

**Comment by sguptatw** [comment]
Observation: All elements are not available immediately when user goes to the link. My assumption is that all elements are not available and taiko starts performing the action. Hence this may cause the inconsistency. Since the observe mode adds a delay seems like that is giving time for the elements to be available and ready for taiko.

In this case focus might solve the problem; But I think there must be a generic solution. Taiko must wait for all elements to be available before performing any action.

![Screen Shot 2018-08-28 at 3.09.38 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/571dd284c8c2e113000ddd5a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6456fb6b7191a37bf112224f5c575ecc3c4a4356bcbbd671f3e57862804e0eebd4395775906847afebd74bbf05bc208b4bd4b5ef8f4ed2f42f67b6d5db1063474f4dcbed5727a19e41c95df54ee5495ca6173062e37f2431.png)

![Screen Shot 2018-08-28 at 3.09.28 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/571dd284c8c2e113000ddd5a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6456fb6b7191a37bf112224f5d575ecc3c4a4356bcbbd671f3e57862804e0eebd4395775906847afebd74bbf05bc208b4bd4b5ef8f4ed2f42f67b6d5db1063474f4dcbed5727a19141c95df54ee5495ca6153764ee702431.png)

**Comment by Apoorva-GA** [comment]
Yeah @sguptatw and this is exactly what I said [here](https://github.com/getgauge/taiko/issues/88#issuecomment-416483113).

**Comment by Apoorva-GA** [comment]
Doesn't that mean same script works from REPL and not when executed as script? which is different from original issue.

**Comment by sguptatw** [comment]
**Expected behavior in the original issue**
Script that works in the observe mode should work in the normal mode as well

**Suggested workaround**
`await focus(inputField({"placeHolder":"What needs to be done?"}))` before `await write("flow");` or `await write("flow", into(inputField({"placeHolder":"What needs to be done?"})));`.

IMO - **The reason why the workaround is not suitable**
Focusing explicitly on the element is a work around. This is not an acceptable workaround 'cause this means taiko is not able to replay consistently what is recorded without changing the script.
Taiko should handle this internally. It should wait for all the page to complete initialization and UI elements to be available before performing the action.

**Updated expected behavior**
Script that works in the observe mode should work `consistently` in the normal mode as well `without changes to the recorded script`

> Kindly let me know your thoughts

**Comment by Apoorva-GA** [comment]
Fix should be available in commit 26bfe11

**Comment by Apoorva-GA** [comment]
As per the discussion,  

- The plan is to wait(until the default timeout) for the focus to be on any of the writable field when the `write('something')` action is being performed. 
- The action should be shown successful only when the complete text is written into the field.

**Comment by sguptatw** [comment]
The flakiness has reduced but not gone completely.

- Running the script several times, the script fails once in a while

```
const { browser, openBrowser, goto, link, click, listItem,checkBox } = require('taiko');

(async () => {
    try {
        await openBrowser();
        await goto("http://todomvc.com/examples/react/#/",{timeout:15000});
        await write("something");
        await press("Enter");  
        await waitFor(1000);
        await click(checkBox({'class':'toggle'},near('something')))
        await hover(checkBox({'class':'toggle'}))
        await closeBrowser();
    } catch (e) {
        console.error(e);
    } finally {
    }
})();
```

![flakyness.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/571dd284c8c2e113000ddd5a/125516c66e82c728ace21e0d46ee989b289b8dac9cfafd0fe64de29b234324676b5ee17e26d0e770ee447e075c0c1bf8415c5944fcfdd828f5b33e62964e49bc8f3900299f7744eeaa880dbe09b0218e4c83b5bd8a4cc4ee3523e199c2.png)

------------------------------

Another example that may help
In the normal mode, a more frequent failure can be observed in the following script
> In the headless mode, you may have to run it a couple of times to observe the flakyness.

```
const { openBrowser, goto, inputField, into, write, press, button, click, link, below, radioButton, contains, toLeftOf, checkBox } = require('taiko');

(async () => {
   try {
       await openBrowser({headless:false});
       await goto("https://www.greateranglia.co.uk/",{timeout:"25000"});
       await write("London",into(inputField({"placeHolder":"Enter origin station"})));
       await press("Enter");
       await write("Manchester",into(inputField({"placeHolder":"Enter destination station"})));
       await press("Enter");
       await click(button("Find times and tickets"));
       await click(radioButton(below(link("Later"))));
       await click("Next");

       await click("Continue");
       await write("email@gmail.com",into(inputField({"placeHolder":"Your email address"})));
       await click(radioButton(toLeftOf(contains("I don't have a password"))));
       await click("Continue");
       await click("Continue");
       await click("Proceed to payment");
       await click(radioButton({"id":"PaymentMethod_OnAccount_Option"}));
       await click("Buy Tickets");
       await click(radioButton(toLeftOf("No thank you")));
       await click("Buy Tickets");
       await click(checkBox(toLeftOf(contains("I've read"))));
       await click("Buy Tickets");
   } catch (e) {
       console.error(e);
   } finally {
       closeBrowser();
   }
})();
```

**Comment by sguptatw** [comment]
Executing the following script is not consistent in observe and normal mode.
```
const { browser, openBrowser, goto, click,link,image } = require('taiko');

(async () => {
    try {
        await openBrowser();
        await goto("https://in.bookmyshow.com/bengaluru");

        await click("Bengaluru");
        await write('NCR', into(await inputField({"placeholder":"Search for your city"})));
        await click("NCR");
        await click("View All");
        await click(image(below(link("Now Showing"))))
        await click(link("Book Tickets"))

        await click(link({"class":"__showtime-link"}))
        await click("Accept")        
        await click(link(toRightOf("D")))
        await click("Select Seats")

        // await click(link(contains("Pay ")))
        // await click(radioButton(toLeftOf(contains("M-Ticket"))))
        await waitFor("5000")
    } catch (e) {
        console.error(e);
    } finally {
        await closeBrowser();
    }
})();
```

**Comment by NivedhaSenthil** [comment]
As discussed with @sguptatw, For the second script it fails in headless mode and works in headful mode even without observe mode. The site seems to be rendering differently in headless mode. The inputField is not rendered at all even after explicit 8 seconds wait, it cannot be seen in the screenshot.

**Comment by sguptatw** [comment]
@NivedhaSenthil yes, with the second script that is not rendering in headless mode. For the following the script is failing to find the element 'cause the screen resolution in the headless mode is small and the UI element is not there.

![screen-resolution](https://user-images.githubusercontent.com/6310197/45216151-37d3f180-b2bd-11e8-9ac7-07fa7723b4f7.png)

```
const { browser, openBrowser, goto, click,link,image } = require('taiko');

(async () => {
    try {
        await openBrowser();
        await goto("https://in.bookmyshow.com/bengaluru");

        await click("Bengaluru");
        await write('NCR', into(await inputField({"placeholder":"Search for your city"})));
        await click("NCR");
        await click("View All");
        await click(image(below(link("Now Showing"))))
        await click(link("Book Tickets"))

        await click(link({"class":"__showtime-link"}))
        await click("Accept")        
        await click(link(toRightOf("D")))
        await click("Select Seats")

        // await click(link(contains("Pay ")))
        // await click(radioButton(toLeftOf(contains("M-Ticket"))))
        await waitFor("5000")
    } catch (e) {
        console.error(e);
    } finally {
        await closeBrowser();
    }
})();
```

**Comment by sguptatw** [comment]
@NivedhaSenthil - Screen-resolution which is used to run the tests seems to be the issue.

> The problem seems to be that when scripts are executed in headless mode, the browser-screen-resolution is small and applications are not able to render elements in the opened screen size.

Tracking this issue separately https://github.com/getgauge/taiko/issues/140
