### ISSUE TITLE
Intercept request are not resetted

### ISSUE THREAD

**Issue by sarut0bi** [getgauge/taiko#884]
Hi,
 
It seems that request intercept are currently not resetted between each scenario.
When i set an 
`await intercept('https://www.google.fr/complete/search?.*',`

* On first run i get no warning
* On second run i get on warning `WARNING: More than one intercept ["https://www.google.fr/complete/search?.*","https://www.google.fr/complete/search?.*"] found for request`
* On third run  `WARNING: More than one intercept ["https://www.google.fr/complete/search?.*","https://www.google.fr/complete/search?.*","https://www.google.fr/complete/search?.*"] found for request`

Is it possible to reset them between each scenarios ?
The only workaround i found for the moment is to close/open browser between each scenario but considerably increase test run time :/

**Comment by rparthas** [comment]
Another solution is to provide a count for the number of times the intercept has to be used - Refer https://github.com/getgauge/taiko/pull/864.  This avoids closing the browser

**Comment by sarut0bi** [comment]
it does not solve parallelization issues ;)

**Comment by negiDharmendra** [comment]
@sarut0bi Please provide more details about the parallelization issues you are talking about.

**Comment by z04jmath** [comment]
I've got some 'Could not intercept request' when running tests with -p switch

**Comment by negiDharmendra** [comment]
@sarut0bi Is it possible for you to share a sample project.

**Comment by z04jmath** [comment]
if you set an URL redirection according to path `http://debugurl/api` => `http://stageurl/api` using `.*/api` filter on the parallel opened browser you ll get a Could not intercept request because you ask for `http://stageurl/api` => `http://stageurl/api`.
Providing a count is sure a nice workaround but I truly hope that resetting before each scenario is more efficient and comprehensible for everyone.

**Comment by rparthas** [comment]
@z04jmath Ok i will take a crack at it.

**Comment by rparthas** [comment]
@z04jmath Intercept is not added per scenario. Can provide a resetIntercept  but even for that a named intercept has to be provided.  While Adding intercept, a uniquely identifiable name has to be provided. We can auto create the name but cannot guarantee the uniqueness  as each scenario can use the same URL and step. Nevertheless, I will explore little on this

**Comment by rparthas** [comment]
resetInterceptors - this is already available. Actually this is what happens when you make call to close browser.

Intercept does not currently have relationship to step or browser and works as a event handler.

**Comment by sarut0bi** [comment]
could you tell me how to 'resetInterceptors' without closing browser also ? :/
Cannot find how in taiko documentation :/

**Comment by rparthas** [comment]
I think it is not exposed. I can give a pull request with examples.  But my only question is when running parallel if the interceptors are resetted would it not affect other scenarios ?
I am still thinking named intercept is better. We can auto generate intercept name and return it during intercept call. This can be provided to resetIntercept to remove that particular intercept.

**Comment by negiDharmendra** [comment]
@sarut0bi  @rparthas has contributed an api(`clearIntercept`) to clear request interceptors.
Which removes interceptor for the provided URL or all interceptors if no URL is specified.

**Examples:**

```
openBrowser()
intercept('gauge.org', 'google.com')
intercept('taiko.gauge.org', 'github.com')
clearIntercept('taiko.gauge.org') // Will remove interceptor for taiko.gauge.org
//Whereas
clearIntercept() // Will remove all interceptors.

```

**Comment by sarut0bi** [comment]
ty @negiDharmendra @rparthas

**Comment by Debashis9012** [comment]
Tested and verified the above changes. `clearIntercept` api works as excepted.  
Tested version:
`0e454f514e98b86e56c09a7aaaf663260add0e43`
