### ISSUE TITLE
Feature request: Scope mouseAction to a selector

### ISSUE THREAD

**Issue by luizsignorelli** [getgauge/taiko#893]
I have a portion of the page that is a map, and I'd like to do a bunch of `mouseAction`s inside the map. 

I'm looking for a way to execute the actions passing coordinates relative to the map, not the whole page:

Instead of:
```
mouseAction('press', {x:0,y:0})
mouseAction('move', {x:0,y:9})
...
```

do:
```
mouseAction($('#map'), 'press', {x:0,y:0})
mouseAction($('#map'), 'move', {x:0,y:9})
...
```

Selenium web driver has something like that: https://www.rubydoc.info/gems/selenium-webdriver/Selenium%2FWebDriver%2FActionBuilder:move_to

**Comment by nehashri** [comment]
@luizsignorelli This seems like a good to have feature.

**Comment by luizsignorelli** [comment]
Thanks @nehashri 

Another reason to do this is that the scoped element would also receive the mouse events. This would enable taiko to test some interactions with the MapBox component for example, which it can't right now.

**Comment by jayandran-Sampath** [comment]
Working on it

**Comment by Debashis9012** [comment]
@luizsignorelli Could you please try it out with the latest taiko and let us know if the fix meets your requirement.

**Comment by Debashis9012** [comment]
This has been tested and verified against `d3c42b08e61f2b2ecb86a01ecdf15f422e3b1bf4` version.
