### ISSUE TITLE
 Error Message: Error: WebSocket is not open: readyState 3 (CLOSED)

### ISSUE THREAD

**Issue by adea11** [getgauge/taiko#896]
### Expected behavior
I have above 40 scenarios using the following functions:

beforeSuite(async () => {
  await openBrowser({ headless: true, args: [
    '--disable-gpu',
    '--disable-dev-shm-usage',
    '--disable-setuid-sandbox',
    '--no-first-run',
    '--no-sandbox',
    '--no-zygote',
    '--window-size=1800,1200'
  ]})})

afterSuite(async () => {
  await closeBrowser()
})

beforeScenario(async () => {
  await deleteCookies()
  await openTab()
})

afterScenario(async () => {
  await closeTab()
})

### Actual behavior
After about 6 scenarios I get the error below:

 Error Message: Error: WebSocket is not open: readyState 3 (CLOSED)
    Stacktrace: 
    Error: WebSocket is not open: readyState 3 (CLOSED)
        at WebSocket.send (node_modules/ws/lib/websocket.js:329:19)
        at Chrome._enqueueCommand (node_modules/chrome-remote-interface/lib/chrome.js:281:18)
        at node_modules/chrome-remote-interface/lib/chrome.js:87:22
        at new Promise (<anonymous>)
        at Chrome.send (node_modules/chrome-remote-interface/lib/chrome.js:86:20)
        at Object.handler [as clearBrowserCookies] (node_modules/chrome-remote-interface/lib/api.js:32:23)
        at module.exports.deleteCookies (node_modules/taiko/lib/taiko.js:669:19)
        at module.exports.<computed> (node_modules/taiko/lib/taiko.js:3542:36)
        at Object.<anonymous> (tests/user.js:26:9)

    Error Message: TypeError: Cannot read property 'message' of undefined
    Stacktrace: 
    TypeError: Cannot read property 'message' of undefined
        at Object.runtimeEvaluate (node_modules/taiko/lib/handlers/runtimeHandler.js:51:18)

### Versions
```
taiko version: 1.0.2 (Chromium: 76.0.3803.0) RELEASE
Gauge version: 1.0.6
Commit Hash: 2bc49db

Plugins
-------
flash (0.0.1)
html-report (4.0.8)
js (2.3.5)
json-report (0.3.2)
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.2)
```

**Comment by nehashri** [comment]
@adea11 I tried to replicate this issue, but I don't seem to be able to. Is it possible to share a minimal repository to reproduce this issue?

**Comment by adea11** [comment]
Thanks @nehashri. Please how can I restart browser if it crash and socket got closed. Is it possible to add [restart if crash] to open browser function --await openBrowser()---

**Comment by nehashri** [comment]
@adea11 There isn't a straightforward way to open the tab if it is closed. I think the reason for this error is because the browser was closed for some reason when `await deleteCookies()` is called. 

Close tab also closes the browser is there is no open tab.
I suggest you look at your test suite and see if the browser instance is actually running or not. If the reason for this error is because the browser instance is killed, we can see what is the cause for this. 

If you can reproduce this issue, it can help us resolve it better.

**Comment by nehashri** [comment]
We are seeing this issue in github actions too. We are working on a fix.

**Comment by felipeespitalher** [comment]
I'm facing the same problem. Do you guys have any updates?


`Error: WebSocket is not open: readyState 3 (CLOSED)
    at WebSocket.send (/home/node/app/node_modules/ws/lib/websocket.js:329:19)
    at Chrome._enqueueCommand (/home/node/app/node_modules/chrome-remote-interface/lib/chrome.js:281:18)
    at Promise (/home/node/app/node_modules/chrome-remote-interface/lib/chrome.js:87:22)
    at new Promise (<anonymous>)
    at Chrome.send (/home/node/app/node_modules/chrome-remote-interface/lib/chrome.js:86:20)
    at Object.handler [as clearBrowserCookies] (/home/node/app/node_modules/chrome-remote-interface/lib/api.js:32:23)
    at module.exports.deleteCookies (/home/node/app/node_modules/taiko/lib/taiko.js:669:19)
    at module.exports.(anonymous function) (/home/node/app/node_modules/taiko/lib/taiko.js:3542:36)
{ Error: 7 PERMISSION_DENIED: The caller does not have permission
    at Object.callErrorFromStatus (/home/node/app/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Http2CallStream.call.on (/home/node/app/node_modules/@grpc/grpc-js/build/src/client.js:96:33)
    at Http2CallStream.emit (events.js:203:15)
    at Http2CallStream.EventEmitter.emit (domain.js:448:20)
    at process.nextTick (/home/node/app/node_modules/@grpc/grpc-js/build/src/call-stream.js:79:22)
    at process._tickCallback (internal/process/next_tick.js:61:11)
  code: 7,
  details: 'The caller does not have permission',
  metadata: Metadata { internalRepr: Map {}, options: {} },
  note:
   'Exception occurred in retry method that was not classified as transient' }`

**Comment by zabil** [comment]
@felipeespitalher is there anything you can share like a sample code or condition where you this happening? This will help speed up the resolution as this seems intermittent.

**Comment by felipeespitalher** [comment]
Those exceptions appear few moments after the script bellow finishes. We are using this script inside of GCP/GKE


```
"dependencies": {
    "@bugsnag/js": "^6.3.2",
    "@bugsnag/plugin-express": "^6.3.0",
    "@google-cloud/debug-agent": "^4.0.1",
    "@google-cloud/logging-winston": "^1.1.1",
    "@google-cloud/trace-agent": "^4.0.1",
    "async": "^3.1.0",
    "date-format": "^3.0.0",
    "express": "^4.17.1",
    "express-winston": "^4.0.1",
    "nconf": "^0.10.0",
    "taiko": "^1.0.2",
    "winston": "^3.2.1"
  }
```


        try {
                await openBrowser({
                        ignoreCertificateErrors: true,
                        observe: true,
                        args: [
                                '--disable-gpu',
                                '--disable-dev-shm-usage',
                                '--disable-setuid-sandbox',
                                '--no-first-run',
                                '--no-sandbox',
                                '--no-zygote'
                        ]
                });
                await setConfig({
                    observeTime: 500,
                    navigationTimeout: 60000,
                    retryInterval: 2000,
                    retryTimeout: 5000,
                    waitForNavigation: true,
                });
                await deleteCookies();

                await goto(process.env.URL);
                await write(process.env.USERNAME, into(textBox({ id: "username" })));
                await write(process.env.PASSWORD, into(textBox({ id: "password" })));
                await click(button('Login'));

               await click('Menu');
               await write(documentNumber, into(textBox({ id: "document" })));
               await click(button('Submit'));
        } catch  (error) {
               console.error(error)
        } finally {
                await closeBrowser();
        }

**Comment by saikrishna321** [comment]
@zabil @nehashri 

Can we expose an event `disconnect` and the test scripts can restart the browser when the browser crashes?

```
const setup = async () => {
    browser = await openBrowser({
        args: ['--disable-gpu', '--no-sandbox', '--disable-dev-shm-usage']
    });

    browser.on('disconnected', setup);;
};
```

**Comment by zabil** [comment]
> We are using this script inside of GCP/GKE

Do you have this problem while running the scripts locally? GCP/GKE maybe constrained. This error happens when the browser crashes or shutdown after opening. Perhaps allocate more memory and make sure the browser does not crash?

> Can we expose an event disconnect 

As there is only one instance of the browser, it could be something globally as a plugin. 

```
taikoEvents.on('disconnected', 'setup')
```

However in this case it is worth figuring out why the browser crashes before restarting when disconnected.

**Comment by felipeespitalher** [comment]
> Do you have this problem while running the scripts locally? GCP/GKE maybe constrained. This error happens when the browser crashes or shutdown after opening. Perhaps allocate more memory and make sure the browser does not crash?

We identified this error at GKE then after some tests we could see this error occurring locally too.
