### ISSUE TITLE
Support different protocols in URL

### ISSUE THREAD

**Issue by arunvelsriram** [getgauge/taiko#903]
### Expected behavior
Opening chrome settings using URL: chrome://settings doesn't work

### Actual behavior
Chromium settings should be opened

### Steps to reproduce
1. Open browser `openBrowser()`
2. Go to chrome://settings `goto("chrome://settings")`

### Versions
```
Node: v10.16.3
Taiko: Version: 1.0.2 (Chromium: 76.0.3803.0) RELEASE
```

I tried to work around the issue by pressing "Cmd," (`press(["Meta", ","])`) which is the keyboard shortcut to open settings but it didn't work.

Looking into the code I found that we are allowing only `http`, `https`, `file` protocols and implemented a fallback to `http` 

https://github.com/getgauge/taiko/blob/ff5d956bcf99bfb5a77fdda02352cd50323a1293/lib/taiko.js#L767

### My use case for opening chromium settings:

I am trying to automate the downloading of multiple files from a website. There are different types of files and I want them to be downloaded in different directories. So I want to change the download location from chromium settings.

Let me know if this makes sense. I can raise a PR to fix this issue.

**Comment by saikrishna321** [comment]
@arunvelsriram IMO you should pass args to `openBrowser` API to set flags. Refer https://peter.sh/experiments/chromium-command-line-switches/

**Comment by arunvelsriram** [comment]
I searched those args already and I couldn't find any to change the download location.

**Comment by zabil** [comment]
It might be `download.default_directory`

**Comment by arunvelsriram** [comment]
https://taiko.gauge.org/#openbrowser

Args to `openBrowser()` is an array of string. How do I use it with `openBrowser()` API?

**Comment by sriv** [comment]
Perhaps this example can help the file download use case:

https://github.com/getgauge/taiko/blob/master/examples/02-file_download.js

**Comment by arunvelsriram** [comment]
@sriv Awesome. That's close to what am looking for. Thanks
