### ISSUE TITLE
Unable to Key into a Zip code field which is a Text field

### ISSUE THREAD

**Issue by harimadusumilli** [getgauge/taiko#909]
### Expected behavior
Taiko should be able to key into the Zipcode- Textbox field on the following site : https://www.travelers.com/index

### Actual behavior
I am able to focus on the field and find out if it exists, but its unable to write into the Zip Code field.

### Steps to reproduce
const { openBrowser, goto, into, textBox, write, closeBrowser } = require('taiko');
(async () => {
    try {
        await openBrowser();
        await goto("https://www.travelers.com/index");
        await textBox({class:'zip'}).exists();
        await write('06074',into(textBox({class:'zip'})));
    } catch (error) {
        console.error(error);
    } finally {
        await closeBrowser();
    }
})();
### Versions

C:\Travellers-Learn\Taiko_example>gauge -v
Gauge version: 1.0.6
Commit Hash: 2bc49db

Plugins
-------
csharp (0.10.5)
dotnet (0.1.2.nightly-2019-02-14)
html-report (4.0.7)
java (0.6.9)
js (2.3.6)
screenshot (0.0.1)
xml-report (0.2.1)
Paste `node` and `taiko` versions here.

C:\Travellers-Learn\Taiko_example>node --version
v10.15.0

C:\Travellers-Learn\Taiko_example>Taiko -v
Version: 1.0.2 (Chromium: 76.0.3803.0) RELEASE

**Comment by nehashri** [comment]
@harimadusumilli This may be because the input type `tel` is not recognized by taiko as a textbox field. I will try and fix this soon.

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed.
Tested version: `0e454f514e98b86e56c09a7aaaf663260add0e43`

**Comment by desiignerstuff** [comment]
I'm having the same issue. Can you point to the fix? Thanks.

**Comment by nehashri** [comment]
@desiignerstuff The fix has been made in commit c24be14466005dbf21f5f988f89ee8892f5070a4. You can download the latest taiko version (master) to get the fix.
