### ISSUE TITLE
Getting Inspector logs

### ISSUE THREAD

**Issue by henriquekieckbusch** [getgauge/taiko#913]
Is it possible to get someway the Inspector logs?

Like Javascript errors, network not found files, you know all the Console messages?

**Comment by nehashri** [comment]
I am guessing you are looking for something like https://github.com/saikrishna321/taiko-diagnostics#logconsoleinfo-command. This is available in the [taiko diagnostics plugin](https://github.com/saikrishna321/taiko-diagnostics).
