### ISSUE TITLE
Element that exists should return true

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#92]
**Expected behavior**
If an element exists, then the exists method should return true

**Actual behavior**
The exists method returns false

**Steps to replicate**
```
const { openBrowser, goto, below, inputField, focus, write, press, click } = require('taiko');

(async () => {
    try {
        await openBrowser();
        await goto("makemytrip.com");
        await focus(inputField(below("From")));
        await write("Bangalore",inputField(below("From")));
        await press("Enter");
        await write("Goa");
        await press("Enter");
        await click(link("20",below(text("August"))));
        await focus(inputField(below("Return")))
        await click(link("24",below(text("August"))));

        await click(button("Search"))
        console.log(await text("ZERO Cancellation |  Cancel your ticket for Free. Buy Zero Cancellation @ only").exists())
    } catch (e) {
        console.error(e);
    } finally {
        closeBrowser();
    }
})();
```
**Version**
```
commit - 215a0767e673443e8f91ddaa0a56e984bad09a94
Fri Aug 3 09:34:39 2018 +0530
```

**Comment by NivedhaSenthil** [comment]
That text is not coming up on chromium actually. I could see it on chrome when I tried it manually but not in chromium bundled with taiko.

PS : exists() now gives either { description: 'Does not exists' } or { description: 'Exists'}

**Comment by sguptatw** [comment]
That is strange, 'cause I am able to see it consistently on chromium also. 

exists gives  { description: 'Does not exists' } even though the text is present.

**Comment by Apoorva-GA** [comment]
In the above case, partial text within a div is being used to test the existence of an element. 
So `contains()` should be used.

`console.log(await text(contains("ZERO Cancellation |  Cancel your ticket for Free. Buy Zero 
   Cancellation @ only")).exists());`
 should work as expected.
