### ISSUE TITLE
Support for profiles

### ISSUE THREAD

**Issue by zabil** [getgauge/taiko#921]
### Option 1

Add `profile` as an option to `openBrowser` for example

```
> openBrowser() // uses a default profile
> click('Register') // actions on the default profile
> openBrowser({profile: admin})
> click('Approve') // Actions on the admin profile
> openBrowser() // Switches back to the default profile 
```

#### Pros
* One method for instantiating and managing browser instances

#### Cons

* Verbose
* Tricky to handle options and maybe confusing to know where the browser is instantiated

For example
```
> openBrowser({headless:true})
> openBrowser({headless:false})
```
### Option 2

Introduce a `switchProfile` method

```
> openBrowser() // uses a default profile
> click('Register') // actions on the default profile
> openBrowser({profile: admin}) // opens and switches to the admin profile
> click('Approve') // Actions on the admin profile
> switchProfile() // Switches back to the default profile 
> click('Post')
> switchProfile('admin')
> click('Reject')
```

#### Pros
* Clear separation of the command and less verbose

#### Cons
* Multiple method calls

Note: This can also be a plugin `taiko-profiles` instead of a core api in that case 

```
> profiles.switch('admin')
```

**Comment by zabil** [comment]
Also note chrome/chromium supports profiles using the option `--profile-directory`

**Comment by sanjusona** [comment]
I have an issue in taiko that is while running a same process twice or more than that the click operation is not working as of before in this first process. it's skipping the process of click operation. it is continuing thought all processes. how to overcome it and why this kind of error is occurring and in one system it is working perfectly but in another system, the same process is throwing an error.

**Comment by zabil** [comment]
@sanjusona this question does not seem related to this issue. Please raise this issue at https://spectrum.chat/gauge preferably with a clear example.

**Comment by zabil** [comment]
Closing this in favor of using incognito windows feature. https://github.com/getgauge/taiko/pull/1150
