### ISSUE TITLE
Error "ReferenceError: timeout is not defined" when there's a timeout

### ISSUE THREAD

**Issue by trein-homeroom** [getgauge/taiko#923]
### Expected behavior

Standard error message when there's a timeout

### Actual behavior

ReferenceError: timeout is not defined

### Steps to reproduce
Run a test (on master) that has an intentional time out and you'll the issue.

The bug is in taiko/lib/taiko.js:3408, perhaps options.navigationTimeoutis meant?

### Versions
master

**Comment by shubhamsc** [comment]
@trein-homeroom Can you provide a simple script where you getting this error?
`ReferenceError: timeout is not defined`

**Comment by trein-homeroom** [comment]
It will happen on any time out.  If you look at the code I pointed to, it's pretty clear it's using an undefined variable.  

Here's a simple script:

await openBrowser();
await goto('https://google.com')
await click('I don't exist')

**Comment by shubhamsc** [comment]
@trein-homeroom  Thanks for pointing the issue, I changed the timeout variable name.
Now it'll print right error message in case of navigation timeout.
