### ISSUE TITLE
How to wait for text on URL and if not, refresh page ?

### ISSUE THREAD

**Issue by jkeks** [getgauge/taiko#924]
### Expected behavior
I Need to detect text on page. 
How to Reload page every 30 sec and then check page for text. And when detected run system command.

### Actual behavior
Cannot do it with accert or wait or text  functions..

**Comment by saikrishna321** [comment]
Install `async-retry`

```
import retry from 'async-retry';

    await retry(
      async () => {
        const res = await text('Something').exists();
        if (!res) {
          await reload();
          throw new Error('Element not found!!');
        }
        return res;
      },
      { retries: 10, factor: 1 },
    );
```

@jkeks Please use https://spectrum.chat/taiko?tab=posts for questions and help.

**Comment by sriv** [comment]
@saikrishna321's solution should work, please comment if it doesn't.
