### ISSUE TITLE
Check code style of every pull request

### ISSUE THREAD

**Issue by zabil** [getgauge/taiko#930]
There is no style check on pull requests. This causes commits to have different code indentations and messes up the diff while trying to understand what changed.

Set style standard on GitHub and verify it against each pull request.

**Comment by sriv** [comment]
we have eslint config in taiko - https://github.com/getgauge/taiko/blob/master/.eslintrc, but I don't see `eslint` being invoked.

gauge-js includes linting as part of tests. Should we do the same here @zabil @nehashri ?

**Comment by zabil** [comment]
Yes, there are two things we might need to do
* A hook that runs eslint before a push
* A bot that checks the PR for formatting.
