### ISSUE TITLE
How to use taiko as part of express application similar to puppeteer

### ISSUE THREAD

**Issue by devilrancy** [getgauge/taiko#935]
I see taiko requires a seperate test runner for executing is there any way I can use it directly in my express app similar to how we use puppeteer.

Ex: In Puppeteer

```const express = require("express");
const app = express();

app.get("/", function(req, res) {
  const puppeteer = require("puppeteer");
  (async () => {
    const browser = await puppeteer.launch({
      args: ["--no-sandbox", "--disable-setuid-sandbox"]
    });
    const page = await browser.newPage();
    await page.goto("https://duckduckgo.com/", {
      waitUntil: "networkidle2"
    });
    await page.type("#search_form_input_homepage", "Puppeteer");
    await page.click("input[type=submit]");
    await page.waitForSelector(".result__a");

    // Extract the results from the page
    const links = await page.evaluate(() => {
      const anchors = Array.from(document.querySelectorAll(".result__a"));
      return anchors.map(anchor => anchor.textContent);
    });
    await browser.close();
    res.send(links.join("\n"));
  })();
});

app.listen(5000, function() {});
```

**Comment by zabil** [comment]
Taiko can be used as a node js library similar to puppeteer. Taiko scripts can be run using the `node` command. Try replacing puppeteer call with Taiko's api in the script above.

**Comment by devilrancy** [comment]
@zabil I tried that but as soon as I try multiple requests at the same time via express API it does not work

**Comment by zabil** [comment]
That's because Taiko's api is not thread safe. You can only call the `openBrowser` once. You need make sure that `closeBrowser` is called before calling the next `openBrowser`. So multiple requests won't work.

**Comment by devilrancy** [comment]
true got you that was the major issue for me although the API is really good could not integrate into our current express based framework which already uses puppeteer extensively.
Do we have any plans further for making it thread-safe for multiple requests?

**Comment by zabil** [comment]
https://github.com/getgauge/taiko/issues/921 should solve it. Ofcourse, all help appreciated.

**Comment by tsachit** [comment]
Is this possible to request taiko script from express or any other nodejs framework? I make small scripts for myself and I like writing in taiko because it has helped me a lot of time. I was trying to fill the form of a website in the background and grab html and display it to the user since api is not available. But looks like taiko is not the right tool for me. Can anyone please guide me if there is a proper way, or should I start learning puppeteer(or any other tool)?
