### ISSUE TITLE
Drop down selection does not work in React apps

### ISSUE THREAD

**Issue by riccardoNovaglia** [getgauge/taiko#936]
Repo with example to reproduce: https://github.com/riccardoNovaglia/taikoselect

### Expected behavior
Selecting from a dropdown causes the value to change

### Actual behavior
The value looks to be selected, but even tho the value in the dropdown looks selected, the app does not respond

### Steps to reproduce
1. checkout repo above, `npm install` top-level and `my-app`
2. start app (`cd my-app`, `npm run start`)
3. manually select from dropdown at the bottom of the page (below "Learn React"), see result update just below
4. run `taiko reproduceIssue.js --observe` and see result not updating

### Versions
```
➜  taikoselect git:(master) ✗ node --version
v12.12.0
➜  taikoselect git:(master) ✗ npm --version
6.12.0
➜  taikoselect git:(master) ✗ taiko --version
Version: 1.0.2 (Chromium: 76.0.3803.0) RELEASE
```

**Comment by Apoorva-GA** [comment]
@riccardoNovaglia This issue has been fixed and available in master but not yet released.
For now you can change the `package.json` file in `taikoselect` folder to the below code which fetched taiko from master and things should work.
```
{
  "name": "taikoselect",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "taiko": "https://github.com/getgauge/taiko"
  }
}
```

**Comment by riccardoNovaglia** [comment]
Amazing, thanks!

**Comment by riccardoNovaglia** [comment]
Any thoughts as to when the next version with the fix might be released?
