### ISSUE TITLE
SwitchTo make taiko unable to interact with the page

### ISSUE THREAD

**Issue by RBLG** [getgauge/taiko#939]
### Expected behavior
After using SwitchTo() taiko should be able to find elements on the current page

### Actual behavior
taiko is unable to find any element on the page using any selector until goto is called

### Steps to reproduce
1. click on a link opening a new tab
2. use switchto() to switch to this tab
3. use click() on any element with any selector (throw element not found)
4. go back to step 2
5. use goto() with the same URL as the current tab
6. repeat step 3 (element is found and taiko click on it)

### Versions
```
taiko: 1.0.2
node: 12.13.0.
```

**Comment by Apoorva-GA** [comment]
@RBLG I could replicate the issue with below scripts. 

Works :
```
const { openBrowser, goto, link, click, closeBrowser } = require('taiko');
(async () => {
    try {
        await openBrowser();
        await goto('https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_link_target');
        await click(link('Visit W3Schools.com!'));
        await goto('https://www.w3schools.com/');
        await click(link('LEARN HTML'));
    } catch (error) {
        console.error(error);
    } finally {
        await closeBrowser();
    }
})();
```
Doesn't work :
```
const { openBrowser, goto, link, click, closeBrowser } = require('taiko');
(async () => {
    try {
        await openBrowser();
        await goto('https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_link_target');
        await click(link('Visit W3Schools.com!'));
        await switchTo('https://www.w3schools.com/');
        await click(link('LEARN HTML'));
    } catch (error) {
        console.error(error);
    } finally {
        await closeBrowser();
    }
})();
```
We will work on fixing this soon. Thanks for reporting.

**Comment by Apoorva-GA** [comment]
This works as expected on [Taiko release 1.0.0](https://github.com/getgauge/taiko/releases/tag/v1.0.0) in case you want, you can revert to 1.0.0 for the fix. 
We will be fixing this soon.

**Comment by zabil** [comment]
This maybe related to https://github.com/getgauge/taiko/issues/940 as electron apps also work on 1.0.0

**Comment by Apoorva-GA** [comment]
Fix available in commit aa29668ca7266d7f46b90c5143bd9f4259579d8f

**Comment by Debashis9012** [comment]
After switching to url we are able to perform the required action on webelement successfully.
Based on the observation this issue has been verified and found fixed.
Tested version:
```
d9a4b6a65628db44301305757a3a5c5ad412c2ce
```

**Comment by Debashis9012** [comment]
This issue has been tested and verified against the master.
Tested version: `9a89e88d65df8744055716483f349b103976784c`

**Comment by JakubSzpak** [comment]
I think its didn't work in
`Version: 1.0.4 (Chromium: 81.0.3994.0) 3c0e34ecf36d90bdb0d329a139ae64e0d0a306e3`
switchTo make taiko unable to interact with the page. However when you change the tab using openTab() and goto(), it makes elements clickable.

**Comment by zabil** [comment]
@JakubSzpak there's a fix for this on the master branch. Can you please install the latest version from master using 

```
npm install https://github.com/getgauge/taiko
```

And check if this works?
