### ISSUE TITLE
Getting exception while writing to a field

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#94]
_From @sguptatw on August 6, 2018 10:9_

**Expected behavior**
Should be able to write into a field without a failure

**Actual behavior**
Getting an exception `(node:213348) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 7)`

**Steps to replicate**
* Set up to run the app `https://openmrs.org/download/`
* Run taiko with the following script
```
const { openBrowser, goto, inputField, into, write, click, text, below } = require('taiko');

(async () => {
    try {
        await openBrowser();
        await goto("http://localhost:8081/openmrs-standalone/referenceapplication/home.page");
        await write("admin",into(inputField({"placeHolder":"Enter your username"})));
        await write("Admin123",into(inputField({"placeHolder":"Enter your password"})));
        await click("Log In");
        await text("You must choose a location!").exists();
        await click("Registration Desk");
        await click("Log In");
        await click("Register a patient");
        await write("First");
        await write("Name",into(inputField(below(text("Middle")))));
        await click("Gender");
        await write("LName",into(inputField(below(text("Family Name")))));
    } catch (e) {
        console.error(e);
    } finally {
        closeBrowser();
    }
})();
```

**Version**
```
taiko - c69ac1f01c1ac25066b806fcbe47d097e675d3c1
```

_Copied from original issue: getgauge/Intellij-Plugin#347_

**Comment by sguptatw** [comment]
_From @gaugebot[bot] on August 6, 2018 10:9_

Thanks for opening this issue!

**Comment by NivedhaSenthil** [comment]
Changing line `await write("LName",into(inputField(below(text("Family Name")))));`
to `await write("LName",into(inputField(below(contains("Family Name")))));`

on clicking element with text 'Gender',  text 'Required' gets added to the field `Family Name` hence doing contains works.

**Comment by sguptatw** [comment]
Yes the script works, but I should not be getting an exception when using text. Furthermore `required` text is in a different span than that of `Family Name` hence tried using text instead of contains.

**Comment by Apoorva-GA** [comment]
@sguptatw tried couple of times, but unable to start OpenMRS.(Getting some spring BeanCreationException).

Could you please try it in demo app if possible?

**Comment by sguptatw** [comment]
I tried with the demo app. But, it has a different flow.

**Comment by nehashri** [comment]
Any updates on this? Is it possible to work with the demo app?

**Comment by sguptatw** [comment]
@nehashri - the demo app has a different flow. Not encountering this error there.
