### ISSUE TITLE
Taiko cannot interact with Electron App

### ISSUE THREAD

**Issue by saikrishna321** [getgauge/taiko#940]
Sample Repo to replicate the problem: https://github.com/saikrishna321/taiko-electron-boilerplate

Run `jest` command to trigger the code.

I enabled chrome proxy to debug the ws calls made to the electron application. I don't see any commands send to dev tools api.

https://gist.github.com/saikrishna321/21aa8ba47d5e6798768dba2b9ac9015b

**Comment by zabil** [comment]
https://github.com/saikrishna321/taiko-electron-boilerplate works with Taiko 1.0.0

**Comment by Apoorva-GA** [comment]
Fixed as part of https://github.com/getgauge/taiko/issues/939. 
@saikrishna321 Please verify.

**Comment by saikrishna321** [comment]
Fixed 🎉 

![giphy (1)](https://user-images.githubusercontent.com/4045041/69555923-d2405380-0f9b-11ea-88b3-72f61b9ef65c.gif)
