### ISSUE TITLE
textBox not identifying angular input textbox but textField identifying the control with Deprecation warning

### ISSUE THREAD

**Issue by srajkavithaa** [getgauge/taiko#941]
### Expected behavior
Need to identify username control which is from an Angular application using "textBox" selector

### Actual behavior
textBox not identifying angular input textbox but textField identifying the control with Deprecation warning
 _**textbox:**_
Command: write("catchsystemadmin", into(textBox({name:"username"})))
Error:
[FAIL] Error: Text field[@name = concat('username', "")] not found, run `.trace` for more info.
**_inputField:_**
> write("catchsytemadmin@catchsoftware.com", into(inputField({id:"username"})))
DEPRECATION WARNING: inputField is deprecated, use textBox api instead
[PASS] Wrote catchsytemadmin@catchsoftware.com into the input field[@id = concat('username', "")]

### Versions
```
Version: 1.0.2 (Chromium:76.0.3803.0)
```

**Comment by Debashis9012** [comment]
@srajkavithaa I am able to replicate the same. Here is the below code:

```
const { openBrowser, goto, click, textBox,write, into, closeBrowser } = require('taiko');
(async () => {
    try {
        await openBrowser();
        await goto("https://catchsoftware.com/");
        await click("CONTACT US");
        write('xyz',into(textBox({id:'first_name'})))
    } catch (error) {
        console.error(error);
    } finally {
        await closeBrowser();
    }
})();
```
Please feel free to add your comments if i missed out any information.

Tested version:
`Version: 1.0.3 (Chromium: 79.0.3945.16) 920b467de1f1dfc55780dc5a6d7c81c3bd42ce5e`

**Comment by Apoorva-GA** [comment]
`write` is an async function so await should be added.
```
const { openBrowser, goto, click, textBox,write, into, closeBrowser } = require('taiko');
(async () => {
    try {
        await openBrowser();
        await goto("https://catchsoftware.com/");
        await click("CONTACT US");
        await write('xyz',into(textBox({id:'first_name'})))
    } catch (error) {
        console.error(error);
    } finally {
        await closeBrowser();
    }
})();
```
The above script works as expected.

**Comment by srajkavithaa** [comment]
Hi Apoorva, thanks for your comments, but the problem I am facing is to identify an angular control which is having an id & name fields. 
**This is my control:**
<mat-form-field _ngcontent-lbv-c3="" class="full-width mat-form-field ng-tns-c4-0 mat-primary mat-form-field-type-mat-input mat-form-field-appearance-legacy mat-form-field-can-float mat-form-field-has-label mat-form-field-hide-placeholder ng-pristine ng-invalid mat-form-field-invalid ng-touched"><div class="mat-form-field-wrapper"><div class="mat-form-field-flex"><div class="mat-form-field-infix"><input _ngcontent-lbv-c3="" class="mat-input-element mat-form-field-autofill-control cdk-text-field-autofill-monitored ng-pristine ng-invalid ng-touched" **id="username"** matinput="" **name="username"** placeholder="Username" required="" type="textbox" aria-invalid="true" aria-required="true"><span class="mat-form-field-label-wrapper"><label class="mat-form-field-label ng-tns-c4-0 mat-empty mat-form-field-empty ng-star-inserted" id="mat-form-field-label-1" for="username" aria-owns="username">Username<span aria-hidden="true" class="mat-placeholder-required mat-form-field-required-marker ng-tns-c4-0 ng-star-inserted"> *</span></label></span></div></div><div class="mat-form-field-underline ng-tns-c4-0 ng-star-inserted"><span class="mat-form-field-ripple"></span></div><div class="mat-form-field-subscript-wrapper"><div class="mat-form-field-hint-wrapper ng-tns-c4-0 ng-trigger ng-trigger-transitionMessages ng-star-inserted" style="opacity: 1; transform: translateY(0%);"><div class="mat-form-field-hint-spacer"></div></div></div></div></mat-form-field>

**and I used this command and got the error:**
 await write("catchsytemadmin@catchsoftware.com", into(textBox({id:"username"})))
[FAIL] Error: Text field[@id = concat('username', "")] not found, run `.trace` for more info.

**But inputField is working fine for me :) :(**
> write("catchsytemadmin@catchsoftware.com", into(inputField({id:"username"})))
DEPRECATION WARNING: inputField is deprecated, use textBox api instead
[PASS] Wrote catchsytemadmin@catchsoftware.com into the input field[@id = concat('username', "")]

Please check and help,
Thanks,
Kavitha

**Comment by Apoorva-GA** [comment]
@srajkavithaa In your case the input type is `textbox`, which is not a standard input type. Hence it is not supported by the `textBox` api of Taiko.

Note: `inputField` works because it matches anything with an input tag.

**Comment by srajkavithaa** [comment]
Hi Apoorva, thanks for the update, As "inputField" mentioned as deprecated, is there any time limit for that and may I know what is the alternative going forward to support all controls with input tag. Thanks again.

**Comment by zabil** [comment]
Unfortunately there won't be replacement api for non standard elements. It's best to use normal [Xpath, css or id selectors](https://taiko.gauge.org/#dollar) for this case.
