### ISSUE TITLE
How to click a radio button based on it's name & value?

### ISSUE THREAD

**Issue by SKMA81** [getgauge/taiko#943]
I have 3rd party generated form,  and the 'Yes' / 'No' options are the below inputs:

Yes
`<input type="radio" id="selfEmploymentYesNo-0-AF-Field-d95400cc-bc8e-4f5c-b698-bd7ec7f50141-9b2c8f2264" name="selfEmploymentYesNo" value="Y" required="true" class="radio2 " autocomplete="off">`

No
`<input type="radio" id="selfEmploymentYesNo-1-AF-Field-d95400cc-bc8e-4f5c-b698-bd7ec7f50141-9b2c8f2264" name="selfEmploymentYesNo" value="N" required="true" class="radio2 " autocomplete="off">`

I'm able to select the radiobutton via the id using:
`radioButton({id:'selfEmploymentYesNo-1-AF-Field-d95400cc-bc8e-4f5c-b698-bd7ec7f50141-9b2c8f2264'}).select()`

But unfortunately, the field id changes each time the form is generated, so cannot be used.

Is it possible to select a radio button based on the name & value? 

Thank you

### Versions
```
node 10.16.3
taiko 1.0.2
```

**Comment by Apoorva-GA** [comment]
@SKMA81 Yes, you can select a radio button based on name and value. Something like below should work.
`radioButton({name:'selfEmploymentYesNo', value:'N'}).select();`

**Comment by SKMA81** [comment]
Ah of course! 

Thank you this works perfectly!

**Comment by varunr-uc** [comment]
<md-radio-button value="0" id="radio_18" role="radio" aria-checked="false" aria-label="No" class="">
not able to select the radio button
help me with this

**Comment by varunr-uc** [comment]
<md-radio-button value="0" id="radio_18" role="radio" aria-checked="false" aria-label="No" class="">

not able to select radio button. help me with this.

**Comment by varunr-uc** [comment]
<md-radio-button value="0" id="radio_18" role="radio" aria-checked="false" aria-label="No" class=""> not able to selct radio button
