### ISSUE TITLE
Integration with Lighthouse fails

### ISSUE THREAD

**Issue by saikrishna321** [getgauge/taiko#944]
Lighthouse provides a node.js module to get performance audits on given page. I'm working on getting this integrated into  [taiko-diagnostics](https://github.com/saikrishna321/taiko-diagnostics)

LH opens a new tab and performs audit on the given URL and closes the tab. Now Taiko hangs on `closeBrowser()` API  at 👇 

https://github.com/getgauge/taiko/blob/37d0345338815d2bbafae849f079c625184839f5/lib/taiko.js#L298

Code Snippet:

```
const puppeteer = require('puppeteer');
const commonMethods = require('./audits');

const { openBrowser, closeBrowser, client , goto} = require('taiko');

let lhr;
let port;

beforeAll(async () => {
   await openBrowser({headless: false });
  port = await client().webSocketUrl.split('/devtools/')[0].replace('ws://', '').split(':')[1];

});
afterAll(async () => {
  await closeBrowser();
});

describe('Google Lighthouse audit tests', async () => {
  beforeAll(async () => {
    const url = 'https://example.com';
    // kick off a Lighthouse audit on the above url
    lhr = await commonMethods.lighthouseAudit(url, port);
  });

  // General accessibility overview score
  it('passes an accessibility audit through Lighthouse', async () => {
    const accessibilityScore = await commonMethods.getLighthouseResult(
      lhr,
      'accessibility'
    );
    expect(accessibilityScore).toBeGreaterThanOrEqual(90);
  });
```

Can someone please help with this?

**Comment by zabil** [comment]
Since Taiko only used to open and close the browser a possible or simpler [workaround](https://github.com/GoogleChrome/lighthouse/blob/master/docs/readme.md) is to use the `chrome-launcher` to run the lighthouse tests.

**Comment by saikrishna321** [comment]
@zabil Thanks for the response. In my case, I need to use LH as part of `taiko` tests as the URL which I want to run the Audit gets authenticated from keycloak and `currentURL()` api from Taiko would help me for this and I will pass that to LH.  For this reason, `chrome-launcher` won't help me.


Findings:

As mentioned above 
> LH opens a new tab and performs audit on the given URL and closes the tab.

After calling `openBrowser` webSocketURL: `ws://127.0.0.1:52703/devtools/page/8BB44A8BD801155315436F397737347F`

At this stage a new CRI connection is created by LH and the target is switched. After running LH Audit when I look at the available targets using cri.List 

```
{ matching:
       [ { description: '',
           devtoolsFrontendUrl:
            '/devtools/inspector.html?ws=127.0.0.1:52703/devtools/page/8BB44A8BD801155315436F397737347F',
           faviconUrl: 'https://taiko.gauge.org/assets/images/taiko_favicon.ico',
           id: '8BB44A8BD801155315436F397737347F',
           title: 'Taiko, free and open source browser automation',
           type: 'page',
           url: 'https://taiko.gauge.org/',
           webSocketDebuggerUrl:
            'ws://127.0.0.1:52703/devtools/page/8BB44A8BD801155315436F397737347F' } ],
      others: [] }
```

In the afterAll hooks 

```
afterAll(async () => {
  console.log(await client().webSocketUrl); ==> ws://127.0.0.1:52703/devtools/page/957A2888836B82D3DB7362003FC86DE2
  console.log(await client().target);  ==> { description: '',
      devtoolsFrontendUrl:
       '/devtools/inspector.html?ws=127.0.0.1:52703/devtools/page/957A2888836B82D3DB7362003FC86DE2',
      id: '957A2888836B82D3DB7362003FC86DE2',
      title: '',
      type: 'page',
      url: 'about:blank',
      webSocketDebuggerUrl:
       'ws://127.0.0.1:52703/devtools/page/957A2888836B82D3DB7362003FC86DE2' }
  
  await closeBrowser(); ==> Hangs because the client() target has changed which was created by LH.

});
```

Fix: connect to the existing target and then close the browser. Call `reconnect()` api 👇 

https://github.com/getgauge/taiko/blob/d9a4b6a65628db44301305757a3a5c5ad412c2ce/lib/taiko.js#L297

**Comment by zabil** [comment]
Assuming this fixed. It's there in the release.
