### ISSUE TITLE
Should not consider case while matching text by default

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#95]
**Proposed behavior**
Text match should be case-insensitive matching.

**Actual behavior**
When css is used to make something to uppercase or lower case, what is rendered on the UI is different from what is in the DOM. Today, Taiko considers the case of the word while matching. 

**Steps to replicate**
* Run the script
```
const { openBrowser, goto, text, click, below } = require('taiko');

(async () => {
    try {
        await openBrowser();
        await goto("https://react-shopping-cart-67954.firebaseapp.com/");
        await click(text("M"));
        await click("Add to cart",below("Dark Thug Blue-Navy T-Shirt"));
        console.log(await text("CHECKOUT").exists())
    } catch (e) {
        console.error(e);
    } finally {
        closeBrowser();
    }
})();
```
> The text is rendered as `CHECKOUT` in the browser but it is `Checkout` in the DOM. Hence taiko is returning that the element does not exist

**Version**
```
commit - f2a3d59d69cc4361fc67f3914d2049f7d20c4965

Tue Aug 7 09:59:55 2018 +0530
```

**Comment by Apoorva-GA** [comment]
Fix should be available in commit f026e93.
