### ISSUE TITLE
Taiko can't find elements inside a shadow DOM

### ISSUE THREAD

**Issue by jakobheine** [getgauge/taiko#952]
### Expected behavior
Taiko should be able to find elements which are inside a shadow DOM element.

### Actual behavior
Taiko does not find elements inside a shadow DOM element, it only gets the elements outside of the shadow DOM element.

### Steps to reproduce
1. Use a shadow DOM web-component inside your frontend. (we use the default shadow DOM tree rendering from LitElement)
2. Run taiko
3. Try to find an element inside your shadow DOM web-component with Taiko

### Versions
LitElement: 2.2.1
Taiko 1.0.2
Node 12.13.0

**Comment by zabil** [comment]
Adding a sample HTML page that uses shadow DOM to render a button.
Taiko does not locate the button currently, it should as to a user it is a button.

```
<html>
	<script>
		class ShadowButton extends HTMLElement {
			constructor() {
				super();

				var button = document.createElement('input');
				button.setAttribute('type', 'button');
				button.setAttribute('value', 'Shadow Click');

				var shadow = this.attachShadow({mode: 'open'});
				shadow.appendChild(button);
			}
		}

                customElements.define('shadow-button', ShadowButton);
	</script>
	<body>
		<shadow-button/>
	</body>
</html>

```

Sample Taiko script

```
const { openBrowser, goto, closeBrowser } = require('taiko');
(async () => {
    try {
        await openBrowser();
        await goto("http://localhost:8000");
        await click("Shadow Click");
    } catch (error) {
        console.error(error);
    } finally {
        await closeBrowser();
    }
})();
```

**Comment by zabil** [comment]
The workaround right now is to use the evaluate API. For example the following HTML

```
<html>
  <script>
    class ShadowButton extends HTMLElement {
      constructor() {
        super();

        var button = document.createElement('input');
        button.setAttribute('type', 'button');
        button.setAttribute('value', 'Shadow Click');
        button.addEventListener("click", event => {
          alert("Hello from the shadows");
        });

        var shadow = this.attachShadow({mode: 'open'});
        shadow.appendChild(button);
      }
    }

    customElements.define('shadow-button', ShadowButton);
  </script>
  <body>
    <shadow-button/>
  </body>
</html>

```

Will work with the script

```
const { openBrowser, goto, closeBrowser } = require('taiko');
(async () => {
  try {
    await openBrowser();
    alert('Hello from the shadows', async () => await accept())
    await goto("localhost:3000");
    await evaluate($("shadow-button"), (element) => {
      element.shadowRoot.querySelector("input").dispatchEvent(new Event("click"));
    })
  } catch (error) {
        console.error(error);
    } finally {
        await closeBrowser();
    }
})();

```

**Comment by spinningarrow** [comment]
Here's a project that tries to solve this for Cypress: https://github.com/abramenal/cypress-shadow-dom#readme. It adds APIs like `shadowGet` which works, although ideally it would be nice to have the existing APIs work for this.

**Comment by zabil** [comment]
Unfortunately, the only feasible way to implement this is have a parallel api `shadowClick` etc, much like the cypress samples shared above.

Closing this for now as it won't be implemented in the core. Maybe someone can give a shot at writing a shadow dom plugin.

**Comment by NivedhaSenthil** [comment]
Taiko now has support for piercing through shadow dom.. do try updating to version 1.0.19 and let know if there are any feedback.
