### ISSUE TITLE
Load local html file full support

### ISSUE THREAD

**Issue by jecsham** [getgauge/taiko#954]
### Expected behavior
Load local html file in the browser and finish the process.

### Actual behavior
Load local html file in the browser but the process never end.

### Steps to reproduce
**Code:** 
```js
await openBrowser();
await openTab(`file://${path.resolve(__dirname, "site/checktx.html")}`.replace(/(\s+)/g, '%20'),
            {
                navigationTimeout: 10000
            }) // using replace here because I have space in the dir path
closeBrowser();
```
**Ouput:**
`[PASS] Browser opened`
Then navigate to the local site and its all, the process never end.
### Versions
```
node v10.15.3
taiko Version: 1.0.2 (Chromium: 76.0.3803.0) RELEASE
```

**Comment by jecsham** [comment]
### Temp solution
Use method `openTab()` instead `goto()`.

```js
await openTab(`file://${path.resolve(__dirname, "site/checktx.html")}`.replace(/(\s+)/g, '%20'),
            {
                navigationTimeout: 10000
            }) 
```

**Comment by negiDharmendra** [comment]
@jecsham I have tried with the Taiko's latest and the version you are on and every thing works fine.
Can you share a sample project or script to replicate it.
