### ISSUE TITLE
taiko REPL not working with Windows 10

### ISSUE THREAD

**Issue by kimr01** [getgauge/taiko#956]
### Expected behavior
TEST 1:
My Os is Wondows 10 - 64x
1. Node.js and npm is installed :node = v12.13.0  npm = 6.12.0
2. Followed taiko installation ( https://taiko.gauge.org/  Quick Installation
   npm install -g taiko
   installed sucessfully
3. from cmd
  C:users\richa\taiko
  It should launch taiko REPL

See image1

TEST2:
After reading #618 Taiko REPL Doesnot working Issue ticket, where solution was suggested
Follow instructions

See Image 2

### Actual behavior
TEst 1. Result : Not working

C:\Users\richa>taiko --version
'taiko' is not recognized as an internal or external command,
operable program or batch file.
![taikoError-taikoNoRecognsed-test1](https://user-images.githubusercontent.com/3803389/70383261-82ca3200-1962-11ea-9954-9f7166538e29.GIF)

TEst 2. Result : Not working

C:\Users\richa>taiko --version
'taiko' is not recognized as an internal or external command,
operable program or batch file.

![taikoError-taikoNoRecognsed_2#618-test2](https://user-images.githubusercontent.com/3803389/70383274-e0f71500-1962-11ea-92d1-ee7964743c79.GIF)

### Steps to reproduce
1. Use OS - Windows 10  - 64 bit
2. Node.js and npm installed - node = v12.13.0  npm = 6.12.0
3. run taiko

### Versions
node = v12.13.0  npm = 6.12.0
`taiko`  = 1.0.2`  and 1.0.3`

**Comment by nehashri** [comment]
I think you have not set the global nodejs libraries to your PATH. Hence, the taiko executable is not found. Please set your path to include %USERPROFILE%\AppData\Roaming\npm (or wherever npm modules was installed). This should solve your problem.

**Comment by kimr01** [comment]
Hi Nehashri

Great support - much appreciated !
Resolved. Please close this ticket.

Regards
Richard


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kimr01** [comment]
RESOLVED
set  user environment path to include %USERPROFILE%\AppData\Roaming\npm
