### ISSUE TITLE
Unable to click on an element which is covered by other element.

### ISSUE THREAD

**Issue by sanjeeth-07** [getgauge/taiko#958]
### Expected behavior
The element should receive a click.
Tried with this alternate function , but it does not work.
`await evaluate(text("XYZ"), ele => ele.click());`

### Actual behavior
  Error Message: Error: Element matching text "XYZ" is covered by other element
  Stacktrace: 
  Error: Element matching text "XYZ" is covered by other element

### Versions
```
node - v10.15.3
"taiko": "latest"
```

**Comment by nehashri** [comment]
@sanjeeth-07 It is not possible to click on a element covered by another element by default. 
You should be able to do this via evaluate though.
However, I think you are not fetching the correct element to click on. The `text` API may not return the element you want to actually click on, but just the text part of it. I suggest you try using a more concrete selector instead.

A sample 
```
await openBrowser();
await goto("google.com");

# this works 
await evaluate(link("Sign In"), ele => ele.click()); 

# but this doesn't work
# await evaluate(text("Sign In"), ele => ele.click());
```

**Comment by sanjeeth-07** [comment]
@nehashri  thanks for the info. It works as expected.

**Comment by sanjeeth-07** [comment]
This is more of a permanent solution for the above. Adding  `waitFor()` before subsequent clicks.
`await waitFor(1000) `
