### ISSUE TITLE
Taiko function to click 'OK' on browser validation message

### ISSUE THREAD

**Issue by adea11** [getgauge/taiko#959]
Please is there a way to click 'OK' on browser validation message

```

**Comment by nehashri** [comment]
@adea11 I cannot understand what you mean by browser validation message. Can you please eloborate? Or provide a sample html to see what you would like to achieve?

**Comment by adea11** [comment]
So on clicking a button I on a web app, I get validation message on which I need to click 'OK' in order to proceed on the page. See screen shot attached 
<img width="454" alt="Screenshot 2019-12-09 at 10 42 12 AM" src="https://user-images.githubusercontent.com/49438334/70434488-3f63e680-1a7c-11ea-81e8-e00cad7d9fec.png">

**Comment by adea11** [comment]
FYI @nehashri

**Comment by zabil** [comment]
@adea11 unfortunately, your question is still not clear. How is this validation message displayed? Is this plain html? Or an alert style pop up box. 

This looks like question. The best place for questions is https://spectrum.chat/taiko/general?tab=posts

Closing it, but please feel free to discuss it here for now. Or even better if you post it to https://spectrum.chat/taiko/general?tab=posts with more details.
