### ISSUE TITLE
Add option for base64 encoded screenshot

### ISSUE THREAD

**Issue by zabil** [getgauge/taiko#96]
### Current behavior

There's no way to get a base64 encoding of the screenshot from the `screenshot` api. This is useful for working with other runners like Gauge because a custom screenshot handler returns a base64 encoding.
 
### Expected Behavior

Introduce an api

```
screenshot({encoding:'base64'})
```

That will return the screenshot in the specified encoding. I recommend making this the default.

For e.g.

```
screenshot()
```

Returns the screenshot in base64 encoding instead of saving a temporary file.

This will make using taiko with Gauge as simple as.

```
gauge.screenshotFn = function () {
    return screenshot();
};
```

For custom paths

```
screenshot({path: '<path>'})
```

**Comment by zabil** [comment]
> I recommend making this the default.

On second thoughts this won't work in the REPL. 
Hence the current default behavior is right. for e.g.

```
> screenshot()
 ✔ Screenshot is created at "Screenshot-1533634891735.png"
```

**Comment by NivedhaSenthil** [comment]
51de58a this makes the option to be given as `{encoding:'base64'}` to make it explicit and avoid redundancy.
