### ISSUE TITLE
Cannot attach file to hidden fileField

### ISSUE THREAD

**Issue by ejlax** [getgauge/taiko#979]
### Expected behavior
when running:
`attach('/Users/eadams/code/Tests/gauge/resources/files/test.csv', fileField({id: 'file-input'},{selectHiddenElement: true}))` 

It should attach file to the fileField.

### Actual behavior

Attempting to attach a file to a fileField but getting error:
`attach('/Users/eadams/code/Tests/gauge/resources/files/test.csv', fileField({id: 'file-input'},{selectHiddenElement: true}))`
`✘ Error: Could not compute box model., run `.trace` for more info.`

```Error: Could not compute box model.
    at _enqueueCommand (/Users/eadams/ops/taiko/node_modules/chrome-remote-interface/lib/chrome.js:93:35)
    at Chrome._handleMessage (/Users/eadams/ops/taiko/node_modules/chrome-remote-interface/lib/chrome.js:256:17)
    at WebSocket._ws.on (/Users/eadams/ops/taiko/node_modules/chrome-remote-interface/lib/chrome.js:234:22)
    at WebSocket.emit (events.js:182:13)
    at WebSocket.EventEmitter.emit (domain.js:460:23)
    at Receiver.receiverOnMessage (/Users/eadams/ops/taiko/node_modules/ws/lib/websocket.js:800:20)
    at Receiver.emit (events.js:182:13)
    at Receiver.EventEmitter.emit (domain.js:460:23)
    at Receiver.dataMessage (/Users/eadams/ops/taiko/node_modules/ws/lib/receiver.js:423:14)
    at perMessageDeflate.decompress (/Users/eadams/ops/taiko/node_modules/ws/lib/receiver.js:380:23)
```

The field is found and exists when running:
` fileField({id: 'file-input'},{selectHiddenElement: true}).exists()
 value: true
 ✔ Exists`

### Steps to reproduce
1. Run attach() with a hidden File Field element

### Versions
```
Taiko: Version: 1.0.3 (Chromium: 81.0.3994.0) RELEASE
Node: v10.13.0
```

**Comment by sriv** [comment]
html to verify this issue:

```
<html>
<body>
    <h6 >Upload Files</h6>
    <div >
        <input type="file" id="file-input" style="display: none;">
        <button >
            <span>Add Files</span>
        </button>
    </div>
</body>
</html>
```

Note: with master it errors out stating `Uncaught s.match is not a function`

**Comment by sriv** [comment]
@ejlax - we just released taiko 1.0.3 and it includes some fixes/changed. with this version, I am able to locate the filefield with the below script:

```
const { openBrowser, goto, closeBrowser, fileField } = require('taiko');
(async () => {
    try {
        await openBrowser();
        await goto('file:///tmp/foo/index.html');
        await fileField({id: 'file-input'}, {selectHiddenElement : true}).exists();
    } catch (error) {
        console.error(error);
    } finally {
        await closeBrowser();
    }
})();
```

Please try against your application and let us know.

**Comment by RorryKelly** [comment]
Hello, I am dealing with different HTML that ejlax but I am getting the same error around attaching files to hidden filefields. If I were run `await fileField({id: 'file-input'}, {selectHiddenElement : true}).exists();` it works fine and returns true, but when I try to use the same fileField with attach() it returns the error `Could not compute box model`

**Comment by sriv** [comment]
Hi @ejlax @RorryKelly  - I believe this behaviour is because `taiko` attempts to highlight the affected element in a red box, and in this case it fails to get the coordinates of the element because it is hidden.

A few points to note:
- your script would most likely work (unless you run with the `--observe` flag)
- your REPL will fail since it tries to highlight the element being acted upon
- as a temporary workaround, you can set `TAIKO_HIGHLIGHT_ON_ACTION=false` when you launch the REPL (or run with `--observe`). This will turn off the element highlighting, which while not ideal would let you proceed without erroring out.

We'll try to make taiko recognize a hidden element and bypass the attempt to highlight it as a fix.

**Comment by negiDharmendra** [comment]
@ejlax @sriv the culprit in released version of taiko https://github.com/getgauge/taiko/blob/d71b7ef745d989378dde8828a429003965fc7d3d/lib/taiko.js#L3471

culprit in master branch of taiko https://github.com/getgauge/taiko/blob/a86ad46a23cbe2eb04c4707e9b2baa2a796df885/lib/elements/elementHelper.js#L16

It should through an error when an element is visible but should print a warning when an element is not visible.
