### ISSUE TITLE
How to keep browser state

### ISSUE THREAD

**Issue by zhaoyao91** [getgauge/taiko#983]
I noticed every time taiko runs, it opens a refresh window, even if I set path to use the pre-installed chrome.

Is there a way to open a window with previous state? such as history, cookie, user login, etc...

Or, if it can open window with the default user profile, which certainly has the user state.

### Versions
```
Taiko Version: 1.0.3 (Chromium: 81.0.3994.0) RELEASE
Node: v12.14.0
```

**Comment by sriv** [comment]
have you tried using a custom profile directory? 

Something like `openBrowser({args:["--user-data-dir" : "/some/profile/path"]})` should preserve browser state in the directory mentioned.

**Comment by sriv** [comment]
> Or, if it can open window with the default user profile, which certainly has the user state.

This is possible only if the default user profile's directory is passed into `openBrowser` via `--user-data-dir` arg. By default taiko launches a new profile for every run, to avoid any undesired side-effects caused by sharing states between tests/runs.

**Comment by zhaoyao91** [comment]
@sriv strangely, according to [this article](https://chromium.googlesource.com/chromium/src/+/master/docs/user_data_dir.md#mac-os-x), i passed the `--user-data-dir=/Users/******/Library/Application Support/Google/Chrome` argument, hoping it would use my default profile.

It it open a new tab and suddenly failed with `Error: Failed to launch chrome!`

**Comment by sriv** [comment]
I can see that working well. (I'm on linux, so the default user-data-dir is `~/.config/google-chrome`, from the same reference you posted).

So here's how I use the `openBrowser`:

`openBrowser({args:["--user-data-dir", "/home/<my_username>/.config/google-chrome"]})` and I can see history, login etc persisted between script runs.

Note that you need to pass `--user-data-dir` and the directory as two entries in the array and not `--user-data-dir=<some_path>`

**Comment by zhaoyao91** [comment]
@sriv hi, I found sth here.

First, it seems we should use `--user-data-dir=xxx` instead of separate args, see https://github.com/getgauge/taiko/blob/master/lib/taiko.js#L268

Then, if I just specify `--user-data-dir` without any `=` or second arg, it will just open the browser with default profile, but just failed the node app immediately.

Finally, I am using macos.

**Comment by sriv** [comment]
hii @zhaoyao91 -

you are right. the syntax is indeed  `openBrowser({args:["--user-data-dir=/home/<my_username>/.config/google-chrome"]})`

I'll let someone in @getgauge/core with access to macOS check this, since it works well on linux for me.

In my incorrect use, it was dropping to the default profile. Silly of me to assume it worked. I checked again with a custom profile directory and by passing `--user-data-dir=/some/path` I was able to see cookies etc persisted.

**Comment by negiDharmendra** [comment]
@zhaoyao91 I am on macos, and it works fine.

By passing `--user-data-dir` arg as`openBrowser({args:["--user-data-dir=<path-to-user-data-dir>"]})` I was able persist my github login session, history and cookies accross browser sessions.

**Comment by zhaoyao91** [comment]
@negiDharmendra yes, if the dir is a custom dir, it will persist browser state here. My problem is, in case I have already installed chrome, and I want to start taiko with the default user profile of the chrome, I found the user-data-dir is `/Users/******/Library/Application Support/Google/Chrome`. But this won't work, it just open a new tab and then failed.

**Comment by negiDharmendra** [comment]
@zhaoyao91 Just make sure that there is no chrome instance before running the taiko script.

**Comment by sriv** [comment]
@zhaoyao91 - were you able to sort this out?

**Comment by zhaoyao91** [comment]
@sriv sorry, our project have switch to raw pupeteer for months and the project have been taken by other co-woker, so currently I am not following this issue :(

**Comment by sriv** [comment]
@zhaoyao91 - cool! Thanks for the update.
