### ISSUE TITLE
how to pass username and password to the website?

### ISSUE THREAD

**Issue by kunaguvarun** [getgauge/taiko#986]
### Expected behavior
when I open my website using goto(), how can I pass my credentials with which the site must be logged in? when I open the page manually without taiko, I can enter them on the small popup and site opens fine but when I try to do that with taiko, the page hangs and I do not see the auth popup. How can I get my header token that is to be passed to the goto?

### Actual behavior
How to pass my credentials to the goto method?

### Steps to reproduce
1.Launch any website that requires auth using goto()
2.The popup window doesn't appear

### Versions
```
node - v12.13.1
taiko latest
```

**Comment by kunaguvarun** [comment]
my question is all about how to interact with the small pop up dialog that appears on visit? The popup can be seen at issue #355

**Comment by sriv** [comment]
> my question is all about how to interact with the small pop up dialog that appears on visit? 

That popup cannot be automated AFAIK. But the good news is that the popup suggests that your app is using HTTP Basic Authentication. 

Please see if this example is relevant: https://github.com/getgauge/taiko/blob/master/examples/06-basic-auth.js

**Comment by kunaguvarun** [comment]
thanks, I tried basic authentication with my site but I was still unauthorized.

**Comment by sriv** [comment]
I guess we would need more input to research this further. Do you have any sample application that mimics the behaviour of your app?

**Comment by kunaguvarun** [comment]
sorry no. there is no sample website to mimic. This is an intranet web application.

**Comment by sriv** [comment]
I'm afraid without some hint to replicate the issue, there's nothing more we can do at this point. Sorry.

I'm closing this, but if you figure out a way to share a case which replicates your issue, please do comment, and we can perhaps then investigate.
