### ISSUE TITLE
Action on event

### ISSUE THREAD

**Issue by mantralayaguru** [getgauge/taiko#987]
### Expected behavior
I could not find a way in Taiko to act on some event/status. For example in my application when the user logs in, the application opens up. However at times due to security, the application pops screen for validation of email or option to "remind later". In Selenium, I can find the title and if the title matches some text, I can do the required step, else continue. How can this be achieved in Taiko?

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Versions
```
Paste `node` and `taiko` versions here.
```

**Comment by moogleberry** [comment]
If there is a predictable trigger for your popup, you can add a step that detects the popup with a selector and using `.exists()`, then saving that to a variable for evaluation at any time.  Though, I imagine you wouldn't want to go through this in every test, in which case you could manage your test case's state to prevent running into the popup at unpredictable times.

**Comment by sriv** [comment]
also discussed here: https://spectrum.chat/taiko/general/how-to-handle-rare-screens~f72b9dc1-4fa8-4c52-be06-53fbe388152d

**Comment by mahesh-narvar** [comment]
Nope, the trigger of pop up is not predictable. It is dynamic in nature.

**Comment by Debashis9012** [comment]
As of now, we can suggest you handle the pop up by adding logic in the login scenario as it is dynamic in nature. 
You can find more details here [Events api](https://taiko.gauge.org/#alert).
Also we are requesting you to share a sample of code to replicate the same scenario.

**Comment by sriv** [comment]
Closing this. Feel free to reopen/comment if you have any details that can help replicate this issue.
