### ISSUE TITLE
Not friendly with webpack

### ISSUE THREAD

**Issue by zhaoyao91** [getgauge/taiko#988]
I try to use taiko as a feature of an electron app which is created with electron-forge ts webpack template.

After bundling, it crashed. First, the `package.main` refer to a bin file which contains `#` symbol, which is not a valid js symbol.

After fixing this by import from `taiko/lib/taiko`, it crashed again, since it requires package.json to get the chromium revision, but after bundling, it cannot find package.json.

I stopped here and switched to use puppeteer-core instead, since taiko seems not been built as a general library, but has some assumption about the runnning environment.

I like taiko's easy api than puppeteer, if they will work in my case, I'd glad to use it to replace puppeteer. Thanks for you guys' great job~

### Versions
```
Taiko Version: 1.0.3 (Chromium: 81.0.3994.0) RELEASE
Node: v12.14.0
```

**Comment by sriv** [comment]
Do you have an example project where importing taiko as a lib fails? We'd like taiko to behave with module loaders, so if there's anything to improve it's good to know. thanks.

**Comment by zhaoyao91** [comment]
Currently no, but I can build one in my spare time.
Another design to make it not good as a lib is the auto-chromium-downloading. Refer to puppeteer-core, it would not do this automatically but instead exposes an api to enable you if you wish.

**Comment by sriv** [comment]
Makes sense. I guess that would involve breaking taiko into sub-package, so that the repl can continue to download chromium, whereas the `core` can expose the functionality.

**Comment by zhaoyao91** [comment]
@sriv 
https://github.com/zhaoyao91/demo-electron-taiko-bug

**Comment by zabil** [comment]
@zhaoyao91 #1408 fixes this issue to raise the right error.
You can try the change along with changing 

https://github.com/zhaoyao91/demo-electron-taiko-bug/blob/da0d9312facaf3a558afd2c5167cf220d8354045/src/try-taiko.ts#L7

To 

```
process.env.TAIKO_BROWSER_PATH = chromePaths.chrome;
```

> Another design to make it not good as a lib is the auto-chromium-downloading. Refer to puppeteer-core, it would not do this automatically but instead exposes an api to enable you if you wish.

You can skip downloading chromium by setting the environment variable 
```
TAIKO_SKIP_CHROMIUM_DOWNLOAD=true
```
