### ISSUE TITLE
Is Clickable / To Be Clickable

### ISSUE THREAD

**Issue by moogleberry** [getgauge/taiko#995]
### Expected behavior
Would like to have a function for determining if an element is currently clickable (alternatively, is covered).  This would be helpful with the waitFor function to wait out arbitrary animations such as modals closing, sliding effects, or temporarily disabled items (eg during validation).

I was hoping to find something like [Protractor's ExpectedConditions.elementToBeClickable ](https://www.protractortest.org/#/api?view=ProtractorExpectedConditions.prototype.elementToBeClickable)

### Versions
```
1.0.3
```

**Comment by djfbryant** [comment]
Also having this issue where our spinner prevents elements being clickable for its duration.

**Comment by zabil** [comment]
This is a convienient API but may affect test readability. For e.g. without the API the test looks like.

```
await waitFor(!text("Modal window").exists())
await click("Element that was covered by a modal window")
```

This test clearly explains the functionality and with explicit dependency on the modal window.

On the other hand with a `isClickable` the test may end up looking like

```
await waitFor(text("Element that was covered by a modal window (or spinner)").isClickable())
await click("Element that was covered by a modal window (or spinner)")
``` 

It does not explain why the element is not clickable. Failures may be hard to debug. I recommend this not being a part of the core. That said, it could be implemented as a function or a plugin. 

Closing this for now, but please feel to carry on the discussion around this.

**Comment by moogleberry** [comment]
```
await waitFor(!text("Modal window").exists())
await click("Element that was covered by a modal window")
```
If this fails and says that "Modal window" is covered by another element, is that preferable to knowing your test will wait for the correct condition?

Adding this does not prevent readability.  A developer concerned about that can still write:
```
await waitFor(!text("Modal window").exists())
await waitFor(text("Element that was covered by a modal window (or spinner)").isClickable())
await click("Element that was covered by a modal window (or spinner)")
```
